### ISSUE TITLE
MediaOptions does not support absolute AssetsPath

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/OrchardCore#10026]
### To Reproduce

1.Add `OrchardCore_Media` options and set `AssetsPath` absolute in App_Data\Sites\Default\appsetting.json:
  
    {
      "ConnectionString": "Data Source=.;Database=xxx;User ID=xx;Password=xxx;pooling=true",
      "DatabaseProvider": "SqlConnection",
      "TablePrefix": "aa",
      "OrchardCore_Media": {
        "AssetsPath": "D:\\site\\asset-test"
      }
    }

2.Start orchard core

3.Orchard Core throws `System.IO.IOException`
llegal path:
'D:\site\OC-test\publish\App_Data\Sites\Default\D:\site\asset-test'

If modified `AssetsPath` absolute to relative path `../../../../../asset-test`, it works well.

### Screenshots

Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ReportApplicationError
System.IO.IOException: 文件名、目录名或卷标语法不正确。 : 'D:\site\OC-test\publish\App_Data\Sites\Default\D:\site\asset-test'
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at OrchardCore.Media.Startup.<ConfigureServices>b__2_1(IServiceProvider serviceProvider)
...
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.ConfigureTenantPipeline(IApplicationBuilder appBuilder)
...
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
...
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.BuildTenantPipeline()

**Comment by deanmarcussen** [comment]
Duplicate https://github.com/OrchardCMS/OrchardCore/issues/6151

PLease refer there for the suggested solution
