### ISSUE TITLE
Migration issue

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#10200]
@Skrypt not sure it's the cause as my current migration version is just around 4
```
{"DataMigrationClass":"OrchardCore.Users.Migrations","Version":4}
```

All modules
```
{
    "Id": 1,
    "DataMigrations": [{
            "DataMigrationClass": "OrchardCore.Deployment.Migrations",
            "Version": 1
        }, {
            "DataMigrationClass": "OrchardCore.Liquid.Migrations",
            "Version": 1
        }, {
            "DataMigrationClass": "OrchardCore.ContentManagement.Records.Migrations",
            "Version": 5
        }, {
            "DataMigrationClass": "OrchardCore.Contents.Migrations",
            "Version": 1
        }, {
            "DataMigrationClass": "OrchardCore.ContentFields.Migrations",
            "Version": 2
        }, {
            "DataMigrationClass": "OrchardCore.Html.Migrations",
            "Version": 5
        }, {
            "DataMigrationClass": "OrchardCore.Indexing.Migrations",
            "Version": 1
        }, {
            "DataMigrationClass": "OrchardCore.Lists.Migrations",
            "Version": 2
        }, {
            "DataMigrationClass": "OrchardCore.Markdown.Migrations",
            "Version": 4
        }, {
            "DataMigrationClass": "OrchardCore.Media.Migrations",
            "Version": 1
        }, {
            "DataMigrationClass": "OrchardCore.Title.Migrations",
            "Version": 2
        }, {
            "DataMigrationClass": "OrchardCore.OpenId.YesSql.Migrations.OpenIdMigrations",
            "Version": 3
        }, {
            "DataMigrationClass": "OrchardCore.Users.Migrations",
            "Version": 4
        }
    ]
}
```

In my app the exception came from `OrchardCore.OpenId`. 
```
2021-08-31 14:47:23.352 +07:00 [INF] Updating feature 'OrchardCore.Users'
2021-08-31 14:47:23.352 +07:00 [INF] Applying migration for 'OrchardCore.Users' from version 4.
2021-08-31 14:47:23.354 +07:00 [INF] Applying migration for 'OrchardCore.Users' from version 5.
2021-08-31 14:47:23.354 +07:00 [INF] Applying migration for 'OrchardCore.Users' from version 6.
2021-08-31 14:47:23.354 +07:00 [INF] Applying migration for 'OrchardCore.Users' from version 7.
2021-08-31 14:47:23.354 +07:00 [INF] Applying migration for 'OrchardCore.Users' from version 8.
2021-08-31 14:47:23.357 +07:00 [INF] Applying migration for 'OrchardCore.Users' from version 9.
2021-08-31 14:47:23.359 +07:00 [INF] Applying migration for 'OrchardCore.Users' from version 10.
2021-08-31 14:47:23.361 +07:00 [INF] Applying migration for 'OrchardCore.Users' from version 11.
2021-08-31 14:47:23.365 +07:00 [INF] Updating feature 'OrchardCore.Lists'
2021-08-31 14:47:23.365 +07:00 [INF] Updating feature 'OrchardCore.ContentTypes'
2021-08-31 14:47:23.365 +07:00 [INF] Applying migration for 'OrchardCore.Lists' from version 2.
2021-08-31 14:47:23.366 +07:00 [INF] Updating feature 'OrchardCore.OpenId'
2021-08-31 14:47:23.366 +07:00 [INF] Applying migration for 'OrchardCore.OpenId' from version 3.
2021-08-31 14:47:23.367 +07:00 [INF] Applying migration for 'OrchardCore.OpenId' from version 4.
2021-08-31 14:47:23.391 +07:00 [INF] Applying migration for 'OrchardCore.OpenId' from version 5.
2021-08-31 14:47:23.401 +07:00 [INF] Applying migration for 'OrchardCore.OpenId' from version 6.
2021-08-31 14:47:23.405 +07:00 [DBG] Creating described context for tenant 'Default'
2021-08-31 14:47:23.405 +07:00 [DBG] Composing blueprint
2021-08-31 14:47:23.468 +07:00 [DBG] Done composing blueprint
2021-08-31 14:47:23.600 +07:00 [INF] Applying migration for 'OrchardCore.OpenId' from version 7.
2021-08-31 14:47:52.150 +07:00 [ERR] Error while running migration version 7 for 'OrchardCore.OpenId'.
Microsoft.Data.SqlClient.SqlException (0x80131904): The DELETE statement conflicted with the REFERENCE constraint "OC_FK_OpenIdApplicationIndex". The conflict occurred in database "MyDb", table "dbo.OC_OpenIdApplicationIndex", column 'DocumentId'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreResults(Boolean& moreResults)
   at Microsoft.Data.SqlClient.SqlDataReader.TryNextResult(Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.NextResult()
   at YesSql.Commands.CreateIndexCommand.<AddToBatch>b__6_0(DbDataReader dr)
   at YesSql.Commands.BatchCommand.ExecuteAsync(DbConnection connection, DbTransaction transaction, ISqlDialect dialect, ILogger logger)
   at YesSql.Session.FlushAsync()
   at YesSql.Session.FlushAsync()
   at OrchardCore.OpenId.YesSql.Migrations.OpenIdMigrations.UpdateFrom7Async()
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId)
ClientConnectionId:0de48100-af6a-41e0-a158-a1bcd331655a
Error Number:547,State:0,Class:16
2021-08-31 14:47:52.164 +07:00 [DBG] Testing Azure Media Storage container cms existence
2021-08-31 14:47:52.390 +07:00 [DBG] Azure Media Storage container cms created.
2021-08-31 14:47:54.523 +07:00 [ERR] An unhandled exception has occurred while executing the request.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'UserId'.
Invalid column name 'IsLockoutEnabled'.
Invalid column name 'LockoutEndUtc'.
Invalid column name 'AccessFailedCount'.
Invalid column name 'UserId'.
Invalid column name 'IsLockoutEnabled'.
Invalid column name 'LockoutEndUtc'.
....
```
**In my view, the errors are causes by this deletion** 
https://github.com/OrchardCMS/OrchardCore/blob/e13cda97e036205ddb7c2fa1c655cc07385bbc2d/src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Migrations/OpenIdMigrations.cs#L488-L496

The failure of this migration will prevents other migration to be executed and cause the error `Invalid column name '****'`

_Originally posted by @hung-doan in https://github.com/OrchardCMS/OrchardCore/issues/7206#issuecomment-910096762_

**Comment by deanmarcussen** [comment]
Please refer this discussion https://github.com/OrchardCMS/OrchardCore/discussions/9119 @hung-doan

**Comment by hung-doan** [comment]
thanks @deanmarcussen , that workaround works for me
