### ISSUE TITLE
Deployment Plan - File Download Target:  Blank page when executing more than once

### ISSUE THREAD

**Issue by evaldsen** [OrchardCMS/OrchardCore#10244]
### Description

When clicking  "select" on the file download target more than once, subsequent download attempts fail and a blank page is shown instead of a file download dialog. (Browser dev-tools shows HTTP status 500). No longer able to run execute with file download target, even after restarting the CMS.

* Browser: Firefox
* OS: Fedora (Linux)
* Environment: localhost

### To Reproduce

1. Go to Configuration > Import/Export > Deployment Plans
2. Add deployment plan if none exists 
3. Execute a deployment plan that supports File Download Target)
4. Click "select" on File Download target (download dialog appears as expected)
5. Click "open" in the file download dialog
5. Click "select" again and blank is displayed (Browser devtools shows HTTP Status 500)
6. Click "back" in the browser, and click "select" again. Same result as 5.

### Expected behavior
A download dialog should appear (again)

### Actual behavior
Unable to execute the same deployment plan again, refreshing/restarting server app does not solve the issue.

Quick fix: Manually remove the temporary file from /tmp. May look something like:  /tmp/ContentDefinitions.zip

### Research
Seems to be an issue with the handling of temporary files in the File download target. When clicking "open" on the file download dialog in Firefox (Fedora), the file is saved under /tmp, which also happens to be the same folder the File Download Target uses (internally) for temporary files. Then there is a conflict because the temporary and resulting file has the same name. 

This is an issue when Orchard is administrated on the same system as it is running. For instance, during development or a production scenario where Admin page is only available from localhost on a server instance. 

### Stacktrace
```
System.IO.IOException: The file '/tmp/ContentDefinitions.zip' already exists.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter) in /_/src/libraries/Common/src/Interop/Unix/Interop.IOErrors.cs:line 22
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode) in /_/src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeFileHandle.Unix.cs:line 37
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.Unix.cs:line 60
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.cs:line 237
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.cs:line 182
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding) in /_/src/libraries/System.IO.Compression.ZipFile/src/System/IO/Compression/ZipFile.Create.cs:line 183
   at System.IO.Compression.ZipFile.DoCreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, Nullable`1 compressionLevel, Boolean includeBaseDirectory, Encoding entryNameEncoding) in /_/src/libraries/System.IO.Compression.ZipFile/src/System/IO/Compression/ZipFile.Create.cs:line 366
   at System.IO.Compression.ZipFile.CreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName) in /_/src/libraries/System.IO.Compression.ZipFile/src/System/IO/Compression/ZipFile.Create.cs:line 236
   at OrchardCore.Deployment.Controllers.ExportFileController.Execute(Int32 id) in /home/{masked}/OrchardCore/src/OrchardCore.Modules/OrchardCore.Deployment/Controllers/ExportFileController.cs:line 77
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Liquid.ScriptsMiddleware.Invoke(HttpContext httpContext) in /home/{masked}/OrchardCore/src/OrchardCore.Modules/OrchardCore.Liquid/ScriptsMiddleware.cs:line 70
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext() in /home/{masked}/OrchardCore/src/OrchardCore.Modules/OrchardCore.Diagnostics/DiagnosticsStartupFilter.cs:line 34
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at OrchardCore.ContentPreview.PreviewStartupFilter.<>c.<<Configure>b__1_1>d.MoveNext() in /home/{masked}/OrchardCore/src/OrchardCore.Modules/OrchardCore.ContentPreview/PreviewStartupFilter.cs:line 21
--- End of stack trace from previous location ---
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in /home/{masked}/OrchardCore/src/OrchardCore/OrchardCore/Modules/ModularTenantRouterMiddleware.cs:line 63
   at OrchardCore.Modules.ModularTenantContainerMiddleware.<>c__DisplayClass4_0.<<Invoke>b__0>d.MoveNext() in /home/{masked}/OrchardCore/src/OrchardCore/OrchardCore/Modules/ModularTenantContainerMiddleware.cs:line 62
--- End of stack trace from previous location ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell) in /home/{masked}/OrchardCore/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs:line 244
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell) in /home/{masked}/OrchardCore/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs:line 249
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell) in /home/{masked}/OrchardCore/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs:line 254
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell) in /home/{masked}/OrchardCore/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs:line 259
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in /home/{masked}/OrchardCore/src/OrchardCore/OrchardCore/Modules/ModularTenantContainerMiddleware.cs:line 60
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by evaldsen** [comment]
Possible solution #10245
