### ISSUE TITLE
Error after updating to 1.1.0

### ISSUE THREAD

**Issue by khurram4u2** [OrchardCMS/OrchardCore#10622]
### To Reproduce
1. Go to 'Update the project to stable orchard v 1.1.0'
2. Click on '...'
3. Scroll down to '...'

   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
[22:49:53 INF] Updating feature 'OrchardCore.ContentFields.Indexing.SQL'
[22:49:53 INF] Updating feature 'OrchardCore.Settings'
[22:49:53 INF] Updating feature 'OrchardCore.Liquid'
[22:49:53 INF] Updating feature 'OrchardCore.Contents'
[22:49:53 INF] Updating feature 'OrchardCore.ContentTypes'
[22:49:53 INF] Updating feature 'OrchardCore.Shortcodes'
[22:49:53 INF] Updating feature 'OrchardCore.ContentFields'
[22:49:53 INF] Applying migration for 'OrchardCore.ContentFields.Indexing.SQL' from version 4.
[22:49:53 WRN] Failed to alter 'Time' column. This is not an error when using SqLite
[22:49:53 INF] Updating feature 'OrchardCore.Users'
[22:49:53 INF] Applying migration for 'OrchardCore.Users' from version 4.
[22:49:53 INF] Applying migration for 'OrchardCore.Users' from version 5.
[22:49:53 INF] Applying migration for 'OrchardCore.Users' from version 6.
[22:49:53 INF] Applying migration for 'OrchardCore.Users' from version 7.
[22:49:53 INF] Applying migration for 'OrchardCore.Users' from version 8.
[22:49:53 INF] Applying migration for 'OrchardCore.Users' from version 9.
[22:49:53 INF] Applying migration for 'OrchardCore.Users' from version 10.
[22:49:53 INF] Request finished in 6138.4546ms 500 text/html; charset=utf-8
[22:49:53 INF] Applying migration for 'OrchardCore.Users' from version 11.
[22:49:53 INF] Updating feature 'OrchardCore.Layers'
[22:49:53 INF] Updating feature 'OrchardCore.Scripting'
[22:49:53 INF] Updating feature 'OrchardCore.Widgets'
[22:49:53 INF] Updating feature 'OrchardCore.Rules'
[22:49:53 INF] Applying migration for 'OrchardCore.Layers' from version 1.
[22:49:53 ERR] Error while running migration version 1 for 'OrchardCore.Layers'.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'index IDX_LayerMetadataIndex_DocumentId already exists'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2813
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 572
   at YesSql.Sql.SchemaBuilder.Execute(IEnumerable`1 statements)
   at YesSql.Sql.SchemaBuilder.AlterTable(String name, Action`1 table)
   at YesSql.Sql.SchemaBuilder.AlterIndexTable(Type indexType, Action`1 table, String collection)
   at YesSql.Sql.SchemaBuilderExtensions.AlterIndexTable[T](ISchemaBuilder builder, Action`1 table, String collection)
   at OrchardCore.Layers.Migrations.UpdateFrom1()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId)
[22:49:53 INF] Updating feature 'OrchardCore.Lists'
[22:49:53 INF] Applying migration for 'OrchardCore.Lists' from version 2.
[22:49:53 INF] Updating feature 'OrchardCore.Menu'
[22:49:53 INF] Updating feature 'OrchardCore.Alias'
[22:49:53 INF] Updating feature 'OrchardCore.Title'
[22:49:53 INF] Applying migration for 'OrchardCore.Menu' from version 2.
[22:49:53 WRN] Could not lookup the admin user, user migrations may not have run yet.
[22:49:53 INF] Executing recipe step 'ContentDefinition'.
[22:49:53 INF] Finished executing recipe step 'ContentDefinition'.
[22:49:53 INF] Applying migration for 'OrchardCore.Menu' from version 3.
[22:49:53 INF] Updating feature 'OrchardCore.OpenId'
[22:49:53 INF] Applying migration for 'OrchardCore.OpenId' from version 3.
[22:49:53 INF] Applying migration for 'OrchardCore.OpenId' from version 4.
[22:49:53 INF] Applying migration for 'OrchardCore.OpenId' from version 5.
[22:49:53 INF] Applying migration for 'OrchardCore.OpenId' from version 6.
[22:49:57 INF] Applying migration for 'OrchardCore.OpenId' from version 7.
[22:49:57 ERR] An unhandled exception has occurred while executing the request.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'table UserIndex has no column named UserId'.

### Screenshots
![image](https://user-images.githubusercontent.com/56805276/139841246-a1d9e509-27be-4d4b-98a7-dc38b819c65c.png)

**Comment by Skrypt** [comment]
index IDX_LayerMetadataIndex_DocumentId already exists
Remove it manually before migrating the data.

**Comment by khurram4u2** [comment]
Could you please explain from which table I have to remove?

**Comment by Skrypt** [comment]
It's not a table it's an index.

**Comment by khurram4u2** [comment]
Should I remove the table? Could any body explain what is 

index IDX_LayerMetadataIndex_DocumentId

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/140011018-e5c00420-2bc0-4709-87d2-dca3d30e4c82.png)

You remove this; not the table.

**Comment by khurram4u2** [comment]
Thanks.
