### ISSUE TITLE
AddDatabaseShellsConfiguration doesn't seem to work when creating new Tenant in SaaS service

### ISSUE THREAD

**Issue by sonicmouse** [OrchardCMS/OrchardCore#10789]
I have created a SaaS service, this is the builder:

```
services.AddOrchardCms(builder => builder
    .AddDatabaseShellsConfiguration()/* config in OrchardCore_Shells_Database appsetting*/);
```

In the appsettings.json, I added the config:
```
"OrchardCore_Shells_Database": { // needs AddDatabaseShellsConfiguration() registered in startup
	"DatabaseProvider": "SqlConnection",
	"ConnectionString": "Server=tcp:XXX,1433;Initial Catalog=XXX;Persist Security Info=False;User ID=XXX;Password=XXX;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;",
	"TablePrefix": "something-cms-shellsettings",
	"MigrateFromFiles": true
},
```
Everything works as expected in the main SaaS service. I can create a new (headless) service. But when I click "Setup" in the UI, I get this error:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at YesSql.QueryExtensions.Query[T](ISession session, String collection)
   at OrchardCore.Data.Documents.DocumentStore.GetOrCreateImmutableAsync[T](Func`1 factoryAsync)
   at OrchardCore.Documents.DocumentManager`1.GetOrCreateImmutableAsync(Func`1 factoryAsync)
   at OrchardCore.Settings.Services.SiteService.GetSiteSettingsAsync()
   at OrchardCore.DisplayManagement.Razor.RazorViewActionFilter.OnActionExecutionAsync(ActionContext context)
  ...
```
It looks like it's trying to read from the flat-file, but since I have it configured to read from the SQL database, it's failing out.

Is there a work-around for this? Maybe I'm not doing something correctly?

**Comment by sonicmouse** [comment]
I had `OrchardCore.Admin` as a feature to be turned on with `AddSetupFeatures()`, which apparently caused some sort of conflict. I removed that and everything is fine now.
