### ISSUE TITLE
Microsoft.Data.SqlClient.SqlException When running the dev project

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#10931]
### Describe the bug
I pulled the latest code and run it using VS 2022. The `OrchardCore.Users.Migrations` throw an exception.

Here is the error that I got. This is the first time I run the OC project on my machine.
```
Microsoft.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Incorrect syntax near '.'.
  Source=Core Microsoft SqlClient Data Provider
  StackTrace:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2848
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 581
   at YesSql.Sql.SchemaBuilder.Execute(IEnumerable`1 statements)
   at YesSql.Sql.SchemaBuilder.CreateForeignKey(String name, String srcTable, String[] srcColumns, String destTable, String[] destColumns)
   at YesSql.Sql.SchemaBuilder.CreateMapIndexTable(Type indexType, Action`1 table, String collection)
   at YesSql.Sql.SchemaBuilderExtensions.CreateMapIndexTable[T](ISchemaBuilder builder, Action`1 table, String collection)
   at OrchardCore.Users.Migrations.Create() in C:\Code\OrchardCore\src\OrchardCore.Modules\OrchardCore.Users\Migrations.cs:line 18

  This exception was originally thrown at this call stack:
    [External Code]
    OrchardCore.Users.Migrations.Create() in Migrations.cs
```
The exception was thrown from the following code

```
            SchemaBuilder.CreateMapIndexTable<UserIndex>(table => table
                .Column<string>("NormalizedUserName") // TODO These should have defaults. on SQL Server they will fall at 255. Exceptions are currently thrown if you go over that.
                .Column<string>("NormalizedEmail")
                .Column<bool>("IsEnabled", c => c.NotNull().WithDefault(true))
                .Column<bool>("IsLockoutEnabled", c => c.NotNull().WithDefault(false))
                .Column<DateTime?>("LockoutEndUtc", c => c.Nullable())
                .Column<int>("AccessFailedCount", c => c.NotNull().WithDefault(0))
                .Column<string>("UserId")
            );
```

### To Reproduce
1. Run the OC project as is
2. Use Sql Server.
3. User Saas recipe

### Expected behavior
The app should run with no errors.

**Comment by deanmarcussen** [comment]
This works fine on the functional tests https://github.com/OrchardCMS/OrchardCore/actions/runs/1638729983

This sounds like a connection string issue

**Comment by CrestApps** [comment]
You are right! I just noticed that I had an email as a table prefix. Maybe, we could strip out bad character from the prefix.

**Comment by Skrypt** [comment]
That looks like an issue I'm trying to fix with Database Schemas on the YesSQL repository.

https://github.com/sebastienros/yessql/pull/418
