### ISSUE TITLE
WebRooPath ArgumentNull exception

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#11347]
From main, clean repo, Blog recipe setup successful but home page fails with:

```
2022-03-10 10:57:49.8972||||Microsoft.Hosting.Lifetime|INFO|Now listening on: http://localhost:5000 
2022-03-10 10:57:49.9413||||Microsoft.Hosting.Lifetime|INFO|Now listening on: https://localhost:5001 
2022-03-10 10:57:49.9413||||Microsoft.Hosting.Lifetime|INFO|Application started. Press Ctrl+C to shut down. 
2022-03-10 10:57:49.9413||||Microsoft.Hosting.Lifetime|INFO|Hosting environment: Production 
2022-03-10 10:57:49.9413||||Microsoft.Hosting.Lifetime|INFO|Content root path: C:\Users\sebros.REDMOND\Documents\Projects\orchardcore\src\OrchardCore.Cms.Web\bin\release\net6.0 
2022-03-10 10:58:14.2850|Default|00-fe59ba86e48dc6aab58f8b5c23891dbe-e741638818dbc010-00||Microsoft.AspNetCore.Server.Kestrel|ERROR|Connection id "0HMG2OVGONFKE", Request id "0HMG2OVGONFKE:00000004": An unhandled exception was thrown by the application. System.ArgumentNullException: Parameter "WebRootPath" must be not null. (Parameter 'WebRootPath')
   at SixLabors.ThrowHelper.ThrowArgumentNullException(String name, String message)
   at SixLabors.ThrowHelper.ThrowArgumentExceptionForNotNullOrWhitespace(String value, String name)
   at SixLabors.ImageSharp.Web.Caching.PhysicalFileSystemCache..ctor(IOptions`1 cacheOptions, IWebHostEnvironment environment, IOptions`1 options, FormatUtilities formatUtilities)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at OrchardCore.Modules.ModularTenantRouterMiddleware.BuildTenantPipeline() in C:\Users\sebros.REDMOND\Documents\Projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 106
   at OrchardCore.Modules.ModularTenantRouterMiddleware.InitializePipelineAsync(ShellContext shellContext) in C:\Users\sebros.REDMOND\Documents\Projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 77
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\Users\sebros.REDMOND\Documents\Projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 60
   at OrchardCore.Modules.ModularTenantContainerMiddleware.<>c__DisplayClass4_0.<<Invoke>b__0>d.MoveNext() in C:\Users\sebros.REDMOND\Documents\Projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 62

```

**Comment by sebastienros** [comment]
Was running from /bin/release/net6 and it doesn't have the wwwroot folder
