### ISSUE TITLE
Null exception in OrchardCore.ContentFields.LinkFieldDisplayDriver

### ISSUE THREAD

**Issue by kevinsmgov** [OrchardCMS/OrchardCore#11389]
### Describe the bug

Content items with optional Link Fields don't allow the Link Field URL to be cleared once saved due to a Null exception in the display driver.

### To Reproduce

1. Create a content type with a Link Field and leave it Optional
2. Create a new instance of that type and fill in a URL and Link Text then save
3. Edit the previously created instance and clear the URL and Link Text then save again.
4. Edit the previously saved instance and the URL and Link Text will be there still
5. Check the Orchard logs - there will be a Null exception from the display driver.

### Expected behavior

When a Link Field that is set to Optional has its values cleared, the Link Field should remain empty when saved.

### Log data

```
2022-03-15 13:15:07.8192|Default|00-0f7383116c1aa8579fcbc7bdf82f2da7-9bbe17eaaac31834-00||OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator|ERROR|IContentFieldDisplayDriver thrown from OrchardCore.ContentFields.Drivers.LinkFieldDisplayDriver by ArgumentNullException System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at System.Text.Encodings.Web.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Text.Encodings.Web.TextEncoder.Encode(String value)
   at OrchardCore.ContentFields.Drivers.LinkFieldDisplayDriver.UpdateAsync(LinkField field, IUpdateModel updater, UpdateFieldEditorContext context) in C:\github\OrchardCMS\OrchardCore\src\OrchardCore.Modules\OrchardCore.ContentFields\Drivers\LinkFieldDisplayDriver.cs:line 104
   at OrchardCore.ContentManagement.Display.ContentDisplay.ContentFieldDisplayDriver`1.OrchardCore.ContentManagement.Display.ContentDisplay.IContentFieldDisplayDriver.UpdateEditorAsync(ContentPart contentPart, ContentPartFieldDefinition partFieldDefinition, ContentTypePartDefinition typePartDefinition, UpdateEditorContext context) in C:\github\OrchardCMS\OrchardCore\src\OrchardCore\OrchardCore.ContentManagement.Display\ContentDisplay\ContentFieldDisplayDriver.cs:line 208
   at OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator.<>c.<<UpdateEditorAsync>b__9_1>d.MoveNext() in C:\github\OrchardCMS\OrchardCore\src\OrchardCore\OrchardCore.ContentManagement.Display\ContentDisplay\ContentItemDisplayCoordinator.cs:line 342
--- End of stack trace from previous location ---
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1,T2,T3,T4](IEnumerable`1 events, Func`6 dispatch, T1 arg1, T2 arg2, T3 arg3, T4 arg4, ILogger logger) in C:\github\OrchardCMS\OrchardCore\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 187    at System.Text.Encodings.Web.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Text.Encodings.Web.TextEncoder.Encode(String value)
   at OrchardCore.ContentFields.Drivers.LinkFieldDisplayDriver.UpdateAsync(LinkField field, IUpdateModel updater, UpdateFieldEditorContext context) in C:\github\OrchardCMS\OrchardCore\src\OrchardCore.Modules\OrchardCore.ContentFields\Drivers\LinkFieldDisplayDriver.cs:line 104
   at OrchardCore.ContentManagement.Display.ContentDisplay.ContentFieldDisplayDriver`1.OrchardCore.ContentManagement.Display.ContentDisplay.IContentFieldDisplayDriver.UpdateEditorAsync(ContentPart contentPart, ContentPartFieldDefinition partFieldDefinition, ContentTypePartDefinition typePartDefinition, UpdateEditorContext context) in C:\github\OrchardCMS\OrchardCore\src\OrchardCore\OrchardCore.ContentManagement.Display\ContentDisplay\ContentFieldDisplayDriver.cs:line 208
   at OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator.<>c.<<UpdateEditorAsync>b__9_1>d.MoveNext() in C:\github\OrchardCMS\OrchardCore\src\OrchardCore\OrchardCore.ContentManagement.Display\ContentDisplay\ContentItemDisplayCoordinator.cs:line 342
--- End of stack trace from previous location ---
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1,T2,T3,T4](IEnumerable`1 events, Func`6 dispatch, T1 arg1, T2 arg2, T3 arg3, T4 arg4, ILogger logger) in C:\github\OrchardCMS\OrchardCore\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 187

```

**Comment by Piedone** [comment]
This looks like it just needs a simple string empty check.

**Comment by kevinsmgov** [comment]
I'm working on a fix for this but I'm curious about the original specification for the Link field - specifically, if a link is not required, why is the link text requirement still checked? I would expect the link text requirement to be conditional on the existence of a URL (in fact, our site needs that behavior).

If I adjust the logic for URL validation to be conditional on the existence of the URL string, it would make sense to me to include  the link text requirement within that block as well.

Can someone point me to that specification?

**Comment by Piedone** [comment]
Note `LinkTextMode`: It's a config independent of the link value (URL) being required. While requiring the link text to be specified but not the URL sounds like an uncommon case for me, it's not unrealistic: You may want to allow editors to add placeholder links.

**Comment by kevinsmgov** [comment]
So there could be two setting values, "Link Text Required" and "Link Text Required with URL" (the second, only requiring the link text if a URL is provided), yes?

**Comment by kevinsmgov** [comment]
Ok, I'm putting a fix together for just the Null exception and I'll raise the link text requirement as a separate issue.
