### ISSUE TITLE
OpenIdBackgroundTask throws "Object does not match target type." when use postgresql

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/OrchardCore#11458]
### Describe the bug
Same code works well in Sqlite. Below is the exception stack trace:
```
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at YesSql.Services.DefaultQuery.Evaluate(Expression expression)
   at YesSql.Services.DefaultQuery.ConvertFragment(IStringBuilder builder, Expression expression)
   at YesSql.Services.DefaultQuery.ConvertFragment(IStringBuilder builder, Expression expression)
   at YesSql.Services.DefaultQuery.ConvertComparisonBinaryExpression(IStringBuilder builder, BinaryExpression expression, String operation)
   at YesSql.Services.DefaultQuery.ConvertFragment(IStringBuilder builder, Expression expression)
   at YesSql.Services.DefaultQuery.ConvertPredicate(IStringBuilder builder, Expression expression)
   at YesSql.Services.DefaultQuery.ConvertEqualityBinaryExpression(IStringBuilder builder, BinaryExpression expression, String operation)
   at YesSql.Services.DefaultQuery.ConvertFragment(IStringBuilder builder, Expression expression)
   at YesSql.Services.DefaultQuery.ConvertPredicate(IStringBuilder builder, Expression expression)
   at YesSql.Services.DefaultQuery.Filter[TIndex](Expression`1 predicate)
   at YesSql.Services.DefaultQuery.Query`1.YesSql.IQuery<T>.With[TIndex](Expression`1 predicate)
   at YesSql.QueryExtensions.Query[T,TIndex](ISession session, Expression`1 predicate, Boolean filterType, String collection)
   at YesSql.QueryExtensions.Query[T,TIndex](ISession session, Expression`1 predicate, String collection)
   at OrchardCore.OpenId.YesSql.Stores.OpenIdAuthorizationStore`1.PruneAsync(DateTimeOffset threshold, CancellationToken cancellationToken)
   at OrchardCore.OpenId.Tasks.OpenIdBackgroundTask.DoWorkAsync(IServiceProvider serviceProvider, CancellationToken cancellationToken)
```
The task is catch the exception then log
```
An error occurred while pruning authorizations from the database.
```
and the exception message is 
```
Object does not match target type.
```
### To Reproduce
1. Use postgresql as the tenant database
2. Enable OpenID Server feature and create an application
3. Login using the created application
4. Wait for the OpenIdBackgroundTask run

### Expected behavior
The orphaned tokens/authorizations should be removed with succeed

**Comment by HengzheLi** [comment]
seems below is the issued code
![image](https://user-images.githubusercontent.com/491759/161415906-a51f45de-3c39-452f-83ed-b8bf62d6a640.png)
When I remove the marked code, everything works well.

**Comment by jtkech** [comment]
Can't try it so not sure at all, but can you try, maybe

    token.CreationDate != null && token.CreationDate.Value < threshold.UtcDateTime

Also this code has been recently updated in the last dev branch but for another issue, see #11382

**Comment by sebastienros** [comment]
Might be related to bugs in posgresql that were fixed in a "mostly" recent release. But maybe an issue with yessql on postres. Please file a bug in yessql to track. Note for myself: CreationDate is nullable

**Comment by Skrypt** [comment]
CreationDate and ExpirationDate are nullable columns. Though, it is unlikely that these columns will have NULL values. Just for info. You may take a look at the database table and assert that there are non-null values before running the migration if that's the case.

**Comment by HengzheLi** [comment]
> That would mean that the DateTime is not stored as a DateTime in the PostgreSQL database...

Yes. The column type is TimeStamp in PostgreSQL as well as ExpirationDate. Maybe that is the reason.
I compare the data in there two columns as the code
```
token.ExpirationDate < DateTime.UtcNow
```
works well and found that the **milisecond** part in ExpiartionDate column all are "000". But it has value "XXX" in CreationDate column. Then I updated the data in CreateDate column setting the milicecond part to "000" too and found that the exception gone in my recently logging.

**Comment by Skrypt** [comment]
Look like a DBType binding issue between YesSQL/Dapper and PostgreSQL.

**Comment by sebastienros** [comment]
> Then I updated the data in CreateDate column setting the milicecond part to "000"

Was it something from recent database updates or older?

**Comment by HengzheLi** [comment]
> > Then I updated the data in CreateDate column setting the milicecond part to "000"
> 
> Was it something from recent database updates or older?

Possible. The issuing data was populated in OC 1.2.1 and after I upgrade to 1.3.0. All new data is OK.

Close this task as it is not an issue anymore.
