### ISSUE TITLE
Object reference not set to an instance of an object exception in production environment

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#11976]
### Describe the bug
I added a new tenant using the Tenants UI. When I click "Setup" button I am redirected to `https://subdomain.domain.com/?token=CfDJ8KtwYcM66YVAqGUg9CLX......` which shows HTTP Error 500.

Looking at the log file I see the following

```
2022-07-08 22:24:07.6669|test123|00-e5f6a593a8645780dc209197a58c33df-99eff78a1a46d690-00||Microsoft.AspNetCore.Server.Kestrel|ERROR|Connection id "0HMJ1550K2I32", Request id "0HMJ1550K2I32:0000000A": An unhandled exception was thrown by the application. System.NullReferenceException: Object reference not set to an instance of an object.
   at YesSql.QueryExtensions.Query[T](ISession session, String collection)
   at OrchardCore.Data.Documents.DocumentStore.GetOrCreateImmutableAsync[T](Func`1 factoryAsync)
   at OrchardCore.Documents.DocumentManager`1.GetOrCreateImmutableAsync(Func`1 factoryAsync)
   at OrchardCore.Settings.Services.SiteService.GetSiteSettingsAsync()
   at OrchardCore.Media.Processing.MediaTokenSettingsUpdater.ActivatedAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.<>c.<<ActivateShellInternalAsync>b__43_0>d.MoveNext()
--- End of stack trace from previous location ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.ActivateShellInternalAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.ActivateShellInternalAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)    at YesSql.QueryExtensions.Query[T](ISession session, String collection)
   at OrchardCore.Data.Documents.DocumentStore.GetOrCreateImmutableAsync[T](Func`1 factoryAsync)
   at OrchardCore.Documents.DocumentManager`1.GetOrCreateImmutableAsync(Func`1 factoryAsync)
   at OrchardCore.Settings.Services.SiteService.GetSiteSettingsAsync()
   at OrchardCore.Media.Processing.MediaTokenSettingsUpdater.ActivatedAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.<>c.<<ActivateShellInternalAsync>b__43_0>d.MoveNext()
--- End of stack trace from previous location ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.ActivateShellInternalAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.ActivateShellInternalAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
```

I can't reproduce this issue locally and it is happening only in Production environment. The production environment is running on Azure Web App using docker container with the following features 

```
services.AddOrchardCms()
             .AddSetupFeatures("OrchardCore.Redis", "OrchardCore.Redis.Lock")
             .AddGlobalFeatures("OrchardCore.DataProtection.Azure", "OrchardCore.Media.Azure.Storage","OrchardCore.Redis", "OrchardCore.Redis.Cache", "OrchardCore.Redis.DataProtection", "OrchardCore.Redis.Lock")
```

The app is running in production with no issues. However, I can't seems to be able to setup new tenants.

Is this a bug? Any idea how I can trace this issue or go about fixing it?

**Comment by Skrypt** [comment]
We need repro steps else it is a shot in the dark. The exception thrown there is not really explicit. It seems like YesSQL did throw a NRE.

**Comment by CrestApps** [comment]
@Skrypt it is a shot in the dark and it is a mean error :)

I finally was able to identify the problem and fix it. But I feel that we should do something about it to prevent such an error some how.

The short answer to fix the issue is changing `.AddGlobalFeatures("OrchardCore.Media.Azure.Storage")` to `.AddTenantFeatures("OrchardCore.Media.Azure.Storage")`

Long answer, is that [MediaTokenSettingsUpdater](https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore.Modules/OrchardCore.Media/Processing/MediaTokenSettingsUpdater.cs#L26) uses `ISiteService` which needs an instance of `ISession` to be able to pull the site settings document. Well, when you click on "Setup" the tenant, the settings does not exists... more specifically the [ISession here instance](https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore/OrchardCore.Data.YesSql/Documents/DocumentStore.cs#L28)  is null at that point of time. So when its registered using `AddTenantFeatures`, the service will get registered after the tenant is setup.

**Comment by jtkech** [comment]
Good catch, maybe we could also update `MediaTokenSettingsUpdater` to also inject `ShellSettings` so that it can check the tenant state, e.g. nothing to do if the tenant is not running (e.g. Initializing).

**Comment by CrestApps** [comment]
@jtkech Great idea! We would also have to add the check here [in the RazorViewFeature](https://github.com/OrchardCMS/OrchardCore/blob/2bce40b0a9b9ba1e1f71f4ffefba819c79849df2/src/OrchardCore/OrchardCore.DisplayManagement/Razor/RazorViewActionFilter.cs#L58-L61) since we can't access the siteSettings if the site isn't running. Iam pushing a PR for this now.

**Comment by jtkech** [comment]
Can't right now but need to think about it as we never had issue in the action filter, and maybe there are scenario where we still need site settings while initializing.

Idem about the media token updater, maybe we just need to do nothing only if the tenant is Uninitialized, and let it working if it is Initializing as it is checked in other places, would need to be tried.
