### ISSUE TITLE
Workflows HTTP functions cause Liquid parsing to fail

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#12340]
### To Reproduce
1. Take a freshly set up Blob as a start.
3. Enable HTTP Workflows Activities.
4. Create a workflow that runs when a Blog Post is published, and displays a Notification with the following Liquid: `Test {{requestForm("TitlePart.Title")}}` (note that other [HTTP-related functions](https://docs.orchardcore.net/en/latest/docs/reference/modules/Workflows/#javascript-functions-in-http-activities) can be used too).
5. Publish a Blob Post. Notice that the notification is not displayed but you'll get the below exception.

```
An unhandled error occurred while executing an activity. Workflow ID: '19'. Activity: '4fas18p51842hw0jmg9ejpqg5s', 'NotifyTask'. Putting the workflow in the faulted state. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Microsoft.AspNetCore.Mvc.Localization.LocalizedHtmlString..ctor(String name, String value, Boolean isResourceNotFound, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Localization.LocalizedHtmlString..ctor(String name, String value)
   at OrchardCore.Workflows.Activities.NotifyTask.ExecuteAsync(WorkflowExecutionContext workflowContext, ActivityContext activityContext) in E:\Projects\OrchardForks\OrchardCore2\src\OrchardCore.Modules\OrchardCore.Workflows\Activities\NotifyTask.cs:line 60
   at OrchardCore.Workflows.Services.WorkflowManager.ExecuteWorkflowAsync(WorkflowExecutionContext workflowContext, ActivityRecord activity) in E:\Projects\OrchardForks\OrchardCore2\src\OrchardCore.Modules\OrchardCore.Workflows\Services\WorkflowManager.cs:line 374    at Microsoft.AspNetCore.Mvc.Localization.LocalizedHtmlString..ctor(String name, String value, Boolean isResourceNotFound, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Localization.LocalizedHtmlString..ctor(String name, String value)
   at OrchardCore.Workflows.Activities.NotifyTask.ExecuteAsync(WorkflowExecutionContext workflowContext, ActivityContext activityContext) in E:\Projects\OrchardForks\OrchardCore2\src\OrchardCore.Modules\OrchardCore.Workflows\Activities\NotifyTask.cs:line 60
   at OrchardCore.Workflows.Services.WorkflowManager.ExecuteWorkflowAsync(WorkflowExecutionContext workflowContext, ActivityRecord activity) in E:\Projects\OrchardForks\OrchardCore2\src\OrchardCore.Modules\OrchardCore.Workflows\Services\WorkflowManager.cs:line 374
```

The reason for this is that down in `LiquidTemplateManager`, `_liquidViewParser.TryParse()` will produce an empty template. The resulting `FluidTemplate` will have 0 Statements, as if parsing completely fails for the template. Other standard Liquid works, but the functions in `HttpMethodsProvider` cause this behavior.

### Expected behavior
Something along the lines of "Test My Title" is displayed as a notification.

**Comment by Piedone** [comment]
Oh well, epic misunderstanding. These are Flue JavaScript functions. As such, they work of course.
