### ISSUE TITLE
Error while running migration version 0 for 'OrchardCore.Search.Lucene'

### ISSUE THREAD

**Issue by rongconzx** [OrchardCMS/OrchardCore#12940]
### Describe the bug
I upgrade the latest Orchard Core(version 1.5) from version 1.0.0. 
Do I miss any config for the new version?

```
[ERR] Error while running migration version 0 for 'OrchardCore.Search.Lucene'.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at OrchardCore.Search.Lucene.Migrations.<>c__DisplayClass2_0.<Create>b__1(ContentPartDefinitionBuilder partBuilder)
   at OrchardCore.ContentManagement.Metadata.ContentDefinitionManagerExtensions.AlterPartDefinition(IContentDefinitionManager manager, String name, Action`1 alteration)
   at OrchardCore.Search.Lucene.Migrations.Create()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId)
 
```
 
Thanks,
Huy Duong.

**Comment by Skrypt** [comment]
We fixed an NRE in a PR that has been merged in the latest dev. This may be related.

**Comment by rongconzx** [comment]
Thanks for your info @Skrypt. But do we have a way to work around this?

**Comment by Skrypt** [comment]
Unregister from the dependency injector; the Migration class from a custom module. Then register the new one in that module to execute the proper migration. Then remove everything once it is done.

**Comment by rongconzx** [comment]
Thank you @Skrypt

**Comment by sebastienros** [comment]
Did you solve the issue?

**Comment by lukasswm** [comment]
I have the same issue upgrading from OrchardCore.Lucene 1.4 to OrchardCore.Search.Lucene 1.5.0. I uninstalled the OrchardCore.Lucene package and installed the OrchardCore.Search.Lucene refrencing that dependency in my modules Manifest:

```
using OrchardCore.Modules.Manifest;

[assembly: Module(
    Name = "xxx",
    Author = "xxx",
    Website = "xxx",
    Version = ManifestConstants.OrchardCoreVersion,
    Description = "xxx",
    Category = "Content",
    Dependencies = new[]
    {
      ...
      "OrchardCore.Search.Lucene"
    })]
```

The exceptions occures on the "LocalizationPart".

I do not understand what this means:

> Unregister from the dependency injector; the Migration class from a custom module. Then register the new one in that module to execute the proper migration. Then remove everything once it is done.

you are mentioning some bug fixes. But how am I suppossed to use that as long as there is no 1.6 Version released?
