### ISSUE TITLE
Gulp 2.0

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#1308]
It could be interesting to upgrade Gulp to the 2.0 version that has just been released : https://github.com/gulpjs/gulp-cli

It seems there are breaking changes, though.

@DaRosenberg : What do you think of this idea?

**Comment by agriffard** [comment]
`gulp rebuild` does an error building jquery-latest.d.ts:
```
D:/Orchard/OrchardCore/src/OrchardCore.Modules/OrchardCore.Resources/Assets/jQuery/Typings/jquery-latest.d.ts(6103,66): error TS2344: Type '"timeout" | "onreadystatechange" | "responseType" | "withCredentials" | "msCaching"' does not satisfy the constraint '"abort" | "open" | "timeout" | "onreadystatechange" | "responseType" | "withCredentials" | "readyState" | "response" | "responseText" | "responseURL" | "responseXML" | "status" | ... 21 more ... | "dispatchEvent"'.
  Type '"msCaching"' is not assignable to type '"abort" | "open" | "timeout" | "onreadystatechange" | "responseType" | "withCredentials" | "readyState" | "response" | "responseText" | "responseURL" | "responseXML" | "status" | ... 21 more ... | "dispatchEvent"'.
```
@sfmskywalker This is referenced from the Workflows module. Can you please help to fix it?

**Comment by agriffard** [comment]
To build, I also had to do a `npm install` in the GraphQl module and some scripts are referenced in `wwwroot/node_modules/...`.

@Jetski5822 @jrestall Was this done like that on purpose?

**Comment by sebastienros** [comment]
Try to find the latest version of these libraries. Do the changes on a new branch because there might be many.

**Comment by agriffard** [comment]
It could be updated to jquery 3.3 at the same time.

I only found this: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jquery/index.d.ts

I'd like @sfmskywalker opinion on it.

**Comment by sebastienros** [comment]
I think we should propagate `npm install` to all modules if they have a package.json such that build/watch will work fine. And this would also allow us not to store these assets on github.

**Comment by sebastienros** [comment]
The graphql one is super weird, in the wwwroot :/ I am working on fixing it.

**Comment by jrestall** [comment]
> To build, I also had to do a `npm install` in the GraphQl module and some scripts are referenced in `wwwroot/node_modules/...`.
> 
> @Jetski5822 @jrestall Was this done like that on purpose?

@Skrypt will know, he added the gulp support to the graphql module.

**Comment by sebastienros** [comment]
I am currently testing this: `npm install --save src\OrchardCore.Modules\OrchardCore.Apis.GraphQL` to add a sub package.json to the main one. That should help. Then we can reference npm assets from `Assets.json` files

**Comment by sebastienros** [comment]
I got it working, I'll create a branch soon and we can work on it.

**Comment by Skrypt** [comment]
Yes it was done on purpose since these SASS files are compiled from source.

**Comment by sebastienros** [comment]
I created the sebros/gulp branch. It's showing how we can handle a package.json from a module. I don't have the typescript issue, but I get this 

```
C:\Users\sebros\Documents\Projects\Orchard2>gulp build
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\sebros\Documents\Projects\Orchard2\node_modules\node-sass\vendor'
    at Object.readdirSync (fs.js:783:3)
    at Object.getInstalledBinaries (C:\Users\sebros\Documents\Projects\Orchard2\node_modules\node-sass\lib\extensions.js:130:13)
    at foundBinariesList (C:\Users\sebros\Documents\Projects\Orchard2\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (C:\Users\sebros\Documents\Projects\Orchard2\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (C:\Users\sebros\Documents\Projects\Orchard2\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (C:\Users\sebros\Documents\Projects\Orchard2\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (C:\Users\sebros\Documents\Projects\Orchard2\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
```

**Comment by sebastienros** [comment]
Now I get this

```
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at C:\Users\sebros\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

**Comment by sebastienros** [comment]
This one is because it's using a global gulp instead of the local one ... some progress is being made

**Comment by sebastienros** [comment]
I fixed everything here: https://github.com/OrchardCMS/OrchardCore/pull/2791

Please review the changes. Also we'll be able to use more things from npm now, look at the examples.
