### ISSUE TITLE
Missing indexes

### ISSUE THREAD

**Issue by MZole** [OrchardCMS/OrchardCore#13225]
### Describe the bug

I have checked out the newest nightly version and tried to enable a bunch of features from a recipe and I get an error saying:
`SqliteException: SQLite Error 1: 'no such table: AutoroutePartIndex'.` I have checked out the database file, and many indexes are indeed missing.

Just for clarification, this recipe was working with 1.5, and I have also checked out what breaking changes are there since the 1.5 release, and it didn't seem to me that something would be wrong with the recipe, but I could be wrong.
Also, [here](https://github.com/OrchardCMS/OrchardCore/blob/main/src/docs/releases/1.6.0.md#features-and-recipes) in the docs, the feature name is changed from `OrchardCore.Features` to `OrchardCore.Feature`, I'm guessing this is just a typo.

### To Reproduce
1. Set up a site
2. Enable the deployments feature
3. Import as a package the following recipe:

```
{
  "steps": [
    {
      "name": "feature",
      "disable": [],
      "enable": [
        "OrchardCore.Admin",
        "OrchardCore.AdminDashboard",
        "OrchardCore.AdminMenu",
        "OrchardCore.AdminTemplates",
        "OrchardCore.Alias",
        "OrchardCore.Apis.GraphQL",
        "OrchardCore.AuditTrail",
        "OrchardCore.Autoroute",
        "OrchardCore.BackgroundTasks",
        "OrchardCore.ContentFields",
        "OrchardCore.ContentFields.Indexing.SQL",
        "OrchardCore.ContentFields.Indexing.SQL.UserPicker",
        "OrchardCore.ContentLocalization",
        "OrchardCore.ContentLocalization.ContentCulturePicker",
        "OrchardCore.ContentLocalization.Sitemaps",
        "OrchardCore.ContentPreview",
        "OrchardCore.ContentTypes",
        "OrchardCore.Contents",
        "OrchardCore.Contents.Deployment.AddToDeploymentPlan",
        "OrchardCore.Contents.Deployment.Download",
        "OrchardCore.Contents.Deployment.ExportContentToDeploymentTarget",
        "OrchardCore.Cors",
        "OrchardCore.CustomSettings",
        "OrchardCore.Deployment",
        "OrchardCore.Deployment.Remote",
        "OrchardCore.Diagnostics",
        "OrchardCore.DynamicCache",
        "OrchardCore.Features",
        "OrchardCore.Feeds",
        "OrchardCore.Flows",
        "OrchardCore.Forms",
        "OrchardCore.HealthChecks",
        "OrchardCore.HomeRoute",
        "OrchardCore.Html",
        "OrchardCore.Https",
        "OrchardCore.Indexing",
        "OrchardCore.Layers",
        "OrchardCore.Liquid",
        "OrchardCore.Lists",
        "OrchardCore.Localization",
        "OrchardCore.Localization.ContentLanguageHeader",
        "OrchardCore.Search.Lucene",
        "OrchardCore.Markdown",
        "OrchardCore.Media",
        "OrchardCore.Media.Cache",
        "OrchardCore.Menu",
        "OrchardCore.Navigation",
        "OrchardCore.Placements",
        "OrchardCore.Placements.FileStorage",
        "OrchardCore.PublishLater",
        "OrchardCore.Queries",
        "OrchardCore.Queries.Sql",
        "OrchardCore.ReCaptcha",
        "OrchardCore.ReCaptcha.Users",
        "OrchardCore.Recipes",
        "OrchardCore.RemotePublishing",
        "OrchardCore.Resources",
        "OrchardCore.ResponseCompression",
        "OrchardCore.ReverseProxy",
        "OrchardCore.Roles",
        "OrchardCore.Rules",
        "OrchardCore.Scripting",
        "OrchardCore.Seo",
        "OrchardCore.Settings",
        "OrchardCore.Shortcodes",
        "OrchardCore.Shortcodes.Templates",
        "OrchardCore.Sitemaps",
        "OrchardCore.Sitemaps.Cleanup",
        "OrchardCore.Sitemaps.RazorPages",
        "OrchardCore.Taxonomies",
        "OrchardCore.Taxonomies.ContentsAdminList",
        "OrchardCore.Templates",
        "OrchardCore.Tenants",
        "OrchardCore.Tenants.Distributed",
        "OrchardCore.Tenants.FeatureProfiles",
        "OrchardCore.Tenants.FileProvider",
        "OrchardCore.Themes",
        "OrchardCore.Title",
        "OrchardCore.Widgets",
        "OrchardCore.Workflows",
        "OrchardCore.Workflows.Http",
        "OrchardCore.Workflows.Timers",
        "OrchardCore.XmlRpc"
      ]
    }
  ]
}
```

**Comment by MikeAlhayek** [comment]
Did you check you logs? Most likely something is failing to migrate.  

That is a typo in the docs. If you want to enable `OrchardCore.Features` be sure to add it to the list.

**Comment by MikeAlhayek** [comment]
@MZole that issue in the change logs was fixed

**Comment by hishamco** [comment]
> That is a typo in the docs. If you want to enable OrchardCore.Features be sure to add it to the list.

`OrchardCore.Features` has been used above, but thanks for updating the docs. It happens :)

**Comment by MZole** [comment]
Thank you for your quick action :)
Yes, I have checked out the log, I just didn't want to paste it here since it's quite long, but you are right, the migrations fail, here is a short section of the exception thrown:

```
2023-02-10 16:51:21.8017|Default|00-dcec94762b38ba25c497ac086f8b32a2-3c324403da931e17-00||OrchardCore.Data.Migration.DataMigrationManager|ERROR|Error while running migration version 0 for 'OrchardCore.ContentFields'. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Can't load for update a cached object
   at OrchardCore.Documents.DocumentManager`1.GetOrCreateMutableAsync(Func`1 factoryAsync) in C:\Users\Zoli\source\repos\OrchardCore(Official)\src\OrchardCore\OrchardCore.Infrastructure\Documents\DocumentManager.cs:line 75
   at OrchardCore.ContentManagement.ContentDefinitionManager.LoadContentDefinitionRecord() in C:\Users\Zoli\source\repos\OrchardCore(Official)\src\OrchardCore\OrchardCore.ContentManagement\ContentDefinitionManager.cs:line 312
   at OrchardCore.ContentManagement.ContentDefinitionManager.LoadPartDefinitions() in C:\Users\Zoli\source\repos\OrchardCore(Official)\src\OrchardCore\OrchardCore.ContentManagement\ContentDefinitionManager.cs:line 117
   at OrchardCore.ContentManagement.Metadata.ContentDefinitionManagerExtensions.MigrateFieldSettings[TField,TSettings](IContentDefinitionManager manager) in C:\Users\Zoli\source\repos\OrchardCore(Official)\src\OrchardCore\OrchardCore.ContentManagement.Abstractions\IContentDefinitionManager.cs:line 121
   at OrchardCore.ContentFields.Migrations.Create() in C:\Users\Zoli\source\repos\OrchardCore(Official)\src\OrchardCore.Modules\OrchardCore.ContentFields\Migrations.cs:line 23
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in C:\Users\Zoli\source\repos\OrchardCore(Official)\src\OrchardCore\OrchardCore.Data.YesSql\Migration\DataMigrationManager.cs:line 200    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in C:\Users\Zoli\source\repos\OrchardCore(Official)\src\OrchardCore\OrchardCore.Data.YesSql\Migration\DataMigrationManager.cs:line 200
2023-02-10 16:51:21.8384|Default|00-dcec94762b38ba25c497ac086f8b32a2-3c324403da931e17-00||OrchardCore.Data.Migration.DataMigrationManager|ERROR|Error while running migration version 0 for 'OrchardCore.ContentLocalization'. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Can't load for update a cached object
   at OrchardCore.Documents.DocumentManager`1.GetOrCreateMutableAsync(Func`1 factoryAsync) in C:\Users\Zoli\source\repos\OrchardCore(Official)\src\OrchardCore\OrchardCore.Infrastructure\Documents\DocumentManager.cs:line 75
   at OrchardCore.ContentManagement.ContentDefinitionManager.LoadContentDefinitionRecord() in C:\Users\Zoli\source\repos\OrchardCore(Official)\src\OrchardCore\OrchardCore.ContentManagement\ContentDefinitionManager.cs:line 312
   at OrchardCore.ContentManagement.ContentDefinitionManager.LoadPartDefinition(String name) in C:\Users\Zoli\source\repos\OrchardCore(Official)\src\OrchardCore\OrchardCore.ContentManagement\ContentDefinitionManager.cs:line 84
   at OrchardCore.ContentManagement.Metadata.ContentDefinitionManagerExtensions.AlterPartDefinition(IContentDefinitionManager manager, String name, Action`1 alteration) in C:\Users\Zoli\source\repos\OrchardCore(Official)\src\OrchardCore\OrchardCore.ContentManagement.Abstractions\IContentDefinitionManager.cs:line 59
   at OrchardCore.ContentLocalization.Records.Migrations.Create() in C:\Users\Zoli\source\repos\OrchardCore(Official)\src\OrchardCore.Modules\OrchardCore.ContentLocalization\Migrations.cs:line 24
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in C:\Users\Zoli\source\repos\OrchardCore(Official)\src\OrchardCore\OrchardCore.Data.YesSql\Migration\DataMigrationManager.cs:line 200    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in C:\Users\Zoli\source\repos\OrchardCore(Official)\src\OrchardCore\OrchardCore.Data.YesSql\Migration\DataMigrationManager.cs:line 200
```

Also, the last version where this recipe works was v.17205, I hope these help to pinpoint quicker the source of the problem.

**Comment by jtkech** [comment]
@MZole 

Okay I could repro and it works if you remove from the list `OC.AdminDashboard` that uses a **migration** recipe `dashboard-widgets.recipe.json` that includes a `Feature` step which is not good.

After enabling features, the first shell scope activates the shell in a child scope that doesn't activate the shell again to prevent recursions, and where migrations are run, so if a migration executes a migration recipe, this is not good that this recipe enables features that may need their own migrations to be run.

Better to just add these features in the related module Manifest.

I will provide a PR, in the meantime you can just remove `OC.AdminDashboard`.

**Comment by MZole** [comment]
I see, thank you, I appreciate your effort :)
