### ISSUE TITLE
REDIS: Error closing the session in the SessionMiddleware

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#13235]
### Describe the bug
I am using REDIS server for distributed cache. I am also using `Users Authentication Ticket Store` feature to store user session info into the cache instead of the browser.

There is no notable error on the app UI. However, when I look at my error logs I see this error appearing all the time.

```
2023-02-10 18:25:55.3207|Default|00-9d3800b63eea150b6faf2b299236f220-a98e997451f10e6b-00||Microsoft.AspNetCore.Session.SessionMiddleware|ERROR|Error closing the session. StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=0KiB, 5980ms elapsed, timeout is 5000ms), command=HMGET, next: HMGET prodDefaultID_OrchardCore.Settings.SiteSettings, inst: 0, qu: 0, qs: 49, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: OrchardRedisCache.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: 6529da447765, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=2,Free=32765,Min=1,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisExtensions.HashMemberGetAsync(IDatabase cache, String key, String[] members)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAndRefreshAsync(String key, Boolean getData, CancellationToken token)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.RefreshAsync(String key, CancellationToken token)
   at Microsoft.AspNetCore.Session.DistributedSession.CommitAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)    at Microsoft.Extensions.Caching.StackExchangeRedis.RedisExtensions.HashMemberGetAsync(IDatabase cache, String key, String[] members)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAndRefreshAsync(String key, Boolean getData, CancellationToken token)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.RefreshAsync(String key, CancellationToken token)
   at Microsoft.AspNetCore.Session.DistributedSession.CommitAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
```

@ns8482e could this be an issue in the feature your created `Users Authentication Ticket Store`? @jtkech I believe you implementd the REDIS service and the distributed cache, any idea what could be causing this issue?

Here are similar logs in other instanced

```
2023-02-10 18:33:55.9844|None|00-703dc0a3cc1b6885372d9cabd4e423ce-4b228dcaa3702772-00||Microsoft.AspNetCore.Hosting.Diagnostics|INFO|Request starting HTTP/1.1 GET http://fullchargeapp.com/knowledge-base - - 
2023-02-10 18:33:55.9844|Default|00-703dc0a3cc1b6885372d9cabd4e423ce-4b228dcaa3702772-00||OrchardCore.Modules.ModularTenantRouterMiddleware|INFO|Begin Routing Request 
2023-02-10 18:34:01.3261|Default|00-703dc0a3cc1b6885372d9cabd4e423ce-4b228dcaa3702772-00||OrchardCore.Documents.DocumentManager|ERROR|Failed to read the 'AutorouteStateDocument' from the distributed cache StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=0KiB, 5332ms elapsed, timeout is 5000ms), command=HMGET, next: HMGET prodDefaultID_OrchardCore.Settings.SiteSettings, inst: 0, qu: 0, qs: 58, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: OrchardRedisCache.redis.cache.windows.net:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: 6529da447765, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=2,Free=32765,Min=1,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
```

**Comment by jtkech** [comment]
I have no idea for now.

Yes we have the `RedisService` used for example by `RedisLock` and `RedisTagCache`, but we don't have a custom Redis cache, we only configure `RedisCacheOptions` and register at the tenant level the regular `StackExchangeRedis.RedisCache` which is then used when `IDistributedCache` is resolved.

For example `DocumentManager` which is not aware of this, just injects and uses `IDistributedCache` directly, idem for the `CacheTicketStore` I assume.

It may depend how the `SessionMiddleware` is registered, hmm but looking at the trace it seems that you also have timeouts to get OC Documents as `prodDefaultID_OrchardCore.Settings.SiteSettings`.

**Comment by sebastienros** [comment]
Note that OC doesn't use Sessions.

**Comment by sebastienros** [comment]
You probably have `UseSession` somewhere in your code. Please try to remove it. It's not solving a potential bug but I think there is a confusion between sessions and tickets store.
