### ISSUE TITLE
Tenant initializing issue

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#13278]
Forgot to enable my SQL Server docker container.
First time I got an issue about a missing server at that location.
Then after enabling back the container I got this issue:

![image](https://user-images.githubusercontent.com/3228637/220139102-7e89bceb-809e-47bb-a099-fd3bdc4bd96c.png)

So, I'm thinking that the tenant did not enable itself properly and failed to initialize and the only thing that can be done then is to restart the app pool.

Seems like an issue with Redis being slow to initialize.

@jtkech

**Comment by jtkech** [comment]
Okay you are using a distributed lock because anyway LocalLock has no timeout.

I first thought about a process waiting for a lock while another process having the lock was waiting for a database connection. But before activating a tenant/shell, we first retrieve the shell descriptor from the database, so we already need to be able to connect to the database.

> Seems like an issue with Redis being slow to initialize.

So yes, I rather think about this too, maybe when the sql server was restarted, a request was able to retrieve the descriptor and then was waiting for a lock to activate the shell, not because another process already acquired the lock, but because, as you said, Redis was long to initialize.

If you are able to repro, for info the default value of a distributed lock timeout before activating a shell is 30s but it is configurable. If you are able to repro we can dig into it together if you want.

**Comment by hyzx86** [comment]
There's another error when you're initializing your tenant if you've noticed it, but when you install if there's a form validation error, it will allow the user to select the Recipe

**Comment by hyzx86** [comment]
I have the same problem, my Redis service is running on a LAN server and has been running for 3 days.

I found this problem today when I started OC local debugging.

But my desktop Redis client looked like everything was working



appsettings.Development.json
```json 
{
  "OrchardCore": {
 "OrchardCore_Shells_Database": {
      "DatabaseProvider": "SqlConnection", // Set to a supported database provider.
      // Set to the database connection string.
      "ConnectionString": "...........;TrustServerCertificate=True;MultipleActiveResultSets=True;",
      //"TablePrefix": "", // Optionally, configure a table prefix.
      "MigrateFromFiles": true // 可选地，允许将现有的App_Data文件自动迁移到数据库.
    },
    // See https://stackexchange.github.io/StackExchange.Redis/Configuration.html
    "OrchardCore_Redis": {
      "Configuration": "...........", // Redis Configuration string.
      "InstancePrefix": "easyoc_localServer_" // Optional prefix allowing a Redis instance to be shared by different applications.
    }
}
}
```

``` 
2023-05-25 14:34:02.5273||||OrchardCore.Environment.Shell.Distributed.DistributedShellHostedService|ERROR|Unable to read the distributed cache before checking if a tenant has changed. StackExchange.Redis.RedisServerException: Error: MISCONF Errors writing to the AOF file: Input/output error
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisExtensions.HashMemberGetAsync(IDatabase cache, String key, String[] members)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAndRefreshAsync(String key, Boolean getData, CancellationToken token)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAsync(String key, CancellationToken token)
   at Microsoft.Extensions.Caching.Distributed.DistributedCacheExtensions.GetStringAsync(IDistributedCache cache, String key, CancellationToken token)
   at OrchardCore.Environment.Shell.Distributed.DistributedShellHostedService.ExecuteAsync(CancellationToken stoppingToken)    at Microsoft.Extensions.Caching.StackExchangeRedis.RedisExtensions.HashMemberGetAsync(IDatabase cache, String key, String[] members)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAndRefreshAsync(String key, Boolean getData, CancellationToken token)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAsync(String key, CancellationToken token)
   at Microsoft.Extensions.Caching.Distributed.DistributedCacheExtensions.GetStringAsync(IDistributedCache cache, String key, CancellationToken token)
   at OrchardCore.Environment.Shell.Distributed.DistributedShellHostedService.ExecuteAsync(CancellationToken stoppingToken)

```
