### ISSUE TITLE
Workflow TimerBackgroundTask blocked and stuck in loop process

### ISSUE THREAD

**Issue by MohitNaroliya** [OrchardCMS/OrchardCore#13344]
### **Functionality**
We have a workflow which runs at 12:00 AM, on day 1 of the month **(Cron Expression 0 0 1 * *)**. Using that workflow, we send email notification to user. After the timer event we have Script task that executes a query to grab user details then we have a foreach loop task to iterate each of the user details then we have email task to send email notification to user. 

It was running fine from few months but this month when it did run, stuck in the loop and sent thousands of emails to the users, that process we try to terminate but no success then we did tenant reload and app pool restart to stop that. After that we noticed that that workflow not executing and other all timer workflow not executing as well. I did debug in VS and found below exception in log. 

For that fix I did clean ```WorkflowBlockingActivitiesIndex``` table and all workflow started working well. 

### **Exception in log**
```
2023-03-01 17:09:16.1746|JunctionCity|0HMOQ8MLJRKQV||OrchardCore.Modules.ModularBackgroundService|ERROR|Error while processing background task 'OrchardCore.Workflows.Timers.TimerBackgroundTask' on tenant 'TestCity'. System.NullReferenceException: Object reference not set to an instance of an object.
   at OrchardCore.Workflows.Services.WorkflowManager.ResumeWorkflowAsync(Workflow workflow, BlockingActivity awaitingActivity, IDictionary`2 input)
   at OrchardCore.Workflows.Services.WorkflowManager.TriggerEventAsync(String name, IDictionary`2 input, String correlationId, Boolean isExclusive, Boolean isAlwaysCorrelated)
   at OrchardCore.Workflows.Services.WorkflowManager.TriggerEventAsync(String name, IDictionary`2 input, String correlationId, Boolean isExclusive, Boolean isAlwaysCorrelated)
   at OrchardCore.Modules.ModularBackgroundService.<>c__DisplayClass11_2.<<RunAsync>b__1>d.MoveNext()    at OrchardCore.Workflows.Services.WorkflowManager.ResumeWorkflowAsync(Workflow workflow, BlockingActivity awaitingActivity, IDictionary`2 input)
   at OrchardCore.Workflows.Services.WorkflowManager.TriggerEventAsync(String name, IDictionary`2 input, String correlationId, Boolean isExclusive, Boolean isAlwaysCorrelated)
   at OrchardCore.Workflows.Services.WorkflowManager.TriggerEventAsync(String name, IDictionary`2 input, String correlationId, Boolean isExclusive, Boolean isAlwaysCorrelated)
   at OrchardCore.Modules.ModularBackgroundService.<>c__DisplayClass11_2.<<RunAsync>b__1>d.MoveNext()
```
### **Workflow Screenshot**
![image](https://user-images.githubusercontent.com/26460323/222417706-c21d6ed8-1b29-4cec-b628-f83ea9753b37.png)

**Comment by jtkech** [comment]
I can see that your cron expression is `* * 1 * *` which means on day-of-month 1 but[ at every minute during this day](https://crontab.guru/#*_*_1_*_*). You may need to use [something like that](https://crontab.guru/#0_0_1_*_*) `0 0 1 * *` instead.

**Comment by jtkech** [comment]
Oops forgot, this is what you are using ;)

**Comment by jtkech** [comment]
@MohitNaroliya 

Sorry I was not able to repro something similar, yes maybe a corrupted state in the database.

Are you using some custom Activity/Event, if so can you share some code?

For the ForEach activity what kind of expressions are you using for the From, To and Step values?

In your environment are you running multiple instances of your app? If so you may need to make your workflow atomic by using a distributed lock.

**Comment by MohitNaroliya** [comment]
@jtkech - Thank you for your response and try. 

Yes, we have a custom task to send email which we call Track Send Email, that custom task work same as the OC Send Email task, we just added that email entry in the email history table. 

**ForEach activity** 
![image](https://user-images.githubusercontent.com/26460323/222713674-7332f5e9-aa2c-407a-b3d4-2b2501be6488.png)

Sorry I didn't get your mean about running multiple instances. We have deployed that app on Azure app service, and it has above 30 tenants configured.

**Comment by jtkech** [comment]
Okay I could repro the same stack trace by simulating a null reference exception while resuming the WF, but this trace happened after you restarted the application, so it doesn't give us so much info about why you had an infinite loop. I tried to simulate a concurrency problem by using break points and for example by trying to remove blocking activities from the database while the WF is running, but was not able to repro the infinite loop, unless if the previous activity provide a big collection of items.

So finally I don't think it is a concurrency issue, maybe an use case where the previous activity provide a big collection to the loop, or an use case where the email task itself send many mails, but would need more info on your custom code.

---

That said here some info. Through the Admin UI you can remove the instances of a given WF. Hmm but it would not have stopped a current execution.

For example on Azure you could have a plan scaled out to use multiple running instances.

A WF has advanced propeties where you can set a timeout (to acquire a lock) and expiration (max time the lock can be held) knowing that as soon as the task using this lock completes, the lock is released. If you put non null values you will have by default a local lock and the WF is marked as atomic. To have a distributed lock you need a running Redis instance and enable the Redis.Lock feature.

If only a local lock we still check some states from the database, but still possible that 2 instances run the WF concurrently if they do the check at the exact same time.

**Comment by ShaneCourtrille** [comment]
@MohitNaroliya To answer your other question about instances, in Azure App Services you typically run multiple instances of your application using the "Scale out (App Service Plan)" configuration node.  MS recommends a minimum of 2 instances so that they can carry out normal maintenance without your site going down fully.

![image](https://github.com/OrchardCMS/OrchardCore/assets/121610/af2eaac3-badd-4d78-a7c3-b488f5c948a0)

**Comment by weirdyang** [comment]
May I know what caused the null reference error in the first place? Currently experiencing this issue too
