### ISSUE TITLE
Error with gulp rebuild

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#13683]
For a few days, I am having an error when I execute `gulp rebuild`:

```
[22:08:20] 'rebuild-assets' errored after 6.75 s
[22:08:20] Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm (D:\Orchard\OrchardCore\node_modules\gulp-typescript\node_modules\source-map\lib\read-wasm.js:8:13)
    at wasm (D:\Orchard\OrchardCore\node_modules\gulp-typescript\node_modules\source-map\lib\wasm.js:25:16)
    at D:\Orchard\OrchardCore\node_modules\gulp-typescript\node_modules\source-map\lib\source-map-consumer.js:264:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[22:08:20] 'rebuild' errored after 6.76 s
```

In order to make it work, I need to execute this command before the `gulp rebuild`:

`set NODE_OPTIONS=--no-experimental-fetch`

**Comment by hishamco** [comment]
I'm also get an error when I build from VS

**Comment by MikeAlhayek** [comment]
@agriffard I don't have any issue running `gulp rebuild`

I am using Node v18.6.0, npm version 9.6.5. You may want to try deleting your `node_modules`

**Comment by sebastienros** [comment]
I followed the instructions [here ](https://docs.orchardcore.net/en/latest/docs/guides/gulp-pipeline/#using-the-command-line) and it doesn't work: I can't run `gulp rebuild`

Probably because gulp is not correctly installed when doing `npm install`.

**Comment by agriffard** [comment]
Same error after deleting `node_modules`, reinstalling and rebuilding with node v20.1

**Comment by hishamco** [comment]
Node & `node_modules` made me crazy all the time :)

**Comment by MikeAlhayek** [comment]
All seems to be needed is to install `source-map` into the project. The PR seems to have fixed this issue.
