### ISSUE TITLE
OrchardCore.OpenId.Tasks.OpenIdBackgroundTask[0], An error occurred while pruning tokens from the database. Object does not match target type

### ISSUE THREAD

**Issue by hieucd04** [OrchardCMS/OrchardCore#14539]
### Environment
- Orchard Core: 1.7.2
- Database: MySQL (mariadb inside Docker)
- OS: My app runs inside Docker which runs inside windows 11

### To Reproduce
I'm just using Orchard Core normally then suddenly, these exceptions appear in my Docker logs stream.

### Expected behavior
No exception thrown.

### Logs
```
2023-10-18 08:00:56 fail: OrchardCore.OpenId.Tasks.OpenIdBackgroundTask[0]
2023-10-18 08:00:56       An error occurred while pruning tokens from the database.
2023-10-18 08:00:56       System.Reflection.TargetException: Object does not match target type.
2023-10-18 08:00:56          at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2023-10-18 08:00:56          at YesSql.Services.DefaultQuery.Evaluate(Expression expression)
2023-10-18 08:00:56          at YesSql.Services.DefaultQuery.ConvertFragment(IStringBuilder builder, Expression expression)
2023-10-18 08:00:56          at YesSql.Services.DefaultQuery.ConvertFragment(IStringBuilder builder, Expression expression)
2023-10-18 08:00:56          at YesSql.Services.DefaultQuery.ConvertComparisonBinaryExpression(IStringBuilder builder, BinaryExpression expression, String operation)
2023-10-18 08:00:56          at YesSql.Services.DefaultQuery.ConvertFragment(IStringBuilder builder, Expression expression)
2023-10-18 08:00:56          at YesSql.Services.DefaultQuery.ConvertEqualityBinaryExpression(IStringBuilder builder, BinaryExpression expression, String operation)
2023-10-18 08:00:56          at YesSql.Services.DefaultQuery.ConvertFragment(IStringBuilder builder, Expression expression)
2023-10-18 08:00:56          at YesSql.Services.DefaultQuery.Filter[TIndex](Expression`1 predicate)
2023-10-18 08:00:56          at YesSql.Services.DefaultQuery.Query`1.YesSql.IQuery<T>.With[TIndex](Expression`1 predicate)
2023-10-18 08:00:56          at YesSql.QueryExtensions.Query[T,TIndex](ISession session, Expression`1 predicate, Boolean filterType, String collection)
2023-10-18 08:00:56          at YesSql.QueryExtensions.Query[T,TIndex](ISession session, Expression`1 predicate, String collection)
2023-10-18 08:00:56          at OrchardCore.OpenId.YesSql.Stores.OpenIdTokenStore`1.PruneAsync(DateTimeOffset threshold, CancellationToken cancellationToken)
2023-10-18 08:00:56          at OrchardCore.OpenId.Tasks.OpenIdBackgroundTask.DoWorkAsync(IServiceProvider serviceProvider, CancellationToken cancellationToken)
2023-10-18 08:00:56 fail: OrchardCore.OpenId.Tasks.OpenIdBackgroundTask[0]
2023-10-18 08:00:56       An error occurred while pruning authorizations from the database.
2023-10-18 08:00:56       System.Reflection.TargetException: Object does not match target type.
2023-10-18 08:00:56          at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2023-10-18 08:00:56          at YesSql.Services.DefaultQuery.Evaluate(Expression expression)
2023-10-18 08:00:56          at YesSql.Services.DefaultQuery.ConvertFragment(IStringBuilder builder, Expression expression)
2023-10-18 08:00:56          at YesSql.Services.DefaultQuery.ConvertFragment(IStringBuilder builder, Expression expression)
2023-10-18 08:00:56          at YesSql.Services.DefaultQuery.ConvertComparisonBinaryExpression(IStringBuilder builder, BinaryExpression expression, String operation)
2023-10-18 08:00:56          at YesSql.Services.DefaultQuery.ConvertFragment(IStringBuilder builder, Expression expression)
2023-10-18 08:00:56          at YesSql.Services.DefaultQuery.ConvertEqualityBinaryExpression(IStringBuilder builder, BinaryExpression expression, String operation)
2023-10-18 08:00:56          at YesSql.Services.DefaultQuery.ConvertFragment(IStringBuilder builder, Expression expression)
2023-10-18 08:00:56          at YesSql.Services.DefaultQuery.Filter[TIndex](Expression`1 predicate)
2023-10-18 08:00:56          at YesSql.Services.DefaultQuery.Query`1.YesSql.IQuery<T>.With[TIndex](Expression`1 predicate)
2023-10-18 08:00:56          at YesSql.QueryExtensions.Query[T,TIndex](ISession session, Expression`1 predicate, Boolean filterType, String collection)
2023-10-18 08:00:56          at YesSql.QueryExtensions.Query[T,TIndex](ISession session, Expression`1 predicate, String collection)
2023-10-18 08:00:56          at OrchardCore.OpenId.YesSql.Stores.OpenIdAuthorizationStore`1.PruneAsync(DateTimeOffset threshold, CancellationToken cancellationToken)
2023-10-18 08:00:56          at OrchardCore.OpenId.Tasks.OpenIdBackgroundTask.DoWorkAsync(IServiceProvider serviceProvider, CancellationToken cancellationToken)

```

**Comment by jtkech** [comment]
Can't repro by just enabling these 2 features but there is nothing to prune, but I can see the query well executed in the background task (I set the period to 1 minute for testing).

**Comment by jtkech** [comment]
Can you check what you have in the `OpenIdAuthorizationIndex` table

**Comment by hieucd04** [comment]
Unfortunately, I factory reset my Docker several times during testing my code base with `1.7.2`.
I no longer have the DB from when those exceptions were thrown. I'm sorry!

**Comment by jtkech** [comment]
No problem

**Comment by jtkech** [comment]
In some model classes we changed a field `Id` from int to long but normally should not be a problem.

Are you starting nodes that use an existing database that were created from a previous version?

**Comment by hieucd04** [comment]
We start with a blank database and:
- We wrote an Orchard Core module which creates Content Type Definitions using `IContentDefinitionManager.AlterTypeDefinition`, `IContentDefinitionManager.AlterPartDefinition`, etc.
- We import our previously exported content data via Deployment Plan.

**Comment by jtkech** [comment]
> We start with a blank database and:

Okay I will try to repro tomorrow

**Comment by jtkech** [comment]
Which database are you using?

As a reminder I noticed that with `Sqlite` the `Id` primary key of the `Index Tables` are still an integer, not a bigint (by default), but normally should still work, but still an issue to fix.

**Comment by hieucd04** [comment]
I'm using MySQL 8

**Comment by jtkech** [comment]
By code I created and saved some `OpenIdAuthorization` in the `OpenId_Document` table, then the related `OpenId_OpenIdAuthorizationIndex` was well populated, and then the authorisations that was not valid was well pruned by the background task. So I was not able to repro.

Can you check if you have any error but before importing your contents or only partially?

And if you have time, check your OpenId tables, all prefixed with the `OpenId_` collection name, particularly the values of the `Type` column in the `OpenId_Document` table.

![OpenId Tables](https://github.com/OrchardCMS/OrchardCore/assets/8586360/811fb712-bccf-4247-98ce-b383224f6197)

Otherwise try to clean and rebuild your app, maybe some bad package restores.

---

I confirm, at least for `Sqlite` an autoincrement key can't be a bigint, only an integer.

**Comment by sebastienros** [comment]
> 2023-10-18 08:00:56          at YesSql.Services.DefaultQuery.Evaluate(Expression expression)

Looks like a reflection issue, since you are now using 1.7.2 I would assume that you have old versions of yessql around and now they are conflicting with the new one. Try to do a deep clean of your repository to get rid of older versions of yessql.

**Comment by hieucd04** [comment]
During the last 2 or 3 days, I have been attempting to reproduce this issue but without any success.
So, maybe you guys are right, this is probably a phantom issue caused by an unclean workspace.

Since this issue cannot be reproduced, there are nothing which can be done here.
I'm closing this one!

**Comment by jtkech** [comment]
Cool then, thanks for having tried it again

**Comment by Kees-Schouten** [comment]
I still have the same issue with Postgresl. I also commented on the issue in the yessql repository, see:

https://github.com/sebastienros/yessql/issues/531
