### ISSUE TITLE
Exception when enabling Lucene/Elasticsearch modules without enabling Queries module in GraphQL

### ISSUE THREAD

**Issue by mdameer** [OrchardCMS/OrchardCore#14999]
When trying to enable "Lucene" or "Elasticsearch" modules without enabling "Queries" module, then navigate to GraphiQL page it will return (500 Internal Server Error) with the following exception, due to trying resolve "IQueryManager" by "LuceneQueryFieldTypeProvider" and "ElasticQueryFieldTypeProvider":

System.NullReferenceException: Object reference not set to an instance of an object.
   at OrchardCore.Queries.Lucene.GraphQL.Queries.LuceneQueryFieldTypeProvider.GetIdentifierAsync() in /Users/mdameer/Downloads/OrchardCore-main/src/OrchardCore.Modules/OrchardCore.Search.Lucene/GraphQL/LuceneQueryFieldTypeProvider.cs:line 33
   at OrchardCore.Apis.GraphQL.Services.SchemaService.GetSchemaAsync() in /Users/mdameer/Downloads/OrchardCore-main/src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/Services/SchemaService.cs:line 87
   at OrchardCore.Apis.GraphQL.GraphQLMiddleware.ExecuteAsync(HttpContext context, ISchemaFactory schemaService, IDocumentWriter documentWriter) in /Users/mdameer/Downloads/OrchardCore-main/src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/GraphQLMiddleware.cs:line 141
   at OrchardCore.Apis.GraphQL.GraphQLMiddleware.Invoke(HttpContext context, IAuthorizationService authorizationService, IAuthenticationService authenticationService, ISchemaFactory schemaService, IDocumentWriter documentWriter) in /Users/mdameer/Downloads/OrchardCore-main/src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/GraphQLMiddleware.cs:line 64

I think that we need to add "OrchardCore. Queries" as a required feature for GraphQL startup in both modules, or create new features for GraphQL in both modules and set "OrchardCore. Queries" as a dependency, what do you think?

**Comment by hishamco** [comment]
```csharp
    [RequireFeatures("OrchardCore.Apis.GraphQL")]
    public class Startup : StartupBase
    {
        public override void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<ISchemaBuilder, LuceneQueryFieldTypeProvider>();
        }
    }
```

I'm not sure how the GraphiQL page shows up without enable `GraphQL` feature?

**Comment by MikeAlhayek** [comment]
> I think that we need to add "OrchardCore.Queries" as a required feature for GraphQL startup in both modules

@mdameer I agree with that statement.

**Comment by hishamco** [comment]
I thought @mdameer will start his first PR :)

**Comment by mdameer** [comment]
@hishamco it would have been a nice kick-off ;)
