### ISSUE TITLE
Exception during content item creation

### ISSUE THREAD

**Issue by alberthajdu** [OrchardCMS/OrchardCore#1514]
There is an unhandled exception during content item creation if you have a part named like a property on ContentItem.

Repro steps:
1. Create a new type.
2. Create a new Part named "Author". Add a field to this part.
3. Attach the part to the type.
4. Try to create a new item from the type.
5. Exception:
2018-02-22 15:52:53.7072|Test|0HLBPVKGT16L3:00000014||Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|ERROR|An unhandled exception has occurred while executing the request System.AggregateException: One or more errors occurred. (Unexpected character encountered while parsing value: {. Path 'Author', line 1, position 295.) ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'Author', line 1, position 295.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at OrchardCore.ContentManagement.ContentItemConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at YesSql.Session.<UpdateEntityAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YesSql.Session.<CommitAsync>d__29.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at YesSql.Session.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceScope.Dispose()
   at OrchardCore.Modules.ModularTenantContainerMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
---> (Inner Exception #0) Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'Author', line 1, position 295.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at OrchardCore.ContentManagement.ContentItemConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at YesSql.Session.<UpdateEntityAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YesSql.Session.<CommitAsync>d__29.MoveNext()<---
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at YesSql.Session.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceScope.Dispose()
   at OrchardCore.Modules.ModularTenantContainerMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

Maybe we could store the parts data in a Parts (or ContentParts like in the ContentDefinition recipe step) property thus avoiding these (and possible future) naming conflicts.

**Comment by sebastienros** [comment]
I suggest to add more validation instead. Adding a `Parts` property would make a big change.

**Comment by carlwoodhouse** [comment]
Oh man, just ran into this too ...

Created a ContentType 'Author' with a part of 'Author' and then if you try to create one you get the above

**Comment by deanmarcussen** [comment]
We currently validate with `ToSafeName` for this

Should be reasonably easy to add validation for the other content item properties which are as @Piedone says are "reserved".
