### ISSUE TITLE
InvalidOperationException when visiting GraphQL explorer

### ISSUE THREAD

**Issue by lampersky** [OrchardCMS/OrchardCore#15304]
I've just updated to the latest OC and getting this when visiting GraphiQL explorer:

```
System.InvalidOperationException: This graph type 'AutorouteInputObjectType' with name 'AutoroutePartInput' has already been initialized. Make sure that you do not use the same instance of a graph type in multiple schemas. It may be so if you registered this graph type as singleton; see https://graphql-dotnet.github.io/docs/getting-started/dependency-injection/ for more info.
   at GraphQL.Types.GraphType.Initialize(ISchema schema) in /_/src/GraphQL/Types/GraphType.cs:line 44
   at GraphQL.Types.SchemaTypes.AddType(IGraphType type, TypeCollectionContext context) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 522
   at GraphQL.Types.SchemaTypes.AddTypeIfNotRegistered(IGraphType type, TypeCollectionContext context) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 776
   at GraphQL.Types.SchemaTypes.Initialize(ISchema schema, IServiceProvider serviceProvider, IEnumerable`1 graphTypeMappings) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 277
   at GraphQL.Types.SchemaTypes..ctor(ISchema schema, IServiceProvider serviceProvider, IEnumerable`1 graphTypeMappings) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 190
   at GraphQL.Types.SchemaTypes..ctor(ISchema schema, IServiceProvider serviceProvider) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 175
   at GraphQL.Types.Schema.CreateSchemaTypes() in /_/src/GraphQL/Types/Schema.cs:line 477
   at GraphQL.Types.Schema.CreateAndInitializeSchemaTypes() in /_/src/GraphQL/Types/Schema.cs:line 448
   at GraphQL.Types.Schema.Initialize() in /_/src/GraphQL/Types/Schema.cs:line 196
   at OrchardCore.Apis.GraphQL.Services.SchemaService.GetSchemaAsync() in C:\repo\OrchardCore\src\OrchardCore.Modules\OrchardCore.Apis.GraphQL\Services\SchemaService.cs:line 116
   at OrchardCore.Apis.GraphQL.GraphQLMiddleware.ExecuteAsync(HttpContext context) in C:\repo\OrchardCore\src\OrchardCore.Modules\OrchardCore.Apis.GraphQL\GraphQLMiddleware.cs:line 142
   at OrchardCore.Apis.GraphQL.GraphQLMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\repo\OrchardCore\src\OrchardCore.Modules\OrchardCore.Apis.GraphQL\GraphQLMiddleware.cs:line 65
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
```

![image](https://github.com/OrchardCMS/OrchardCore/assets/6403130/e052141f-3c28-4824-b756-49218af27626)

**Comment by MikeAlhayek** [comment]
@hyzx86 I think the upgrade PR #15129 is causing multiple GraphQL issue and this is one of them.

**Comment by MikeAlhayek** [comment]
@lampersky can you please pull the latest from main or use the latest previews and see if this is still an issue for you?

**Comment by lampersky** [comment]
@MikeAlhayek same issue with latest changes from main:

![image](https://github.com/OrchardCMS/OrchardCore/assets/6403130/9c93181d-27be-43b5-bf47-9344ec09cff1)

**Comment by lampersky** [comment]
@MikeAlhayek I'm using `OrchardCore.Cms.Web` project from OC repo. No custom modules. Also I'm not registering any additional dependecies.

![image](https://github.com/OrchardCMS/OrchardCore/assets/6403130/c29b5257-1a00-4712-862a-3741c9d19ed3)

**Comment by MikeAlhayek** [comment]
Strange. Do you know if you are using a default recipe? I can't seems to reproduce the issue which is strange. I tried the blog recipe and enabled the GraphQL feature.

**Comment by lampersky** [comment]
@MikeAlhayek did you try to reconfigure existing ContentPart? and then go to GraphQL editor?

**Comment by MikeAlhayek** [comment]
Thanks I was able to reproduce. Check out the referenced PR if you have time to test it out.

**Comment by sebastienros** [comment]
@MikeAlhayek couldn't repro, what exactly did you do?

**Comment by MikeAlhayek** [comment]
First you have to visit the GraphiQL.  Then edit any content type "like the articles content type".

Then refresh GraphiQL page again and you should encounter the issue.
