### ISSUE TITLE
Invalid serial number for shell descriptor

### ISSUE THREAD

**Issue by cbadger-montecitobank** [OrchardCMS/OrchardCore#16019]
I get an "Invalid serial number for shell descriptor" error if I have a module with two data migrations, and each migration executes a recipe with a "Feature" step.  Example from DataMigration class:

        public async Task<int> CreateAsync()
        {
            await _recipeMigrator.ExecuteAsync("0001_migration.json", this);

            return 1;
        }

        public async Task<int> UpdateFrom1Async()
        {
            await _recipeMigrator.ExecuteAsync("0002_migration.json", this);

            return 2;
        }

Both recipes ("0001_migration.json" and "0002_migration.json") contain a "Feature" step that is meant to ensure certain core features are activated. If both of these migrations run back-to-back, which would happen when activating the feature for the first time, I get this error when the second recipe runs:

> `2024-05-08 13:45:50.2348|||0HN3FJV95DQPC:00000001|OrchardCore.Data.Migration.DataMigrationManager|ERR|Error while running migration version 1 for 'My.Test.Modules.FeaturesModule'.
System.InvalidOperationException: Invalid serial number for shell descriptor
   at OrchardCore.Environment.Shell.Data.Descriptors.ShellDescriptorManager.UpdateShellDescriptorAsync(Int32 priorSerialNumber, IEnumerable`1 enabledFeatures)
   at OrchardCore.Environment.Shell.ShellDescriptorFeaturesManager.UpdateFeaturesAsync(ShellDescriptor shellDescriptor, IEnumerable`1 featuresToDisable, IEnumerable`1 featuresToEnable, Boolean force)
   at OrchardCore.Features.Recipes.Executors.FeatureStep.ExecuteAsync(RecipeExecutionContext context)
   at OrchardCore.Recipes.Services.RecipeExecutor.<>c__DisplayClass7_0.<<ExecuteStepAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteStepAsync(RecipeExecutionContext recipeStep)
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, IDictionary`2 environment, CancellationToken cancellationToken)
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, IDictionary`2 environment, CancellationToken cancellationToken)
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, IDictionary`2 environment, CancellationToken cancellationToken)
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, IDictionary`2 environment, CancellationToken cancellationToken)
   at OrchardCore.Recipes.Services.RecipeMigrator.ExecuteAsync(String recipeFileName, IDataMigration migration)
   at Mbt.Phase7.Modules.FeaturesModule.Migrations.DataMigrations.UpdateFrom1Async() in C:\workspace\Mbt.Phase7\Modules\FeaturesModule\Migrations\DataMigrations.cs:line 24
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId)`

Works fine if I just have the one recipe run.

I'm running on OC 1.8.2.  Is there something I'm doing wrong here?  Other than abandoning the use of the RecipeMigrator to activate features, is there a way to make this work?

Thank you.

**Comment by Piedone** [comment]
This looks like a bug indeed, so your workaround is what you need to do currently. Declaring dependencies in your module's manifest is recommended anyway if your module indeed depends on them.

**Comment by gaojianzhuang** [comment]
The same error for me.
```
2024-10-13 14:21:12.8401|Default||0HN7B9S62296H:00000005|OrchardCore.Setup.Services.SetupService|ERR|An error occurred while initializing the datastore.
System.InvalidOperationException: Invalid serial number for shell descriptor
   at OrchardCore.Environment.Shell.Data.Descriptors.ShellDescriptorManager.UpdateShellDescriptorAsync(Int32 priorSerialNumber, IEnumerable`1 enabledFeatures)
   at OrchardCore.Setup.Services.SetupService.<>c__DisplayClass14_1.<<SetupInternalAsync>b__1>d.MoveNext()
2024-10-13 14:39:44.0474|Default||0HN7BA6RUM31P:00000005|OrchardCore.Setup.Services.SetupService|ERR|An error occurred while initializing the datastore.
System.InvalidOperationException: Invalid serial number for shell descriptor
   at OrchardCore.Environment.Shell.Data.Descriptors.ShellDescriptorManager.UpdateShellDescriptorAsync(Int32 priorSerialNumber, IEnumerable`1 enabledFeatures)
   at OrchardCore.Setup.Services.SetupService.<>c__DisplayClass14_1.<<SetupInternalAsync>b__1>d.MoveNext()
   ```

**Comment by tcobbfis** [comment]
> The same error for me on v2.0.2.
> 
> ```
> 2024-10-13 14:21:12.8401|Default||0HN7B9S62296H:00000005|OrchardCore.Setup.Services.SetupService|ERR|An error occurred while initializing the datastore.
> System.InvalidOperationException: Invalid serial number for shell descriptor
>    at OrchardCore.Environment.Shell.Data.Descriptors.ShellDescriptorManager.UpdateShellDescriptorAsync(Int32 priorSerialNumber, IEnumerable`1 enabledFeatures)
>    at OrchardCore.Setup.Services.SetupService.<>c__DisplayClass14_1.<<SetupInternalAsync>b__1>d.MoveNext()
> 2024-10-13 14:39:44.0474|Default||0HN7BA6RUM31P:00000005|OrchardCore.Setup.Services.SetupService|ERR|An error occurred while initializing the datastore.
> System.InvalidOperationException: Invalid serial number for shell descriptor
>    at OrchardCore.Environment.Shell.Data.Descriptors.ShellDescriptorManager.UpdateShellDescriptorAsync(Int32 priorSerialNumber, IEnumerable`1 enabledFeatures)
>    at OrchardCore.Setup.Services.SetupService.<>c__DisplayClass14_1.<<SetupInternalAsync>b__1>d.MoveNext()
> ```

I'm on 2.0.2 and I'm currently getting this error also

**Comment by JasonPG2007** [comment]
Is this still a valid issue now that didn't anyone solve it?

**Comment by Piedone** [comment]
Most possibly yes. However, I'd encourage you to try to reproduce bugs in such cases (when there's no apparent sign of it being fixed, like with a corresponding PR) with the latest `main`. Thank you!
