### ISSUE TITLE
fix: `InvalidOperationException` thrown in `QueryAliasIndex` when `ISession` is still in "connecting" state

### ISSUE THREAD

**Issue by ApacheTech** [OrchardCMS/OrchardCore#16069]
### Describe the bug

When loading multiple pages of a site quickly in multiple tabs, a `InvalidOperationException` exception is thrown, due to calling the `IOrchardHelper.GetContentItemByAliasAsync()` method.

```
InvalidOperationException: BeginExecuteReader requires an open and available Connection. The connection's current state is connecting.

    System.Threading.Tasks.ContinuationResultTaskFromResultTask<TAntecedentResult, TResult>.InnerInvoke()
    System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state)
    System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state)
    System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref Task currentTaskSlot, Thread threadPoolThread)
    Dapper.SqlMapper.QueryAsync<T>(IDbConnection cnn, Type effectiveType, CommandDefinition command) in SqlMapper.Async.cs
    YesSql.Store.ProduceAsync<T, TState>(WorkerQueryKey key, Func<TState, Task<T>> work, TState state)
    YesSql.Services.DefaultQuery+Query<T>.FirstOrDefaultImpl()
    YesSql.Services.DefaultQuery+Query<T>.FirstOrDefaultImpl()
    AliasPartRazorHelperExtensions.GetContentItemIdByAliasAsync(IOrchardHelper orchardHelper, string alias)
    AliasPartRazorHelperExtensions.GetContentItemByAliasAsync(IOrchardHelper orchardHelper, string alias, bool latest)
    Data8.Website.ApiDocs.Components.Abstractions.MenuContentItemComponentBase.OnInitializedAsync() in MenuContentItemComponentBase.cs
    30. ContentItem = await OrchardHelper.GetContentItemByAliasAsync(Alias);
```
### To Reproduce

My specific case uses a Blazor8 de-coupled site, global `InteractiveServer`, and uses `GetContentItemByAliasAsync` for menus, and routing.

Steps to reproduce the behaviour:
1. Within a site that uses `GetContentItemByAliasAsync` for anything such as routing, menus, etc.
2. Create a page with a link to a page that uses `GetContentItemByAliasAsync`.
3. Within your browser, use "middle-click" to open several tabs using that link. My specific case uses a menu, and opening multiple tabs with middle-click, one for each item of the menu.
4. On some tabs, you will see an `Internal Server Error`, with a stack-trace similar to above.

### Expected behaviour

Each tab should load correctly, waiting for the YesSql session to be open and available, before executing the query.

### Screenshots

![image](https://github.com/OrchardCMS/OrchardCore/assets/5599639/60f127f0-4c00-4554-9ba9-cf56ddcc08c0)

![image](https://github.com/OrchardCMS/OrchardCore/assets/5599639/fe43b3a3-825f-4d08-af6d-b1bce6bddcfe)

### Possible Solution

This method would likely need to be fleshed out to use a retry policy, or wait for the session to be open and available, before querying the database:

https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.Alias/Services/AliasPartContentHandleProvider.cs#L37

**Comment by Piedone** [comment]
Hmm, curious. Doesn't this look like some YesSql issue @sebastienros?

Which OC version are you using?

**Comment by ApacheTech** [comment]
OrchardCore 1.8.3

**Comment by Piedone** [comment]
Are you using SQL Server? And what's the hosting environment, SQL Azure?

**Comment by ApacheTech** [comment]
I have a suspicion that there is a YesSql connection service somewhere set to `Singleton`, and then a `Scoped` service is consuming that connection.

When I open multiple tabs, it is the older tabs that end up in error, not the new ones. If it was just congestion, or queuing, you would expect the new tabs performance to degrade overtime.

Tab 1 starts loading, initialises a connection. That connection gets cached as a singleton.
Tab 2 starts loading, initialises a connection. That connection gets cached as the same singleton.
Tab 3 starts loading, initialises a connection. That connection gets cached as the same singleton.
Tab 4 starts loading, initialises a connection. That connection gets cached as the same singleton.

At this point, Tab 1 has a cached connection that it expects to be open, and available, but it's actually only just been initialised by tab 4, and is still connecting.

That would seem to make sense, in this scenario.

**Comment by MikeAlhayek** [comment]
Can you try setting `MultipleActiveResultSets` to false?

**Comment by ApacheTech** [comment]
I have tried disabling MARS; it didn't make any difference.

**Comment by ApacheTech** [comment]
I've gone through the application on a `StateHasChanged` purge, and I've turned off pre-rendering, for now.

I've been able to uncover a different stack trace that seems to say that it is a race condition with the Dapper connection.

One scope is caching its connection, while another scope is trying to use that same cache. What I can't tell at the moment, is who is the onus on to ensure scope safety with this? Is it the app-dev (me), the framework (OC), or the data access (YesSql/Dapper)?

```
[2024-05-16T15:17:40.280Z] Error: System.InvalidOperationException: BeginExecuteReader requires an open and available Connection. The connection's current state is connecting.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__195_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 434
   at YesSql.Store.ProduceAsync[T,TState](WorkerQueryKey key, Func`2 work, TState state)
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at AliasPartRazorHelperExtensions.GetContentItemIdByAliasAsync(IOrchardHelper orchardHelper, String alias)
   at AliasPartRazorHelperExtensions.GetContentItemByAliasAsync(IOrchardHelper orchardHelper, String alias, Boolean latest)
   at Data8.Website.ApiDocs.Components.Abstractions.MenuContentItemComponentBase.OnInitializedAsync() in C:\dev\prop\Data8.Website\src\Data8.Website.ApiDocs\Components\Abstractions\MenuContentItemComponentBase.cs:line 30
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by MikeAlhayek** [comment]
@ApacheTech it could be something in the framework. 

Are you by any chance able to upgrade to 2.0? With 2.0 and the YesSql upgrade, there is an option to detect occurrent issue. If you are able to upgrade, you can configure YesSqlOptions by setting EnableThreadSafetyChecks to true.

**Comment by ApacheTech** [comment]
I thought OrchardCore only went to 1.8.3 at the moment?

After further digging, this is a clash between the Blazor component lifecycle, and whatever Dapper/Yessql/OC is doing behind the scenes. If I push all calls to `GetContentItemByAliasAsync` into `OnIntializedAsync`, instead of `OnParametersSetAsync`, then I don't seem to get the errors... but it also breaks the component. `OnInitializedAsync` is only called once per component, per circuit; you need the logic within `OnParametersSetAsync` to be able to handle the dynamic routing.

**Comment by MikeAlhayek** [comment]
> I thought OrchardCore only went to 1.8.3 at the moment?

1.8.3 is production ready. 2.0 "which will be released soon", is available using the preview feed.

https://docs.orchardcore.net/en/latest/getting-started/preview-package-source/

You can review the release notes and address all the breaking changes
https://docs.orchardcore.net/en/latest/releases/2.0.0/

**Comment by ApacheTech** [comment]
Well.... that's my Friday sorted.

Our GoLive is supposed to be around mid-June, early July. Is there a proposed release date for 2.0?

**Comment by Piedone** [comment]
There's no planned date but _maybe_ mid-June looks realistic.

We'll release once [all 2.0 issues are fixed](https://github.com/OrchardCMS/OrchardCore/milestone/18) and (due to the huge fundamental changes with migrating to `System.Text.Json`) we've done sufficient testing with some Lombiq projects (done for the OSS ones, just some last polishing: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/692) and Orchard Core Commerce (WIP: https://github.com/OrchardCMS/OrchardCore.Commerce/issues/442). Perhaps also DotNest.

If the open bugs don't affect you, and you don't mind potentially finding new ones, then you can use the preview packages right now. Then, upgrading to the actual released 2.0 version will be seamless for you (unless we add new breaking changes :)).

**Comment by sebastienros** [comment]
You can already try with the main branch or the nuget packages that ship nightly, no need to wait.

**Comment by sebastienros** [comment]
`MenuContentItemComponentBase.OnInitializedAsync()` seems to be calling `GetContentItemIdByAliasAsync`, correct?

In this case please add a `lock` on this method and tell us if that fixes the issue. If that is the case then your component is invoked by multiple threads which is not supported by YesSql (or dapper, or anything with transactions/connections). You would probably need to use some locking/semaphore, or find another way to do that, or fix the component.

**Comment by ApacheTech** [comment]
> `MenuContentItemComponentBase.OnInitializedAsync()` seems to be calling `GetContentItemIdByAliasAsync`, correct?
> 
> In this case please add a `lock` on this method and tell us if that fixes the issue. If that is the case then your component is invoked by multiple threads which is not supported by YesSql (or dapper, or anything with transactions/connections). You would probably need to use some locking/semaphore, or find another way to do that, or fix the component.

Using a `SemaphoreSlim(1, 1)`, it does seem to resolve this issue.

Would this be just a quirk of using OrchardCore with Blazor, or is it something that can be addressed at a lower level? If it is something for the app-dev to be aware of, that's fine. I'm seeing more and more people wanting to use Blazor with OrchardCore, so this is something good to know, and pass on to new devs dipping their toes in the water.

**Comment by MikeAlhayek** [comment]
@ApacheTech we welcome any PR that would improve things for Blazor. If you have an improvement, please submit a PR. I think @ns8482e and @agriffard worked with Blazor and OrchardCore.

**Comment by Piedone** [comment]
And @Skrypt.

**Comment by ApacheTech** [comment]
Was a fix for this ever added to 2.x?

**Comment by ApacheTech** [comment]
Thank you for your insightful, and detailed answer.

What is the expected ETA?

**Comment by Piedone** [comment]
Please look at the conversation above, and under your PR. This isn't actionable and thus won't be worked on.
