### ISSUE TITLE
GraphQL schema building fails and is inefficient

### ISSUE THREAD

**Issue by gvkries** [OrchardCMS/OrchardCore#16182]
### Describe the bug
After merging #16143, building the GraphQL schema may fail if a field is resolved through DI multiple times.
E.g. if we have a content type with a media field and also a `CustomUserSetting` with another media field as well, it fails with: 

```
System.InvalidOperationException: A different instance of the GraphType 'MediaFieldQueryObjectType' with the name 
'MediaField' has already been registered within the schema. Please use the same instance for all references 
within the schema, or use GraphQLTypeReference to reference a type instantiated elsewhere.
To view additional trace enable GlobalSwitches.TrackGraphTypeInitialization switch.
   at GraphQL.Types.SchemaTypes.EnsureTypeEquality(IGraphType existingType, IGraphType newType, TypeCollectionContext context) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 803
   at GraphQL.Types.SchemaTypes.AddTypeIfNotRegistered(IGraphType type, TypeCollectionContext context) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 780
   at GraphQL.Types.SchemaTypes.Initialize(ISchema schema, IServiceProvider serviceProvider, IEnumerable`1 graphTypeMappings) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 277
   at GraphQL.Types.SchemaTypes..ctor(ISchema schema, IServiceProvider serviceProvider, IEnumerable`1 graphTypeMappings) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 190
   at GraphQL.Types.SchemaTypes..ctor(ISchema schema, IServiceProvider serviceProvider) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 175
   at GraphQL.Types.Schema.CreateSchemaTypes() in /_/src/GraphQL/Types/Schema.cs:line 477
   at GraphQL.Types.Schema.CreateAndInitializeSchemaTypes() in /_/src/GraphQL/Types/Schema.cs:line 448
   at GraphQL.Types.Schema.Initialize() in /_/src/GraphQL/Types/Schema.cs:line 196
   at OrchardCore.Apis.GraphQL.Services.SchemaService.GetSchemaAsync() 

[...]
```
This comes from the fact that `ObjectGraphType<T>`s are now resolved multiple times as @tropcicstefan pointed out. The types are added manually to the schema and are also resolved by initializing the schema. This causes conflicting instances being used.

As we cannot register the GraphQL types as neither `Scoped` nor `Singleton`, we must ensure that building the schema will always use the correct instances. This may require some rework how we build the schema.

**Comment by MikeAlhayek** [comment]
@gvkries Isn't this addresses by #16151?

Do you know if this issue exists in 1.8 or just main?

**Comment by gvkries** [comment]
> @gvkries Isn't this addresses by #16151?
> 
> Do you know if this issue exists in 1.8 or just main?

Nope, I found this today. It's in main only. I'm providing an fix soon, I hope...

**Comment by MikeAlhayek** [comment]
okay. This is a 2.0 issue. If your PR is ready before the triage meeting in 2 hours, we can probably review the changes today. Trying to finish all the issues that are tagged with 2.0

**Comment by gvkries** [comment]
I added a PR as a proposal. Not sure about it, maybe too many changes... 😇 I changed how the GraphQL types are accessed quite a lot.
