### ISSUE TITLE
TimeField , DateTimeField and DateField  cannot be deserialised from Json

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#16203]
### Describe the bug
 
I found this in my custom code, but if someone has enabled the `OrchardCore.ContentFields.Indexing.SQL` feature on OC 2.0 and is using `TimeField` they will run into this problem!

### To Reproduce

         [Fact]
        public void TimeSpanFiledTests()
        {
            var jsonStr = """
                {
                    "Value":"13:05"
                }
                """;
            var jobject = JsonNode.Parse(jsonStr);
            var timeFiled = jobject.ToObject<TimeField>();

            Assert.Equal("13:05", timeFiled.Value.ToString());
        }

```
IContentHandler thrown from OrchardCore.ContentManagement.Handlers.ContentPartHandlerCoordinator by JsonException System.Text.Json.JsonException: The JSON value could not be converted to System.Nullable`1[System.TimeSpan]. Path: $.Value | LineNumber: 0 | BytePositionInLine: 16.
 ---> System.FormatException: The JSON value is not in a supported TimeSpan format.
   at System.Text.Json.ThrowHelper.ThrowFormatException(DataType dataType)
   at System.Text.Json.Serialization.Converters.TimeSpanConverter.ReadCore(Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.NullableConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpanAsObject(ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromNodeAsObject(JsonNode node, JsonTypeInfo jsonTypeInfo)
   at OrchardCore.ContentManagement.ContentExtensions.Get(ContentElement contentElement, Type contentElementType, String name)
   at OrchardCore.ContentManagement.Handlers.ContentPartHandlerCoordinator.InvokeHandlers[TContext,TFieldContext](TContext context, TFieldContext fieldContext, Func`4 partHandlerAction, Func`4 fieldHandlerAction, Boolean createPartIfNotExists, Boolean createFieldIfNotExists)
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger)    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpanAsObject(ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromNodeAsObject(JsonNode node, JsonTypeInfo jsonTypeInfo)
   at OrchardCore.ContentManagement.ContentExtensions.Get(ContentElement contentElement, Type contentElementType, String name)
   at OrchardCore.ContentManagement.Handlers.ContentPartHandlerCoordinator.InvokeHandlers[TContext,TFieldContext](TContext context, TFieldContext fieldContext, Func`4 partHandlerAction, Func`4 fieldHandlerAction, Boolean createPartIfNotExists, Boolean createFieldIfNotExists)
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger)
```

**Comment by Piedone** [comment]
Thanks for the test!

How exactly do you reproduce this with Field Indexing?

**Comment by hyzx86** [comment]
Because this code calls the deserialisation function

https://github.com/OrchardCMS/OrchardCore/blob/8ef3a02f8a8ff1313f2cfbe5f158fb34f46706f3/src/OrchardCore.Modules/OrchardCore.ContentFields/Indexing/SQL/TimeFieldIndexProvider.cs#L70-L83

**Comment by Piedone** [comment]
I mean, how do you use Field Indexing that brings this bug out?

**Comment by hyzx86** [comment]
> I mean, how do you use Field Indexing that brings this bug out?

我创建了一个配方，如果你导入它，将会在日志中看到详细的错误信息，我打算将它添加到 单元测试中

```json
{
  "name": "dynamicIndexTest",
  "displayName": "dynamicIndexTests",
  "description": "Test dynamicIndex",
  "author": "Tony Han",
  "website": "",
  "version": "1.0.0",
  "issetuprecipe": false,
  "categories": [ "test" ],
  "tags": [],
  "steps": [
    {
      "name": "Feature",
      "enable": [ "OrchardCore.ContentFields.Indexing.SQL" ]
    },
    {
      "name": "ContentDefinition",
      "ContentTypes": [
        {
          "Name": "Message",
          "DisplayName": "Message",
          "Settings": {
            "ContentTypeSettings": {
              "Creatable": true,
              "Draftable": true,
              "Versionable": true,
              "Listable": true,
              "Securable": true
            }
          },
          "ContentTypePartDefinitionRecords": [
            {
              "PartName": "Message",
              "Name": "Message",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "5"
                }
              }
            },
            {
              "PartName": "DIndexPart",
              "Name": "DIndexPart"
            }
          ]
        }
      ],
      "ContentParts": [
        {
          "Name": "Message",
          "Settings": {},
          "ContentPartFieldDefinitionRecords": [
            {
              "FieldName": "TextField",
              "Name": "TextFieldTest"
            },
            {
              "FieldName": "MultiTextField",
              "Name": "MultiTextFieldTest"
            },
            {
              "FieldName": "HtmlField",
              "Name": "HtmlFieldTest"
            },
            {
              "FieldName": "MediaField",
              "Name": "MediaFieldTest"
            },
            {
              "FieldName": "BooleanField",
              "Name": "BooleanFieldTest"
            },
            {
              "FieldName": "TimeField",
              "Name": "TimeFieldTest"
            },
            {
              "FieldName": "DateTimeField",
              "Name": "DateTimeFieldTest"
            },
            {
              "FieldName": "DateField",
              "Name": "DateFieldTest"
            },
            {
              "FieldName": "NumericField",
              "Name": "NumericFieldTest"
            },
            {
              "FieldName": "ContentPickerField",
              "Name": "ContentPickerFieldTest"
            },
            {
              "FieldName": "UserPickerField",
              "Name": "UserPickerFieldTest"
            }

          ]
        }
      ]
    },
    {
      "name": "content",
      "data": [
        {
          "ContentItemId": "testId1",
          "ContentType": "Message",
          "DisplayText": "Message",
          "Latest": true,
          "Published": true, 
          "Owner": "[js: parameters('AdminUserId')]",
          "Author": "[js: parameters('AdminUsername')]",
          "Message": {
            "TextFieldTest": { "Text": "TextFieldTestValue" },
            "MultiTextFieldTest": { "Values": [ "MultiTextFieldValue1", "MultiTextFieldValue2" ] },
            "HtmlFieldTest": { "Html": "HtmlFieldTestValue" },
            "MediaFieldTest": { "Paths": [ "Path1", "Path2" ] },
            "BooleanFieldTest": { "Value": true },
            "TimeFieldTest": { "Value": "12:05" },
            "DateTimeFieldTest": { "Value": "2024-5-5 22:50:58" },
            "DateFieldTest": { "Value": "2024-5-5" },
            "NumericFieldTest": { "Value": 123 },
            "ContentPickerFieldTest": { "ContentItemIds": [ "testContentItemId" ] },
            "UserPickerFieldTest": { "UserIds": [ "TestUserID" ] }
          },
          "TitlePart": {
            "Title": "[locale en]You have successfully registered![/locale][locale fr]Vous vous êtes inscrit avec succès![/locale]"
          }
        }
      ]
    }
  ]
}

```

**Comment by hyzx86** [comment]
STJ only supports `13:05:00` , but NSJ also supports `13:05` ~~ Maybe it can't be considered as a bug.

**Comment by Piedone** [comment]
Thanks for the details! All clear now.

Since this breaks existing installations that use `TimeField` (right?), it's a bug. I suggest two things:

- Foremost, see if you can get STJ to deserialize this with some serializer settings. If yes, then all good.
- If not, or perhaps additionally, change `TimeField` to also save the seconds (as `00`).

Please let me know once the PR is ready.

**Comment by hyzx86** [comment]
It looks like there is a similar problem with `DateField` and `DateTimeField` . It looks like there's more formatting requirements in STJ.

```
    System.Text.Json.JsonException : The JSON value could not be converted to System.Nullable`1[System.DateTime]. Path: $.Value | LineNumber: 0 | BytePositionInLine: 26.
    ---- System.FormatException : The JSON value is not in a supported DateTime format.
```

**Comment by sebastienros** [comment]
So it's not related to SQL Indexing, right? It's just that indexing triggered the code path that was deserializing the document to a `TimeField`, but this should be reproduced without it?

Could you share what JSON is saved with 1.8.3 (NSJ) in a document when using such fields? Just to confirm that it's NSJ that created this format, and that the DateTime format it used is also incompatible with STJ. This might be related to the culture when it saved the valus with NSJ.

**Comment by hyzx86** [comment]
@sebastienros Maybe this unit test can verify this

https://github.com/OrchardCMS/OrchardCore/pull/16205/files#diff-2bcc78e3f585c1b83870f961490da0f13bc6b560422f0960751e739aad947938
