### ISSUE TITLE
How can I passing data from a shape to a shape and using received data?

### ISSUE THREAD

**Issue by lthoa** [OrchardCMS/OrchardCore#1625]
How can I passing data to a shape and using received data?

**The example below does not work:**
_In Content__LandingPage template:_
{% shape "Content__About" for Model.ContentItem.Content.About %}

_In Content__About template:_
{% if Model.Items.size > 0 %}
....

**Comment by sebastienros** [comment]
I understand you are trying to use the same way we can pass data using the `include` tag, but with a shape. Maybe we should expose a global object that shapes could use, and where we could freely set data. I tried to prevent to be able to change any state in liquid, for safety.

**Comment by sebastienros** [comment]
Or support the `for` parameter like `include` does, but with shapes. But this is actually changing the model. Or expose the caller's variables. Maybe this latest suggestion work already, using `assign` and trying to access the values from the other shape template.

**Comment by jtkech** [comment]
I don't remember the details around this but it seems that it would be useful. So, the first question would be if you want to allow this. Hmm, for liquid maybe we could use the `HttpContext` to hold some shared values during a request.

I was not aware of the `include` tag and to be able to use it with `for`. Can we already use it in our solution in a liquid template? Is there any example?

**Comment by paynecrl97** [comment]
I think the `include` tag is a Shopify specific tag as opposed to a liquid tag? It has access to the caller's variables, but I don't *think* any changes made to those variables by the included snippet will make it back up to the caller's scope (https://help.shopify.com/themes/liquid/tags/theme-tags#include).

Anyway, this is how I've been passing data to shapes:

```
{{ "Content__About" | shape_new: SomeProperty: MyPropertiesValue | shape_render }}
```

And then, in the `Content__About` liquid file, you'll be able to access `MyPropertiesValue` like so: `Model.SomePropertyValue`.

**Comment by jtkech** [comment]
👍 didn't think about using `shape_new`. Looks like to be the solution, not just a workaround.

**Comment by Skrypt** [comment]
I tried using {% include 'SomeLiquidTemplate' %} and it fails with a file not found exception. Though using the trick of creating a new shape works. Should we not support also simply the `include` filter?

**Comment by sebastienros** [comment]
I don't think we ever set the `TemplateContext` local or global FileProvider. It might remain to `NullProvider` which is the default in liquid.

**Comment by Skrypt** [comment]
Here is the exception logged : 

```
2019-06-13 15:29:20.6301|Default|80000069-0005-fc00-b63f-84710c7967bb||OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay|ERROR|Func`2 thrown from System.Func`2[[OrchardCore.DisplayManagement.Implementation.ShapeDisplayContext, OrchardCore.DisplayManagement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Threading.Tasks.Task, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] by FileNotFoundException System.IO.FileNotFoundException: Searchbox.liquid
   at Fluid.Ast.IncludeStatement.WriteToAsync(TextWriter writer, TextEncoder encoder, TemplateContext context)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Fluid.BaseFluidTemplate`1.RenderAsync(TextWriter writer, TextEncoder encoder, TemplateContext context)
   at OrchardCore.Liquid.Services.LiquidShapes.BuildViewModelAsync(ShapeDisplayContext shapeDisplayContext) in E:\Repositories\AffairesExtra - OrchardCore\src\OrchardCore.Modules\OrchardCore.Liquid\Services\LiquidShapes.cs:line 28
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents](IEnumerable`1 events, Func`2 dispatch, ILogger logger) in E:\Repositories\AffairesExtra - OrchardCore\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 78    at Fluid.Ast.IncludeStatement.WriteToAsync(TextWriter writer, TextEncoder encoder, TemplateContext context)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Fluid.BaseFluidTemplate`1.RenderAsync(TextWriter writer, TextEncoder encoder, TemplateContext context)
   at OrchardCore.Liquid.Services.LiquidShapes.BuildViewModelAsync(ShapeDisplayContext shapeDisplayContext) in E:\Repositories\AffairesExtra - OrchardCore\src\OrchardCore.Modules\OrchardCore.Liquid\Services\LiquidShapes.cs:line 28
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents](IEnumerable`1 events, Func`2 dispatch, ILogger logger) in E:\Repositories\AffairesExtra - OrchardCore\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 78
```

**Comment by sebastienros** [comment]
I suggest a `shape_property [name], [value]` filter since we have a `Properties` dictionary on `IShape` now

**Comment by jptissot** [comment]
Implemented in PR.
