### ISSUE TITLE
OrchardCore_Media__AssetsPaths says it supports absolute paths but doesn't

### ISSUE THREAD

**Issue by rjpowers10** [OrchardCMS/OrchardCore#16263]
### Describe the bug
[The media docs state](https://docs.orchardcore.net/en/latest/reference/modules/Media/#configuration) that absolute paths can be used for the AssetsPath variable. However, trying to do so results in an invalid path.

```
// The path used to store media assets. The path can be relative to the tenant's App_Data folder, or absolute.
"AssetsPath": "Media",
```

### Orchard Core version
1.8.2, but looking at the code I'm pretty sure the issue exists in the main branch as well.

### To Reproduce
1. Set OrchardCore__OrchardCore_Media__AssetsPath to an absolute path.
2. Start the site.

[It looks like the code](https://github.com/OrchardCMS/OrchardCore/blob/da734895847ed789354250ca53387250745328e1/src/OrchardCore.Modules/OrchardCore.Media/Startup.cs#L229) is simply concatenating the paths without checking if the setting is absolute.

### Expected behavior
The media is stored in the directory specified by the absolute path without exceptions.

### Logs and screenshots
![image](https://github.com/OrchardCMS/OrchardCore/assets/68876423/f6353019-d0d8-41e9-ac5a-b86c69ff3d8f)

```
2024-06-07T13:24:22.5612455-04:00||0HN472QE302SN:00000005|Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|ERR|An unhandled exception has occurred while executing the request.
System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\[REDACTED]\source\repos\[REDACTED]\src\[REDACTED]\App_Data\Sites\Default\C:\Users\[REDACTED]\Desktop\Media'
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at OrchardCore.Media.Startup.<>c.<ConfigureServices>b__4_1(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at OrchardCore.Media.Startup.Configure(IApplicationBuilder app, IEndpointRouteBuilder routes, IServiceProvider serviceProvider)
   at OrchardCore.Modules.ShellPipelineExtensions.ConfigurePipelineAsync(IApplicationBuilder builder)
   at OrchardCore.Modules.ShellPipelineExtensions.BuildPipelineInternalAsync(ShellContext context)
   at OrchardCore.Modules.ShellPipelineExtensions.BuildPipelineAsync(ShellContext context)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at OrchardCore.Logging.SerilogTenantNameLoggingMiddleware.Invoke(HttpContext context)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.<>c__DisplayClass4_0.<<Invoke>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by Piedone** [comment]
I'm not sure how this could actually work well. I think rather the docs should be fixed.

With the current logic, this config is a path under the configurable App_Data, and under a tenant-specific folder.

If we were to actually allow absolute paths, then we'd either need to somehow also support (or guard against) putting all Media files for all tenants into the same folder, or we'd need to add tenant-specific folder under it. In the latter case, the semantics of the config would be different in the absolute and relative case, or we'd need to introduce a new config for the absolute one.

In the interim, configuring `ShellOptions.ShellsApplicationDataPath` isn't suitable for you BTW?

**Comment by rjpowers10** [comment]
I have a customer wanting to do an on-prem IIS install and I'm hoping to make the root folder stateless, much like I do in Azure App Service with  `OrchardCore.Media.Azure`, `OrchardCore.DataProtection.Azure`, and `OrchardCore.Shells.Azure`. I was approaching the problem my trying to move those folders individually (like App Service) but thanks for pointing out `ShellOptions.ShellsApplicationDataPath`. That seems like a better direction for me. I'll try that approach.
