### ISSUE TITLE
OrchardCore.Twitter breaks workflow editor

### ISSUE THREAD

**Issue by sarahelsaig** [OrchardCMS/OrchardCore#16349]
### Describe the bug

Trying to access the workflow editor results in an exception stating "The shape type 'UpdateTwitterStatusTask_Fields_Thumbnail' is not found". Presumably caused by the X/Twitter rename.

### Orchard Core version

Latest preview and `main`.

### To Reproduce
1. Set up site.
2. Go to Admin > Configurations > Features
3. Enable `OrchardCore.Workflows` and `OrchardCore.Twitter` features
4. Go to Admin > Workflows
5. Create a workflow.
6. Click the Edit button.
7. Observe the shape error below.

### Expected behavior

Shape should exist.

### Logs and screenshots

Exception:
```
2024-06-19 22:54:47.3850|Default|00-04f0a42200845818f451ada9ad045b2d-d31a032860419f6b-00|1|Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|ERROR|An unhandled exception has occurred while executing the request. System.Exception: The shape type 'UpdateTwitterStatusTask_Fields_Thumbnail' is not found
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs:line 130
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs:line 189
   at OrchardCore.DisplayManagement.Zones.ZoneShapes.ContentZone(IDisplayHelper DisplayAsync, Object Shape, IShapeFactory ShapeFactory) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.DisplayManagement/Zones/ZoneShapes.cs:line 54
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.<ProcessAsync>g__Awaited|13_0(Task`1 task) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs:line 300
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs:line 135
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs:line 189
   at CallSite.Target(Closure, CallSite, Object)
   at AspNetCoreGeneratedDocument.Views_Activity_Thumbnail.ExecuteAsync() in /home/sarah/Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Workflows/Views/Activity.Thumbnail.cshtml:line 7
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(String partialViewName, Object model, ViewDataDictionary viewData, TextWriter writer)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.PartialAsync(String partialViewName, Object model, ViewDataDictionary viewData)
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.<ProcessAsync>g__Awaited|13_0(Task`1 task) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs:line 300
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs:line 135
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs:line 189
   at CallSite.Target(Closure, CallSite, Object)
   at AspNetCoreGeneratedDocument.Views_WorkflowType_Edit.ExecuteAsync() in /home/sarah/Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Workflows/Views/WorkflowType/Edit.cshtml:line 88
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Liquid.ScriptsMiddleware.Invoke(HttpContext httpContext) in /home/sarah/Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Liquid/ScriptsMiddleware.cs:line 70
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext() in /home/sarah/Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Diagnostics/DiagnosticsStartupFilter.cs:line 34
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore/Modules/ModularTenantRouterMiddleware.cs:line 47
   at OrchardCore.Modules.ModularTenantContainerMiddleware.<>c__DisplayClass4_0.<<Invoke>b__0>d.MoveNext() in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore/Modules/ModularTenantContainerMiddleware.cs:line 61
--- End of stack trace from previous location ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs:line 291
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs:line 296
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs:line 301
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs:line 306
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs:line 307
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore/Modules/ModularTenantContainerMiddleware.cs:line 59
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)    at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs:line 130
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs:line 189
   at OrchardCore.DisplayManagement.Zones.ZoneShapes.ContentZone(IDisplayHelper DisplayAsync, Object Shape, IShapeFactory ShapeFactory) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.DisplayManagement/Zones/ZoneShapes.cs:line 54
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.<ProcessAsync>g__Awaited|13_0(Task`1 task) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs:line 300
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs:line 135
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs:line 189
   at CallSite.Target(Closure, CallSite, Object)
   at AspNetCoreGeneratedDocument.Views_Activity_Thumbnail.ExecuteAsync() in /home/sarah/Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Workflows/Views/Activity.Thumbnail.cshtml:line 7
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(String partialViewName, Object model, ViewDataDictionary viewData, TextWriter writer)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.PartialAsync(String partialViewName, Object model, ViewDataDictionary viewData)
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.<ProcessAsync>g__Awaited|13_0(Task`1 task) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs:line 300
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs:line 135
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultHtmlDisplay.cs:line 189
   at CallSite.Target(Closure, CallSite, Object)
   at AspNetCoreGeneratedDocument.Views_WorkflowType_Edit.ExecuteAsync() in /home/sarah/Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Workflows/Views/WorkflowType/Edit.cshtml:line 88
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Liquid.ScriptsMiddleware.Invoke(HttpContext httpContext) in /home/sarah/Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Liquid/ScriptsMiddleware.cs:line 70
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext() in /home/sarah/Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Diagnostics/DiagnosticsStartupFilter.cs:line 34
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore/Modules/ModularTenantRouterMiddleware.cs:line 47
   at OrchardCore.Modules.ModularTenantContainerMiddleware.<>c__DisplayClass4_0.<<Invoke>b__0>d.MoveNext() in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore/Modules/ModularTenantContainerMiddleware.cs:line 61
--- End of stack trace from previous location ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs:line 291
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs:line 296
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs:line 301
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs:line 306
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs:line 307
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in /home/sarah/Projects/OrchardCore/src/OrchardCore/OrchardCore/Modules/ModularTenantContainerMiddleware.cs:line 59
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by sarahelsaig** [comment]
As far as I can see the shapes such as [UpdateXStatusTask.Fields.Design.cshtml](https://github.com/OrchardCMS/OrchardCore/blob/9d79ab57351a0703e72c5a9278d6d2739de440a1/src/OrchardCore.Modules/OrchardCore.Twitter/Views/Items/UpdateXStatusTask.Fields.Design.cshtml#L4) should retain the "Twitter" name because all the matching models (such as [UpdateTwitterStatusTaskViewModel](https://github.com/OrchardCMS/OrchardCore/blob/9d79ab57351a0703e72c5a9278d6d2739de440a1/src/OrchardCore.Modules/OrchardCore.Twitter/Workflows/ViewModels/UpdateTwitterStatusTaskViewModel.cs#L5)), the drivers, and the module itself still have "Twitter" in the type name. It's also an unnecessary non-user-facing breaking change. What do you think? @hishamco @MikeAlhayek

**Comment by MikeAlhayek** [comment]
Maybe rollback the PR that changed Twitter to X.

**Comment by hishamco** [comment]
I remember there was a PR follow-up after renaming the module. Is the issue with backward compatibility or breaks the workflow editor only?

**Comment by sarahelsaig** [comment]
I've only tested the workflow creation. I wanted to edit unrelated workflows and this feature just happened to be enabled at the same time and interfered.

I don't have a key for the Twitter 1.1 API that the [`TwitterClient`](https://github.com/OrchardCMS/OrchardCore/blob/9d79ab57351a0703e72c5a9278d6d2739de440a1/src/OrchardCore.Modules/OrchardCore.Twitter/Services/TwitterClient.cs#L49) service uses so I couldn't test the actual functionality of the workflow..As I understand you can't get new 1.1 keys any more. Also now I find out that [the 1.1 API has been deprecated and access has been limited](https://devcommunity.x.com/t/v1-1-api-no-longer-working/199890/4) since last year. For this reason maybe it would be best to remove the [`UpdateTwitterStatusTask`](https://github.com/OrchardCMS/OrchardCore/blob/9d79ab57351a0703e72c5a9278d6d2739de440a1/src/OrchardCore.Modules/OrchardCore.Twitter/Workflows/Activities/UpdateTwitterStatusTask.cs#L12) or at least mark it as deprecated in the task description and [in the docs](https://docs.orchardcore.net/en/latest/reference/modules/X/#x-twitter-integration)?

**Comment by Piedone** [comment]
This issue is not just for backward compatibility, the Twitter feature completely breaks the Workflows editor on a newly set up site too.

**Comment by Piedone** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/15930 was also opened for this previously and I think we should take that: either we shouldn't care about the whole X rename much and add it solely to UI labels, or we should commit and do it fully, what that PR is supposed to address.
