### ISSUE TITLE
Enabling feature breaks Admin Menu

### ISSUE THREAD

**Issue by MikeAlhayek** [OrchardCMS/OrchardCore#16405]
### Describe the bug
Enabled any feature seems to break the Admin Menu. I think this is SJT related issue

### Orchard Core version

Add the version of the Orchard Core NuGet packages you use, or the commit hash if you can reproduce this with the source code.

### To Reproduce
1. Enable Redis cache feature
2. Enabled Admin Menu and add 2 content type menu nodes
3. Go to Configurations >> Recipes >> Run the `Blog - Lucene Search` recipe
4. you'll notice the menu items disappeared from the left side.
5. Also, if you go to Configuration >> Admin Menus >> Edit nodes

 > Can't show the item of type: OrchardCore.AdminMenu.Models.AdminNode. Maybe a required module has been disabled?

![image](https://github.com/OrchardCMS/OrchardCore/assets/24724371/74cb5094-9e20-4aee-985a-bcadc6b9eb28)

### Logs and screenshots
> OrchardCore.AdminMenu.Services.AdminMenuNavigationProvidersCoordinator|ERROR|No Builder registered for admin node of type 'AdminNode' 

https://github.com/OrchardCMS/OrchardCore/blob/52dca204ee223fb8495dcd1e3fae03a4b1129fbd/src/OrchardCore.Modules/OrchardCore.AdminMenu/Services/AdminMenuNavigationProvidersCoordinator.cs#L71

**Comment by MikeAlhayek** [comment]
@Piedone can you recreate this issue is your environment?

@gvkries could this be related to  `ITypeFeatureProvider` changes?

**Comment by Piedone** [comment]
With 52dca204ee223fb8495dcd1e3fae03a4b1129fbd I can't see this, some repro steps are missing I assume. Starting with the Blog recipe, it works:

![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/368d976b-2aac-4e5d-91a5-a8b8578e347d)

BTW you have to show what the Simulator menu does :).

**Comment by MikeAlhayek** [comment]
@Piedone I am afraid that is confidential demo for the 2024 conference :) 

By the way, I get the same issue when also running a recipe.

**Comment by Piedone** [comment]
What exactly are you doing? I have no repro with 80ef1c7a0860a35b0260e833ee6b0161cd53e442:



https://github.com/OrchardCMS/OrchardCore/assets/1976647/35dde921-54db-4596-9db3-3f818ae54589


This tarts after an SQLite Blog setup.

**Comment by gvkries** [comment]
I also cannot reproduce this...

**Comment by MikeAlhayek** [comment]
I am looking more into this. This seems to only happens when REDIS cache is enabled.

Try starting your app with the following and configure REDIS instance.

```
ocBuilder.AddSetupFeatures("OrchardCore.Redis", "OrchardCore.Redis.Lock")
         .AddGlobalFeatures("OrchardCore.Redis",
         "OrchardCore.Redis.Cache",
         "OrchardCore.Redis.DataProtection",
         "OrchardCore.Redis.Lock");
```

**Comment by MikeAlhayek** [comment]
This may not be related but I am seeing this in the logs

```

ERROR|Failed to read the 'ContentDefinitionRecord' from the distributed cache System.Text.Json.JsonException: '0x1F' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '0x1F' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at System.Text.Json.JConvert.DeserializeObject[TValue](String json, JsonSerializerOptions options)
   at OrchardCore.Documents.DefaultDocumentSerializer.DeserializeAsync[TDocument](Byte[] data)
   at OrchardCore.Documents.DocumentManager`1.GetFromDistributedCacheAsync()
   at OrchardCore.Documents.DocumentManager`1.GetInternalAsync(Boolean failover)
   at OrchardCore.Documents.DocumentManager`1.GetOrCreateImmutableAsync(Func`1 factoryAsync)    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at System.Text.Json.JConvert.DeserializeObject[TValue](String json, JsonSerializerOptions options)
   at OrchardCore.Documents.DefaultDocumentSerializer.DeserializeAsync[TDocument](Byte[] data)
   at OrchardCore.Documents.DocumentManager`1.GetFromDistributedCacheAsync()
   at OrchardCore.Documents.DocumentManager`1.GetInternalAsync(Boolean failover)
   at OrchardCore.Documents.DocumentManager`1.GetOrCreateImmutableAsync(Func`1 factoryAsync)
```

**Comment by Piedone** [comment]
I see, then maybe this is again an STJ issue. I won't be able to try it anytime soon, but I guess this being related to Redis was the missing piece.

**Comment by MikeAlhayek** [comment]
I figured out the issue with `ERROR|Failed to read the 'ContentDefinitionRecord' from the distributed cache System.Text.Json.JsonException: '0x1F' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.`

I'll submit a PR to fix that issue. It could also fix this issue as well.

**Comment by MikeAlhayek** [comment]
PR #16414 Fixes the `Failed to read the 'ContentDefinitionRecord' from the distributed cache System.Text.Json.JsonException: '0x1F'` error. But does not fix the AdminMenu issue.

**Comment by MikeAlhayek** [comment]
PR #16415 seems to have fixed this issue!

**Comment by Piedone** [comment]
Combo breaker :).
