### ISSUE TITLE
Create Localized Name Tenant, An error occured while executing this request!

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1658]
1.Create Tenant
2.Name <If this name is "Chinese", other languages are not tested>   **Here is the cause of the error**
`The name of the tenant.`
3.setup
4.Tenants /admin account
5: "An error occurred while executing this request."

```
1.创建租户
2.Name <这里名字如果是“中文”，其它语言未测试>**这里是造成错误的原因**
`租客的名字.`
3.设置
4.登陆租户 /管理员帐户
5：出现错误“执行此请求时发生错误。”
```

Create Name Tenant, whether it can consider adding "Display Name", "Technical Name", separate, and "Display Name" as the subsequent localization field
`创建名称租户，是否可以考虑添加“显示名称”，“技术名称”分开，“显示名称”作为日后的本地化字段`
![1](https://user-images.githubusercontent.com/28694676/38312043-40f1e61c-3853-11e8-9f5e-933d1bb35f21.gif)

**Comment by Skrypt** [comment]
I don't think it's related with chinese names. It's probably just a bug with the tenants initialization. Try restarting the website to see if it still does the same error. Also please provide which branch/commit you are on.

**Comment by pgy866** [comment]
Nightly (dev): 1.0.0-beta2-5122 

IIS restarts, recycles the application pool, and restarts the tenant within the site. The problem persists. If it is an English name, there is no problem
`IIS 重启，回收应用程序池，以及站点内重启租户，问题依旧存在，如果是英文名称，则没有任何问题`
![1](https://user-images.githubusercontent.com/28694676/38313864-91bab23c-3857-11e8-92da-e2ad2bdabedf.gif)

**Comment by pgy866** [comment]
Nightly (dev): 1.0.0-beta2-5122 

IIS restarts, recycles the application pool, and restarts the tenant within the site. The problem persists. If it is an English name, there is no problem
`IIS 重启，回收应用程序池，以及站点内重启租户，问题依旧存在，如果是英文名称，则没有任何问题`
![1](https://user-images.githubusercontent.com/28694676/38313864-91bab23c-3857-11e8-92da-e2ad2bdabedf.gif)

**Comment by PinpointTownes** [comment]
Given that it happens just after logging in, I'm tempted to say that's because OC returns a cookie containing the name of the tenant (in this case, `orchauth_[name of the tenant]`). HTTP request/response headers can't contain non-ASCII characters, so if your tenant uses such characters, it will fail when returning the response.

**Comment by PinpointTownes** [comment]
If it's really caused by that, https://github.com/OrchardCMS/OrchardCore/issues/1610 might be a good way to solve this issue.

**Comment by pgy866** [comment]
[orchard-log-2018-04-04.log](https://github.com/OrchardCMS/OrchardCore/files/1878633/orchard-log-2018-04-04.log)

**Comment by sebastienros** [comment]
I think we should add some validation for the tenant name as it might be used for technical values like filenames and so on. The issue mentioned by @PinpointTownes was about security, it would also fix it but we want to be able to use a friendly name in some technical parts, like folders.

**Comment by Zonciu** [comment]
Got this exception while using a Chinese name as the site name, that will interrupt the installation process, the web will show 500, you can refresh the web page and get into the home page, but you can't login because the database is incomplete(no user data).

Exception
```
2018-05-02 00:20:49.8898|Default|0HLDFFTAIK531:00000003|0|OrchardCore.Setup.Services.SetupService|ERROR|MySqlException thrown from ISetupEventHandler by OrchardCore.Users.Services.SetupEventHandler 
2018-05-02 00:20:49.9593|Default|0HLDFFTAIK531:00000003|13|Microsoft.AspNetCore.Server.Kestrel|ERROR|Connection id "0HLDFFTAIK531", Request id "0HLDFFTAIK531:00000003": An unhandled exception was thrown by the application. System.AggregateException: One or more errors occurred. (Incorrect string value: '\xE7\x99\xBD\xE7\xBA\xB8...' for column 'Content' at row 1) ---> MySql.Data.MySqlClient.MySqlException: Incorrect string value: '\xE7\x99\xBD\xE7\xBA\xB8...' for column 'Content' at row 1
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet)
   at MySql.Data.MySqlClient.MySqlDataReader.<ReadFirstResultSetAsync>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<CreateAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteScalarAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<ExecuteScalarImplAsync>d__55`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YesSql.Session.<UpdateEntityAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YesSql.Session.<CommitAsync>d__29.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at YesSql.Session.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
   at OrchardCore.Setup.Services.SetupService.<SetupInternalAsync>d__14.MoveNext() in /home/travis/build/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Setup/Services/SetupService.cs:line 238
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrchardCore.Setup.Controllers.SetupController.<IndexPOST>d__10.MoveNext() in /home/travis/build/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Setup/Controllers/SetupController.cs:line 149
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrchardCore.DeferredTasks.DeferredTaskMiddleware.<Invoke>d__3.MoveNext() in /home/travis/build/OrchardCMS/OrchardCore/src/OrchardCore/OrchardCore.DeferredTasks/DeferredTaskMiddleware.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.<Invoke>d__4.MoveNext() in /home/travis/build/OrchardCMS/OrchardCore/src/OrchardCore/OrchardCore.Modules/ModularTenantRouterMiddleware.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.<Invoke>d__4.MoveNext() in /home/travis/build/OrchardCMS/OrchardCore/src/OrchardCore/OrchardCore.Modules/ModularTenantContainerMiddleware.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at OrchardCore.Modules.ModularTenantContainerMiddleware.<Invoke>d__4.MoveNext() in /home/travis/build/OrchardCMS/OrchardCore/src/OrchardCore/OrchardCore.Modules/ModularTenantContainerMiddleware.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
---> (Inner Exception #0) MySql.Data.MySqlClient.MySqlException (0x80004005): Incorrect string value: '\xE7\x99\xBD\xE7\xBA\xB8...' for column 'Content' at row 1
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet)
   at MySql.Data.MySqlClient.MySqlDataReader.<ReadFirstResultSetAsync>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<CreateAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteScalarAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapper.SqlMapper.<ExecuteScalarImplAsync>d__55`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YesSql.Session.<UpdateEntityAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at YesSql.Session.<CommitAsync>d__29.MoveNext()<---
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at YesSql.Session.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
   at OrchardCore.Setup.Services.SetupService.<SetupInternalAsync>d__14.MoveNext() in /home/travis/build/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Setup/Services/SetupService.cs:line 238
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrchardCore.Setup.Controllers.SetupController.<IndexPOST>d__10.MoveNext() in /home/travis/build/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Setup/Controllers/SetupController.cs:line 149
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrchardCore.DeferredTasks.DeferredTaskMiddleware.<Invoke>d__3.MoveNext() in /home/travis/build/OrchardCMS/OrchardCore/src/OrchardCore/OrchardCore.DeferredTasks/DeferredTaskMiddleware.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.<Invoke>d__4.MoveNext() in /home/travis/build/OrchardCMS/OrchardCore/src/OrchardCore/OrchardCore.Modules/ModularTenantRouterMiddleware.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.<Invoke>d__4.MoveNext() in /home/travis/build/OrchardCMS/OrchardCore/src/OrchardCore/OrchardCore.Modules/ModularTenantContainerMiddleware.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at OrchardCore.Modules.ModularTenantContainerMiddleware.<Invoke>d__4.MoveNext() in /home/travis/build/OrchardCMS/OrchardCore/src/OrchardCore/OrchardCore.Modules/ModularTenantContainerMiddleware.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
```

**Comment by hishamco** [comment]
@pgy866 can you reproduce this with the latest bits?

**Comment by hishamco** [comment]
Closed due no respond from the author
