### ISSUE TITLE
Indexing PDFs broken when using Elasticsearch and Azure Media Storage features together

### ISSUE THREAD

**Issue by cbadger-montecitobank** [OrchardCMS/OrchardCore#17291]
### Describe the bug

Indexing PDFs using the `Elasticsearch` feature with the `Azure Media Storage` feature appears broken after upgrading to OrchardCore 2.x.

We store our media library files in Azure blob storage, and index the contents of PDFs stored in the media library using the Elasticsearch integration.  This worked perfectly fine in OrchardCore 1.x, but after upgrading to 2.x we now get this error:

```
2024-12-20 16:03:34.3240|||0HN91A5D6FVBI:000000BB|OrchardCore.Contents.Indexing.ContentItemIndexCoordinator|ERR|IContentFieldIndexHandler thrown from OrchardCore.Media.Indexing.MediaFieldIndexHandler by ArgumentException
System.ArgumentException: The provided stream did not support reading.
   at UglyToad.PdfPig.Core.StreamInputBytes..ctor(Stream stream, Boolean shouldDispose)
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.Open(Stream stream, ParsingOptions options)
   at UglyToad.PdfPig.PdfDocument.Open(Stream stream, ParsingOptions options)
   at OrchardCore.Media.Indexing.PdfMediaFileTextProvider.GetTextAsync(String path, Stream fileStream)
   at OrchardCore.Media.Indexing.PdfMediaFileTextProvider.GetTextAsync(String path, Stream fileStream)
   at OrchardCore.Media.Indexing.MediaFieldIndexHandler.BuildIndexAsync(MediaField field, BuildFieldIndexContext context)
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1,T2,T3,T4,T5](IEnumerable`1 events, Func`7 dispatch, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, ILogger logger)
```
This issue seems to be related to a change in `PdfMediaFileTextProvider.cs`, which now uses a `FileStream` instead of a `MemoryStream` to hand off the file data to `UglyToad.PdfPig` for processing. If I modify the OrchardCore source code to revert back to using a MemoryStream, everything works fine again.

### Orchard Core version

2.1.3 (using Nuget packages)

### To Reproduce

1. Enable the ElasticSearch and Azure Media Storage features, and configure appropriately.
2. Create a new content item from a content type with a Media field.
3. Use the media field to pick a PDF from the media library.
4. Publish the content item, which should trigger an indexing of the PDF content.

### Expected behavior

Indexing should work fine, and text from the PDF should show up in the search index.

**Comment by hishamco** [comment]
If this is related to PR #16958 could you please debug and check why the stream does not support reading

**Comment by cbadger-montecitobank** [comment]
After further debugging, this seems to be the offending line:

`seekableStream = new FileStream(Path.GetTempFileName(), FileMode.OpenOrCreate, FileAccess.Write, FileShare.None, 4096, FileOptions.DeleteOnClose);`

If I change the parameter `FileAccess.Write` to `FileAccess.ReadWrite` then the stream becomes readable and everything works fine again.

**Comment by hishamco** [comment]
Do you plan to submit a PR for this?

**Comment by cbadger-montecitobank** [comment]
There's been several patch releases of Orchard Core since I fixed this bug and the PR was approved, yet none of the releases seem to include the fix.  Just curious how this will eventually make it into a release. Thank you.

**Comment by MikeAlhayek** [comment]
This was merged into main which means it'll be part of v3. J just back ported it into v2 and will be available with the next release 2.1.8 which is not planned anytime soon. I just release 2.1.7 today, too bad this was not back ported already.

**Comment by cbadger-montecitobank** [comment]
Thanks for the quick response Mike.  Going forward, when fixing an Orchard Core bug is there a way to indicate a desire to have it backported to the current major release?  Or did I create the PR off the wrong branch to begin with if I wanted it in 2.x?  Thanks!

**Comment by MikeAlhayek** [comment]
You can request it and we'll evaluate the request. But sure, feel free to ping me if needed and I'll look.
