### ISSUE TITLE
Workflow LogTask throws Esprima.ParserException

### ISSUE THREAD

**Issue by GadgetGeekUK** [OrchardCMS/OrchardCore#1838]
Using DEV branch:
I've created a simple Workflow Event in my module, in the UI connected the 'done' output to a Workflow Log Task which should log the plain text message 'Event received' .

When I fire the triggering event using:
```
await _workflowManager.TriggerEventAsync(nameof(MyReceivedEvent));
```

I get the following exception from the 'LogTask':
```
2018-05-24 10:58:10.8182|Default|0HLE1BHSCUMPI:00000005||OrchardCore.Workflows.Services.WorkflowManager|ERROR|An unhandled error occurred while executing an activity. Workflow ID: '81'. Activity: '4ndsk507df2k1x2f0kw8m7bc42', 'LogTask'. Putting the workflow in the faulted state. Esprima.ParserException: Line 1': Unexpected identifier
   at Esprima.JavaScriptParser.ThrowUnexpectedToken(Token token, String message)
   at Esprima.JavaScriptParser.ConsumeSemicolon()
   at Esprima.JavaScriptParser.ParseLabelledStatement()
   at Esprima.JavaScriptParser.ParseStatement()
   at Esprima.JavaScriptParser.ParseStatementListItem()
   at Esprima.JavaScriptParser.ParseProgram(Boolean strict)
   at OrchardCore.Scripting.JavaScript.JavaScriptEngine.<>c__DisplayClass10_0.<Evaluate>b__0(ICacheEntry entry) in D:\MEL\Orchard2\src\OrchardCore\OrchardCore.Scripting.JavaScript\JavaScriptEngine.cs:line 58
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at OrchardCore.Scripting.JavaScript.JavaScriptEngine.Evaluate(IScriptingScope scope, String script) in D:\MEL\Orchard2\src\OrchardCore\OrchardCore.Scripting.JavaScript\JavaScriptEngine.cs:line 55
   at OrchardCore.Scripting.DefaultScriptingManager.Evaluate(String directive, IFileProvider fileProvider, String basePath, IEnumerable`1 scopedMethodProviders) in D:\MEL\Orchard2\src\OrchardCore\OrchardCore.Scripting.Core\DefaultScriptingManager.cs:line 48
   at OrchardCore.Workflows.Evaluators.JavaScriptWorkflowScriptEvaluator.<EvaluateAsync>d__7`1.MoveNext() in D:\MEL\Orchard2\src\OrchardCore.Modules\OrchardCore.Workflows\Scripting\JavaScriptWorkflowScriptEvaluator.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OrchardCore.Workflows.Activities.LogTask.<ExecuteAsync>d__17.MoveNext() in D:\MEL\Orchard2\src\OrchardCore.Modules\OrchardCore.Workflows\Activities\LogTask.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OrchardCore.Workflows.Services.WorkflowManager.<ExecuteWorkflowAsync>d__18.MoveNext() in D:\MEL\Orchard2\src\OrchardCore.Modules\OrchardCore.Workflows\Services\WorkflowManager.cs:line 312    at Esprima.JavaScriptParser.ThrowUnexpectedToken(Token token, String message)
   at Esprima.JavaScriptParser.ConsumeSemicolon()
   at Esprima.JavaScriptParser.ParseLabelledStatement()
   at Esprima.JavaScriptParser.ParseStatement()
   at Esprima.JavaScriptParser.ParseStatementListItem()
   at Esprima.JavaScriptParser.ParseProgram(Boolean strict)
   at OrchardCore.Scripting.JavaScript.JavaScriptEngine.<>c__DisplayClass10_0.<Evaluate>b__0(ICacheEntry entry) in D:\MEL\Orchard2\src\OrchardCore\OrchardCore.Scripting.JavaScript\JavaScriptEngine.cs:line 58
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at OrchardCore.Scripting.JavaScript.JavaScriptEngine.Evaluate(IScriptingScope scope, String script) in D:\MEL\Orchard2\src\OrchardCore\OrchardCore.Scripting.JavaScript\JavaScriptEngine.cs:line 55
   at OrchardCore.Scripting.DefaultScriptingManager.Evaluate(String directive, IFileProvider fileProvider, String basePath, IEnumerable`1 scopedMethodProviders) in D:\MEL\Orchard2\src\OrchardCore\OrchardCore.Scripting.Core\DefaultScriptingManager.cs:line 48
   at OrchardCore.Workflows.Evaluators.JavaScriptWorkflowScriptEvaluator.<EvaluateAsync>d__7`1.MoveNext() in D:\MEL\Orchard2\src\OrchardCore.Modules\OrchardCore.Workflows\Scripting\JavaScriptWorkflowScriptEvaluator.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OrchardCore.Workflows.Activities.LogTask.<ExecuteAsync>d__17.MoveNext() in D:\MEL\Orchard2\src\OrchardCore.Modules\OrchardCore.Workflows\Activities\LogTask.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OrchardCore.Workflows.Services.WorkflowManager.<ExecuteWorkflowAsync>d__18.MoveNext() in D:\MEL\Orchard2\src\OrchardCore.Modules\OrchardCore.Workflows\Services\WorkflowManager.cs:line 312
```

**Comment by sebastienros** [comment]
Apparently this task takes some JS, and the value is not valid JS.

**Comment by sfmskywalker** [comment]
Yes, this is a mistake - it should parse liquid instead. I'm going to fix it now, but in the meantime you can surround your log text with quotes (making it a valid string literal).
