### ISSUE TITLE
Error when trying to use Windows Authentication

### ISSUE THREAD

**Issue by mcapewell** [OrchardCMS/OrchardCore#2074]
So I have a beautiful modular web app written using Beta 1 and *almost* everything seems to work after upgrading to Beta 2 except for Windows Authentication.

With windowsAuthentication as false then everything works fine, but if I change launchSettings.json so that windowsAuthentication is true and anonymousAuthentication is false then I get the following exception:

System.ArgumentException: Invalid token for impersonation - it cannot be duplicated.
   at System.Security.Principal.WindowsIdentity.CreateFromToken(IntPtr userToken)
   at System.Security.Principal.WindowsIdentity..ctor(IntPtr userToken, String authType, Int32 isAuthenticated)
   at System.Security.Principal.WindowsIdentity..ctor(IntPtr userToken)
   at Microsoft.AspNetCore.Server.IISIntegration.AuthenticationHandler.GetUser()
   at Microsoft.AspNetCore.Server.IISIntegration.AuthenticationHandler.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchard2\src\OrchardCore\OrchardCore.Modules\ModularTenantRouterMiddleware.cs:line 82
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchard2\src\OrchardCore\OrchardCore.Modules\ModularTenantContainerMiddleware.cs:line 89
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

Any ideas?

**Comment by sebastienros** [comment]
We need to investigate, I have no idea about Windows Auth support in ASP.NET 2.1

**Comment by mcapewell** [comment]
Thanks for the reply.

As a very simple test, I created an empty ASP.NET Core 2.1 website with Windows Auth enabled. Absolutely nothing else in the project and it runs fine.

Added the OrchardCore NuGet package and added AddOrchardCore and UseOrchardCore to the Startup class and I get the above exception.

**Comment by eratos** [comment]
You can also replicate this by taking the OrchardCore.Mvc.Web sample project, checking "Enable Windows Authentication" in the debug properties of the project and unchecking "Enable Anonymous Authentication".  Start the OrchardCore.Mvc.Web app and the exception appears.

**Comment by sebastienros** [comment]
@PinpointTownes do you have an idea of what could go wrong? Or if something has changed in 2.1 that could conflict with what we are doing.

**Comment by PinpointTownes** [comment]
@sebastienros honestly? No idea :smile: 

@Tratcher may know as he implemented WA in the IIS integration middleware.

**Comment by Tratcher** [comment]
Windows auth has been supported in core on IIS since 1.0. 

That stack trace is bizarre:
```
at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchard2\src\OrchardCore\OrchardCore.Modules\ModularTenantRouterMiddleware.cs:line 82
at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchard2\src\OrchardCore\OrchardCore.Modules\ModularTenantContainerMiddleware.cs:line 89
at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

Why is IISMiddleware.Invoke run twice? Did ModularTenantContainerMiddleware cause this?

**Comment by jtkech** [comment]
Hmm, maybe in `ModularTenantRouterMiddleware` there are some `IStartupFilter` that would need to not be re-run. For infos, in `ModularTenantRouterMiddleware` when executing `startupFilters`, if i remove the `IISSetupFilter`, which calls `IISMiddleware`, it doesn't fail.

**Comment by jtkech** [comment]
So, when creating a tenant container in `CreateChildContainer()`, if we don't clone the `IStartupFilter` (registered at the app level) assuming they are already part of the main pipeline (but not sure), then in `ModularTenantRouterMiddleware` we execute only those registered at the tenant level (e.g the data protection startup filter). Then it doesn't fail, but not sure of all of this.

**Comment by jtkech** [comment]
So, not cloning hosting startup filters to the tenant container seems to work, i will suggest a PR.

E.g, one of them is the `AutoRequestServicesStartupFilter` which enlists the `RequestServicesContainerMiddleware`. Then, even this filter is not resolved in the tenant context and then the middleware not added to the tenant pipeline, i could check that it has been executed by using.

    var servicesFeature = httpContext.Features.Get<IServiceProvidersFeature>();

@Tratcher thanks for having seen that `IISMiddleware` was invoked twice.
