### ISSUE TITLE
Microsoft.AspNetCore.Routing.RouteCreationException: A default handler must be set on the IRouteBuilder.

### ISSUE THREAD

**Issue by mdockal** [OrchardCMS/OrchardCore#2135]
I am trying to create my own Sofware As A Service App using the latest build of Orchard Core.

1. Created a new ASP.NET Core Web Application OrchardCore.Web
2. dotnet new -i OrchardCore.Cms.Templates::1.0.0-beta3-* --nuget-source https://www.myget.org/F/orchardcore-preview/api/v3/index.json
3. dotnet new ocmodule -n OrchardCore.Module1
4. Added OrchardCore.Module1 Project to Solution and added Reference to Web Project
5. Copied Views Folder,  _ViewImports.cshtml, _ViewStart.cshtml and appsettings.json from dev OrchardCore.Samples/OrcharCore.MVC.Web to the OrchardCore.Web Project
6. Added OrchardCore.Application.Mvc.Targets, OrchardCore.Diagnostics.Elm and   OrchardCore.Hosting.Console to OrchardCore.Web just like the sample project.
7. Changed Startup.cs in the web project:

```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOrchardCore();
            services.AddMvc();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseStaticFiles();

            app.UseOrchardCore();

            
        }
```

8. Changed Startup.cs in OrchardCore.Module1:

```
public class Startup : StartupBase
    {
        private readonly IConfiguration _configuration;

        public Startup(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        

        public override void Configure(IApplicationBuilder builder, IRouteBuilder routes, IServiceProvider serviceProvider)
        {
            routes.MapAreaRoute(
                name: "Home",
                areaName: "OrchardCore.Module1",
                template: "Home/Index",
                defaults: new { controller = "Home", action = "Index" }
            );
        }
    }

```
9. Got Exception:

Microsoft.AspNetCore.Routing.RouteCreationException
  HResult=0x80131500
  Message=A default handler must be set on the IRouteBuilder.
  Source=Microsoft.AspNetCore.Routing
  StackTrace:
   at Microsoft.AspNetCore.Builder.MapRouteRouteBuilderExtensions.MapRoute(IRouteBuilder routeBuilder, String name, String template, Object defaults, Object constraints, Object dataTokens)
   at Microsoft.AspNetCore.Builder.MvcAreaRouteBuilderExtensions.MapAreaRoute(IRouteBuilder routeBuilder, String name, String areaName, String template, Object defaults, Object constraints, Object dataTokens)
   at Microsoft.AspNetCore.Builder.MvcAreaRouteBuilderExtensions.MapAreaRoute(IRouteBuilder routeBuilder, String name, String areaName, String template, Object defaults)
   at OrchardCore.Module1.Startup.Configure(IApplicationBuilder builder, IRouteBuilder routes, IServiceProvider serviceProvider) in C:\Users\Mark\Projects\OrchardCore1\OrchardCore.Module1\Startup.cs:line 23
   at OrchardCore.Modules.ModularTenantRouterMiddleware.ConfigureTenantPipeline(IApplicationBuilder appBuilder, IServiceProvider scopeServiceProvider) in C:\projects\orchard2\src\OrchardCore\OrchardCore.Modules\ModularTenantRouterMiddleware.cs:line 125
   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.BuildTenantPipeline(IServiceProvider rootServiceProvider, IServiceProvider scopeServiceProvider) in C:\projects\orchard2\src\OrchardCore\OrchardCore.Modules\ModularTenantRouterMiddleware.cs:line 105
   at OrchardCore.Modules.ModularTenantRouterMiddleware.<Invoke>d__4.MoveNext() in C:\projects\orchard2\src\OrchardCore\OrchardCore.Modules\ModularTenantRouterMiddleware.cs:line 70

Attached is the source code:
[OrchardCore1.zip](https://github.com/OrchardCMS/OrchardCore/files/2227361/OrchardCore1.zip)

**Comment by jtkech** [comment]
Not closed to my computer but try

    services.AddOrchardCore().AddMvc();

**Comment by Skrypt** [comment]
I think it should be 

```C#
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;

namespace OrchardCore.Templates.Cms.Web
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOrchardCms();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseStaticFiles();

            app.UseOrchardCore();
        }
    }
}
```

**Comment by mdockal** [comment]
@jtkech when I tried services.AddOrchardCore().AddMvc()  I got a 404 error so I thought it wasn't working.  However, when I went to https://localhost:44334/OrchardCore.Module1/home/index I got the text from the module.  Now I got the Hello World! from the view.  I removed template:"Home/Index" and changed it to template:"" from the Startup.cs in the Module1 and it works now!

```
 public override void Configure(IApplicationBuilder builder, IRouteBuilder routes, IServiceProvider serviceProvider)
        {
            routes.MapAreaRoute(
                name: "Home",
                areaName: "OrchardCore.Module1",
                template: "",
                defaults: new { controller = "Home", action = "Index" }
            );
        }
```

![image](https://user-images.githubusercontent.com/26497457/43219552-417a2920-900d-11e8-8ab8-1d20ef357eb9.png)

**Comment by mdockal** [comment]
@Skrypt I am not using Orchard CMS just Orchard Core so services.AddOrchardCms() is not an option.  Trying to build an Saas Application

**Comment by Skrypt** [comment]
Well it's one of those 2 methods most of the time 😄
