### ISSUE TITLE
graphiql.js error

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/OrchardCore#2213]
> Error: ContentPartsInput fields must be an object with field names as keys or a function which returns such an object.
    at invariant (http://localhost:5000/OrchardCore.Apis.GraphQL/Scripts/graphiql.js:25010:11)
    at GraphQLInputObjectType._defineFieldMap (http://localhost:5000/OrchardCore.Apis.GraphQL/Scripts/graphiql.js:28610:29)
    at GraphQLInputObjectType.getFields (http://localhost:5000/OrchardCore.Apis.GraphQL/Scripts/graphiql.js:28601:49)
    at typeMapReducer (http://localhost:5000/OrchardCore.Apis.GraphQL/Scripts/graphiql.js:29968:26)
    at http://localhost:5000/OrchardCore.Apis.GraphQL/Scripts/graphiql.js:29971:20
    at Array.forEach (<anonymous>)
    at typeMapReducer (http://localhost:5000/OrchardCore.Apis.GraphQL/Scripts/graphiql.js:29969:28)
    at typeMapReducer (http://localhost:5000/OrchardCore.Apis.GraphQL/Scripts/graphiql.js:29934:12)
    at Array.reduce (<anonymous>)
    at http://localhost:5000/OrchardCore.Apis.GraphQL/Scripts/graphiql.js:29961:36

1. Set up a new instance as SAAS, 
2. enable GraphQlL module.
3. navigate to GraphQL Explore.

get the error

**Comment by HengzheLi** [comment]
:( The exception had show the fixing which was ignore by me because lack of graphql knowledge.

> with field names as keys or a function

It should include the Name field in query sentence.
