### ISSUE TITLE
Crash when Orchard Core app hosted in a virtual directory

### ISSUE THREAD

**Issue by eratos** [OrchardCMS/OrchardCore#2249]
https://github.com/OrchardCMS/OrchardCore/blob/0326e2a19fb49b16b53f1ef357be06b9cc8679bf/src/OrchardCore/OrchardCore.Environment.Shell/RunningShellTable.cs#L171

The selected line above appears to have an error - we check that the appRelativePath has a Length > 0 but then call IndexOf using a startIndex of 1 - this will fail if the appRelativePath is exactly 1 character in length.

This behaviour was found by Hosting an app in a virtual directory on IIS.  Access the app through http://host:port/virtualdir fails, crashing with the stack trace below.

Accessing through the same URL but with a trailing slash added http://host:port/virtualdir/ works as expected.

Stack trace:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.String.IndexOf(Char value, Int32 startIndex, Int32 count)
   at OrchardCore.Environment.Shell.RunningShellTable.GetHostAndPrefix(String host, String appRelativePath)
   at OrchardCore.Environment.Shell.RunningShellTable.TryMatchInternal(String host, String appRelativePath, ShellSettings& result)
   at OrchardCore.Environment.Shell.RunningShellTable.Match(String host, String appRelativePath)
   at OrchardCore.Modules.RunningShellTableExtensions.Match(IRunningShellTable table, HttpContext httpContext)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()

**Comment by sebastienros** [comment]
Would be awesome if you could provide a PR as you can repro the issue locally.

**Comment by eratos** [comment]
Actually I think I may be mistaken - IndexOf can take a starting index equal to the length of the string, and the crash I observed is from a beta1 build of OrchardCore back in November, before PR 1698 which fixes this issue already.
