### ISSUE TITLE
Null Reference Exception when attempting to inject HttpConnectionDispatcher in Startup.CS

### ISSUE THREAD

**Issue by hazdogga** [OrchardCMS/OrchardCore#2268]
This problem arose when attempting to utilise SignalR Core as part of a new Orchard Core Module. The offending line of code was:
`builder.UseSignalR(routes => {routes.MapHub<TestHub>("/testhub");});`

This line threw an NRE, the stack trace was followed to an attempt at injecting an `HttpConnectionDispatcher`.

Easiest way to reproduce this issue is to create a new, empty Orchard Core module, inheriting `StartupBase `for your `Startup.cs` class, and attempt to inject an `HttpConnectionDispatcher `with the following line of code:
`var dispatcher = builder.ApplicationServices.GetRequiredService<HttpConnectionDispatcher>();`

An exception should occur, producing a lengthy stack trace:
```
Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager.Start()
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager.<.ctor>b__6_0()
   at System.Threading.CancellationTokenSource.InternalRegister(Action`1 callback, Object stateForCallback, SynchronizationContext syncContext, ExecutionContext executionContext)
   at System.Threading.CancellationToken.Register(Action`1 callback, Object state, Boolean useSyncContext, Boolean useExecutionContext)
   at System.Threading.CancellationToken.Register(Action callback)
   at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager..ctor(ILoggerFactory loggerFactory, IApplicationLifetime appLifetime)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at RealTimeData.Startup.Configure(IApplicationBuilder builder, IRouteBuilder router, IServiceProvider serviceProvider)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.ConfigureTenantPipeline(IApplicationBuilder appBuilder, IServiceProvider scopeServiceProvider) 
   at OrchardCore.Modules.ModularTenantRouterMiddleware.<>c__DisplayClass5_0.<BuildTenantPipeline>b__0(IApplicationBuilder builder) 
   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.BuildTenantPipeline(IServiceProvider rootServiceProvider, IServiceProvider scopeServiceProvider) 
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext)
```

Note: SignalR core nuget package (or source) required to reproduce.

**Comment by creativbox** [comment]
I was trying the same, but there is a bug in SignalR which causes this NRE when the application start has already been signaled (which is always the case in OrchardCore modules). I've filed an issue in the SignalR repository. 
In the meantime I was thinking about a workaround, by replacing the IApplicationLifetime for the tenants.

**Comment by jcharlesworthuk** [comment]
If you find a workaround please share, I am also experiencing this exact same problem

**Comment by creativbox** [comment]
I've replaced the application lifetime with tenant events for now. In the modules ConfigureServices() I register this:

```
// Replace IApplicationLifetime with a per tenant lifetime manager
services.AddSingleton<IApplicationLifetime, TenantApplicationLifetime>();
services.AddTransient<IModularTenantEvents>(sp => (TenantApplicationLifetime)sp.GetService<IApplicationLifetime>());
```

The TenantApplicationLifetime is something like this:

 ```
// TODO: Remove once https://github.com/aspnet/SignalR/issues/2875 has been fixed
public class TenantApplicationLifetime : IApplicationLifetime, IModularTenantEvents
{
    private readonly CancellationTokenSource _startedSource = new CancellationTokenSource();
    private readonly CancellationTokenSource _stoppingSource = new CancellationTokenSource();
    private readonly CancellationTokenSource _stoppedSource = new CancellationTokenSource();

    public CancellationToken ApplicationStarted => _startedSource.Token;
    public CancellationToken ApplicationStopping => _stoppingSource.Token;
    public CancellationToken ApplicationStopped => _stoppedSource.Token;

    public void StopApplication()
    {
    }

    public Task ActivatedAsync()
    {
        return Task.CompletedTask;
    }

    public Task ActivatingAsync()
    {
        return Task.CompletedTask;
    }

    public Task TerminatedAsync()
    {
        if (!_stoppedSource.IsCancellationRequested)
            _stoppedSource.Cancel(false);

        return Task.CompletedTask;
    }

    public Task TerminatingAsync()
    {
        if (!_stoppingSource.IsCancellationRequested)
            _stoppingSource.Cancel(false);

        return Task.CompletedTask;
    }

    internal void OnTenantStarted()
    {
        if (!_startedSource.IsCancellationRequested)
            _startedSource.Cancel(false);
    }
}
```
It's not possible to use the IModularTenantEvents.ActivatedAsync event, because this is also signaled to early for SignalR, so I signal the started event manually in Configure():

```
// Notify about started tenant, should be last in Configure()
((TenantApplicationLifetime)app.ApplicationServices.GetService<IApplicationLifetime>()).OnTenantStarted();
```
This is all super hacky, but it works. Note that there is already a PR that fixes the underlaying issue in SignalR.

**Comment by sebastienros** [comment]
We should soon be able to move to 2.2-preview, and I assume next preview will contain the fix.

**Comment by creativbox** [comment]
This issue has been fixed externally and can be closed.

**Comment by sebastienros** [comment]
Thanks @creativbox
