### ISSUE TITLE
error in AutoroutePartDisplay

### ISSUE THREAD

**Issue by psijkof** [OrchardCMS/OrchardCore#2475]
Create new instance of OC
Create content type with autoroutepart
Create new item

Observe error thrown:

```
fail: OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator[0]
       IContentPartDisplayDriver thrown from OrchardCore.Autoroute.Drivers.AutoroutePartDisplay by NullReferenceException
 System.NullReferenceException: Object reference not set to an instance of an object.
    at OrchardCore.Autoroute.Drivers.AutoroutePartDisplay.<>c__DisplayClass9_0.<<Edit>b__0>d.MoveNext() in C:\projects\orchard2\src\OrchardCore.Modules\OrchardCore.Autoroute\Drivers\AutoroutePartDisplay.cs:line 61
 --- End of stack trace from previous location where exception was thrown ---
    at OrchardCore.DisplayManagement.ShapeFactoryExtensions.<>c__DisplayClass6_0`1.<<CreateAsync>b__0>d.MoveNext() in C:\projects\orchard2\src\OrchardCore\OrchardCore.DisplayManagement\IShapeFactory.cs:line 77
 --- End of stack trace from previous location where exception was thrown ---
    at OrchardCore.DisplayManagement.Implementation.DefaultShapeFactory.CreateAsync(String shapeType, Func`1 shapeFactory, Action`1 creating, Action`1 created) in C:\projects\orchard2\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultShapeFactory.cs:line 139
    at OrchardCore.DisplayManagement.Views.ShapeResult.ApplyImplementationAsync(BuildShapeContext context, String displayType) in C:\projects\orchard2\src\OrchardCore\OrchardCore.DisplayManagement\Views\ShapeResult.cs:line 106
    at OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator.<>c__DisplayClass11_2.<<BuildEditorAsync>b__0>d.MoveNext() in C:\projects\orchard2\src\OrchardCore\OrchardCore.ContentManagement.Display\ContentDisplay\ContentItemDisplayCoordinator.cs:line 169
 --- End of stack trace from previous location where exception was thrown ---
    at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents](IEnumerable`1 events, Func`2 dispatch, ILogger logger) in C:\projects\orchard2\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 85
```

**Comment by psijkof** [comment]
This is avoided by specifying configuration for the HomeRoute in the Settings step.
This fixed it for us:
```
{
      "name": "Settings",
      "HomeRoute": {}
},
```
