### ISSUE TITLE
Send verification email issue (sendgrid)

### ISSUE THREAD

**Issue by sipronunciaaigor** [OrchardCMS/OrchardCore#2483]
I registered the website as a web app on azure free and a free sendgrid account.
I then tested the account by sending emails both on port 25 and 587.
After adding users modules and allowing users to register, I tested the registration process and waited in vain for an incoming email.
Then I tried to send the verification email with the admin account and I got "An error occured while executing this request."

p.s.: is orchard producing easily accessible logs? where are they stored? is there a way to show errors explicitly?

**Comment by hyzx86** [comment]
Is there has any files in folder  `App_Data\logs` ?
in windows like this :
![image](https://user-images.githubusercontent.com/15613121/46777452-1e054e80-cd42-11e8-81c1-c27a3222a961.png)

**Comment by sipronunciaaigor** [comment]
directly not having the logs folder...

![folder-structure](https://user-images.githubusercontent.com/16055024/46787953-b8868180-cd84-11e8-81a3-bf633d149bf3.jpg)

I'm not compiling the orchard solution, but I'm using the nuget package for the production

**Comment by hyzx86** [comment]
Did you check the directory write permissions?
You deploy the source code or, compiled released? 
The  folder `Sites`  you manually upload or system generated ？
if it is system generated folder，then write permissions should be no problem.

You can check the  Windows application event.
on azure maybe this article can help you 
https://docs.microsoft.com/en-us/azure/security/security-azure-log-integration-faq

**Comment by hyzx86** [comment]
At the file line 40, the `viewEngineResult.View` is null , C:\Users\hyzx8\Source\Repos\OrchardCore\src\OrchardCore.Modules\OrchardCore.Users\Controllers\BaseEmailController.cs

![image](https://user-images.githubusercontent.com/15613121/46792191-57a37d00-cd75-11e8-8d7d-7cd046ce6b91.png)

**Comment by hyzx86** [comment]
System.InvalidCastException: Unable to cast object of type 'StackExchange.Profiling.Data.ContextProfiledDbConnection' to type 'Microsoft.Data.Sqlite.SqliteConnection'.
same as this issue:
[https://github.com/OrchardCMS/OrchardCore/issues/2484](url)

**Comment by sipronunciaaigor** [comment]
> Did you check the directory write permissions?

No

> You deploy the source code or, compiled released?

I'm using the publishing options in visual studio. Essentially I downloaded the file .PublishSettings from Azure and pressed the "Publish" button in VS.

> The folder `Sites` you manually upload or system generated ？
> if it is system generated folder，then write permissions should be no problem.

System generated

> You can check the Windows application event.
> on azure maybe this article can help you
> https://docs.microsoft.com/en-us/azure/security/security-azure-log-integration-faq

Will do.

I'll also update as soon as I'm able to log it/find a log for it

**Comment by sebastienros** [comment]
If you published with VS, probably your server is running IIS which won't grant write access to App_data by default.

**Comment by hyzx86** [comment]
@sipronunciaaigor 

you should to add NLog.config to  your site root path
the file config like this

`<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Warn"
      internalLogFile="App_Data/logs/internal-nlog.txt">

    <extensions>
        <add assembly="NLog.Web.AspNetCore"/>
        <add assembly="OrchardCore.Logging.NLog"/>
    </extensions>

    
    <targets>
        
        <target xsi:type="File" name="allfile" fileName="${var:configDir}/App_Data/logs/orchard-log-${shortdate}.log"
                    layout="${longdate}|${orchard-tenant-name}|${aspnet-traceidentifier}|${event-properties:item=EventId.Id}|${logger}|${uppercase:${level}}|${message} ${exception:format=ToString,StackTrace}" />

        
    </targets>

    <rules>
        
        <logger name="*" minlevel="Error" writeTo="allfile" />
    </rules>
</nlog>`

**Comment by hyzx86** [comment]
the Log is still not work ...

[图片]

**Comment by hyzx86** [comment]
You can follow this project:
https://github.com/OrchardCMS/OrchardCore/tree/dev/src/OrchardCore.Cms.Web

**Comment by hyzx86** [comment]
Clikc Reset Password:

`2018-10-13 23:35:37.1268|Default|0HLHH44T0UN88:00000004||Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|ERROR|An unhandled exception has occurred while executing the request. System.ArgumentNullException: Value cannot be null.
Parameter name: view
   at Microsoft.AspNetCore.Mvc.Rendering.ViewContext..ctor(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, TextWriter writer, HtmlHelperOptions htmlHelperOptions)
   at OrchardCore.Users.Controllers.BaseEmailController.SendEmailAsync(String email, String subject, Object model, String viewName) in C:\Users\hyzx8\Source\Repos\OrchardCore\src\OrchardCore.Modules\OrchardCore.Users\Controllers\BaseEmailController.cs:line 41
   at OrchardCore.Users.Controllers.ResetPasswordController.ForgotPassword(ForgotPasswordViewModel model) in C:\Users\hyzx8\Source\Repos\OrchardCore\src\OrchardCore.Modules\OrchardCore.Users\Controllers\ResetPasswordController.cs:line 80
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\Users\hyzx8\Source\Repos\OrchardCore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 76
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\Users\hyzx8\Source\Repos\OrchardCore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 99
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.Mvc.Rendering.ViewContext..ctor(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, TextWriter writer, HtmlHelperOptions htmlHelperOptions)
   at OrchardCore.Users.Controllers.BaseEmailController.SendEmailAsync(String email, String subject, Object model, String viewName) in C:\Users\hyzx8\Source\Repos\OrchardCore\src\OrchardCore.Modules\OrchardCore.Users\Controllers\BaseEmailController.cs:line 41
   at OrchardCore.Users.Controllers.ResetPasswordController.ForgotPassword(ForgotPasswordViewModel model) in C:\Users\hyzx8\Source\Repos\OrchardCore\src\OrchardCore.Modules\OrchardCore.Users\Controllers\ResetPasswordController.cs:line 80
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\Users\hyzx8\Source\Repos\OrchardCore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 76
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\Users\hyzx8\Source\Repos\OrchardCore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 99
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

`

**Comment by hyzx86** [comment]
Send Maill Error

**Comment by jtkech** [comment]
@sipronunciaaigor just tried it on my local machine and it works when i test it by using the testing button in the smtp settings, the mail was successfully sent and received.

But when i test it through the confirmation it fails, i could repro the exact issue described by @hyzx86, thanks for pointed it out. I will fix it.

That said, as i remember, when hosting on azure web apps (a while ago), it was not working directly, i needed to use a service allowed by azure as `SendGrid`. Then it was working the same but by using `smtp.sendgrid.com`.

**Comment by jtkech** [comment]
@sipronunciaaigor @hyzx86 

Okay, i found a temporary fix then the confirmation was working, i will do a PR soon.

@sipronunciaaigor can you try it but by using the testing button in the smpt settings in the admin, because on my side it was working from the beginning. Hmm, but i think you will need an allowed external service as `SendGrid`.

**Comment by jtkech** [comment]
@sipronunciaaigor sorry, just saw through the title of the issue that you are using `SendGrid`.

So, i fixed the issue as described by @hyzx86 and checked again through the email confirmation that the mail is successfully sent and recieved. I will do a PR.
