### ISSUE TITLE
InvalidCastException: Unable to cast object of type 'StackExchange.Profiling.Data.ContextProfiledDbConnection' to type 'Microsoft.Data.Sqlite.SqliteConnection'.

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#2484]
Suddenly reported this error. 
May be due to Miniprofile

InvalidCastException: Unable to cast object of type 'StackExchange.Profiling.Data.ContextProfiledDbConnection' to type 'Microsoft.Data.Sqlite.SqliteConnection'

![image](https://user-images.githubusercontent.com/15613121/46815027-a02a5d00-cdac-11e8-969f-79089e623e8f.png)

`2018-10-11 10:32:56.0656|Default|0HLHF414O87KS:00000002||Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|ERROR|An unhandled exception has occurred while executing the request. System.InvalidCastException: Unable to cast object of type 'StackExchange.Profiling.Data.ContextProfiledDbConnection' to type 'Microsoft.Data.Sqlite.SqliteConnection'.
   at Microsoft.Data.Sqlite.SqliteCommand.set_DbConnection(DbConnection value)
   at System.Data.Common.DbCommand.set_Connection(DbConnection value)
   at StackExchange.Profiling.Data.ProfiledDbCommand.UnwrapAndAssignConnection(DbConnection value) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 160
   at StackExchange.Profiling.Data.ProfiledDbCommand..ctor(DbCommand command, DbConnection connection, IDbProfiler profiler) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 63
   at StackExchange.Profiling.Data.ContextProfiledDbConnection.CreateDbCommand() in C:\Users\hyzx8\Source\Repos\OrchardCore\src\OrchardCore.Modules\OrchardCore.MiniProfiler\ContextProfiledConnection.cs:line 143
   at System.Data.Common.DbConnection.System.Data.IDbConnection.CreateCommand()
   at Dapper.CommandDefinition.SetupCommand(IDbConnection cnn, Action`2 paramReader) in C:\projects\dapper\Dapper\CommandDefinition.cs:line 112
   at Dapper.SqlMapper.TrySetupAsyncCommand(CommandDefinition command, IDbConnection cnn, Action`2 paramReader) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 396
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 413
   at YesSql.Store.ProduceAsync[T](WorkerQueryKey key, Func`1 work)
   at YesSql.Session.GetAsync[T](Int32[] ids)
   at YesSql.SessionExtensions.GetAsync[T](ISession session, Int32 id)
   at OrchardCore.Users.Services.UserStore.FindByIdAsync(String userId, CancellationToken cancellationToken) in C:\Users\hyzx8\Source\Repos\OrchardCore\src\OrchardCore\OrchardCore.Users.Core\Services\UserStore.cs:line 95
   at Microsoft.AspNetCore.Identity.SignInManager`1.ValidateSecurityStampAsync(ClaimsPrincipal principal)
   at Microsoft.AspNetCore.Identity.SecurityStampValidator`1.ValidateAsync(CookieValidatePrincipalContext context)
   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 86
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\Users\hyzx8\Source\Repos\OrchardCore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 76
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\Users\hyzx8\Source\Repos\OrchardCore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 99
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)    at Microsoft.Data.Sqlite.SqliteCommand.set_DbConnection(DbConnection value)
   at System.Data.Common.DbCommand.set_Connection(DbConnection value)
   at StackExchange.Profiling.Data.ProfiledDbCommand.UnwrapAndAssignConnection(DbConnection value) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 160
   at StackExchange.Profiling.Data.ProfiledDbCommand..ctor(DbCommand command, DbConnection connection, IDbProfiler profiler) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 63
   at StackExchange.Profiling.Data.ContextProfiledDbConnection.CreateDbCommand() in C:\Users\hyzx8\Source\Repos\OrchardCore\src\OrchardCore.Modules\OrchardCore.MiniProfiler\ContextProfiledConnection.cs:line 143
   at System.Data.Common.DbConnection.System.Data.IDbConnection.CreateCommand()
   at Dapper.CommandDefinition.SetupCommand(IDbConnection cnn, Action`2 paramReader) in C:\projects\dapper\Dapper\CommandDefinition.cs:line 112
   at Dapper.SqlMapper.TrySetupAsyncCommand(CommandDefinition command, IDbConnection cnn, Action`2 paramReader) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 396
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 413
   at YesSql.Store.ProduceAsync[T](WorkerQueryKey key, Func`1 work)
   at YesSql.Session.GetAsync[T](Int32[] ids)
   at YesSql.SessionExtensions.GetAsync[T](ISession session, Int32 id)
   at OrchardCore.Users.Services.UserStore.FindByIdAsync(String userId, CancellationToken cancellationToken) in C:\Users\hyzx8\Source\Repos\OrchardCore\src\OrchardCore\OrchardCore.Users.Core\Services\UserStore.cs:line 95
   at Microsoft.AspNetCore.Identity.SignInManager`1.ValidateSecurityStampAsync(ClaimsPrincipal principal)
   at Microsoft.AspNetCore.Identity.SecurityStampValidator`1.ValidateAsync(CookieValidatePrincipalContext context)
   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 86
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\Users\hyzx8\Source\Repos\OrchardCore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 76
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\Users\hyzx8\Source\Repos\OrchardCore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 99
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
`

**Comment by hyzx86** [comment]
Error page :
https://localhost:44300/OrchardCore.Roles/Admin/Edit/Moderator

**Comment by hyzx86** [comment]
After recompiling many times, the problem disappears

**Comment by hyzx86** [comment]
It’s work fine after removing Miniprofile from Features

**Comment by hyzx86** [comment]
@sebastienros The problem still seems to be there. When Redis and MiniProfile are enabled and sql server is used.
