### ISSUE TITLE
The error that was raised when upgraded from 1.0.0-beta3-68792 to 1.0.0-beta3-68886

### ISSUE THREAD

**Issue by kamikyo** [OrchardCMS/OrchardCore#2509]
After I upgraded from 1.0.0-beta3-68792 to 1.0.0-beta3-68886, the following issues occurred:

```
System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.OpenIddictValidationBuilder Microsoft.Extensions.DependencyInjection.OpenIddictValidationBuilder.AddEventHandler(System.Func`2<!!0,System.Threading.Tasks.Task>)'.
   at SimpleOpenId.Startup.<>c.<ConfigureServices>b__0_3(OpenIddictValidationBuilder options)
   at Microsoft.Extensions.DependencyInjection.OpenIddictValidationExtensions.AddValidation(OpenIddictBuilder builder, Action`1 configuration)
   at SimpleOpenId.Startup.ConfigureServices(IServiceCollection services) in D:\work\kefu\CS\SimpleOpenId\Startup.cs:line 26
   at OrchardCore.Environment.Shell.Builders.ShellContainerFactory.CreateContainer(ShellSettings settings, ShellBlueprint blueprint) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Environment\Shell\Builders\ShellContainerFactory.cs:line 88
   at OrchardCore.Environment.Shell.Builders.ShellContextFactory.CreateDescribedContextAsync(ShellSettings settings, ShellDescriptor shellDescriptor) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Environment\Shell\Builders\ShellContextFactory.cs:line 75
   at OrchardCore.Environment.Shell.Builders.ShellContextFactory.OrchardCore.Environment.Shell.Builders.IShellContextFactory.CreateShellContextAsync(ShellSettings settings) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Environment\Shell\Builders\ShellContextFactory.cs:line 49
   at OrchardCore.Environment.Shell.ShellHost.GetOrCreateShellContextAsync(ShellSettings settings) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Environment\Shell\ShellHost.cs:line 88
   at OrchardCore.Environment.Shell.ShellHost.<CreateAndRegisterShellsAsync>b__15_0(ShellSettings settings) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Environment\Shell\ShellHost.cs:line 182
```
It happens in one of my custom modules.
This module uses a custom openiddict configuration:
```
services.AddOpenIddict()
                .AddCore(options =>
                {
                    options.UseEntityFrameworkCore()
                        .UseDbContext<CSDbContext>();
                })
                .AddServer(options =>
                {
                    options.UseMvc();
                    options.EnableAuthorizationEndpoint("/connect/authorize")
                    .EnableLogoutEndpoint("/connect/logout")
                    .EnableTokenEndpoint("/connect/token");
                    //.EnableUserinfoEndpoint("/api/userinfo");
                    //options.RegisterScopes(OpenIdConnectConstants.Scopes.Email,
                    //    OpenIdConnectConstants.Scopes.Profile,
                    //    OpenIddictConstants.Scopes.Roles);
                    options.RegisterScopes(OpenIdConnectConstants.Scopes.Profile,
                        OpenIdConnectConstants.Scopes.OfflineAccess);
                    options
                        .AllowClientCredentialsFlow()
                        .AllowRefreshTokenFlow(); //如果要使用OfflineAccess，则需要启用refreshtoken
                    options.EnableRequestCaching();
                    options.DisableHttpsRequirement();
                    options.AcceptAnonymousClients();
                })
                .AddValidation(options =>
                {
                    options.AddEventHandler<OpenIddictValidationEvents.RetrieveToken>(notifaction =>
                    {
                        notifaction.Context.Token = notifaction.Context.Request.Query["access_token"];
                        return Task.CompletedTask;
                    });
                });
```

When executed into code
`. Addvalidation`
raised the question above.
Did I make a mistake using the above?

At present, my alternative is as follows:
remove
`. Addvalidation(...)`
Replace with the following code:
```
services.AddAuthentication()
                .AddOAuthValidation(options =>
                {
                    options.Events.OnRetrieveToken = context =>
                    {
                        context.Token = context.Request.Query["access_token"];
                        return Task.CompletedTask;
                    };
                });
```

**Comment by PinpointTownes** [comment]
We recently migrated the OpenID module to use OpenIddict `2.0.0-rtm-1116`. Can you please make sure you're using the same version in your own project?

**Comment by kamikyo** [comment]
@PinpointTownes 
There is no such error when I upgrade openiddict to 2.0.0-rtm-1116. 
The puzzle is that NuGet doesn't have this version of what you said, so I have to manually edit my csproj file.
![image](https://user-images.githubusercontent.com/7645337/47057521-b3498c80-d1f3-11e8-8be9-154401f67c41.png)

Thank you Pinpointtownes, your OpenIddict is very useful to me.

**Comment by kamikyo** [comment]
@PinpointTownes I am very sorry, you still have a question that needs your help.
I encountered this error when I created the table using EF Core's Migrations.
```
Failed executing DbCommand (45ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE INDEX `IX_OpenIddictAuthorizations_ApplicationId_Scopes_Status_Subject~` ON `OpenIddictAuthorizations` (`ApplicationId`, `Scopes`, `Status`, `Subject`, `Type`);
MySql.Data.MySqlClient.MySqlException (0x80004005): Specified key was too long; max key length is 3072 bytes ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Specified key was too long; max key length is 3072 bytes
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 44
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 88
   at MySql.Data.MySqlClient.MySqlDataReader.ReadFirstResultSetAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 299
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(MySqlCommand command, CommandBehavior behavior, ResultSetProtocol resultSetProtocol, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 284
   at MySqlConnector.Core.TextCommandExecutor.ExecuteReaderAsync(String commandText, MySqlParameterCollection parameterCollection, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 37
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 261
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 62
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Specified key was too long; max key length is 3072 bytes
```
**The database I am using is MySQL Community 5.6.26**

**Comment by PinpointTownes** [comment]
Looks like you're using the "official" MySQL provider, which is known for having a few bugs.
Could you please try with the Pomelo provider?

On my side, I'll consider adding explicit column lengths to see if it can help avoid these issues.

**Comment by PinpointTownes** [comment]
@kamikyo FYI, I tried my best to make the official MySQL provider developed by Oracle work flawlessly with OpenIddict but it's just impossible without introducing nasty hacks (e.g it doesn't correctly build `DateTimeOffset` instances from `timestamp` columns, which results in wrong token expiration dates).

So to be clear, I will - deliberately - not support it. Instead, I encourage you to use the Pomelo provider, which works like a charm. If you want to use it anyway, you'll be able to work around the issue you described by overriding some key lengths from `DbContext.OnModelConfiguring()` and replacing things like `OpenIddictTokenStore.GetCreationDateAsync()` and `GetExpirationDateAsync()` to take Oracle's `DateTimeOffset` bug into account.
