### ISSUE TITLE
Upgrade yessql.abstractions to v2.0.0.0-beta-1269 throws an error

### ISSUE THREAD

**Issue by kamikyo** [OrchardCMS/OrchardCore#2517]
```
System.TypeLoadException: Method 'get_Dialect' in type 'YesSql.Store' from assembly 'YesSql.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Microsoft.Extensions.DependencyInjection.OrchardCoreBuilderExtensions.<>c.<AddDataAccess>b__0_1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.OrchardCoreBuilderExtensions.<>c.<AddDataAccess>b__0_2(IServiceProvider sp) in C:\projects\orchard2\src\OrchardCore\OrchardCore.Data\OrchardCoreBuilderExtensions.cs:line 91
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at OrchardCore.Environment.Shell.Builders.ShellContextFactory.OrchardCore.Environment.Shell.Builders.IShellContextFactory.CreateShellContextAsync(ShellSettings settings) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Environment\Shell\Builders\ShellContextFactory.cs:line 42
   at OrchardCore.Environment.Shell.ShellHost.GetOrCreateShellContextAsync(ShellSettings settings) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Environment\Shell\ShellHost.cs:line 88
   at OrchardCore.Environment.Shell.ShellHost.<CreateAndRegisterShellsAsync>b__15_0(ShellSettings settings) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Environment\Shell\ShellHost.cs:line 182
```
The Orchardcore version I'm using is v1.0.0-beta3-68912
When I downgraded Yessql to v2.0.0-beta3-1266, there was no such error.

**Comment by sebastienros** [comment]
How can we repro the issue?

**Comment by kamikyo** [comment]
@sebastienros I'm sorry, because of the jet lag, I didn't get back to you in time.
we can repro the issue like this:
![image](https://user-images.githubusercontent.com/7645337/47099047-188a9580-d267-11e8-9ca8-41454a99d911.png)
AccountModule.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Module.Targets" Version="1.0.0-beta3-68918" />
    <PackageReference Include="OrchardCore.Users" Version="1.0.0-beta3-68918" />
    <PackageReference Include="YesSql.Abstractions" Version="2.0.0-beta-1266" />
  </ItemGroup>

</Project>
```
Migrations.cs
```
using OrchardCore.Data.Migration;

namespace AccountModule
{
    public class Migrations : DataMigration
    {
        public int Create()
        {
            SchemaBuilder.CreateMapIndexTable(nameof(UserExtendSearchIndex), table => table
                .Column<int>("UID")
                .Column<string>("Account")
                .Column<string>("WorkNo")
                .Column<string>("Name")
                .Column<string>("NickName")
            );
            return 5;
        }
    }
}
```
UserExtendSearchIndex.cs
```
using YesSql.Indexes;

namespace AccountModule
{
    public class UserExtendSearchIndex : MapIndex
    {
        public int UID { get; set; }
        public string Account { get; set; }
        public string WorkNo { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
    }
}
```
UserExtendSearchIndexProvider.cs
```
using Newtonsoft.Json.Linq;
using OrchardCore.Users.Models;
using YesSql.Indexes;

namespace AccountModule
{
    public class UserExtendSearchIndexProvider : IndexProvider<User>
    {
        public override void Describe(DescribeContext<User> context)
        {
            context.For<UserExtendSearchIndex>().Map(u =>
                new UserExtendSearchIndex
                {
                    UID = u.Id,
                    Account = u.UserName,
                    NickName = u.Properties["NickName"]?.Value<string>(),
                    Name = u.Properties["RealName"]?.Value<string>(),
                    WorkNo = u.Properties["WorkNo"]?.Value<string>()
                });
        }
    }
}
```

cms.csproj
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="OrchardCore.Application.Cms.Targets" Version="1.0.0-beta3-68918" />
    <PackageReference Include="OrchardCore.Application.Targets" Version="1.0.0-beta3-68918" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AccountModule\AccountModule.csproj" />
  </ItemGroup>

</Project>
```
Startup.cs
```
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using OrchardCore.ResourceManagement;

namespace cms
{
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOrchardCms();
            services.AddScoped<IResourceManifestProvider, MyResourceManifest>();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseStaticFiles();
            app.UseOrchardCore();
        }
    }
}
```
MyResourceManifest.cs (don't want to use cdn)
```
using OrchardCore.ResourceManagement;

namespace cms
{
    public class MyResourceManifest : IResourceManifestProvider
    {
        public void BuildManifests(IResourceManifestBuilder builder)
        {
            var manifest = builder.Add();

            manifest
                .DefineScript("jQuery")
                .SetUrl("/jquery.min.js")
                .SetVersion("3.3.1")
                ;
        }
    }
}
```

Now, we can deploy orchardcore cms normally using YesSql.Abstractions 2.0.0-beta-1266
However, if you use 2.0.0-beta-1269, you will get the following error during the deployment phase.
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'get_DbConnectionType' in type 'OrchardCore.MiniProfiler.MiniProfilerConnectionFactory' from assembly 'OrchardCore.MiniProfiler, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 76
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 100
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
System.TypeLoadException: Method 'get_DbConnectionType' in type 'OrchardCore.MiniProfiler.MiniProfilerConnectionFactory' from assembly 'OrchardCore.MiniProfiler, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```
Ok, in order to reproduce the error I mentioned at the beginning, we first install orchardcore cms (SaaS) using 2.0.0-beta-1266 
**PS:I almost forgot to tell you that the database I am using is MySQL Community 5.6.26**
We use 2.0.0-beta-1266 to complete the installation of orchard core cms. Then, we modify AccountModule.csproj and let the module re-run the site using 2.0.0-beta-1269. Now we get this error：

```
System.TypeLoadException: Method 'get_Dialect' in type 'YesSql.Store' from assembly 'YesSql.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
...
...
```

**Comment by sebastienros** [comment]
We are not using 1269 yet in Orchard Core. Then if you want to use 1269 I think you need to reference the 6 packages from yessql.

My suggestion is to not update to 1269 until Orchard Core does it by itself. I don't see any reason you would want to do it, there is just a change to test and async method, and it should not unblock any scenario.
