### ISSUE TITLE
NullReferenceException while downloading Deployment File

### ISSUE THREAD

**Issue by mdockal** [OrchardCMS/OrchardCore#2558]
Created a Tenant called Blog in the current dev build of Orchard Core.   Setup with a blog recipe sqlite database.  Went to admin, created a deployment plan.   Added a Content Definition step to export the following blog content types to use in my Decoupled CMS.  
Article | Liquid Page | Blog Post | Blog | Container | Blockquote | Liquid | Page 

Clicked Execute and then tried to download the file. Got the following exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.

   at OrchardCore.ContentTypes.Deployment.ContentDefinitionDeploymentSource.ProcessDeploymentStepAsync(DeploymentStep step, DeploymentPlanResult result) in C:\projects\orchard2\src\OrchardCore.Modules\OrchardCore.ContentTypes\Deployment\ContentDefinitionDeploymentSource.cs:line 30

   at OrchardCore.Deployment.Core.Services.DeploymentManager.ExecuteDeploymentPlanAsync(DeploymentPlan deploymentPlan, DeploymentPlanResult result) in C:\projects\orchard2\src\OrchardCore\OrchardCore.Deployment.Core\Services\DeploymentManager.cs:line 28

   at OrchardCore.Deployment.Controllers.ExportFileController.Execute(Int32 id) in C:\projects\orchard2\src\OrchardCore.Modules\OrchardCore.Deployment\Controllers\ExportFileController.cs:line 55

   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

   at System.Threading.Tasks.ValueTask`1.get_Result()

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()

   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)

   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)

   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)

   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 76

   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 99

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by psijkof** [comment]
I am able to reproduce on latest packages. Will investigate the source.

**Comment by psijkof** [comment]
When this PR gets merged, the issue should be gone.
