### ISSUE TITLE
Miniprofiler issue : Nuget solution (latest beta-3)

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#2615]
I'm getting this issue now with Nuget packages solution.

```
An unhandled exception occurred while processing the request.
TypeLoadException: Method 'get_DbConnectionType' in type 'OrchardCore.MiniProfiler.MiniProfilerConnectionFactory' from assembly 'OrchardCore.MiniProfiler, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Unknown location

ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'get_DbConnectionType' in type 'OrchardCore.MiniProfiler.MiniProfilerConnectionFactory' from assembly 'OrchardCore.MiniProfiler, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)

Loader Exceptions:
Method 'get_DbConnectionType' in type 'OrchardCore.MiniProfiler.MiniProfilerConnectionFactory' from assembly 'OrchardCore.MiniProfiler, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Stack Query Cookies Headers
TypeLoadException: Method 'get_DbConnectionType' in type 'OrchardCore.MiniProfiler.MiniProfilerConnectionFactory' from assembly 'OrchardCore.MiniProfiler, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Show raw exception details
System.TypeLoadException: Method 'get_DbConnectionType' in type 'OrchardCore.MiniProfiler.MiniProfilerConnectionFactory' from assembly 'OrchardCore.MiniProfiler, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
ReflectionTypeLoadException: Unable to load one or more of the requested types.
 Method 'get_DbConnectionType' in type 'OrchardCore.MiniProfiler.MiniProfilerConnectionFactory' from assembly 'OrchardCore.MiniProfiler, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
System.Reflection.RuntimeAssembly.get_DefinedTypes()
Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable<ApplicationPart> parts, ControllerFeature feature)
Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature<TFeature>(TFeature feature)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.UpdateCollection()
Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in ModularTenantRouterMiddleware.cs
OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in ModularTenantContainerMiddleware.cs
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Show raw exception details
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'get_DbConnectionType' in type 'OrchardCore.MiniProfiler.MiniProfilerConnectionFactory' from assembly 'OrchardCore.MiniProfiler, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 76
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 99
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
System.TypeLoadException: Method 'get_DbConnectionType' in type 'OrchardCore.MiniProfiler.MiniProfilerConnectionFactory' from assembly 'OrchardCore.MiniProfiler, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

**Comment by sebastienros** [comment]
Wrong combination of dlls, restore again

**Comment by Skrypt** [comment]
I did a git clean -xdf and dotnet restore on the folder and I get the same result. Myget delay?

**Comment by Skrypt** [comment]
Got it. Needed to set back Version="1.0.0-beta3-*" in csproj. If I set it to a fixed version it fails as expected.
