### ISSUE TITLE
ContentTypes created via migrations now crash drivers

### ISSUE THREAD

**Issue by carlwoodhouse** [OrchardCMS/OrchardCore#2881]
Repo steps
1. Create a simple contenttype via a migration
```
     _contentDefinitionManager.AlterTypeDefinition("test101", cfg => cfg
        .Draftable()
        .Versionable()
        .Creatable()
        .Listable()
        .WithPart("test101", part => part.WithPosition("2"))
        .WithPart("TitlePart", part => part.WithPosition("1")));
```
2. Go to the admin and click create new, it throws the following exception and the editors dont load ..
```
2018-12-17 16:03:31.9206|Default|0HLJ4749HKRO4:00000004||OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator|ERROR|IContentPartDisplayDriver thrown from OrchardCore.Title.Drivers.TitlePartDisplay by NullReferenceException System.NullReferenceException: Object reference not set to an instance of an object.
   at OrchardCore.ContentManagement.Display.ContentDisplay.ContentPartDisplayDriver`1.Factory(String shapeType, Func`2 shapeBuilder, Func`2 initializeAsync) in C:\development\github\OrchardCore\src\OrchardCore\OrchardCore.ContentManagement.Display\ContentDisplay\ContentPartDisplayDriverTPart.cs:line 33
   at OrchardCore.DisplayManagement.Handlers.DisplayDriverBase.Factory(String shapeType, Func`2 shapeBuilder) in C:\development\github\OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement\Handlers\DisplayDriverBase.cs:line 112
   at OrchardCore.DisplayManagement.Handlers.DisplayDriverBase.Initialize[TModel](String shapeType, Func`2 initializeAsync) in C:\development\github\OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement\Handlers\DisplayDriverBase.cs:line 36
   at OrchardCore.Title.Drivers.TitlePartDisplay.Edit(TitlePart titlePart) in C:\development\github\OrchardCore\src\OrchardCore.Modules\OrchardCore.Title\Drivers\TitlePartDisplay.cs:line 25
   at OrchardCore.ContentManagement.Display.ContentDisplay.ContentPartDisplayDriver`1.Edit(TPart part, BuildPartEditorContext context) in C:\development\github\OrchardCore\src\OrchardCore\OrchardCore.ContentManagement.Display\ContentDisplay\ContentPartDisplayDriverTPart.cs:line 223
   at OrchardCore.ContentManagement.Display.ContentDisplay.ContentPartDisplayDriver`1.EditAsync(TPart part, BuildPartEditorContext context) in C:\development\github\OrchardCore\src\OrchardCore\OrchardCore.ContentManagement.Display\ContentDisplay\ContentPartDisplayDriverTPart.cs:line 218
   at OrchardCore.ContentManagement.Display.ContentDisplay.ContentPartDisplayDriver`1.OrchardCore.ContentManagement.Display.ContentDisplay.IContentPartDisplayDriver.BuildEditorAsync(ContentPart contentPart, ContentTypePartDefinition typePartDefinition, BuildEditorContext context) in C:\development\github\OrchardCore\src\OrchardCore\OrchardCore.ContentManagement.Display\ContentDisplay\ContentPartDisplayDriverTPart.cs:line 174
   at OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator.<>c__DisplayClass11_2.<<BuildEditorAsync>b__0>d.MoveNext() in C:\development\github\OrchardCore\src\OrchardCore\OrchardCore.ContentManagement.Display\ContentDisplay\ContentItemDisplayCoordinator.cs:line 200
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents](IEnumerable`1 events, Func`2 dispatch, ILogger logger) in C:\development\github\OrchardCore\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 78    at OrchardCore.ContentManagement.Display.ContentDisplay.ContentPartDisplayDriver`1.Factory(String shapeType, Func`2 shapeBuilder, Func`2 initializeAsync) in C:\development\github\OrchardCore\src\OrchardCore\OrchardCore.ContentManagement.Display\ContentDisplay\ContentPartDisplayDriverTPart.cs:line 33
   at OrchardCore.DisplayManagement.Handlers.DisplayDriverBase.Factory(String shapeType, Func`2 shapeBuilder) in C:\development\github\OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement\Handlers\DisplayDriverBase.cs:line 112
   at OrchardCore.DisplayManagement.Handlers.DisplayDriverBase.Initialize[TModel](String shapeType, Func`2 initializeAsync) in C:\development\github\OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement\Handlers\DisplayDriverBase.cs:line 36
   at OrchardCore.Title.Drivers.TitlePartDisplay.Edit(TitlePart titlePart) in C:\development\github\OrchardCore\src\OrchardCore.Modules\OrchardCore.Title\Drivers\TitlePartDisplay.cs:line 25
   at OrchardCore.ContentManagement.Display.ContentDisplay.ContentPartDisplayDriver`1.Edit(TPart part, BuildPartEditorContext context) in C:\development\github\OrchardCore\src\OrchardCore\OrchardCore.ContentManagement.Display\ContentDisplay\ContentPartDisplayDriverTPart.cs:line 223
   at OrchardCore.ContentManagement.Display.ContentDisplay.ContentPartDisplayDriver`1.EditAsync(TPart part, BuildPartEditorContext context) in C:\development\github\OrchardCore\src\OrchardCore\OrchardCore.ContentManagement.Display\ContentDisplay\ContentPartDisplayDriverTPart.cs:line 218
   at OrchardCore.ContentManagement.Display.ContentDisplay.ContentPartDisplayDriver`1.OrchardCore.ContentManagement.Display.ContentDisplay.IContentPartDisplayDriver.BuildEditorAsync(ContentPart contentPart, ContentTypePartDefinition typePartDefinition, BuildEditorContext context) in C:\development\github\OrchardCore\src\OrchardCore\OrchardCore.ContentManagement.Display\ContentDisplay\ContentPartDisplayDriverTPart.cs:line 174
   at OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator.<>c__DisplayClass11_2.<<BuildEditorAsync>b__0>d.MoveNext() in C:\development\github\OrchardCore\src\OrchardCore\OrchardCore.ContentManagement.Display\ContentDisplay\ContentItemDisplayCoordinator.cs:line 200
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents](IEnumerable`1 events, Func`2 dispatch, ILogger logger) in C:\development\github\OrchardCore\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 78
```

This was working fine till very recently

**Comment by carlwoodhouse** [comment]
ok it seems its to do with settings on the type, and is fixed in this open pr #2873
