### ISSUE TITLE
OpenIdServerSettings can't save any settings

### ISSUE THREAD

**Issue by mmdqq** [OrchardCMS/OrchardCore#2941]
![20181225135853](https://user-images.githubusercontent.com/4881282/50414126-a8902100-084e-11e9-9eec-ba9bc09315b9.png)
It show "Site settings updated successfully." but nothing is changed.
I think something wrong at 
![20181225140006](https://user-images.githubusercontent.com/4881282/50414188-0c1a4e80-084f-11e9-9f14-596e025de5a6.png)

**Comment by Skrypt** [comment]
Stack trace : 

```C#
2019-01-08 17:08:30.0530|Default|0HLJLMM6IPR7C:0000000C||OrchardCore.DisplayManagement.DisplayManager|ERROR|IDisplayDriver`1 thrown from OrchardCore.OpenId.Drivers.OpenIdServerSettingsDisplayDriver by InvalidOperationException System.InvalidOperationException: The certificate was not found.
   at OrchardCore.OpenId.Services.OpenIdServerService.GetCertificate(StoreLocation location, StoreName name, String thumbprint) in E:\Repositories\OrchardCore\src\OrchardCore.Modules\OrchardCore.OpenId\Services\OpenIdServerService.cs:line 327
   at OrchardCore.OpenId.Services.OpenIdServerService.ValidateSettingsAsync(OpenIdServerSettings settings) in E:\Repositories\OrchardCore\src\OrchardCore.Modules\OrchardCore.OpenId\Services\OpenIdServerService.cs:line 123
   at OrchardCore.OpenId.Drivers.OpenIdServerSettingsDisplayDriver.UpdateAsync(OpenIdServerSettings settings, BuildEditorContext context) in E:\Repositories\OrchardCore\src\OrchardCore.Modules\OrchardCore.OpenId\Drivers\OpenIdServerSettingsDisplayDriver.cs:line 178
   at OrchardCore.DisplayManagement.Entities.SectionDisplayDriver`2.UpdateAsync(TModel model, UpdateEditorContext context) in E:\Repositories\OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement\Entities\SectionDisplayDriver.cs:line 74
   at OrchardCore.DisplayManagement.DisplayManager`1.<>c__DisplayClass12_0.<<UpdateEditorAsync>b__0>d.MoveNext() in E:\Repositories\OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement\DisplayManager.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents](IEnumerable`1 events, Func`2 dispatch, ILogger logger) in E:\Repositories\OrchardCore\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 78    at OrchardCore.OpenId.Services.OpenIdServerService.GetCertificate(StoreLocation location, StoreName name, String thumbprint) in E:\Repositories\OrchardCore\src\OrchardCore.Modules\OrchardCore.OpenId\Services\OpenIdServerService.cs:line 327
   at OrchardCore.OpenId.Services.OpenIdServerService.ValidateSettingsAsync(OpenIdServerSettings settings) in E:\Repositories\OrchardCore\src\OrchardCore.Modules\OrchardCore.OpenId\Services\OpenIdServerService.cs:line 123
   at OrchardCore.OpenId.Drivers.OpenIdServerSettingsDisplayDriver.UpdateAsync(OpenIdServerSettings settings, BuildEditorContext context) in E:\Repositories\OrchardCore\src\OrchardCore.Modules\OrchardCore.OpenId\Drivers\OpenIdServerSettingsDisplayDriver.cs:line 178
   at OrchardCore.DisplayManagement.Entities.SectionDisplayDriver`2.UpdateAsync(TModel model, UpdateEditorContext context) in E:\Repositories\OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement\Entities\SectionDisplayDriver.cs:line 74
   at OrchardCore.DisplayManagement.DisplayManager`1.<>c__DisplayClass12_0.<<UpdateEditorAsync>b__0>d.MoveNext() in E:\Repositories\OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement\DisplayManager.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents](IEnumerable`1 events, Func`2 dispatch, ILogger logger) in E:\Repositories\OrchardCore\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 78

```

**Comment by PinpointTownes** [comment]
@sebastienros don't hesitate to assign me OpenID-related issues and flag them with the `Orchard.OpenId` tag so I don't miss them :smile: 

This is a known issue, indeed caused by the exception mentioned by @Skrypt. The fix is already part of https://github.com/OrchardCMS/OrchardCore/pull/2886/files#diff-c9cd759f1b867f013a6a96541afb11feR438, so we may want to merge it for beta3.

**Comment by PinpointTownes** [comment]
I should have probably mentioned here, but to avoid this error, the "solution" - until we merge the PR I mentioned - is to either check the testing mode checkbox - which will result in an ephemeral key being created - or populate the certificate field with actual values. Essentially, you just tried to save invalid changes in this case.
