### ISSUE TITLE
Indexing Task Manager Error : The incoming request has too many parameters.

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#3096]
Hi,

The method tries to send all (delete/insert) at once. Maybe we need to limit this to blocks of 1000 records.

```
2019-01-27 05:48:39.8626|None|0HLK3SUDG0G7J||OrchardCore.Indexing.Services.IndexingTaskManager|ERROR|An error occured while updating indexing tasks 
2019-01-27 05:48:39.8876||||OrchardCore.Modules.ModularBackgroundService|ERROR|Error while executing 'ModularBackgroundService', the service is stopping. System.AggregateException: One or more errors occurred. (The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.) ---> System.Data.SqlClient.SqlException: The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 687
   at OrchardCore.Indexing.Services.IndexingTaskManager.FlushAsync() in C:\projects\orchard2\src\OrchardCore.Modules\OrchardCore.Indexing\IndexingTaskManager.cs:line 122
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at OrchardCore.Indexing.Services.IndexingTaskManager.Dispose() in C:\projects\orchard2\src\OrchardCore.Modules\OrchardCore.Indexing\IndexingTaskManager.cs:line 66
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at OrchardCore.Hosting.ShellBuilders.ShellContext.ServiceScopeWrapper.Dispose() in C:\projects\orchard2\src\OrchardCore\OrchardCore.Abstractions\Shell\Builders\ShellContext.cs:line 279
   at OrchardCore.Modules.ModularBackgroundService.<>c__DisplayClass12_0.<<RunAsync>b__0>d.MoveNext() in C:\projects\orchard2\src\OrchardCore\OrchardCore\Modules\ModularBackgroundService.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.EnumerableExtensions.<>c__DisplayClass0_1`1.<<ForEachAsync>b__1>d.MoveNext() in C:\projects\orchard2\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\EnumerableExtensions.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.ModularBackgroundService.RunAsync(IEnumerable`1 runningShells, CancellationToken stoppingToken) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Modules\ModularBackgroundService.cs:line 147
   at OrchardCore.Modules.ModularBackgroundService.ExecuteAsync(CancellationToken stoppingToken) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Modules\ModularBackgroundService.cs:line 81
---> (Inner Exception #0) System.Data.SqlClient.SqlException (0x80131904): The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 687
   at OrchardCore.Indexing.Services.IndexingTaskManager.FlushAsync() in C:\projects\orchard2\src\OrchardCore.Modules\OrchardCore.Indexing\IndexingTaskManager.cs:line 122
ClientConnectionId:a8764098-9565-4968-b0b1-e0f40a5fb198
Error Number:8003,State:1,Class:16<---
    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at OrchardCore.Indexing.Services.IndexingTaskManager.Dispose() in C:\projects\orchard2\src\OrchardCore.Modules\OrchardCore.Indexing\IndexingTaskManager.cs:line 66
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at OrchardCore.Hosting.ShellBuilders.ShellContext.ServiceScopeWrapper.Dispose() in C:\projects\orchard2\src\OrchardCore\OrchardCore.Abstractions\Shell\Builders\ShellContext.cs:line 279
   at OrchardCore.Modules.ModularBackgroundService.<>c__DisplayClass12_0.<<RunAsync>b__0>d.MoveNext() in C:\projects\orchard2\src\OrchardCore\OrchardCore\Modules\ModularBackgroundService.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.EnumerableExtensions.<>c__DisplayClass0_1`1.<<ForEachAsync>b__1>d.MoveNext() in C:\projects\orchard2\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\EnumerableExtensions.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.ModularBackgroundService.RunAsync(IEnumerable`1 runningShells, CancellationToken stoppingToken) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Modules\ModularBackgroundService.cs:line 147
   at OrchardCore.Modules.ModularBackgroundService.ExecuteAsync(CancellationToken stoppingToken) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Modules\ModularBackgroundService.cs:line 81

```

**Comment by jpiquot** [comment]
We could do these changes : 
```

       private async Task FlushAsync()
        {
            List<IndexingTask> localQueue;

            lock (_tasksQueue)
            {
                localQueue = new List<IndexingTask>(_tasksQueue);
            }

            if (!localQueue.Any())
            {
                return;
            }

            var transaction = await _session.DemandAsync();
            var dialect = SqlDialectFactory.For(transaction.Connection);

            try
            {
                var contentItemIds = new HashSet<string>();

                // Remove duplicate tasks, only keep the last one
                for (var i = localQueue.Count; i > 0; i--)
                {
                    var task = localQueue[i - 1];

                    if (contentItemIds.Contains(task.ContentItemId))
                    {
                        localQueue.RemoveAt(i - 1);
                    }
                    else
                    {
                        contentItemIds.Add(task.ContentItemId);
                    }
                }
                var pageSize = 500;
                var pages = localQueue.Count / pageSize;
                if (localQueue.Count / pageSize != 0)
                {
                    pages++;
                }

                for (var i = 0; i < pages; i++)
                {
                    // At this point, content items ids should be unique in _taskQueue
                    var ids = localQueue
                        .Skip(i*pageSize)
                        .Take(pageSize)
                        .Select(x => x.ContentItemId).ToArray();
                    
                    var table = $"{_tablePrefix}{nameof(IndexingTask)}";

                    var deleteCmd = $"delete from {dialect.QuoteForTableName(table)} where {dialect.QuoteForColumnName("ContentItemId")} {dialect.InOperator("@Ids")};";
                    await transaction.Connection.ExecuteAsync(deleteCmd, new { Ids = ids }, transaction);

                    var insertCmd = $"insert into {dialect.QuoteForTableName(table)} ({dialect.QuoteForColumnName("CreatedUtc")}, {dialect.QuoteForColumnName("ContentItemId")}, {dialect.QuoteForColumnName("Type")}) values (@CreatedUtc, @ContentItemId, @Type);";
                    await transaction.Connection.ExecuteAsync(insertCmd, _tasksQueue, transaction);
                }
            }
            catch (Exception e)
            {
                _session.Cancel();
                Logger.LogError("An error occured while updating indexing tasks", e);
                throw;
            }

            _tasksQueue.Clear();
        }

```

**Comment by sebastienros** [comment]
We need paging here if not already done.

**Comment by Skrypt** [comment]
This is the issue I was getting from my database import.
