### ISSUE TITLE
after publishing the first run doesn't shows install page [stdout]

### ISSUE THREAD

**Issue by Arashz22** [OrchardCMS/OrchardCore#3115]
after publishing self-containd x86 and running my website for the first time installation page doesn't appear.
does any one knows what this stdout log mean ?
what is the error ?
```
Hosting environment: Production
Content root path: D:\HostingSpaces\esprichoo.com\ArashZandi.ir
Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer[2]
      Connection ID "7638109367677513107", Request ID "80006d97-0400-6a00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
System.Data.SqlClient.SqlException (0x80131904): Login failed for user 'WIN-L8EGNA16HA0\IWPD_1641(arashzan)'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at YesSql.Session.DemandAsync()
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at OrchardCore.Environment.Shell.Data.Descriptors.ShellDescriptorManager.GetShellDescriptorAsync() in C:\OtherFiles\WorkSpace-Offline\OrchardCore\src\OrchardCore\OrchardCore.Infrastructure\Shell\ShellDescriptorManager.cs:line 55
   at OrchardCore.Environment.Shell.Builders.ShellContextFactory.OrchardCore.Environment.Shell.Builders.IShellContextFactory.CreateShellContextAsync(ShellSettings settings) in C:\OtherFiles\WorkSpace-Offline\OrchardCore\src\OrchardCore\OrchardCore\Environment\Shell\Builders\ShellContextFactory.cs:line 43
   at OrchardCore.Environment.Shell.ShellHost.GetOrCreateShellContextAsync(ShellSettings settings) in C:\OtherFiles\WorkSpace-Offline\OrchardCore\src\OrchardCore\OrchardCore\Environment\Shell\ShellHost.cs:line 89
   at OrchardCore.Environment.Shell.ShellHost.PreCreateAndRegisterShellsAsync() in C:\OtherFiles\WorkSpace-Offline\OrchardCore\src\OrchardCore\OrchardCore\Environment\Shell\ShellHost.cs:line 186
   at OrchardCore.Environment.Shell.ShellHost.InitializeAsync() in C:\OtherFiles\WorkSpace-Offline\OrchardCore\src\OrchardCore\OrchardCore\Environment\Shell\ShellHost.cs:line 62
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\OtherFiles\WorkSpace-Offline\OrchardCore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 37
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
ClientConnectionId:60728923-0829-4249-96df-e1e87bb510f0
Error Number:18456,State:1,Class:14

```

**Comment by sebastienros** [comment]
The issue is written in the log excerpt you posted:
`System.Data.SqlClient.SqlException (0x80131904): Login failed for user 'WIN-L8EGNA16HA0\IWPD_1641(arashzan)'.
`
