### ISSUE TITLE
With multiple workflows running, we have deadlock errors.

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#3130]
Hi,

Moving id generation to a new session in YesSQL makes things better. But we still have issues with long running workflows. The root cause is coming from the opened transaction held by the Worflow manager.

Transactions on very short actions are generally not an issue, but keeping these open for a long time like running workflows that have long running activities can generate deadlocks.

```
2019-02-02 13:43:09.3248|None|0HLK91F4EL20L||OrchardCore.Workflows.Services.WorkflowStore|ERROR|IWorkflowHandler thrown from OrchardCore.Workflows.Http.Handlers.WorkflowRoutesHandler by SqlException System.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 291) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteReader(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Dapper.SqlMapper.ExecuteScalarImplAsync[T](IDbConnection cnn, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 1217
   at YesSql.Session.UpdateEntityAsync(Object entity) in C:\projects\yessql-un1yf\src\YesSql.Core\Session.cs:line 238
   at YesSql.Session.CommitAsync() in C:\projects\yessql-un1yf\src\YesSql.Core\Session.cs:line 522
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl() in C:\projects\yessql-un1yf\src\YesSql.Core\Services\DefaultQuery.cs:line 860
   at OrchardCore.Workflows.Http.Handlers.WorkflowRoutesHandler.UpdateRouteEntriesAsync(WorkflowContext context) in C:\projects\orchard2\src\OrchardCore.Modules\OrchardCore.Workflows\Http\Handlers\WorkflowInstanceRoutesHandler.cs:line 44
   at OrchardCore.Workflows.Http.Handlers.WorkflowRoutesHandler.UpdatedAsync(WorkflowUpdatedContext context) in C:\projects\orchard2\src\OrchardCore.Modules\OrchardCore.Workflows\Http\Handlers\WorkflowInstanceRoutesHandler.cs:line 32
   at OrchardCore.Workflows.Services.WorkflowStore.<>c__DisplayClass14_1.<<SaveAsync>b__1>d.MoveNext() in C:\projects\orchard2\src\OrchardCore.Modules\OrchardCore.Workflows\Services\WorkflowStore.cs:line 126
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents](IEnumerable`1 events, Func`2 dispatch, ILogger logger) in C:\projects\orchard2\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 78
ClientConnectionId:8fa797bb-6ba4-4e27-9a9a-bf4dbf4e7913
Error Number:1205,State:51,Class:13    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteReader(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Dapper.SqlMapper.ExecuteScalarImplAsync[T](IDbConnection cnn, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 1217
   at YesSql.Session.UpdateEntityAsync(Object entity) in C:\projects\yessql-un1yf\src\YesSql.Core\Session.cs:line 238
   at YesSql.Session.CommitAsync() in C:\projects\yessql-un1yf\src\YesSql.Core\Session.cs:line 522
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl() in C:\projects\yessql-un1yf\src\YesSql.Core\Services\DefaultQuery.cs:line 860
   at OrchardCore.Workflows.Http.Handlers.WorkflowRoutesHandler.UpdateRouteEntriesAsync(WorkflowContext context) in C:\projects\orchard2\src\OrchardCore.Modules\OrchardCore.Workflows\Http\Handlers\WorkflowInstanceRoutesHandler.cs:line 44
   at OrchardCore.Workflows.Http.Handlers.WorkflowRoutesHandler.UpdatedAsync(WorkflowUpdatedContext context) in C:\projects\orchard2\src\OrchardCore.Modules\OrchardCore.Workflows\Http\Handlers\WorkflowInstanceRoutesHandler.cs:line 32
   at OrchardCore.Workflows.Services.WorkflowStore.<>c__DisplayClass14_1.<<SaveAsync>b__1>d.MoveNext() in C:\projects\orchard2\src\OrchardCore.Modules\OrchardCore.Workflows\Services\WorkflowStore.cs:line 126
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents](IEnumerable`1 events, Func`2 dispatch, ILogger logger) in C:\projects\orchard2\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 78
2019-02-02 13:43:09.4409||||OrchardCore.Modules.ModularBackgroundService|ERROR|Error while executing 'ModularBackgroundService', the service is stopping. System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable.
   at System.Data.SqlClient.SqlTransaction.ZombieCheck()
   at System.Data.SqlClient.SqlTransaction.Commit()
   at YesSql.Session.Dispose() in C:\projects\yessql-un1yf\src\YesSql.Core\Session.cs:line 438
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at OrchardCore.Hosting.ShellBuilders.ShellContext.ServiceScopeWrapper.Dispose() in C:\projects\orchard2\src\OrchardCore\OrchardCore.Abstractions\Shell\Builders\ShellContext.cs:line 272
   at OrchardCore.Modules.ModularBackgroundService.<>c__DisplayClass12_0.<<RunAsync>b__0>d.MoveNext() in C:\projects\orchard2\src\OrchardCore\OrchardCore\Modules\ModularBackgroundService.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.EnumerableExtensions.<>c__DisplayClass0_1`1.<<ForEachAsync>b__1>d.MoveNext() in C:\projects\orchard2\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\EnumerableExtensions.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.ModularBackgroundService.RunAsync(IEnumerable`1 runningShells, CancellationToken stoppingToken) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Modules\ModularBackgroundService.cs:line 85
   at OrchardCore.Modules.ModularBackgroundService.ExecuteAsync(CancellationToken stoppingToken) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Modules\ModularBackgroundService.cs:line 71    at System.Data.SqlClient.SqlTransaction.ZombieCheck()
   at System.Data.SqlClient.SqlTransaction.Commit()
   at YesSql.Session.Dispose() in C:\projects\yessql-un1yf\src\YesSql.Core\Session.cs:line 438
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at OrchardCore.Hosting.ShellBuilders.ShellContext.ServiceScopeWrapper.Dispose() in C:\projects\orchard2\src\OrchardCore\OrchardCore.Abstractions\Shell\Builders\ShellContext.cs:line 272
   at OrchardCore.Modules.ModularBackgroundService.<>c__DisplayClass12_0.<<RunAsync>b__0>d.MoveNext() in C:\projects\orchard2\src\OrchardCore\OrchardCore\Modules\ModularBackgroundService.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.EnumerableExtensions.<>c__DisplayClass0_1`1.<<ForEachAsync>b__1>d.MoveNext() in C:\projects\orchard2\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\EnumerableExtensions.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.ModularBackgroundService.RunAsync(IEnumerable`1 runningShells, CancellationToken stoppingToken) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Modules\ModularBackgroundService.cs:line 85
   at OrchardCore.Modules.ModularBackgroundService.ExecuteAsync(CancellationToken stoppingToken) in C:\projects\orchard2\src\OrchardCore\OrchardCore\Modules\ModularBackgroundService.cs:line 71

```

**Comment by sebastienros** [comment]
I see `ModularBackgroundService` in the stack, probably an issue with the background task for workflows. Could you describe how I can repro it locally, like what is a "long running workflow" I could test?

NB: I just realized (@barthamark made me) that even if we call `CommitAsync` we don't actually release the transaction, if will be done only when the session is disposed and keeping it too long will increase the risk of db locks, so this need to be remembered when doing such things. Or I might have to change what `CommitAsync` actually does, and rename this one `FlushAsync` to be explicit.

**Comment by sebastienros** [comment]
I changed YesSql to support both now. Next I will create a PR to change how we use Flush and Commit in OC.

**Comment by sebastienros** [comment]
@jpiquot can you try with the latest dev branch?

**Comment by jpiquot** [comment]
Thanks @sebastienros . It's OK now.
