### ISSUE TITLE
ShouldListBlogPostWhenCallingAQuery test fails intermitently

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#3157]
In my last commit in dev cdaca20 we can see that `ShouldListBlogPostWhenCallingAQuery` failed. We can also see that it is not an ordering issue but a blog posts count issue.

    Error Message:
     Assert.Equal() Failure
    Expected: 2
    Actual:   1

But not sure because the trace also show a lucene `LockObtainFailedException` which was not the case before when the test was failing intermitently. So maybe another issue.

    fail: OrchardCore.ContentManagement.DefaultContentManager[0]
      IContentHandler thrown from OrchardCore.Lucene.Handlers.LuceneIndexingContentHandler by 
    LockObtainFailedException
    Lucene.Net.Store.LockObtainFailedException: Lock obtain timed out: NativeFSLock@/home/travis/build/OrchardCMS/OrchardCore/test/OrchardCore.Tests/bin/Release/netcoreapp2.2/App_Data/Sites/dd09394dab394e72bc484834f2f5a571/Lucene/Search/write.lock
    at Lucene.Net.Store.Lock.Obtain(Int64 lockWaitTimeout) in C:\BuildAgent\work\b1b63ca15b99dddb\src\Lucene.Net\Store\Lock.cs:line 133
    at Lucene.Net.Index.IndexWriter..ctor(Directory d, IndexWriterConfig conf) in C:\BuildAgent\work\b1b63ca15b99dddb\src\Lucene.Net\Index\IndexWriter.cs:line 829
    at OrchardCore.Lucene.LuceneIndexManager.Write(String indexName, Action`1 action, Boolean close) in /home/travis/build/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Lucene/LuceneIndexManager.cs:line 273
    at OrchardCore.Lucene.Handlers.LuceneIndexingContentHandler.PublishedAsync(PublishContentContext context) in /home/travis/build/OrchardCMS/OrchardCore/src/OrchardCore.Modules/OrchardCore.Lucene/Handler/LuceneIndexingContentHandler.cs:line 40
    at OrchardCore.ContentManagement.DefaultContentManager.<>c__DisplayClass23_1.<<CreateAsync>b__3>d.MoveNext() in /home/travis/build/OrchardCMS/OrchardCore/src/OrchardCore/OrchardCore.ContentManagement/DefaultContentManager.cs:line 393
    --- End of stack trace from previous location where exception was thrown ---
    at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents](IEnumerable`1 events, Func`2 dispatch, ILogger logger) in /home/travis/build/OrchardCMS/OrchardCore/src/OrchardCore/OrchardCore.Abstractions/Modules/Extensions/InvokeExtensions.cs:line 78

So, here there is a lucene writer locking issue in `LuceneIndexingContentHandler` while publishing a blog post. But we use a lock on the `LuceneIndexManager` tenant singleton. So, this would mean that we are not locking on the same instance.

Hmm, just after the tenant setup when the shell has been recreated, maybe the lucene writers (related to the previous instance of `LuceneIndexManager`) are not fully released (on lucene side) when we attempt to create and publish a blog post. If so, we would need to add a delay after the tenant setup.

**Comment by jtkech** [comment]
It happened 2 times the last month on my machine, in both cases it was a count issue.

So, in the unit tests i suggest to add a little delay just after a tenant setup so that lucen has a better chance to complete its index update and close its writer before doing a first query on it.
