### ISSUE TITLE
How to send email at a specific time?

### ISSUE THREAD

**Issue by szilardcsere89** [OrchardCMS/OrchardCore#3187]
Sending ad-hoc emails is pretty easy using a controller and a view as template. Necessary contexts are given to render the template: ViewContext, ControllerContext

But what if I want to send email at a specific time?
My first approach was to doing that in a background job. At this time there are no contexts and view cannot be rendered.

Any other idea that can solve my issue?

**Comment by sebastienros** [comment]
We might need a Scheduled Tasks feature like in O1. At least to support Publish/Archive Later. It could also provide a workflow event though limited as it would be run only once.

Do you really need a scheduled task though or a recurring task, like "Send queued emails every night" mad be able to queue these emails in a jobs queue?

**Comment by szilardcsere89** [comment]
Yes, scheduled task is needed. There are given dates when these emails should be sent. But my issue is not about scheduling but rendering views in a background task where ControllerContext is not available. Eg.: UrlHelper cannot be used to generate urls.

**Comment by jtkech** [comment]
Just for infos and as i remember

In the `sebros/render` branch we worked to render views when there is no `ViewContext` but, as i remember, it still needs an `HttpContext`. That said in the background we build a fake `HttpContext`.

Note: In another branch i'm working, i removed this fake `HttpContext` but, thinking about this kind of things, i reintroduced it.

**Comment by szilardcsere89** [comment]
The following code worked for me without controller's context for weeks, but now I got error, when it tries to find the view:

```
pivate readonly IHttpContextAccessor _httpContextAccessor;
private readonly IOptions<MvcViewOptions> _options;
...

public async Task<string> RenderViewAsync()
{
    var actionContext = new ActionContext(
        _httpContextAccessor.HttpContext,
        new RouteData(),
        new ActionDescriptor());

        actionContext.RouteData.Values.Add("area", "MyArea");
        actionContext.RouteData.Values.Add("controller", "MyController");

        // Throws ex here:
        var viewResult = _options.Value.ViewEngines
           .Select(x => x.FindView(actionContext, "Index", false))
           .FirstOrDefault();
    ...
}
```

System.NullReferenceException: Object reference not set to an instance of an object.
   at OrchardCore.Users.Services.UsersThemeSelector.GetThemeAsync() in C:\projects\orchard2\src\OrchardCore.Modules\OrchardCore.Users\Services\UsersThemeSelector.cs:line 38
   at OrchardCore.DisplayManagement.Theming.ThemeManager.GetThemeAsync() in C:\projects\orchard2\src\OrchardCore\OrchardCore.DisplayManagement\Theming\ThemeManager.cs:line 32
   at OrchardCore.DisplayManagement.LocationExpander.ThemeViewLocationExpanderProvider.PopulateValues(ViewLocationExpanderContext context) in C:\projects\orchard2\src\OrchardCore\OrchardCore.DisplayManagement\LocationExpander\ThemeViewLocationExpanderProvider.cs:line 35
   at OrchardCore.Mvc.LocationExpander.CompositeViewLocationExpanderProvider.PopulateValues(ViewLocationExpanderContext context) in C:\projects\orchard2\src\OrchardCore\OrchardCore.Mvc.Core\LocationExpander\CompositeViewLocationExpanderProvider.cs:line 32
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
