### ISSUE TITLE
OpenId token validation does not work when hosted in Azure App Service

### ISSUE THREAD

**Issue by simon-d** [OrchardCMS/OrchardCore#3222]
All authenticated requests using a JWT bearer token fail when running in an Azure App Service.

Steps to reproduce:

Clone last OC, build and deploy to an Azure App service, then enable the OpenId Authorization Server module
![image](https://user-images.githubusercontent.com/1459793/53220065-82ea9100-36b2-11e9-8b7a-6c69950c1ead.png)

Setup Open Id Authorization server to use JWT tokens
![image](https://user-images.githubusercontent.com/1459793/53220010-3f902280-36b2-11e9-94a4-35a4e978b834.png)

Setup an openId public client to connect using the implicit flow.
![image](https://user-images.githubusercontent.com/1459793/53220041-66e6ef80-36b2-11e9-8610-7f7a92090723.png)

Use postman to a valid access token, then make a request to the /connect/userinfo endpoint.

Expected result:

Http 200 with JSON payload containing the Sub Id number

Actual result:

Http 401 Unauthorized
![image](https://user-images.githubusercontent.com/1459793/53220150-e1b00a80-36b2-11e9-8cc2-ae31a3a87d2e.png)

Doing these same setup steps and running locally, the request to /connect/userinfo works successfully, so it is something to do with running in Azure App Service that is causing the issue. This was working until recently.

**Comment by PinpointTownes** [comment]
The error seems to indicate that the validated token was signed using a key that can no longer be found. Recently, we introduced automatic signing certificates generation and storage, so this issue may be caused by an issue preventing the certificates from being persisted in the `App_Data` folder. Is there anything interesting in the logs?

**Comment by petedavis** [comment]
Yeah there is an issue with finding the generated certificate. I pushed up the dev branch to a new app service and I quite quickly had 7 guid named certificates in the `App_Data\Sites\Default\IdentityModel-Signing-Certificates` folder.

Should there ever be more than one?

```
2019-02-24 23:44:58.577 +00:00 [Warning] OrchardCore.OpenId.Services.OpenIdServerService: An error occurred while trying to extract a X.509 certificate.
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The system cannot find the file specified
   at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at OrchardCore.OpenId.Services.OpenIdServerService.GetManagedSigningCertificatesAsync() in C:\Users\peter\source\repos\OrchardCore\src\OrchardCore.Modules\OrchardCore.OpenId\Services\OpenIdServerService.cs:line 504
```

**Comment by petedavis** [comment]
It appears that the above stack trace occurs on startup, and every time that the process is restarted another certificate is created.

**Comment by petedavis** [comment]
@PinpointTownes this is no longer working on an Azure App Service. 

I have changed the code to read the bytes from the file and then try and construct the X509Certificate2 from the byte array and I get the same exception. I also hard coded a password to eliminate that. So it appears that it is a possible .net core on azure issue? @sebastienros ??
```
2019-02-25 01:25:46.112 +00:00 [Warning] OrchardCore.OpenId.Services.OpenIdServerService: An error occurred while trying to extract a X.509 certificate from file D:\home\site\wwwroot\App_Data\Sites\Default\IdentityModel-Signing-Certificates\c0629832-a32f-4a17-a5d4-a4f964443e6e.pfx
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The system cannot find the file specified
   at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
   at OrchardCore.OpenId.Services.OpenIdServerService.GetManagedSigningCertificatesAsync() in C:\Users\peter\source\repos\OrchardCore\src\OrchardCore.Modules\OrchardCore.OpenId\Services\OpenIdServerService.cs:line 510
```

**Comment by petedavis** [comment]
I have found the solution. [The flags required to create the X509Certificate2 on azure is different](https://stackoverflow.com/questions/18959418/site-in-azure-websites-fails-processing-of-x509certificate2).
```
X509KeyStorageFlags.MachineKeySet | 
    X509KeyStorageFlags.PersistKeySet | 
    X509KeyStorageFlags.Exportable
```

@PinpointTownes can you please advise on how we can make this work. I am not familiar with what your conditional compilation flags are covering. 

I will update our private fork with just these flags for now to get the code working again.

**Comment by PinpointTownes** [comment]
@petedavis these flags look good to me: .pfx certificates are by definition not backed by a hardware security module so they should always be exportable. I would have preferred using ephemeral key sets (whose enum was recently introduced, hence the #ifdef), but if it doesn't work on Azure, then we'll have to deal with that.

Any chance you could test that on IIS? (with user profile loading disabled first and loading enabled)

**Comment by sebastienros** [comment]
I created a PR, please review
