### ISSUE TITLE
Uploading 1MB image results in error

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#3263]
When uploading image larger than 1MB I get the following error (Note I tried to set the MaxRequestBodySize of OrchardCore.Media settings in appsettings but no joy):

Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware|ERROR|An unhandled exception has occurred while executing the request. System.InvalidOperationException: The maximum request body size cannot be modified after the app has already started reading from the request body.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpMaxRequestBodySizeFeature.set_MaxRequestBodySize(Nullable`1 value)
   at OrchardCore.Media.Services.MediaSizeLimitAttribute.InternalMediaSizeFilter.OnAuthorization(AuthorizationFilterContext context) in C:\projects\orchard2\src\OrchardCore.Modules\OrchardCore.Media\Services\MediaSizeLimitAttribute.cs:line 79

**Comment by scleaver** [comment]
Actually, scratch that... it's happening on any file size now on latest build for me. Currently using 1.0.0-beta3-70815

**Comment by pgy866** [comment]
1.0.0-beta3-70815  I have no problem.
![5](https://user-images.githubusercontent.com/28694676/53653439-41e01700-3c86-11e9-92f4-8e49fb6372a5.gif)

**Comment by sebastienros** [comment]
There is a piece of code that reads the form before the file size can be checked. In the commit that added the file size verification I also changed the AntiforgeryToken validation to use the attribute instead of the filter, because otherwise we'd have the issue you are reporting. 

Are you using the nuget packages? Can you check that you have the correct OrchardCore.Mvc.Core version which contains this line: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Mvc.Core/Startup.cs#L40

**Comment by petedavis** [comment]
Im getting the exact same issue from the current dev branch and with nuget package based app.

I have just pulled down the latest from dev, and setup clean default tenant.

(for readability)
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The maximum request body size cannot be modified after the app has already started reading from the request body.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpMaxRequestBodySizeFeature.set_MaxRequestBodySize(Nullable`1 value)
   at OrchardCore.Media.Services.MediaSizeLimitAttribute.InternalMediaSizeFilter.OnAuthorization(AuthorizationFilterContext context) in C:\Users\peter\source\repos\OrchardCore\src\OrchardCore.Modules\OrchardCore.Media\Services\MediaSizeLimitAttribute.cs:line 76
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.Extensions.DependencyInjection.CommitSessionMiddleware.Invoke(HttpContext httpContext) in C:\Users\peter\source\repos\OrchardCore\src\OrchardCore\OrchardCore.Data\OrchardCoreBuilderExtensions.cs:line 147
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\Users\peter\source\repos\OrchardCore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 82
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\Users\peter\source\repos\OrchardCore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 99
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by sebastienros** [comment]
I will remove implement it differently then. Sorry for these issues. But I can't repro locally which is sad.

**Comment by peterkeating** [comment]
Came across this issue when referencing the NuGet package (`70841`). However, when running from the source code (`dev` branch) it works as expected.

**Comment by sebastienros** [comment]
I am reverting this change, and will be using a different technique in the meantime, but I'd like we find the reason because it might show some bug in MVC, and the attribute is better than what I intend to do (@jtkech if you can still investigate).

**Comment by jtkech** [comment]
Okay, i will do it soon.

**Comment by jtkech** [comment]
Here some findings.

So it "works" if i use a `!` operator before `maxRequestBodySizeFeature.IsReadOnly`

    if (maxRequestBodySizeFeature != null && !maxRequestBodySizeFeature.IsReadOnly)
    {
        maxRequestBodySizeFeature.MaxRequestBodySize = _maxUploadSize;
    }

Regarding [these comments](https://github.com/aspnet/AspNetCore/blob/master/src/Http/Http.Features/src/IHttpMaxRequestBodySizeFeature.cs), `IsReadOnly` may be true if `IHttpUpgradeFeature.UpgradeAsync` has been called.

        /// <summary>
        /// Indicates whether <see cref="MaxRequestBodySize"/> is read-only.
        /// If true, this could mean that the request body has already been read from
        /// or that <see cref="IHttpUpgradeFeature.UpgradeAsync"/> was called.
        /// </summary>
        bool IsReadOnly { get; }

Then, if called `MaxRequestBodySize` does not affect upgraded connections which are always unlimited.

        /// <summary>
        /// The maximum allowed size of the current request body in bytes.
        /// When set to null, the maximum request body size is unlimited.
        /// This cannot be modified after the reading the request body has started.
        /// This limit does not affect upgraded connections which are always unlimited.
        /// </summary>
        /// <remarks>
        /// Defaults to the server's global max request body size limit.
        /// </remarks>
        long? MaxRequestBodySize { get; set; }

**Comment by sebastienros** [comment]
You are saying that the code has a flaw?

Good, however I already created the other PR. Thanks for the explanation.

**Comment by jtkech** [comment]
Yes, as i understand we were updating `maxRequestBodySizeFeature` when it was `IsReadOnly`. Just checking the opposite seemed to fix the issue.

Then, when not using `AutoValidateAntiforgeryTokenAttribute` i saw that `IsReadOnly` was false, so it was not failing but in this case we were not doing anything while we could have updated the feature.

**Comment by sebastienros** [comment]
But the Media filter should happen before AutoValidateAntiforgeryTokenAttribute

**Comment by jtkech** [comment]
Yes, not easy to check.

**Comment by jtkech** [comment]
Okay, i could repro through the command line using the debug compiled version of the application. So it will be easier to debug.

Maybe not worth to check it because i saw that you fixed it in another way. But still interesting to see if there is an mvc filter ordering issue.

**Comment by jtkech** [comment]
So, i made 2 testing attributes, when there are used to decorate an action controller the order property is taken into account. But if we add them through `mvcOptions.Filters.Add()`, there are executed in the order that there are added regardless their order property.


            var builder = services.AddMvc(options =>
            {
                // Forcing AntiForgery Token Validation on by default, it's only in Razor Pages by default
                options.Filters.Add(typeof(AutoValidateAntiforgeryTokenAttribute));
                options.Filters.Add(typeof(TestFilterAttribute1));
                options.Filters.Add(typeof(TestFilterAttribute));

                // Custom model binder to testing purpose
                options.ModelBinderProviders.Insert(0, new CheckMarkModelBinderProvider());
            });

**Comment by sebastienros** [comment]
Can you set the order in the overload of the `Add` ?

**Comment by jtkech** [comment]
Okay, i'm going to try it.

**Comment by jtkech** [comment]
Yes it works, just tried the following.

                options.Filters.Add(typeof(TestFilterAttribute1), 950);
                options.Filters.Add(typeof(TestFilterAttribute), 910);

Then `TestFilterAttribute1` runs after `TestFilterAttribute` even it is enlisted first. And both run after `MediaSizeLimitAttribute` whose order property is 900.

**Comment by jtkech** [comment]
Seems that they are just used as `IFilterFactory` but not checked a `IOrderedFilter`. Then maybe `IOrderedFilter` instances are created based on the order parameters.

**Comment by jtkech** [comment]
Yes, see [here](https://github.com/aspnet/AspNetCore/blob/c565386a3ed135560bc2e9017aa54a950b4e35dd/src/Mvc/Mvc.Core/src/Filters/FilterCollection.cs#L44), [here](https://github.com/aspnet/AspNetCore/blob/c565386a3ed135560bc2e9017aa54a950b4e35dd/src/Mvc/Mvc.Core/src/Filters/FilterCollection.cs#L89), and [here](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/TypeFilterAttribute.cs#L27).
