### ISSUE TITLE
Upgrade from master (beta2) to dev

### ISSUE THREAD

**Issue by bashuss** [OrchardCMS/OrchardCore#3382]
I just tried to upgrade my project from beta2 (currently master-branch) to current dev-branch. I especially wanted to test new modules like "taxonomy" and "file content definition".

So I tried to enable modules in the order they are listet, which created exceptions:

```
`System.TypeInitializationException: The type initializer for 'OrchardCore.Users.ResetPasswordStartup' threw an exception. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()

   at Fluid.MemberAccessStrategy.Register(Type type, String name, IMemberAccessor getter)

   at Fluid.MemberAccessStrategyExtensions.Register(IMemberAccessStrategy strategy, Type type)

   at Fluid.MemberAccessStrategyExtensions.Register[T](IMemberAccessStrategy strategy)

   at OrchardCore.Users.ResetPasswordStartup..cctor() in C:\Users\bernd\Desktop\Orchard Core Dev\OrchardCore\src\OrchardCore.Modules\OrchardCore.Users\Startup.cs:line 165

   --- End of inner exception stack trace ---

   at OrchardCore.Users.ResetPasswordStartup..ctor()

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCreateInstance(CreateInstanceCallSite createInstanceCallSite, ServiceProviderEngineScope scope)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, ServiceProviderEngineScope scope)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)

   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)

   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)

   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)

   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices[T](IServiceProvider provider)

   at OrchardCore.Environment.Shell.Builders.ShellContainerFactory.CreateContainer(ShellSettings settings, ShellBlueprint blueprint) in C:\Users\bernd\Desktop\Orchard Core Dev\OrchardCore\src\OrchardCore\OrchardCore\Environment\Shell\Builders\ShellContainerFactory.cs:line 97

   at OrchardCore.Environment.Shell.Builders.ShellContextFactory.CreateDescribedContextAsync(ShellSettings settings, ShellDescriptor shellDescriptor) in C:\Users\bernd\Desktop\Orchard Core Dev\OrchardCore\src\OrchardCore\OrchardCore\Environment\Shell\Builders\ShellContextFactory.cs:line 75

   at OrchardCore.Environment.Shell.Builders.ShellContextFactory.OrchardCore.Environment.Shell.Builders.IShellContextFactory.CreateShellContextAsync(ShellSettings settings) in C:\Users\bernd\Desktop\Orchard Core Dev\OrchardCore\src\OrchardCore\OrchardCore\Environment\Shell\Builders\ShellContextFactory.cs:line 49

   at OrchardCore.Environment.Shell.ShellHost.GetOrCreateShellContextAsync(ShellSettings settings) in C:\Users\bernd\Desktop\Orchard Core Dev\OrchardCore\src\OrchardCore\OrchardCore\Environment\Shell\ShellHost.cs:line 89

   at OrchardCore.Environment.Shell.ShellHost.GetScopeAndContextAsync(ShellSettings settings) in C:\Users\bernd\Desktop\Orchard Core Dev\OrchardCore\src\OrchardCore\OrchardCore\Environment\Shell\ShellHost.cs:line 127

   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\Users\bernd\Desktop\Orchard Core Dev\OrchardCore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 55

   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`
```
The modules were marked as enabled after restart though.

But: 

1. All previously existing content definitions (located in database) were gone, until I disabled "file content definitions"-module again.
2. Modules (e.g. Taxonomies) enabled while "file content definitions" was active had their definitions written to files, so these definitions are now missing in the database. Reenabling these modules does not recreate these definitions in the other storage location!

Is there some kind of "official way" for migrating to a newer version?
Is there a way to repair these type definitions or export them from one location to another?

**Comment by sebastienros** [comment]
I fixed the issue in Fluid a couple of days ago, can you try again?

**Comment by sebastienros** [comment]
If you enable File Content Definition from a beta2, you will need to copy the document from the database to this file.

**Comment by bashuss** [comment]
> I fixed the issue in Fluid a couple of days ago, can you try again?

Sure I can disable and enable modules. I just do not know, if this would be reproducing the same code paths - I did not have a bright day, when I tested: forgot to make a database backup before...

> If you enable File Content Definition from a beta2, you will need to copy the document from the database to this file.

Sounds like the source and target locations a self explaining... I'll have a try. Thanks

**Comment by sebastienros** [comment]
Thanks for reporting it worked
