### ISSUE TITLE
Media Error

### ISSUE THREAD

**Issue by AcellaEDU** [OrchardCMS/OrchardCore#3582]
**Step 1**. Create a site using **The Agency Theme**
**Step 2**. Click **New** => **Page**.

![image](https://user-images.githubusercontent.com/6829626/57212071-31804b80-6feb-11e9-8025-9ee92e0ce740.png)

![image](https://user-images.githubusercontent.com/6829626/57212083-3e9d3a80-6feb-11e9-8dfb-ffe4eb358244.png)

**Comment by AcellaEDU** [comment]
How/Where to init mediaApplicationUrl?

**Comment by AcellaEDU** [comment]
I added Media Field. Next, I attached files .jpg and .pdf.

**Result**
![image](https://user-images.githubusercontent.com/6829626/57223453-c9436100-700e-11e9-91ab-1ce3f042c287.png)

**Expectation**
I expected that there will be links to attached files. If I mistake, how to attached files (*.pdf, *.doc, etc) from Assets

**Comment by matiasmolleja** [comment]
There is a bug added with a recent PR. I will fix it.

**Comment by AcellaEDU** [comment]
@matiasmolleja  thanks for your fix.
@sebastienros 

I found next:

### **Part 1**
Periodically, throw exception and OC crash:
![image](https://user-images.githubusercontent.com/6829626/57279254-34457400-70b1-11e9-8be5-b2ae11f994c3.png)

I added the **MediaField** with **Attached** editor type in a **Page** - **Agency Theme**.

**Stack Trace**
```
OrchardCore.FileStorage.FileStoreException
  HResult=0x80131500
  Message=Cannot get file stream because the file 'mediafields/temp/4d0d99ce-b811-4796-9a79-ba9f14eb50d1ABDTDIT-18398443-280319-2201-78.pdf' does not exist.
  Source=OrchardCore.FileStorage.FileSystem
  StackTrace:
   at OrchardCore.FileStorage.FileSystem.FileSystemStore.GetFileStreamAsync(String path) in C:\JobProjects\OrchardCore\src\OrchardCore\OrchardCore.FileStorage.FileSystem\FileSystemStore.cs:line 160
   at OrchardCore.Media.Services.MediaFileStore.GetFileStreamAsync(String path) in C:\JobProjects\OrchardCore\src\OrchardCore.Modules\OrchardCore.Media\Services\MediaFileStore.cs:line 72
   at OrchardCore.Media.Services.AttachedMediaFieldFileService.<GetFileHashAsync>d__15.MoveNext() in C:\JobProjects\OrchardCore\src\OrchardCore.Modules\OrchardCore.Media\Services\AttachedMediaFieldFileService.cs:line 118
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OrchardCore.Media.Services.AttachedMediaFieldFileService.<>c__DisplayClass13_0.<<MoveNewFilesToContentItemDirAndUpdatePaths>b__1>d.MoveNext() in C:\JobProjects\OrchardCore\src\OrchardCore.Modules\OrchardCore.Media\Services\AttachedMediaFieldFileService.cs:line 87
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

### **Part 2**
I don't see a business value from this:
![image](https://user-images.githubusercontent.com/6829626/57281131-02351180-70b3-11e9-86cc-5991506bcafb.png)

It should be a link.
