### ISSUE TITLE
Issue in running Liquid expression in Workflows

### ISSUE THREAD

**Issue by siyamandayubi** [OrchardCMS/OrchardCore#3729]
In heavy load, I got the following exception

```
2019-05-30 04:50:31.7711|Default|80000028-0000-fe00-b63f-84710c7967bb||Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|ERROR|An unhandled exception has occurred while executing the request. System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Fluid.Values.FluidValue.Create(Object value)
   at OrchardCore.Contents.Liquid.ContentLiquidTemplateEventHandler.RenderingAsync(TemplateContext context) in C:\Projects\OC\OrchardCore\src\OrchardCore.Modules\OrchardCore.Contents\Liquid\ContentLiquidTemplateEventHandler.cs:line 22
   at OrchardCore.Workflows.Expressions.LiquidWorkflowExpressionEvaluator.CreateTemplateContextAsync(WorkflowExecutionContext workflowContext) in C:\Projects\OC\OrchardCore\src\OrchardCore.Modules\OrchardCore.Workflows\Expressions\LiquidWorkflowExpressionEvaluator.cs:line 97
   at OrchardCore.Workflows.Expressions.LiquidWorkflowExpressionEvaluator.EvaluateAsync[T](WorkflowExpression`1 expression, WorkflowExecutionContext workflowContext) in C:\Projects\OC\OrchardCore\src\OrchardCore.Modules\OrchardCore.Workflows\Expressions\LiquidWorkflowExpressionEvaluator.cs:line 53
   at OrchardCore.Workflows.Http.Activities.SignalEvent.CanExecuteAsync(WorkflowExecutionContext workflowContext, ActivityContext activityContext) in C:\Projects\OC\OrchardCore\src\OrchardCore.Modules\OrchardCore.Workflows\Http\Activities\SignalEvent.cs:line 39
   at OrchardCore.Workflows.Services.WorkflowManager.StartWorkflowAsync(WorkflowType workflowType, ActivityRecord startActivity, IDictionary`2 input, String correlationId) in C:\Projects\OC\OrchardCore\src\OrchardCore.Modules\OrchardCore.Workflows\Services\WorkflowManager.cs:line 273
   at OrchardCore.Workflows.Services.WorkflowManager.TriggerEventAsync(String name, IDictionary`2 input, String correlationId) in C:\Projects\OC\OrchardCore\src\OrchardCore.Modules\OrchardCore.Workflows\Services\WorkflowManager.cs:line 160
```

The error says, multipe threads want to access a shared dictionary, to me the root cause of the issue is the following line:

https://github.com/OrchardCMS/OrchardCore/blob/6e597b49c018d006ed9b00ec569b1b638846c3f9/src/OrchardCore.Modules/OrchardCore.Workflows/Expressions/LiquidWorkflowExpressionEvaluator.cs#L49

Here, several handlers who want to change the common dictionary of the expressionContext are running in async mode. Maybe we should call such handlers in sync mode.

**Comment by jtkech** [comment]
Thanks for the infos, i will take a look this night, i started working on this kind of things #3726.

`_workflowContextHandlers.InvokeAsync` call async handlers but sequentially, hmm maybe this is `_expressionEvaluator.EvaluateAsync` that,  maybe, has been called concurrently, i will see.

**Comment by sebastienros** [comment]
Unrelated to this issue, but looking at how WF creates contexts, there are lots of code that could be reused. Like property registrations which could be done statically on the global member access strategy. Or the service resolution that could be done once per request instead of for each context.

**Comment by sebastienros** [comment]
Some comments on the issue

`FluidValue.TypeMappings` is a public property to provide a `Func` that will convert an `object` to a `FluidValue`. We use it in several places in OC to register global conversion. We need to verify that these calls are not concurrent. I might need to refactor the API to prevent any issue. From what I looked the calls are done in static ctors, so this should be fine.


Then if not this, we need to find what calls could be using the same `TemplateContext` concurrently. It is not thread safe.

Many lines of code should be removed from `RenderAsync` calls and put into static ctors, as they only register well-known properties and don't use the context argument.

@siyamandayubi can you explain what url triggered this issue, and what kind of workflow this is? It would be easier if we could repro locally.

**Comment by jtkech** [comment]
@sebastienros 

Looking at the trace, `context.LocalScope.SetValue()` => `_properties[name] = FluidValue.Create(value)`, and just saw that `FluidValue.Create()` uses `TypeMappings.TryGetValue()`. So, even it is not done on the same `TemplateContext`, we could have a concurrent access on this global dico.

        public static FluidValue Create(object value)
        {
            if (value == null)
            {
                return NilValue.Instance;
            }

            if (value is FluidValue fluidValue)
            {
                return fluidValue;
            }

            var typeOfValue = value.GetType();

            // First check for a specific type conversion before falling back 
            // to an automatic one
            if (TypeMappings.TryGetValue(typeOfValue, out var mapping))
            {
                return mapping(value);
            }
            ...

Note: I saw that you merged my PR related to `Task.WhenAll()`, thanks but maybe some other updates to do. It was marked as `not ready` ;)

**Comment by sebastienros** [comment]
@siyamandayubi do you have any custom module that uses Fluid? Like declaring custom properties or values? The code in OC seems to handle all the cases correctly. Or are you using an older version?

**Comment by siyamandayubi** [comment]
@sebastienros  I am not using the beta 3, not the latest version of dev

**Comment by jtkech** [comment]
Just for infos and to complete my last comment. But these are only read accesses and the only places we add items in this shared dictionary are in static constructors.

**Comment by sebastienros** [comment]
@siyamandayubi I'd love a repro then. After analyzing the code we can't find any reason for this issue. And I have fixed some concurrency issues in the last version that could explain this. Could you try to repro with at least an updated Fluid package (just dropping in a site and restarting, after you ensure it compiles fine). Or please tell us what you are doing so we could try to repro.

**Comment by siyamandayubi** [comment]
@sebastienros  I tried to reproduce it, but it is difficult to simulate heavy load. 

But meanwhile, I got another similar exception from deployed instance yesterday,

2019-05-31 11:20:13.0589|Default|8000001e-0002-fb00-b63f-84710c7967bb||OrchardCore.Workflows.Services.WorkflowManager|ERROR|An unhandled error occurred while executing an activity. Workflow ID: '4301'. Activity: '4bn5tseptmf5vzmg4xqjwx5awg', 'MapperTask'. Putting the workflow in the faulted state. System.AggregateException: One or more errors occurred. (Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.) ---> System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Fluid.Values.FluidValue.Create(Object value)
   at OC.Common.Services.WorkflowExecutionContextHandler.GetEntityProperty(WorkflowExecutionExpressionContext context, WorkflowExecutionContext obj, String name, String type) in C:\Projects\OC\OrchardCore\src\OrchardCore.Modules\OC.Common\Services\WorkflowExecutionContextHandler.cs:line 171
   at OC.Common.Services.WorkflowExecutionContextHandler.<>c__DisplayClass5_1.<EvaluatingExpressionAsync>b__8(String name) in C:\Projects\OC\OrchardCore\src\OrchardCore.Modules\OC.Common\Services\WorkflowExecutionContextHandler.cs:line 66
   at Fluid.Accessors.AsyncDelegateAccessor`2.Fluid.IAsyncMemberAccessor.GetAsync(Object obj, String name, TemplateContext ctx)
   at Fluid.Values.ObjectValue.GetValueAsync(String name, TemplateContext context)
   at Fluid.Ast.IndexerSegment.ResolveAsync(FluidValue value, TemplateContext context)
   at Fluid.Ast.MemberExpression.EvaluateAsync(TemplateContext context)
   at Fluid.Ast.FilterExpression.EvaluateAsync(TemplateContext context)
   at Fluid.Ast.AssignStatement.WriteToAsync(TextWriter writer, TextEncoder encoder, TemplateContext context)
   at Fluid.BaseFluidTemplate`1.RenderAsync(TextWriter writer, TextEncoder encoder, TemplateContext context)
   at OrchardCore.DisplayManagement.Liquid.LiquidViewTemplateExtensions.RenderAsync(LiquidViewTemplate template, LiquidOptions options, IServiceProvider services, TextWriter writer, TextEncoder encoder, TemplateContext context) in C:\Projects\OC\OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement.Liquid\LiquidViewTemplate.cs:line 173
   at OrchardCore.Liquid.LiquidTemplateManagerExtensions.RenderAsync(ILiquidTemplateManager manager, String template, TextEncoder encoder, TemplateContext context) in C:\Projects\OC\OrchardCore\src\OrchardCore\OrchardCore.Liquid.Abstractions\ILiquidTemplateManager.cs:line 27
   at OrchardCore.Workflows.Expressions.LiquidWorkflowExpressionEvaluator.EvaluateAsync[T](WorkflowExpression`1 expression, WorkflowExecutionContext workflowContext) in C:\Projects\OC\OrchardCore\src\OrchardCore.Modules\OrchardCore.Workflows\Expressions\LiquidWorkflowExpressionEvaluator.cs:line 53

I am trying to change the following Dictionary in Fluid which is static (and common across thread) to ConcurrentDictionary and check the result.

https://github.com/sebastienros/fluid/blob/4dd4d6cbbe9b15eaa409874f96102f1e619d2dc7/Fluid/Values/FluidValue.cs#L13

I will update this thread in case of any news

**Comment by jtkech** [comment]
@siyamandayubi yes, using a `ConcurrentDictionary` would fix the issue but it would hide the source cause that would be good to find.

Okay, methods are called in an async way but executed sequentially (each one is awaited). Anyway, even called synchronously, because `TypeMappings` is a static dictionary, it could still be accessed concurrently. But these are only readings, so we have to find where an entry could be added to `TypeMappings` while it is read.

It seems that you have an `OC.Common` module that implements a `WorkflowExecutionContextHandler`, and also a custom `MapperTask` activity. Could you show us any of your related custom code?




@sebastienros as a side note, in `WorkflowManager`, there is still one `Task.WhenAll()` that instanciates activities by using `ActivatorUtilities.CreateInstance(serviceProvider, type)`. I kept it because the service provider is thread safe, but maybe a service implementation factory could be run concurrently. Note: I tried to simulate it for the `ISession` factory, but the service is already realized before this `WhenAll()`.

**Comment by siyamandayubi** [comment]
@sebastienros @jtkech 
I found the issue. In one of my custom modules, the TypeMapping has been changed outside the startup code. I think if I move the changes to the startup, the issue will be fixed.

**Comment by siyamandayubi** [comment]
@sebastienros  @jakenuts  but anyway, would it be safer to change the TypeMapping to ConcurrentDictionary, so the issue would not repeat for someone else too. Or in the documentation, mentioning it that all initialization must be that in the Startup

**Comment by jtkech** [comment]
Yes but i let @sebastienros decide it because i think it uses a simple dictionary for performance reasons ;)

**Comment by sebastienros** [comment]
Yes, I will change the fluid API to make it thread safe while keeping an internal dictionary.
