### ISSUE TITLE
Layer module: removing all zones issue.

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#3835]
I removed a zone in my site settings and after I got this issue because it couldn't save the widget to a zone that doesn't exist.

```
2019-06-20 03:07:02.0157|Default|80002ed3-0000-de00-b63f-84710c7967bb||OrchardCore.DisplayManagement.DisplayManager|ERROR|IDisplayDriver`1 thrown from OrchardCore.Layers.Drivers.LayerSiteSettingsDisplayDriver by NullReferenceException System.NullReferenceException: Object reference not set to an instance of an object.
   at OrchardCore.Layers.Drivers.LayerSiteSettingsDisplayDriver.UpdateAsync(LayerSettings settings, BuildEditorContext context) in E:\Repositories\AffairesExtra - OrchardCore\src\OrchardCore.Modules\OrchardCore.Layers\Drivers\LayerSiteSettingsDisplayDriver.cs:line 58
   at OrchardCore.DisplayManagement.Entities.SectionDisplayDriver`2.UpdateAsync(TModel model, UpdateEditorContext context) in E:\Repositories\AffairesExtra - OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement\Entities\SectionDisplayDriver.cs:line 74
   at OrchardCore.DisplayManagement.DisplayManager`1.<>c__DisplayClass11_0.<<UpdateEditorAsync>b__0>d.MoveNext() in E:\Repositories\AffairesExtra - OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement\DisplayManager.cs:line 137
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents](IEnumerable`1 events, Func`2 dispatch, ILogger logger) in E:\Repositories\AffairesExtra - OrchardCore\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 85    at OrchardCore.Layers.Drivers.LayerSiteSettingsDisplayDriver.UpdateAsync(LayerSettings settings, BuildEditorContext context) in E:\Repositories\AffairesExtra - OrchardCore\src\OrchardCore.Modules\OrchardCore.Layers\Drivers\LayerSiteSettingsDisplayDriver.cs:line 58
   at OrchardCore.DisplayManagement.Entities.SectionDisplayDriver`2.UpdateAsync(TModel model, UpdateEditorContext context) in E:\Repositories\AffairesExtra - OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement\Entities\SectionDisplayDriver.cs:line 74
   at OrchardCore.DisplayManagement.DisplayManager`1.<>c__DisplayClass11_0.<<UpdateEditorAsync>b__0>d.MoveNext() in E:\Repositories\AffairesExtra - OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement\DisplayManager.cs:line 137
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents](IEnumerable`1 events, Func`2 dispatch, ILogger logger) in E:\Repositories\AffairesExtra - OrchardCore\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 85


```

**Comment by Skrypt** [comment]
To repro you need to go to https://localhost:44300/Admin/Settings/zones and remove all zones in the textbox.

**Comment by agriffard** [comment]
Is it still occuring @Skrypt or can it be closed?

**Comment by Skrypt** [comment]
Needs to be tested to make sure.

**Comment by Skrypt** [comment]
Fixed
