### ISSUE TITLE
SQL Server: There is no error message after clicking the Finish Setup. 

### ISSUE THREAD

**Issue by OksXen** [OrchardCMS/OrchardCore#3937]
Identical issue is:  Closed but can't reproduce. 
https://github.com/OrchardCMS/OrchardCore/issues/1528

**Comment by OksXen** [comment]
This is the DSN: 
Data Source=DEV-MSSQL01-VM.cms.9c9media.net\DEVSQL01;Initial Catalog=occms_test;User ID=occms_test;Password=d>'X*5aBb;"L&


Log File: 


2019-07-15 15:33:24.3493|Default|80000032-0000-f900-b63f-84710c7967bb||Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer|ERROR|Connection ID "17942340917054668845", Request ID "80000032-0000-f900-b63f-84710c7967bb": An unhandled exception was thrown by the application. System.ArgumentException: Keyword not supported: '"l&;connect timeout'.
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms)
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at YesSql.DbConnectionFactory`1.CreateConnection()
   at YesSql.Store.InitializeAsync()...

**Comment by carlwoodhouse** [comment]
`Keyword not supported: '"l&;connect timeout'.`

shouldnt that be `Connection Timeout` in a sql connection string?

**Comment by OksXen** [comment]
Yes - it could be. Except, it was not passed in as part of the sql connection string when I got the error.

**Comment by Skrypt** [comment]
The exception could be handled more gracefully but at this point we rely on getting the SQL connection to return the exception simply because it is more accurate.  Though, we could eventually do a connection test to validate the form before moving forward with anything else.

**Comment by sebastienros** [comment]
> validate the connection string

That's a good idea. We could provide a custom handler or query for each db provider because each will need custom logic to verify the database is available.

**Comment by OksXen** [comment]
- related 500 error page issue, after clicking on "Finish Setup"
https://github.com/OksXen/OrchardCore/issues/1

**Comment by hishamco** [comment]
> validate the connection string

It would be nice if we move the verification into YesSQL layer, if sound is good I can create a PR for it

**Comment by OksXen** [comment]
The issue were that 


I updated the code, to catch the error and then display the error message instead of a blank page.
