### ISSUE TITLE
Install in Postgresql 10 Fails with InvalidOperationException (Beta 3)

### ISSUE THREAD

**Issue by tmccal2** [OrchardCMS/OrchardCore#4083]
I ran a beta 3 of OrchardCore and I have encountered this error while installing OrchardCore, resulting in a blank page.
```
Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLP6IUK7NPU1", Request id "0HLP6IUK7NPU1:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Invalid serial number for shell descriptor
   at OrchardCore.Environment.Shell.Data.Descriptors.ShellDescriptorManager.UpdateShellDescriptorAsync(Int32 priorSerialNumber, IEnumerable`1 enabledFeatures, IEnumerable`1 parameters) in /home/taylor/Projects/OrchardCore/src/OrchardCore/OrchardCore.Infrastructure/Shell/ShellDescriptorManager.cs:line 94
   at OrchardCore.Setup.Services.SetupService.SetupInternalAsync(SetupContext context) in /home/taylor/Projects/OrchardCore/src/OrchardCore/OrchardCore.Setup.Core/SetupService.cs:line 166
   at OrchardCore.Setup.Services.SetupService.SetupAsync(SetupContext context) in /home/taylor/Projects/OrchardCore/src/OrchardCore/OrchardCore.Setup.Core/SetupService.cs:line 71
   at OrchardCore.Setup.Controllers.SetupController.IndexPOST(SetupViewModel model) in /home/taylor/Projects/OrchardCore/src/OrchardCore.Modules/OrchardCore.Setup/Controllers/SetupController.cs:line 166
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.Extensions.DependencyInjection.CommitSessionMiddleware.Invoke(HttpContext httpContext) in /home/taylor/Projects/OrchardCore/src/OrchardCore/OrchardCore.Data/OrchardCoreBuilderExtensions.cs:line 150
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in /home/taylor/Projects/OrchardCore/src/OrchardCore/OrchardCore/Modules/ModularTenantRouterMiddleware.cs:line 82
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in /home/taylor/Projects/OrchardCore/src/OrchardCore/OrchardCore/Modules/ModularTenantContainerMiddleware.cs:line 99
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by sebastienros** [comment]
And it repros constantly? Have you tried with Sqlite too?

**Comment by tmccal2** [comment]
I have tried it with Sqlite and it installed successfully.

**Comment by sebastienros** [comment]
As an action I think we should start running the functional tests on PostgresQL too, and maybe on MSSQL and MySQL. AppVeyor supports that.

Example here:
https://github.com/sebastienros/yessql/blob/dev/appveyor.yml#L9-L31

**Comment by jptissot** [comment]
I often see this exception as well. Usually it happens if you try to setup a tenant and you make a mistake (forget to set the table prefix for example) this will fail.  Any subsequent attempts to setup the tenant without restarting the site will result in this exception being thrown.

**Comment by tmccal2** [comment]
I have just installed with PSQL 10 setting a prefix. That installation was successful.

**Comment by sebastienros** [comment]
So the issue is that it ALWAYS fails when there is no prefix?

**Comment by jptissot** [comment]
It's when the prefix already exists in the db. 

When this happens the tenant is stuck in a bad state and an app restart is needed (restart the docker container) to be able to setup the tenant successfully.

Repro: 
- New tenant, try to set it up when the table prefix is already taken.
- Tenant creation errors out
- Go back to Tenant settings, add table prefix
- Try to setup again. Setup will fail with the exception posted in the OP
- Restart docker image (or application)
- Try to setup again. Setup will succeed.
