### ISSUE TITLE
Error when accessing asset cache configuration

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#4228]
When accessing the "Asset cache" configuration the following error occurs:

`ystem.InvalidOperationException: Unable to resolve service for type 'OrchardCore.Media.IMediaFileStoreCache' while attempting to activate 'OrchardCore.Media.Azure.Controllers.MediaCacheController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.Startup.<Configure>b__3_0(HttpContext context, Func`1 next) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Diagnostics\Startup.cs:line 37
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at OrchardCore.HomeRoute.HomeRouteMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.HomeRoute\HomeRouteMiddleware.cs:line 35
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 84
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 101
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 59
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

Would assume it is because I have no settings for azure in my appsettings.json as yet.

**Comment by jptissot** [comment]
cc @deanmarcussen

**Comment by hishamco** [comment]
@matiasmolleja @deanmarcussen could anyone of you look in this one please

**Comment by hishamco** [comment]
@matiasmolleja @deanmarcussen could anyone of you look in this one please

**Comment by jtkech** [comment]
> Would assume it is because I have no settings for azure in my appsettings.json as yet.

Yes, seems to be the case as i can see in the code

The related service is not registered if `CheckOptions` doesn't return true, e.g if there is no settings.

            // Only replace default implementation if options are valid.
            var connectionString = _configuration[$"OrchardCore.Media.Azure:{nameof(MediaBlobStorageOptions.ConnectionString)}"];
            var containerName = _configuration[$"OrchardCore.Media.Azure:{nameof(MediaBlobStorageOptions.ContainerName)}"];
            if (CheckOptions(connectionString, containerName, _logger))
            {
            ...
            ...
            ...

        private static bool CheckOptions(string connectionString, string containerName, ILogger logger)
        {
            var optionsAreValid = true;

            if (String.IsNullOrWhiteSpace(connectionString))
            {
                logger.LogError("Azure Media Storage is enabled but not active because the {ConnectionString} is missing or empty in application configuration.", nameof(MediaBlobStorageOptions.ConnectionString));
                optionsAreValid = false;
            }

            if (String.IsNullOrWhiteSpace(containerName))
            {
                logger.LogError("Azure Media Storage is enabled but not active because the {ContainerName} is missing or empty in application configuration.", nameof(MediaBlobStorageOptions.ContainerName));
                optionsAreValid = false;
            }

            return optionsAreValid;
        }

**Comment by scleaver** [comment]
If I recall, previously in the admin UI use to show an error alert when there were no settings.

**Comment by jtkech** [comment]
Yes, the related handler is no more used

**Comment by deanmarcussen** [comment]
Yes, we remove the handler / filter that must check everytime if the configuration is valid, for performance reasons. 

However this does mean the asset cache will throw this exception.

But actually this is a good place to show an error that the appsettings.json configuration is missing. So I will do a small PR to resolve the service from the serviceprovider, instead of the constructor, and show an error message in the ui if it is null.
