### ISSUE TITLE
Azure Pipe Error

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#4555]
I made a web app on azure with the 3.0 extensions installed.
I cloned the Orchard Core repo.
Just ran Azure Pipe and got this error:

C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk.Publish\targets\TransformTargets\Microsoft.NET.Sdk.Publish.TransformFiles.targets(50,5): Error MSB4018: The "TransformWebConfig" task failed unexpectedly.
System.Exception: In process hosting is not supported for AspNetCoreModule. Change the AspNetCoreModule to at least AspNetCoreModuleV2.
   at Microsoft.NET.Sdk.Publish.Tasks.WebConfigTransform.SetAspNetCoreHostingModel(String aspNetCoreHostingModelValue, String aspNetCoreModuleName, XElement aspNetCoreElement)
   at Microsoft.NET.Sdk.Publish.Tasks.WebConfigTransform.TransformAspNetCore(XElement aspNetCoreElement, String appName, Boolean configureForAzure, Boolean useAppHost, String extension, String aspNetCoreModuleName, String aspNetCoreHostingModelValue, String projectFullPath)
   at Microsoft.NET.Sdk.Publish.Tasks.WebConfigTransform.Transform(XDocument webConfig, String appName, Boolean configureForAzure, Boolean useAppHost, String extension, String aspNetCoreModuleName, String aspNetCoreHostingModel, String environmentName, String projectFullPath)
   at Microsoft.NET.Sdk.Publish.Tasks.TransformWebConfig.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.&lt;ExecuteInstantiatedTask&gt;d__26.MoveNext()"

**Comment by JoshTango** [comment]
Could this be related?

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <AspNetCoreModuleName>AspNetCoreModuleV2</AspNetCoreModuleName>
  </PropertyGroup>

**Comment by JoshTango** [comment]
`  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <AspNetCoreModuleName>AspNetCoreModuleV2</AspNetCoreModuleName>
  </PropertyGroup>`

**Comment by sebastienros** [comment]
Looks like you are using an old version of the Orchard csproj, as I see netcoreapp2.2 instead of netcoreapp3.0. And in our new project template it uses AspNetModulev2 too.

**Comment by JoshTango** [comment]
I cloned the orchard project from GitHub into an azure repo this morning?
That xml I posted was from the web not from the project code.

**Comment by JoshTango** [comment]
This is from the csproj file in my repo:

**Comment by JoshTango** [comment]
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ncrontab" />
    <PackageReference Include="NodaTime" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrchardCore.Abstractions\OrchardCore.Abstractions.csproj" />
    <ProjectReference Include="..\OrchardCore.Localization.Abstractions\OrchardCore.Localization.Abstractions.csproj" />
  </ItemGroup>

</Project>

**Comment by JoshTango** [comment]
seems my app service is using .net 2.2 even though I installed the extensions for 3.0
maybe the extensions dont apply to the build processes yet?

**Comment by JoshTango** [comment]
Ok its a well known error:

https://stackoverflow.com/questions/56574113/build-net-core-3-0-on-azure-pipelines/56574356
