### ISSUE TITLE
Dependency injection for IRecipeMigrator and IContentDefinitionManager

### ISSUE THREAD

**Issue by fmacedoo** [OrchardCMS/OrchardCore#4598]
Hi guys,

I have a brand new web project using OrchardCore and at this point i intend to use Migrations to setup my website.

The question is: what am i doing wrong as i am not able to inject some services like IRecipeMigrator or even IContentDefinitionManager?

See below my simple Startup.cs and Migrations.cs files.

```c#
namespace cms_novo
{   
    using Microsoft.AspNetCore.Builder;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Hosting;
    using OrchardCore.ContentManagement;
    using OrchardCore.Data.Migration;

    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOrchardCms();
            services.AddScoped<IDataMigration, Migrations>();

           // services.AddContentManagement();
        }
        
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseOrchardCore();
        }
    }
}
```

```c#
namespace cms_novo
{
    using System.Threading.Tasks;
    using OrchardCore.Data.Migration;
    using OrchardCore.Recipes.Services;

    public class Migrations : DataMigration
    {
        private readonly IRecipeMigrator _recipeMigrator;

        public Migrations(IRecipeMigrator recipeMigrator) {
            _recipeMigrator = recipeMigrator;
        }
        
        public async Task<int> CreateAsync() {
            await _recipeMigrator.ExecuteAsync("migration.recipe.json", this);

            return 1;
        }
    }
}
```

I get:

```
Exception has occurred: CLR/System.AggregateException
An unhandled exception of type 'System.AggregateException' occurred in Microsoft.Extensions.DependencyInjection.dll: 'Some services are not able to be constructed'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.InvalidOperationException : Unable to resolve service for type 'OrchardCore.Recipes.Services.IRecipeMigrator' while attempting to activate 'cms_novo.Migrations'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
```

Something closer to it happen when i try the code below:

```c#
using OrchardCore.ContentManagement;
[...]
services.AddContentManagement();
```

I get:
```
Exception has occurred: CLR/System.AggregateException
An unhandled exception of type 'System.AggregateException' occurred in Microsoft.Extensions.DependencyInjection.dll: 'Some services are not able to be constructed'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.InvalidOperationException : Unable to resolve service for type 'Microsoft.Extensions.Caching.Memory.IMemoryCache' while attempting to activate 'OrchardCore.ContentManagement.ContentDefinitionManager'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
```

**Comment by hishamco** [comment]
Have a look to this https://github.com/OrchardCMS/OrchardCore/blob/22a1543eae741fe273f8839dbaddb4b451a4ec51/src/OrchardCore.Modules/OrchardCore.Recipes/README.md

**Comment by fmacedoo** [comment]
I appreciate your tip, but it didn’t answer about the dependency exceptions.

**Comment by deanmarcussen** [comment]
@fmacedoo quickly as I have not had time to try, but from looking I think you need / want to setup your migration code in a module, rather than the core startup project

**Comment by fmacedoo** [comment]
Perfect @deanmarcussen. Just created my migrations as a Module and it worked perfectly as i expected.

**Comment by jtkech** [comment]
Just for infos we have helpers so that you can also register services from the application but as they are registered through a module startup, e.g

            services.AddOrchardCms()
                .AddOrchardCore()
                .ConfigureServices(s =>
                {
                    s.AddScoped<IDataMigration, Migrations>();
                });

**Comment by stevo-knievo** [comment]
The following code worked for me if you have custom code in the core startup project. (Nuget: OrchardCore.Application.Cms.Core.Targets, 1.0.0-rc2-15520)

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddOrchardCms()
        .ConfigureServices(s =>
        {
            s.AddScoped<IFooService, FooService>();
        });
}
```

And I guess scoped is the recommend and only option, correct?

Now I'm wondering if it is considered best practices to use modules for custom code and leave the core project blank.

Thanks in advance.

**Comment by jtkech** [comment]
@stevo-knievo 

Yes, `AddOrchardCms()` now returns an `OrchardCoreBuilder` so that we can use `ConfigureServices()` on it directly

> And I guess scoped is the recommend and only option, correct?

So, the above helper allow to add registrations when building a given tenant container, and where you can register scoped services but also transient services and singleton services. Here a singleton is a tenant singleton whose lifetime is the lifetime of the related tenant, e.g. when we enable a module / feature in a tenant, it is released and rebuilt on demand, meaning e.g. that a tenant singleton has been released and then rebuilt when resolved again through the new container.

> Now I'm wondering if it is considered best practices to use modules for custom code and leave the core project blank.

Using modules allow more modularity by enabling / disabling features for a given tenant, e.g. through the admin UI or from recipes, the registrations in the above helper from the main app can't be disabled, they are always done, and for any tenant if you have multiple tenants, but this allows to add global functionalities without having to create a module

**Comment by stevo-knievo** [comment]
@jtkech 
Thank you so much for your detailed reply.

Currently, I'm having a headless CMS with two custom API-endpoints/services. So I'm not really building a feature at the moment. But out of curiosity, I moved everything into a module (separate project) and re-wired it. But I couldn't get it to work.

I was wondering if there is an example somewhere that explains how to use modules in the context of the CMS.

Thanks again!

**Comment by jtkech** [comment]
@stevo-knievo 

There are different things to know, your module need to define some properties, usually in a `Manifest.cs` file, your module project needs to reference the `OrchardCore.Module.Targets` package, and so on, look at this doc
https://docs.orchardcore.net/en/dev/docs/getting-started/templates/#new-module-from-visual-studio-manual-way
