### ISSUE TITLE
AlterPartDefinition and WithField cause a NullReferenceException

### ISSUE THREAD

**Issue by fmacedoo** [OrchardCMS/OrchardCore#4607]
Hi guys,

Inside my Migration class, i'd like to define a Part with a Field. When i run the AlterPartDefinition with no fields definition, it works, but when i set a field within a builder it get me the exception pasted below.

```
Exception has occurred: CLR/System.NullReferenceException
An exception of type 'System.NullReferenceException' occurred in OrchardCore.ContentManagement.dll but was not handled in user code: 'Object reference not set to an instance of an object.'
   at OrchardCore.ContentManagement.ContentDefinitionManager.Apply(ContentPartDefinition model, ContentPartDefinitionRecord record) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.ContentManagement\ContentDefinitionManager.cs:line 202
   at OrchardCore.ContentManagement.ContentDefinitionManager.StorePartDefinition(ContentPartDefinition contentPartDefinition) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.ContentManagement\ContentDefinitionManager.cs:line 80
   at OrchardCore.ContentManagement.Metadata.ContentDefinitionManagerExtensions.AlterPartDefinition(IContentDefinitionManager manager, String name, Action`1 alteration) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.ContentManagement.Abstractions\IContentDefinitionManager.cs:line 56
   at Farfetch.InternalApps.Presentation.Cms.Modules.Bot.Migrations.BotMigrations.Create() in C:\Users\fmacedo\ff-projects\farfetch-internal-apps\src\Presentation.Cms.Modules.Bot\Migrations\BotMigrations.cs:line 18
```

It crashes
```c#
_contentDefinitionManager.AlterPartDefinition("MyPart", alteration => alteration
    .WithField("MyField")
);
```

It works
```c#
_contentDefinitionManager.AlterPartDefinition("MyPart", alteration => {});
```

Could you help me to understand that?

**Comment by deanmarcussen** [comment]
@fmacedoo You need to specify a bit detail in the builder in order to create a field.

The bit you are missing is the `OfType("MediaField")`

```
 _contentDefinitionManager.AlterTypeDefinition("Product", type => type
    .WithPart("Product", part => part
        .WithField("Image", field => field
            .OfType("MediaField")
            .WithDisplayName("Main image"))
        .WithField("Price", field => field
            .OfType("NumericField")
            .WithDisplayName("Price"))
    )
);
```

See here for examples https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.ContentTypes/

**Comment by fmacedoo** [comment]
Great @deanmarcussen, it worked perfectly.

Just a quick question: could the exception be more friendly?

**Comment by fmacedoo** [comment]
@deanmarcussen i would like to enjoy that post to ask another question, if possible. I would like to know if there is a way to programatically setup and configure features. I am asking it in order to include the cms service at my ci/cd pipeline.

**Comment by deanmarcussen** [comment]
Not exactly, but once an OC site has setup once, it doesn't need to setup by the CI again, if I understand you correctly.

What I think you could look at is features like setup recipes, and/or deployment plans to move data from dev to prod

Gitter is a good place for these kind of questions https://gitter.im/OrchardCMS/OrchardCore

**Comment by fmacedoo** [comment]
Thanks @deanmarcussen, i do appreaciate your help. I'll take a look at it.
