### ISSUE TITLE
Error occurring when using | query on a query with the 'Return Content Items' unchecked

### ISSUE THREAD

**Issue by DaveEmmerson** [OrchardCMS/OrchardCore#4624]
I have a query that looks for Bulletin content type items that are latest and published. That works and in the query runner in the admin site I can see the correct results being returned.

I want to use the index values in my page, rather than retrieving all the content items, so I've not clicked the check box.

I can use {{ Queries.Bulletins | query }} as a template and I get the results displayed.

That works fine, but now I need some additional output - a field called Sent on the Bulletin type.

I click the 'add to index' and the 'stored' checkboxes on the field.

That works in the admin site query runner, I still get the same results, but now they have a Bulletin.Sent column with the correct values in.

Try to use {{ Queries.Bulletins | query }} and it errors with this:

```
System.ArgumentException: Can not add property Bulletin.Sent to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.
   at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JObject..ctor(Object content)
   at OrchardCore.Lucene.LuceneQuerySource.<>c__DisplayClass10_0.<<ExecuteQueryAsync>b__0>d.MoveNext() in C:\code\OrchardCore\src\OrchardCore.Modules\OrchardCore.Lucene\Services\LuceneQuerySource.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Lucene.LuceneIndexManager.SearchAsync(String indexName, Func`2 searcher) in C:\code\OrchardCore\src\OrchardCore.Modules\OrchardCore.Lucene\LuceneIndexManager.cs:line 154
   at OrchardCore.Lucene.LuceneQuerySource.ExecuteQueryAsync(Query query, IDictionary`2 parameters) in C:\code\OrchardCore\src\OrchardCore.Modules\OrchardCore.Lucene\Services\LuceneQuerySource.cs:line 53
   at OrchardCore.Queries.Liquid.QueryFilter.ProcessAsync(FluidValue input, FilterArguments arguments, TemplateContext ctx) in C:\code\OrchardCore\src\OrchardCore.Modules\OrchardCore.Queries\Liquid\QueryFilter.cs:line 34
   at Fluid.Ast.FilterExpression.EvaluateAsync(TemplateContext context)
   at Fluid.Ast.AssignStatement.WriteToAsync(TextWriter writer, TextEncoder encoder, TemplateContext context)
   at Fluid.BaseFluidTemplate`1.Awaited(ValueTask`1 task, TextWriter writer, TextEncoder encoder, TemplateContext context, List`1 statements, Int32 startIndex)
   at Fluid.FluidTemplateExtensions.<RenderAsync>g__Awaited|3_0(ValueTask task, StringWriter writer, StringBuilderPool builder)
   at OrchardCore.DisplayManagement.Liquid.LiquidViewTemplateExtensions.RenderAsync(LiquidViewTemplate template, LiquidOptions options, IServiceProvider services, TextEncoder encoder, TemplateContext templateContext) in C:\code\OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement.Liquid\LiquidViewTemplate.cs:line 225
   at OrchardCore.Liquid.Services.LiquidTemplateManager.RenderAsync(String source, TextEncoder encoder, TemplateContext context) in C:\code\OrchardCore\src\OrchardCore.Modules\OrchardCore.Liquid\Services\LiquidTemplateManager.cs:line 53
   at OrchardCore.Templates.Services.TemplatesShapeBindingResolver.<>c__DisplayClass7_0.<<BuildShapeBinding>b__0>d.MoveNext() in C:\code\OrchardCore\src\OrchardCore.Modules\OrchardCore.Templates\Services\TemplatesShapeBindingResolver.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ProcessAsync(ShapeBinding shapeBinding, IShape shape, DisplayContext context) in C:\code\OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 268
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in C:\code\OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 119
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in C:\code\OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 174
   at CallSite.Target(Closure , CallSite , Object )
   at AspNetCore.Views_Item_Display.ExecuteAsync() in C:\code\OrchardCore\src\OrchardCore.Modules\OrchardCore.Contents\Views\Item\Display.cshtml:line 7
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext() in C:\code\OrchardCore\src\OrchardCore.Modules\OrchardCore.Diagnostics\DiagnosticsStartupFilter.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\code\OrchardCore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 82
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\code\OrchardCore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 99
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\code\OrchardCore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 59
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by sebastienros** [comment]
Are you doing a Lucene or a SQL query ?

**Comment by DaveEmmerson** [comment]
Sorry, it's a lucene query.

Took the match all query and then restricted down to only the content type
I wanted and only those marked as latest and published.

Works on the admin side, but fails when used from a liquid block on a page.

Works if the retrieve content items checkbox is checked, but doesn't when
not.

**Comment by Skrypt** [comment]
Ah! I will test it, maybe because of my latest changes or you are confused on which type of data is returned. I will look.

**Comment by DaveEmmerson** [comment]
@Skrypt yeah, for some reason the field I ask it to index comes back twice in the document and causes the JObject constructor to fail because of the duplicate property name:

```
var results = new List<JObject>();
foreach (var document in docs.TopDocs.ScoreDocs.Select(hit => searcher.Doc(hit.Doc)))
{
    results.Add(new JObject(document.Select(x => new JProperty(x.Name, x.GetStringValue()))));
}
```

So it's something to do with the indexing process I guess. I should have some more time to look at this now, so I'll see if I can track the issue further down.

**Comment by DaveEmmerson** [comment]
![image](https://user-images.githubusercontent.com/2356855/68113996-f2c14480-feec-11e9-8a62-4ffd8adaed1f.png)

**Comment by DaveEmmerson** [comment]
@Skrypt some further digging and I might have the cause. The duplication appears to come in at the index building stage:

![image](https://user-images.githubusercontent.com/2356855/68139389-f3280280-ff21-11e9-8f36-4cf838f55b93.png)

due to this

![image](https://user-images.githubusercontent.com/2356855/68139498-1c489300-ff22-11e9-803c-b7540fd0a4b3.png)

```
foreach (var key in context.Keys)
{
    keys.Add($"{key}.{partFieldDefinition.Name}");
}
keys.Add($"{typePartDefinition.Name}.{partFieldDefinition.Name}");
```

The context has a Keys of [ "Bulletin" ], so the foreach adds Bulletin.Sent, then on line 30 it uses the typePartDefintion.Name, which also is "Bulletin", so you end up with Bulletin.Sent in the keys list twice.

@hswami could you shed any light? Is the typePartDefinition.Name line unnecessary or does the context.Keys need to have the typePartDefinition.Name filtered out perhaps?

**Comment by Skrypt** [comment]
Sorry I couldn't follow up on this. I will try this week if I can.

**Comment by sebastienros** [comment]
Can you provide some repro steps? Explaining how to build Bulletin, the field (Sent) and what content items to create to repro the issue. Thanks.

**Comment by DaveEmmerson** [comment]
Yeah, I'll either do it tonight if I can, or will sort it out at work
tomorrow. Might be good to try out the docker image :)

**Comment by DaveEmmerson** [comment]
**Setup**

docker run --name orchardcms --network host orchardproject/orchardcore-cms-linux:dev

set up Test site with sqllite

enable features: content fields, content types, templates, lucene, queries

create content type: Bulletin
add a field: Sent, Date Field
edit field, enable indexing, enable storage in index

new content: Bulletin, created 2 test records with different dates 28/11/2019, 13/11/2019

search/indexing/lucene indices: add index Default

add query: new lucene query

Bulletins

```
{
  "query": {
    "bool": {
      "must": [
        { "term": { "Content.ContentItem.ContentType": "Bulletin" } }
      ]
    }
  }
}
```

new content type: Bulletins

edit template

`{{ Queries.Bulletins | query }}`

create new Bulletins


**Test cases**

1) Run query in admin screen - results come back fine

2) content items: find the Bulletins, View
   An error occurred while executing this request.

Edit query, tick 'retrieve content items'

3) Run query - results come back fine

4) content items: find the bulletins, View
   Results returned without error
