### ISSUE TITLE
Form value count limit 1024 exceeded issue

### ISSUE THREAD

**Issue by protoncm** [OrchardCMS/OrchardCore#4633]
I have encounter on this issue when i submitting form. 
```
System.IO.InvalidDataException
  HResult=0x80131501
  Message=Form value count limit 1024 exceeded.
  Source=Microsoft.AspNetCore.Http
  StackTrace:
   at Microsoft.AspNetCore.Http.Features.FormFeature.<InnerReadFormAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Http.Features.FormFeature.ReadForm()
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Form()
   at OrchardCore.Routing.FormValueRequiredMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates) in ....\OrchardCore.Abstractions\Routing\FormValueRequiredMatcherPolicy.cs:line 60

```
My scenario same as old [issue](https://github.com/OrchardCMS/OrchardCore/issues/3422) thread. (it doesn't work currently)

My questions are.
1. Can i set a configuration somewhere in Orchard Core without additional module ?
2. What the best way to resolve this ?

**Comment by deanmarcussen** [comment]
Yes, you are experiencing a aspnet core default limitation / configuration.

The mitigation for this (but maybe we should consider an OrchardCore setting for it to make it easier) is to configure the FormOptions in your startup class.

This is how I figured how to do it for media (which we then fixed a better way)
```
         services.Configure<FormOptions>(x =>
            {
                x.ValueLengthLimit = Int32.MaxValue;
                x.MultipartBodyLengthLimit = Int64.MaxValue; // In case of multipart
            });
```
refer https://github.com/OrchardCMS/OrchardCore/issues/3855

For your exact issue it may be about one of the other `FormOptions` values.

The other thing to note is that I could only get it working when I configuring it from the main projects Startup class, not a module Startup class.
