### ISSUE TITLE
Migrations do not allow columns of type byte[]

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#4658]
When running the following migration : 
```
public int UpdateFrom2()
        {
            SchemaBuilder.AlterTable(nameof(CommentRecord), table =>
            { 
                table.AddColumn<string>(nameof(CommentRecord.GroupId), c => c.WithLength(26));
                table.AddColumn<int>(nameof(CommentRecord.CommentGroupType));
                table.AddColumn<byte[]>(nameof(CommentRecord.File))

            });
 
                return 3;
  }
```
Im getting the exception 

```System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: This operation is only valid on generic types.
   at System.RuntimeType.GetGenericTypeDefinition()
   at YesSql.Sql.Schema.SchemaUtils.ToDbType(Type type)
   at YesSql.Sql.Schema.AlterTableCommand.AddColumn[T](String columnName, Action`1 column)
   at Intelli.Comments.Migrations.<>c.<UpdateFrom2>b__4_0(IAlterTableCommand table) in C:\OrchardCore.Dev.3.0\OrchardCore\src\IntelliCore.Modules\Intelli.Comments\Migrations.cs:line 70
   at YesSql.Sql.SchemaBuilder.AlterTable(String name, Action`1 table)
   at Intelli.Comments.Migrations.UpdateFrom2() in C:\OrchardCore.Dev.3.0\OrchardCore\src\IntelliCore.Modules\Intelli.Comments\Migrations.cs:line 53
```
Caused by the byte[] column I am trying to add for a file attachment .
Is this a yessql limitation ?

**Comment by Skrypt** [comment]
@giannik I've never seen a database table accept an array as a DB Column Type.

**Comment by sebastienros** [comment]
@Skrypt it's called a Blob and that's how you map byte arrays in any API in .NET

**Comment by Skrypt** [comment]
I see what you mean. Makes sense. YesSQL work I guess.

**Comment by sebastienros** [comment]
Please create a pr that updates yessql to version 1446

**Comment by Skrypt** [comment]
https://github.com/OrchardCMS/OrchardCore/pull/4661

**Comment by giannik** [comment]
wow, that was fast. 
Thanks.
