### ISSUE TITLE
Error first cms load using PostgreSQL

### ISSUE THREAD

**Issue by Norbus** [OrchardCMS/OrchardCore#4839]
Hello,

I'm experiencing a problem with orchard. From time to time in getting error while reading streams from db after first page load... When I try to reload page - problem disappears

Call stack:

> 12:38:30.459: [APP/PROC/WEB.0] 2019-11-19 11:38:30.4513|Default|0HLRCP8QN7S1P:00000001||Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|ERROR|An unhandled exception has occurred while executing the request. Npgsql.NpgsqlException (0x80004005): Exception while reading from stream
12:38:30.459: [APP/PROC/WEB.0]  ---> System.IO.EndOfStreamException: Attempted to read past the end of the stream.
12:38:30.459: [APP/PROC/WEB.0]    at Npgsql.NpgsqlReadBuffer.<>c__DisplayClass34_0.<<Ensure>g__EnsureLong|0>d.MoveNext()
12:38:30.459: [APP/PROC/WEB.0]    at Npgsql.NpgsqlReadBuffer.<>c__DisplayClass34_0.<<Ensure>g__EnsureLong|0>d.MoveNext()
12:38:30.459: [APP/PROC/WEB.0] --- End of stack trace from previous location where exception was thrown ---
12:38:30.459: [APP/PROC/WEB.0]    at Npgsql.NpgsqlConnector.<>c__DisplayClass163_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
12:38:30.459: [APP/PROC/WEB.0] --- End of stack trace from previous location where exception was thrown ---
12:38:30.459: [APP/PROC/WEB.0]    at Npgsql.NpgsqlConnector.<>c__DisplayClass163_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
12:38:30.459: [APP/PROC/WEB.0] --- End of stack trace from previous location where exception was thrown ---
12:38:30.459: [APP/PROC/WEB.0]    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
12:38:30.459: [APP/PROC/WEB.0]    at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
12:38:30.459: [APP/PROC/WEB.0]    at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
12:38:30.459: [APP/PROC/WEB.0]    at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
12:38:30.459: [APP/PROC/WEB.0]    at YesSql.Store.ProduceAsync[T](WorkerQueryKey key, Func`2 work, Object[] args)
12:38:30.459: [APP/PROC/WEB.0]    at YesSql.Services.DefaultQuery.Query`1.ListImpl()
12:38:30.459: [APP/PROC/WEB.0]    at ContentRazorHelperExtensions.QueryContentItemsAsync(IOrchardHelper orchardHelper, Func`2 query) in D:\_Dev\__egmina\egmina-orchard-cms\src\OrchardCore.Modules\OrchardCore.Contents\Razor\ContentRazorHelperExtensions.cs:line 88
12:38:30.459: [APP/PROC/WEB.0]    at AspNetCore.Pages_index.ExecuteAsync() in D:\_Dev\__egmina\egmina-orchard-cms\src\OrchardCore.Cms.Web\Pages\index.cshtml:line 14
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
12:38:30.459: [APP/PROC/WEB.0] --- End of stack trace from previous location where exception was thrown ---
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
12:38:30.459: [APP/PROC/WEB.0] --- End of stack trace from previous location where exception was thrown ---
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
12:38:30.459: [APP/PROC/WEB.0]    at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
12:38:30.459: [APP/PROC/WEB.0]    at OrchardCore.Media.Services.MediaFileStoreResolverMiddleware.Invoke(HttpContext context) in D:\_Dev\__egmina\egmina-orchard-cms\src\OrchardCore.Modules\OrchardCore.Media\Services\MediaFileStoreResolverMiddleware.cs:line 122
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
12:38:30.459: [APP/PROC/WEB.0]    at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext() in D:\_Dev\__egmina\egmina-orchard-cms\src\OrchardCore.Modules\OrchardCore.Diagnostics\DiagnosticsStartupFilter.cs:line 47
12:38:30.459: [APP/PROC/WEB.0] --- End of stack trace from previous location where exception was thrown ---
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)    at Npgsql.NpgsqlReadBuffer.<>c__DisplayClass34_0.<<Ensure>g__EnsureLong|0>d.MoveNext()
12:38:30.459: [APP/PROC/WEB.0] --- End of stack trace from previous location where exception was thrown ---
12:38:30.459: [APP/PROC/WEB.0]    at Npgsql.NpgsqlConnector.<>c__DisplayClass163_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
12:38:30.459: [APP/PROC/WEB.0] --- End of stack trace from previous location where exception was thrown ---
12:38:30.459: [APP/PROC/WEB.0]    at Npgsql.NpgsqlConnector.<>c__DisplayClass163_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
12:38:30.459: [APP/PROC/WEB.0] --- End of stack trace from previous location where exception was thrown ---
12:38:30.459: [APP/PROC/WEB.0]    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
12:38:30.459: [APP/PROC/WEB.0]    at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
12:38:30.459: [APP/PROC/WEB.0]    at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
12:38:30.459: [APP/PROC/WEB.0]    at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
12:38:30.459: [APP/PROC/WEB.0]    at YesSql.Store.ProduceAsync[T](WorkerQueryKey key, Func`2 work, Object[] args)
12:38:30.459: [APP/PROC/WEB.0]    at YesSql.Services.DefaultQuery.Query`1.ListImpl()
12:38:30.459: [APP/PROC/WEB.0]    at ContentRazorHelperExtensions.QueryContentItemsAsync(IOrchardHelper orchardHelper, Func`2 query) in D:\_Dev\__egmina\egmina-orchard-cms\src\OrchardCore.Modules\OrchardCore.Contents\Razor\ContentRazorHelperExtensions.cs:line 88
12:38:30.459: [APP/PROC/WEB.0]    at AspNetCore.Pages_index.ExecuteAsync() in D:\_Dev\__egmina\egmina-orchard-cms\src\OrchardCore.Cms.Web\Pages\index.cshtml:line 14
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
12:38:30.459: [APP/PROC/WEB.0] --- End of stack trace from previous location where exception was thrown ---
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
12:38:30.459: [APP/PROC/WEB.0] --- End of stack trace from previous location where exception was thrown ---
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
12:38:30.459: [APP/PROC/WEB.0]    at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
12:38:30.459: [APP/PROC/WEB.0]    at OrchardCore.Media.Services.MediaFileStoreResolverMiddleware.Invoke(HttpContext context) in D:\_Dev\__egmina\egmina-orchard-cms\src\OrchardCore.Modules\OrchardCore.Media\Services\MediaFileStoreResolverMiddleware.cs:line 122
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
12:38:30.459: [APP/PROC/WEB.0]    at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext() in D:\_Dev\__egmina\egmina-orchard-cms\src\OrchardCore.Modules\OrchardCore.Diagnostics\DiagnosticsStartupFilter.cs:line 47
12:38:30.459: [APP/PROC/WEB.0] --- End of stack trace from previous location where exception was thrown ---
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
12:38:30.459: [APP/PROC/WEB.0]    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task) 

Can somebody help me with this? I don't have any idea why this happens.

**Comment by jtkech** [comment]
Can you show us your code in your `src\OrchardCore.Cms.Web\Pages\index.cshtml`.

**Comment by Norbus** [comment]
Sure:

> @page
@inject OrchardCore.IOrchardHelper Orchard
@addTagHelper *, OrchardCore.Media

<section class="home">
    <div class="container">
        <div class="row">


            <div class="col-md-8 col-sm-12 col-xs-12">
                <div class="owl-carousel owl-theme slide" id="featured">

                    @{
                        var ogloszenia = await Orchard.GetRecentContentItemsByContentTypeAsync("ogloszenie");
                    }

                    @foreach (var ogloszenie in ogloszenia)
                    {

                        <div class="item">
                            <article class="featured">
                                <div class="overlay"></div>
                                <figure>
                                    <img asset-src="@ogloszenie.Content.ogloszenie.Image.Paths[0]" style="height: 100%; object-fit: contain;" alt="Gmina" />
                                </figure>
                                <div class="details">
                                    <div class="category"><a href="/ogloszenie/@ogloszenie.Content.AliasPart.Alias">Ogłoszenie</a></div>
                                    <h1><a href="/ogloszenie/@ogloszenie.Content.AliasPart.Alias">@ogloszenie</a></h1>
                                    <div class="time">@ogloszenie.Content.ogloszenie.datatime.Value</div>
                                </div>
                            </article>
                        </div>

                    }

                </div>
                <div class="line">
                    <div>Aktualności</div>
                </div>
                <div class="line transparent little"></div>
                <div id="newsLoop" class="row">
                    @{
                        var wszystkieaktualnosci = await Orchard.GetRecentContentItemsByContentTypeAsync("aktualnosci");
                    }
                    @foreach (var aktualnosci in wszystkieaktualnosci)
                    {
                        <article class="col-md-12 article-list newsList">
                            <div class="inner">
                                <figure>
                                    <a href="/aktualnosci/@aktualnosci.Content.AliasPart.Alias">
                                        <img asset-src="@aktualnosci.Content.aktualnosci.Image.Paths[0]" style="height: 100%; object-fit: cover;" alt="Aktualności Gminne" />
                                    </a>
                                </figure>
                                <div class="details">
                                    <div class="detail">
                                        <div class="time">@aktualnosci.Content.aktualnosci.datatime.Value</div>
                                    </div>
                                    <h1><a href="/aktualnosci/@aktualnosci.Content.AliasPart.Alias">@aktualnosci</a></h1>
                                    <footer>
                                        <a class="btn btn-primary more" href="/aktualnosci/@aktualnosci.Content.AliasPart.Alias">
                                            <div>Więcej</div>
                                            <div><i class="ion-ios-arrow-thin-right"></i></div>
                                        </a>
                                    </footer>
                                </div>
                            </div>
                        </article>
                    }
                    <div class="col-md-12 text-center">
                        <ul class="pagination news">
                            <li id="prev-news" class="prev"><a href="javascript:void(0)"><i class="ion-ios-arrow-left"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-md-4 sidebar" id="sidebar">
                <div class="sidebar-title for-tablet">Sidebar</div>
                <aside>
                    <h1 class="aside-title">Wydarzenia</h1>
                    <div id="eventsLoop" class="aside-body">

                        @{
                            var wydarzenia = await Orchard.GetRecentContentItemsByContentTypeAsync("Wydarzenie");
                        }

                        @foreach (var wydarzenie in wydarzenia)
                        {
                            <article class="article-mini eventList">
                                <div class="inner">
                                    <figure>
                                        <a href="/wydarzenie/@wydarzenie.Content.AliasPart.Alias">
                                            <img asset-src="@wydarzenie.Content.Wydarzenie.Image.Paths[0]" style="height: 100%; object-fit: contain;" alt="Wydarzenia gminne" />
                                        </a>
                                    </figure>
                                    <div class="padding">
                                        <h1><a href="/wydarzenie/@wydarzenie.Content.AliasPart.Alias">@wydarzenie</a></h1>
                                        <div class="detail">
                                            <div class="time">@wydarzenie.Content.Wydarzenie.datatime.Value</div>
                                        </div>
                                    </div>
                                </div>
                            </article>
                        }
                        <div class="col-md-12 text-center">
                            <ul class="pagination events">
                                <li id="prev-events" class="prev"><a href="javascript:void(0)"><i class="ion-ios-arrow-left"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </aside>
                <aside>
                    <div class="aside-body">
                        <div class="featured-author">
                            <div class="featured-author-inner">
                                <aside id="sponsored">
                                    <h1 class="aside-title">Przydatne linki</h1>
                                    <div class="aside-body">
                                        <ul class="sponsored">

                                            @{
                                                var przydatnelinki = await Orchard.GetRecentContentItemsByContentTypeAsync("przydatnelinki");
                                            }

                                            @foreach (var wszystkieprzydatnelinki in przydatnelinki)
                                            {
                                                <li>
                                                    <a href="@Html.Raw(wszystkieprzydatnelinki.Content.HtmlBodyPart.Html)">
                                                        <img asset-src="@wszystkieprzydatnelinki.Content.przydatnelinki.Image.Paths[0]" alt="Gmina" />
                                                    </a>
                                                </li>
                                            }

                                        </ul>
                                    </div>
                                </aside>
                            </div>
                        </div>
                    </div>
                </aside>
            </div>
        </div>
    </div>
</section>

**Comment by sebastienros** [comment]
These are due to network issues between your server and the database instance.
Are you using a proxy like istio ?

`System.IO.EndOfStreamException: Attempted to read past the end of the stream.`

**Comment by Norbus** [comment]
The PostgreSQL database is behind Keepalived and HAProxy (for HA purposes). Java-based projects in our company seem to run fine with this configuration and have no such errors.

**Comment by Piedone** [comment]
This doesn't seem to be still a bug, so I'll close now. Please reopen if you still experience this.
