### ISSUE TITLE
Unable to update from 1.0.0-beta3-72408 to 1.0.0-rc1-10782 with Postgresql

### ISSUE THREAD

**Issue by xumix** [OrchardCMS/OrchardCore#4842]
Basically changed to .net core 3 and updated package to `1.0.0-rc1-10782`
When strating the app I not get this:
```
Npgsql.PostgresException (0x80004005): 42703: column "Version" does not exist in table  "Document"
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 678
   at YesSql.Commands.UpdateDocumentCommand.ExecuteAsync(DbConnection connection, DbTransaction transaction, ISqlDialect dialect, ILogger logger)
   at YesSql.Session.UpdateEntityAsync(Object entity)
   at YesSql.Session.FlushAsync()
   at YesSql.Session.CommitAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.BeforeDisposeAsync() in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 261
   at OrchardCore.Environment.Shell.Scope.ShellScope.ActivateShellAsync() in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 207
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 152
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 59
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

  Exception data:

    Severity: ОШИБКА

    SqlState: 42703

    MessageText: column "Version" does not exist in table  "Document"

    Position: 39

    File: d:\pginstaller.auto\postgres.windows-x64\src\backend\parser\analyze.c

    Line: 2346

    Routine: transformUpdateTargetList
```

**Comment by Skrypt** [comment]
Fix is to add the Version column in the Document table as a nullable int.

**Comment by sebastienros** [comment]
Weird as it should have been done automatically, @deanmarcussen wrote some code for that.

**Comment by deanmarcussen** [comment]
PR in for this with yes sql https://github.com/sebastienros/yessql/pull/219

Adding the version column as @Skrypt suggested should also resolve this for you @xumix

**Comment by xumix** [comment]
@Skrypt @deanmarcussen 
Thanks!

**Comment by deanmarcussen** [comment]
Reopening to track it until the yessql fix is in

**Comment by MatthijsKrempel** [comment]
@deanmarcussen sebastienros/yessql#219 is merged, just not pushed to NuGet yet.

**Comment by sebastienros** [comment]
I need to merge yessql to master

**Comment by MatthijsKrempel** [comment]
Awesome!
