### ISSUE TITLE
Workflow script function executeQuery() throws "The connection does not support MultipleActiveResultSets."

### ISSUE THREAD

**Issue by mawendel** [OrchardCMS/OrchardCore#5106]
Using a workflow script task, i'm trying to update a content item by creating a simple javascript object. Probably related #4963 

`2019-12-23 04:55:19.8850|Default|80000148-0001-f900-b63f-84710c7967bb||OrchardCore.Workflows.Services.WorkflowStore|ERROR|IWorkflowHandler thrown from OrchardCore.Workflows.Http.Handlers.WorkflowRoutesHandler by InvalidOperationException System.InvalidOperationException: The connection does not support MultipleActiveResultSets.
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)
   at Microsoft.Data.SqlClient.SqlInternalTransaction.Rollback()
   at Microsoft.Data.SqlClient.SqlInternalTransaction.Dispose(Boolean disposing)
   at Microsoft.Data.SqlClient.SqlInternalTransaction.Dispose()
   at Microsoft.Data.SqlClient.SqlTransaction.Dispose(Boolean disposing)
   at System.Data.Common.DbTransaction.Dispose()
   at YesSql.Session.ReleaseTransaction()
   at YesSql.Session.Cancel()
   at YesSql.Session.FlushAsync()
   at YesSql.Services.DefaultQuery.Query1.FirstOrDefaultImpl()
   at OrchardCore.Workflows.Http.Handlers.WorkflowRoutesHandler.UpdateRouteEntriesAsync(WorkflowContext context) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Workflows\Http\Handlers\WorkflowInstanceRoutesHandler.cs:line 44
   at OrchardCore.Workflows.Http.Handlers.WorkflowRoutesHandler.CreatedAsync(WorkflowCreatedContext context) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Workflows\Http\Handlers\WorkflowInstanceRoutesHandler.cs:line 27
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable1 events, Func3 dispatch, T1 arg1, ILogger logger) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 134    at Microsoft.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)
   at Microsoft.Data.SqlClient.SqlInternalTransaction.Rollback()
   at Microsoft.Data.SqlClient.SqlInternalTransaction.Dispose(Boolean disposing)
   at Microsoft.Data.SqlClient.SqlInternalTransaction.Dispose()
   at Microsoft.Data.SqlClient.SqlTransaction.Dispose(Boolean disposing)
   at System.Data.Common.DbTransaction.Dispose()
   at YesSql.Session.ReleaseTransaction()
   at YesSql.Session.Cancel()
   at YesSql.Session.FlushAsync()
   at YesSql.Services.DefaultQuery.Query1.FirstOrDefaultImpl()
   at OrchardCore.Workflows.Http.Handlers.WorkflowRoutesHandler.UpdateRouteEntriesAsync(WorkflowContext context) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Workflows\Http\Handlers\WorkflowInstanceRoutesHandler.cs:line 44
   at OrchardCore.Workflows.Http.Handlers.WorkflowRoutesHandler.CreatedAsync(WorkflowCreatedContext context) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Workflows\Http\Handlers\WorkflowInstanceRoutesHandler.cs:line 27
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable1 events, Func3 dispatch, T1 arg1, ILogger logger) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 134
`

**Comment by jptissot** [comment]
We chatted on gitter an I tried to reproduce this issue on SQLite and PGSql and both work just fine. This may be a YesSql bug with MsSQL.
@sebastienros

**Comment by jptissot** [comment]
Actually, I added a AutoroutePart to the type I was updating and got this exception (using PGSQL)
```
2019-12-23 21:08:30.2518|Default|0HLS5DR41FMRL:0000001C||OrchardCore.Workflows.Http.Controllers.HttpWorkflowController|DEBUG|Invoking new workflow of type '4jm5zycy0m8r73j20c36g85w53' with start activity '4n6vbz8n3c35y2gcxrp6q8djc1'
2019-12-23 21:08:30.2655|Default|0HLS5DR41FMRL:0000001C||OrchardCore.Workflows.Services.WorkflowStore|ERROR|IWorkflowHandler thrown from OrchardCore.Workflows.Http.Handlers.WorkflowRoutesHandler by NpgsqlException Npgsql.NpgsqlException (0x80004005): Exception while reading from stream
 ---> System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at Npgsql.NpgsqlReadBuffer.<>c__DisplayClass34_0.<<Ensure>g__EnsureLong|0>d.MoveNext()
   at Npgsql.NpgsqlReadBuffer.<>c__DisplayClass34_0.<<Ensure>g__EnsureLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.ExecuteInternalCommand(Byte[] data, Boolean async)
   at Npgsql.NpgsqlTransaction.Rollback(Boolean async)
   at Npgsql.NpgsqlTransaction.Rollback()
   at Npgsql.NpgsqlTransaction.Dispose(Boolean disposing)
   at YesSql.Session.ReleaseTransaction()
   at YesSql.Session.Cancel()
   at YesSql.Session.FlushAsync()
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at OrchardCore.Workflows.Http.Handlers.WorkflowRoutesHandler.UpdateRouteEntriesAsync(WorkflowContext context) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Workflows\Http\Handlers\WorkflowInstanceRoutesHandler.cs:line 44
   at OrchardCore.Workflows.Http.Handlers.WorkflowRoutesHandler.CreatedAsync(WorkflowCreatedContext context) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Workflows\Http\Handlers\WorkflowInstanceRoutesHandler.cs:line 27
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 134    at Npgsql.NpgsqlReadBuffer.<>c__DisplayClass34_0.<<Ensure>g__EnsureLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.ExecuteInternalCommand(Byte[] data, Boolean async)
   at Npgsql.NpgsqlTransaction.Rollback(Boolean async)
   at Npgsql.NpgsqlTransaction.Rollback()
   at Npgsql.NpgsqlTransaction.Dispose(Boolean disposing)
   at YesSql.Session.ReleaseTransaction()
   at YesSql.Session.Cancel()
   at YesSql.Session.FlushAsync()
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at OrchardCore.Workflows.Http.Handlers.WorkflowRoutesHandler.UpdateRouteEntriesAsync(WorkflowContext context) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Workflows\Http\Handlers\WorkflowInstanceRoutesHandler.cs:line 44
   at OrchardCore.Workflows.Http.Handlers.WorkflowRoutesHandler.CreatedAsync(WorkflowCreatedContext context) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Workflows\Http\Handlers\WorkflowInstanceRoutesHandler.cs:line 27
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 134
```

**Comment by hishamco** [comment]
@mawendel could you try to add `MultipleActiveResultSets=True` into your SQL Server connection string?

**Comment by mawendel** [comment]
@hishamco yes i could, but unless OrchardCore is built to utilize MARS then its generally not a good idea to do that afaik. 

As @jptissot updated, it looks like a problem with the AutoroutePart.

**Comment by jptissot** [comment]
Yes, as soon as I add the AutoroutePart to the type, the workflow stops working.

**Comment by jptissot** [comment]
I am not able to reproduce using SQLite though 🤔

**Comment by hishamco** [comment]
> i could, but unless OrchardCore is built to utilize MARS then its generally not a good idea to do that afaik.

OC is using YesSQL under the hood, but I didn't see any place in OC that result set are used, but nothing stop you from doing that

If you have a certain scenario please let us know

**Comment by jptissot** [comment]
Repro:

- Create a type with a Title, Autotroute and some fields.
- Create a workflow that has a script task that uses the updateContentItem globalMethod
- Trigger the workflow

**Comment by mawendel** [comment]
@hishamco the problem is with updateContentItem() as @jptissot posted above, its a simple update in workflow task that does this when a content item has an AutoroutePart.

**Comment by hishamco** [comment]
Ok, good catch

**Comment by jtkech** [comment]
I will take a look asap.

Meanwhile, just for testing could you set the options so that the WF instance is not saved each time it is executed. OR try to use the `CommitTask` just after the activity updating the item.

**Comment by mawendel** [comment]
@jtkech i tried adding the CommitTask and it didnt seem to make a difference.

However, I discovered that if i stop my debug and restart the webapp. The very first time, and first time only, it will actually go through with the update. If i try a second time, it just "dies" in the middle of the workflow and will often not even show that an instance was running (no faulted workflow!).

**Comment by jptissot** [comment]
@mawendel I saw the same behavior.

**Comment by jtkech** [comment]
Okay, just tried with postgreSQL, i think i found the issue

In the `updateContentItem` srcipting method, that is a synchronous method, the result of `contentManager.UpdateAsync()` is not awaited with a `.GetAwaiter().GetResult()`.

I will do a PR.

**Comment by Skrypt** [comment]
Yep it works
