### ISSUE TITLE
Fatal error on Lucene inded rebuild or reset on 1.0.0-rc1-11323

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#5173]
**Step 1**

![step-1](https://user-images.githubusercontent.com/1761249/71642375-056cb580-2cb3-11ea-8ed7-85d3c2b10f4d.png)

**Step 2**
![step-2](https://user-images.githubusercontent.com/1761249/71642376-056cb580-2cb3-11ea-9055-2994de5dc98b.png)

**Step 3**
![step-3](https://user-images.githubusercontent.com/1761249/71642377-056cb580-2cb3-11ea-930f-ccf51980c6a0.png)

**Step 4**

This is the content of the `Blog` Lucene index folder 

![step-4](https://user-images.githubusercontent.com/1761249/71642378-06054c00-2cb3-11ea-9ee1-5feb8dcaef87.png)

**Step 5**
![step-5](https://user-images.githubusercontent.com/1761249/71642379-06054c00-2cb3-11ea-8804-360b607a7cee.png)

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at OrchardCore.Lucene.LuceneIndexingService.<>c__DisplayClass12_0.<<ProcessContentItemsAsync>b__0>d.MoveNext() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Lucene\Services\LuceneIndexingService.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 209
   at OrchardCore.Lucene.LuceneIndexingService.ProcessContentItemsAsync(String indexName) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Lucene\Services\LuceneIndexingService.cs:line 225
   at OrchardCore.Lucene.Controllers.AdminController.Rebuild(String id) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Lucene\Controllers\AdminController.cs:line 268
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Diagnostics\DiagnosticsStartupFilter.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at OrchardCore.ContentPreview.PreviewStartupFilter.<>c.<<Configure>b__1_1>d.MoveNext() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.ContentPreview\PreviewStartupFilter.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 209
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 61
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I am using OrchardCore in decoupled mode. It uses Default tenant and the path to the Lucene index folder is `\App_Data\Sites\Default\Lucene\Blog`.

**Comment by dodyg** [comment]
OK so this is the line that throws exception 

https://github.com/OrchardCMS/OrchardCore/blob/e7468f4ae05dc91777ad0424601aa3031090e33d/src/OrchardCore.Modules/OrchardCore.Lucene/Services/LuceneIndexingService.cs#L183

**Comment by dodyg** [comment]
So this error is specific to this one of my decoupled CMS. I tested on my other traditional site it is working fine.

**Comment by dodyg** [comment]
This could be the root of the problem. When I click on culture settings, I got an exception.

![cultures-1](https://user-images.githubusercontent.com/1761249/71642710-4ddaa200-2cb8-11ea-9d85-1acd6b6f0e1a.png)


```
System.Exception: Shape type 'LocalizationSettings_Edit' not found
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context)
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 174
   at CallSite.Target(Closure , CallSite , Object )
   at OrchardCore.DisplayManagement.Zones.ZoneShapes.ContentZone(Object DisplayAsync, Object Shape) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.DisplayManagement\Zones\ZoneShapes.cs:line 62
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.<ProcessAsync>g__Awaited|12_0(Task`1 task) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 296
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 116
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 174
   at CallSite.Target(Closure , CallSite , Object )
   at AspNetCore._Areas_OrchardCore_Settings_Views_SiteSettings_Edit.ExecuteAsync() in /Areas/OrchardCore.Settings/Views/SiteSettings.Edit.cshtml:line 6
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(String partialViewName, Object model, ViewDataDictionary viewData, TextWriter writer)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.PartialAsync(String partialViewName, Object model, ViewDataDictionary viewData)
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.<ProcessAsync>g__Awaited|12_0(Task`1 task) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 296
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 116
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 174
   at CallSite.Target(Closure , CallSite , Object )
   at AspNetCore._Areas_OrchardCore_Settings_Views_Admin_Index.<ExecuteAsync>b__14_0() in /Areas/OrchardCore.Settings/Views/Admin/Index.cshtml:line 8
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.GetChildContentAsync(Boolean useCachedResult, HtmlEncoder encoder)
   at Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCore._Areas_OrchardCore_Settings_Views_Admin_Index.ExecuteAsync() in /Areas/OrchardCore.Settings/Views/Admin/Index.cshtml:line 5
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Diagnostics\DiagnosticsStartupFilter.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at OrchardCore.ContentPreview.PreviewStartupFilter.<>c.<<Configure>b__1_1>d.MoveNext() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.ContentPreview\PreviewStartupFilter.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 209
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 59
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by dodyg** [comment]
I solve the culture settings exception by disabling the Content Localization module and enabling it again.

![cultures-3](https://user-images.githubusercontent.com/1761249/71642935-92b40800-2cbb-11ea-8c5a-0cb3c4e4d4df.png)

**Comment by dodyg** [comment]
The problem is that the error with rebuilding index is still the same

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at OrchardCore.Lucene.LuceneIndexingService.<>c__DisplayClass12_0.<<ProcessContentItemsAsync>b__0>d.MoveNext() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Lucene\Services\LuceneIndexingService.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 209
   at OrchardCore.Lucene.LuceneIndexingService.ProcessContentItemsAsync(String indexName) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Lucene\Services\LuceneIndexingService.cs:line 225
   at OrchardCore.Lucene.Controllers.AdminController.Reset(String id) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Lucene\Controllers\AdminController.cs:line 247
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Diagnostics\DiagnosticsStartupFilter.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at OrchardCore.ContentPreview.PreviewStartupFilter.<>c.<<Configure>b__1_1>d.MoveNext() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.ContentPreview\PreviewStartupFilter.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 209
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 61
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by Skrypt** [comment]
Hmm the issue is probably because settings.Culture is throwing a NRE.

**Comment by Skrypt** [comment]
Ok I created a content type named "Acme".
Then I created a content item that contains no LocalizationPart.
I edited the Content Type definition to add the LocalizationPart.
I created a new content item with that culture.
So I have 2 content items. One with a LocalizationPart and one without it.

`context.ContentItem.Content?.LocalizationPart?.Culture`

This part of the code should take care of null values when a ContentItem has no LocalizationPart.
This could throw if there is no context.ContentItem but this should never happen unless I'm wrong.
And for the settings.Culture ; It should have been affected as soon as you created the Lucene index. So, I'm not sure here where the NRE comes from.

**Comment by Skrypt** [comment]
Last thing I need to try is a solution with Nuget packages but that should have the same outcome as the source code solution.

**Comment by dodyg** [comment]
![lucene-settings](https://user-images.githubusercontent.com/1761249/71648503-a5572d00-2d0d-11ea-9e13-b29f7f64da2f.png)

**Comment by dodyg** [comment]
Is this the package symbol server  `https://www.myget.org/F/orchardcore-preview/symbols`?

**Comment by Skrypt** [comment]
This is a LuceneSettings not a LuceneIndexSettings.

**Comment by dodyg** [comment]
![lucene-index-settings](https://user-images.githubusercontent.com/1761249/71648901-cec68780-2d12-11ea-802a-dfb3134024fc.png)

**Comment by dodyg** [comment]
hmm..I cannot get the values

![cannot-get-values](https://user-images.githubusercontent.com/1761249/71649187-4c8b9280-2d15-11ea-9e71-3de7ce66d888.png)

**Comment by Skrypt** [comment]
You sure you did a proper merge or that we are talking about the same source code than the dev branch we have here? Else I would need to debug this on your pc

**Comment by dodyg** [comment]
It's a decoupled project. I am relying on the nuget packages.

**Comment by dodyg** [comment]
OK I switch to Kestrel debugging instead of IISExpress and getting some progress.

**Comment by dodyg** [comment]
![context-is-null](https://user-images.githubusercontent.com/1761249/71649434-6a59f700-2d17-11ea-8560-3e815c96e49b.png)

**Comment by dodyg** [comment]
![lucene-task-batch](https://user-images.githubusercontent.com/1761249/71649528-4814a900-2d18-11ea-89b0-f331d3f56dc9.png)

This is the task batch where NRE happens

**Comment by Skrypt** [comment]
Add me on Skype so I can see this.

**Comment by Skrypt** [comment]
Ok so the issue I think is that it tries to find a ContentItem which does not exist in your document table. So basically it has been removed previously and does not exist anymore in your ContentItemIndex or Document table.

**Comment by dodyg** [comment]
Bingo - document id 273 doesn't exist

![lucene-missing-data](https://user-images.githubusercontent.com/1761249/71649707-90809680-2d19-11ea-866c-ec3e203a0fd4.png)

**Comment by Skrypt** [comment]
```
                            if (publishedIndexContext != null || latestIndexContext != null)
                            {
                                // Update the document from the index if its lastIndexId is smaller than the current task id. 
                                foreach (var index in allIndices)
                                {
                                    if (index.Value >= task.Id || !settingsByIndex.TryGetValue(index.Key, out var settings))
                                    {
                                        continue;
                                    }

                                    var context = !settings.IndexLatest ? publishedIndexContext : latestIndexContext;
                                    bool ignoreIndexedCulture = settings?.Culture == "any" ? false : context.ContentItem.Content?.LocalizationPart?.Culture != settings?.Culture;

                                    // Ignore if the content item content type or culture is not indexed in this index
                                    if (context.ContentItem == null || !settings.IndexedContentTypes.Contains(context.ContentItem.ContentType) || ignoreIndexedCulture)
                                    {
                                        continue;
                                    }

                                    updatedDocumentsByIndex[index.Key].Add(context.DocumentIndex);
                                }
                            }
```

I think this will fix it.

**Comment by dodyg** [comment]
OK I found two Content Items referred in `IndexingTask` table that no longer exists. Once I deleted them, both the Lucene index Reset and Rebuild works.

![lucene-reset](https://user-images.githubusercontent.com/1761249/71650159-ed318080-2d1c-11ea-8b83-ebd205918de2.png)


Thank you so much for your help @Skrypt.

**Comment by Skrypt** [comment]
Awesome 😄
