### ISSUE TITLE
1.0.0-rc1-10004  Create content item error  'no such table: TextFieldIndex'  ，And no log file was created

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#5176]
orchard core version : 1.0.0-rc1-10004

`Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: TextFieldIndex'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 678
   at YesSql.Session.FlushAsync()
   at YesSql.Session.CommitAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.BeforeDisposeAsync() in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 198
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 101
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 59
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

this is a new contenttype
![image](https://user-images.githubusercontent.com/15613121/71642693-30263080-2cea-11ea-9ece-a537027e5c73.png)

**Comment by deanmarcussen** [comment]
you are using the Content fields indexing feature I think?

This issue is fixed in the dev branch. Suggest you upgrade to the myget feed

**Comment by Skrypt** [comment]
Migration did not run when enabling the module probably.

**Comment by hyzx86** [comment]
@deanmarcussen 
Yes , it work fine when I disable the  Content fields indexing  feature

**Comment by hyzx86** [comment]
update to 1.0.0-rc1-113311 to fix this problem
