### ISSUE TITLE
Lucene index creation from a recipe, in a module:  SQLite Error 6: 'database schema is locked: main'.

### ISSUE THREAD

**Issue by PiemP** [OrchardCMS/OrchardCore#5233]
Hi all, 

I'm having an issue when I try t o run a recipe that contains the instructions to create a Lucene's index.
I'm working on dev branch and after lasts commit I have seen some news in the Lucene's index creation code inside the recipe. I have updated my recipes inside my modules like this: 
```
  {
      "name": "lucene-index",
      "Indices": [
        {
          "BoxLinks": {
            "AnalyzerName": "standardanalyzer",
            "IndexLatest": false,
            "IndexedContentTypes": [
              "BoxLink"
            ]
          }
        }
      ]
    }
```
But when I try to setup a new site I receive this error: 
```
OrchardCore.Data.Migration.DataMigrationManager|ERROR|Error while running migration version 0 for '...BoxLink'. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 6: 'database schema is locked: main'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText, SqliteParameter[] parameters)
   at Microsoft.Data.Sqlite.SqliteTransaction..ctor(SqliteConnection connection, IsolationLevel isolationLevel)
   at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel)
   at Microsoft.Data.Sqlite.SqliteConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   at System.Data.Common.DbConnection.BeginTransaction(IsolationLevel isolationLevel)
   at YesSql.Session.DemandAsync()
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at OrchardCore.Lucene.LuceneIndexSettingsService.LoadDocumentAsync(ISession session) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore.Modules\OrchardCore.Lucene\Services\LuceneIndexSettingsService.cs:line 121
   at OrchardCore.Lucene.LuceneIndexSettingsService.UpdateIndexAsync(LuceneIndexSettings settings) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore.Modules\OrchardCore.Lucene\Services\LuceneIndexSettingsService.cs:line 95
   at OrchardCore.Lucene.LuceneIndexingService.CreateIndexAsync(LuceneIndexSettings indexSettings) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore.Modules\OrchardCore.Lucene\Services\LuceneIndexingService.cs:line 243
   at OrchardCore.Lucene.Recipes.LuceneIndexStep.ExecuteAsync(RecipeExecutionContext context) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore.Modules\OrchardCore.Lucene\Recipes\LuceneIndexStep.cs:line 46
   at OrchardCore.Recipes.Services.RecipeExecutor.<>c__DisplayClass12_0.<<ExecuteStepAsync>b__0>d.MoveNext() in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 175
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 195
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteStepAsync(RecipeExecutionContext recipeStep) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 156
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 100
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 118
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 146
   at OrchardCore.Recipes.Services.RecipeMigrator.ExecuteAsync(String recipeFileName, IDataMigration migration) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeMigrator.cs:line 41
   at It.Csc.OrchardCorePA.Content.BoxLink.Migrations.CreateAsync() in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCorePA\Modules\It.Csc.OrchardCorePA.Content.BoxLink\Migrations.cs:line 33
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 207    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText, SqliteParameter[] parameters)
   at Microsoft.Data.Sqlite.SqliteTransaction..ctor(SqliteConnection connection, IsolationLevel isolationLevel)
   at Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel)
   at Microsoft.Data.Sqlite.SqliteConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   at System.Data.Common.DbConnection.BeginTransaction(IsolationLevel isolationLevel)
   at YesSql.Session.DemandAsync()
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at OrchardCore.Lucene.LuceneIndexSettingsService.LoadDocumentAsync(ISession session) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore.Modules\OrchardCore.Lucene\Services\LuceneIndexSettingsService.cs:line 121
   at OrchardCore.Lucene.LuceneIndexSettingsService.UpdateIndexAsync(LuceneIndexSettings settings) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore.Modules\OrchardCore.Lucene\Services\LuceneIndexSettingsService.cs:line 95
   at OrchardCore.Lucene.LuceneIndexingService.CreateIndexAsync(LuceneIndexSettings indexSettings) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore.Modules\OrchardCore.Lucene\Services\LuceneIndexingService.cs:line 243
   at OrchardCore.Lucene.Recipes.LuceneIndexStep.ExecuteAsync(RecipeExecutionContext context) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore.Modules\OrchardCore.Lucene\Recipes\LuceneIndexStep.cs:line 46
   at OrchardCore.Recipes.Services.RecipeExecutor.<>c__DisplayClass12_0.<<ExecuteStepAsync>b__0>d.MoveNext() in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 175
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 195
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteStepAsync(RecipeExecutionContext recipeStep) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 156
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 100
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 118
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 146
   at OrchardCore.Recipes.Services.RecipeMigrator.ExecuteAsync(String recipeFileName, IDataMigration migration) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeMigrator.cs:line 41
   at It.Csc.OrchardCorePA.Content.BoxLink.Migrations.CreateAsync() in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCorePA\Modules\It.Csc.OrchardCorePA.Content.BoxLink\Migrations.cs:line 33
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in D:\lavoro\.net_core\OrchardCore-GIT\OrchardCore\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 207
```

Hope this can be an useful report. I'm trying to understand what is going wrong, but I miss some OC's meetings in the Christmas time and I believe to have lost something important 😅.

**Comment by Skrypt** [comment]
You are trying to update a database that has a locked status. When you are trying to create a Tenant make sure there is no folder already named as the same as the tenant you are trying to create. It might be the issue where it tries to execute a migration on a SQLite database that was already initialized with a migration and/or already used by an other tenant.

I tried from the dev branch creating a new tenant while using TheBlog recipe and it worked without any issue.

**Comment by PiemP** [comment]
I don't understand what happen...tomorrow I try to test it more... But is not a new tenants case and I don't believe is a missing } or missing comma. It's only a new OC's site with my theme and my custom module.  This is  my module recipe:
```
{
  "name": "",
  "displayName": "",
  "description": "",
  "author": "",
  "website": "",
  "version": "",
  "issetuprecipe": false,
  "categories": "",
  "tags": [],
  // The variables are evaluated the first time they are accessed, and reused across steps
  "variables": {
  },

  "steps": [
    {
      "name": "ContentDefinition",
      "ContentTypes": [
        {
          "Name": "BoxLink",
          "DisplayName": "BoxLink",
          "Settings": {
            "ContentTypeSettings": {
              "Creatable": true,
              "Listable": true,
              "Draftable": true,
              "Versionable": true,
              "Securable": true
            }
          },
          "ContentTypePartDefinitionRecords": [
            {
              "PartName": "BoxLink",
              "Name": "BoxLink",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "1"
                }
              }
            },
            {
              "PartName": "BagPart",
              "Name": "BagPart",
              "Settings": {
                "ContentIndexSettings": {},
                "ContentTypePartSettings": {
                  "DisplayName": "Bag",
                  "Description": "Provides a collection behavior for your content item.",
                  "Position": "2"
                },
                "BagPartSettings": {
                  "ContainedContentTypes": [
                    "LinkWithIcon"
                  ]
                }
              }
            },
            {
              "PartName": "TitlePart",
              "Name": "TitlePart",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "0"
                }
              }
            }
          ]
        },
        {
          "Name": "BoxLinkSelect",
          "DisplayName": "BoxLinkSelect",
          "Settings": {
            "ContentTypeSettings": {
              "Draftable": true,
              "Versionable": true,
              "Stereotype": "Widget",
              "Securable": true
            }
          },
          "ContentTypePartDefinitionRecords": [
            {
              "PartName": "BoxLinkSelect",
              "Name": "BoxLinkSelect",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "0"
                }
              }
            }
          ]
        },
        {
          "Name": "BoxLinkAll",
          "DisplayName": "BoxLinkAll",
          "Settings": {
            "ContentTypeSettings": {
              "Draftable": true,
              "Versionable": true,
              "Stereotype": "Widget",
              "Securable": true
            }
          },
          "ContentTypePartDefinitionRecords": [
            {
              "PartName": "BoxLinkAllPart",
              "Name": "BoxLinkAllPart",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "0"
                }
              }
            }
          ]
        },
        {
          "Name": "BoxLinkMngmt",
          "DisplayName": "Gestione BoxLink",
          "Settings": {
            "ContentTypeSettings": {
              "Creatable": false,
              "Listable": false,
              "Draftable": false,
              "Versionable": false,
              "Securable": true
            },
            "FullTextAspectSettings": {}
          },
          "ContentTypePartDefinitionRecords": [
            {
              "PartName": "BoxLinkMngmt",
              "Name": "BoxLinkMngmt",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "0"
                }
              }
            },
            {
              "PartName": "BagPart",
              "Name": "BoxLinks",
              "Settings": {
                "ContentTypePartSettings": {
                  "DisplayName": "Elenco BoxLink",
                  "Description": "boxlink visualizzabili nella pagina",
                  "Position": "1"
                },
                "ContentIndexSettings": {},
                "BagPartSettings": {
                  "ContainedContentTypes": [
                    "BoxLink"
                  ]
                }
              }
            },
            {
              "PartName": "AliasPart",
              "Name": "AliasPart",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "2"
                },
                "ContentIndexSettings": {},
                "AutoroutePartSettings": {
                }
              }
            }
          ]
        },
        {
          "Name": "BannerMngmt",
          "DisplayName": "Gestione Banner",
          "Settings": {
            "ContentTypeSettings": {
              "Creatable": false,
              "Listable": false,
              "Draftable": false,
              "Versionable": false,
              "Securable": true
            },
            "FullTextAspectSettings": {}
          },
          "ContentTypePartDefinitionRecords": [
            {
              "PartName": "BannerMngmt",
              "Name": "BannerMngmt",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "0"
                }
              }
            },
            {
              "PartName": "BagPart",
              "Name": "Banners",
              "Settings": {
                "ContentTypePartSettings": {
                  "DisplayName": "Elenco Banner",
                  "Description": "banner visualizzabili nella pagina",
                  "Position": "1"
                },
                "ContentIndexSettings": {},
                "BagPartSettings": {
                  "ContainedContentTypes": [
                    "LinkWithImage"
                  ]
                }
              }
            },
            {
              "PartName": "AliasPart",
              "Name": "AliasPart",
              "Settings": {
                "ContentTypePartSettings": {
                  "Position": "2"
                },
                "ContentIndexSettings": {},
                "AutoroutePartSettings": {
                }
              }
            }
          ]
        }
      ],
      "ContentParts": [
        {
          "Name": "BoxLink",
          "Settings": {
            "ContentPartSettings": {}
          },
          "ContentPartFieldDefinitionRecords": [
          ]
        },
        {
          "Name": "BoxLinkMngmt",
          "Settings": {
            "ContentPartSettings": {}
          },
          "ContentPartFieldDefinitionRecords": [
          ]
        },
        {
          "Name": "BannerMngmt",
          "Settings": {
            "ContentPartSettings": {}
          },
          "ContentPartFieldDefinitionRecords": [
          ]
        },
        {
          "Name": "BoxLinkSelect",
          "Settings": {
            "ContentPartSettings": {}
          },
          "ContentPartFieldDefinitionRecords": [
            {
              "FieldName": "ContentPickerField",
              "Name": "Boxlink",
              "Settings": {
                "ContentIndexSettings": {
                  "Included": false,
                  "Stored": false,
                  "Analyzed": false,
                  "Sanitized": false,
                  "Tokenized": false,
                  "Template": null
                },
                "ContentPartFieldSettings": {
                  "DisplayName": "Boxlink",
                  "Position": "0"
                },
                "ContentPickerFieldSettings": {
                  "Hint": "ATTENZIONE! Devi salvare la pagina per visualizzare l'elenco dei boxlink da aggiungere, la 1° volta che aggiungi questo elemento ad una pagina.",
                  "Required": true,
                  "DisplayedContentTypes": [
                    "BoxLink"
                  ]
                }
              }
            }
          ]
        },
        {
          "Name": "BoxLinkAllPart",
          "Settings": {
            "ContentPartSettings": {
              "Attachable": true,
              "Description": "Widget to print some element in page."
            }
          },
          "ContentPartFieldDefinitionRecords": []
        }
      ]
    },
    {
      "name": "lucene-index",
      "Indices": [
        {
          "BoxLinks": {
            "AnalyzerName": "standardanalyzer",
            "IndexLatest": false,
            "IndexedContentTypes": [
              "BoxLink"
            ]
          }
        }
      ]
    },
    {
      "name": "queries",
      "Queries": [
        {
          "Source": "Lucene",
          "Name": "AllBoxLinks",
          "Index": "BoxLinks",
          "Template": "{\r\n  \"query\": {\r\n         \"term\":  { \"Content.ContentItem.ContentType\" : \"BoxLink\" }\r\n         }\r\n  }",
          "Schema": null,
          "ReturnContentItems": true
        }
      ]
    }
  ]
}
```
I have used this thing to do it before, but now seems it doesn't work. If I remove the code that create the Lucene's index this recipe, it's working well.

**Comment by Skrypt** [comment]
If you look into your App_Data/Sites/YourTenantName/Lucene does it already contains a folder named BoxLinks? Also, if you look in your Database in the Document table there is single row now that contains the Index settings. If you are trying to import this recipe directly from the import/export feature this will fail because the index already exists. Let me try to repro this scenario and give you feedback on what I find.

**Comment by Skrypt** [comment]
No just tested your recipe on top of a TheBlogTheme tenant and it worked. I imported the recipe file twice to see if it would fail and it worked.

![image](https://user-images.githubusercontent.com/3228637/72025880-8e519700-3247-11ea-917b-76cbef1dd5c7.png)
![image](https://user-images.githubusercontent.com/3228637/72025890-97426880-3247-11ea-9056-95a2546e7db1.png)

**Comment by Skrypt** [comment]
So the other thing I need to test now is a recipe that gets executed automatically from a Module I guess.

**Comment by PiemP** [comment]
> If you look into your App_Data/Sites/YourTenantName/Lucene does it already contains a folder named BoxLinks?

No folder BoxLinks.

> So the other thing I need to test now is a recipe that gets executed automatically from a Module I guess.

I believe you can repro this issue creating a setup recipe that call a module with a migration that call a recipe that create a Lucene's index. 

I Try to debug the process to see what happen.

**Comment by Skrypt** [comment]
Ok now I get the issue. Probably a scope issue.

**Comment by PiemP** [comment]
I believe the problem is in LuceneIndexSettingsService class: in this class is used the IStore to create a ISession but I have test this class changing it scopes form Singleton to Scoped, removed the IStore property and added an ISession property and now the issue seems fixed...but I have to make some other test...

**Comment by Skrypt** [comment]
We made this service intentionally as a singleton, not sure why we would want this to be a Scoped service. We then probably miss some locking mechanism.

**Comment by jtkech** [comment]
Yes i remember, `LuceneIndexSettingsService` can't be a scoped service as it is referenced by `LuceneIndexManager` that is a singleton.

But its methods as `UpdateIndexAsync()` are executed in a scoped context. I remember that when we were creating a session, we thought about this potential issue.

So the solution would be to resolve on the fly the current scoped session, by using an `IHttpContextAccessor` or the `ShellScope.Services` as the `SiteService` singleton does.

Or the caller of these methods would have to provide as a parameter the scoped service provider or the current session itself.

**Comment by PiemP** [comment]
There is a reason why `LuceneIndexManager` must be a singleton? I don't have completely test the changes that I have made, but for now seems all working well after changing the scope of  `LuceneIndexSettingsService` and  `LuceneIndexManager` from Singleton to Scoped.

I have changed the class scope because I have looked at QueryStep (that it uses QueryManager class) and other *Step classes used in the recipes executions and I have see that some of that use ISession and not IStore object. But to allow ISession object use from the DI container I presume is necessary to change the `LuceneIndexSettingsService` scope from Singleton to Scoped.

**Comment by Skrypt** [comment]
Not sure exactly what's missing as of now but I think this can be fixed by keeping the service as a singleton. This should be a singleton for scalability concern.

**Comment by jtkech** [comment]
As i remember it's because it manage lucene indexex and needs to use a Lock at the tenant singleton level, here a lock on itself. Yes, one solution would be to use both services as scoped services and then have a `Named Tenant Lock` service as i implemented in the distributed branch.

**Comment by Skrypt** [comment]
But are we not locking already when creating a new index in the LuceneIndexManager? I'm sure you are right but that's strange we can't use a singleton here as there is no real need to have more than one instance of this class per tenant.

**Comment by jtkech** [comment]
> But are we not locking already when creating a new index in the LuceneIndexManager?

Yes you're right and that's ok as it is a singleton so the lock works if 2 threads (e.g related to 2 rquest scopes) want to update an index. But, if we make it a scoped service to be able to inject the session, locking on the scoped instance would be useless, that's why i'm talking about a locking singleton service.
