### ISSUE TITLE
[GraphQL] Fields cannot start with a number

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#5251]
Repro:

Add a field to a type that starts with a number. In my case, it was a Boolean field named 18OrOlder. 

The GraphQL Schema generation will throw an exception in the logs (GraphiQL will be blank)

**Comment by carlwoodhouse** [comment]
note: the fieldnames are generated from the technical name and the admin doesnt allow field names starting with a number ..

**Comment by jptissot** [comment]
I think I did this via a Recipe migration.

**Comment by carlwoodhouse** [comment]
i suspect the reason graphql itself complains is that that names beginning with numbers don't conform to the graphql spec.

(see: https://graphql.github.io/graphql-spec/June2018/#sec-Names)

**Comment by jptissot** [comment]
```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      => ConnectionId:0HLSLSGK83F4M => RequestPath:/api/graphql RequestId:0HLSLSGK83F4M:00000007, SpanId:|64b5b33b-40080ca188c7a510., TraceId:64b5b33b-40080ca188c7a510, ParentId:
      An unhandled exception has occurred while executing the request.
System.ArgumentOutOfRangeException: A field name must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but 18OrOlder does not. (Parameter 'name')
   at GraphQL.Utilities.NameValidator.ValidateName(String name, String type)
   at GraphQL.Types.ComplexGraphType`1.AddField(FieldType fieldType)
   at OrchardCore.ContentManagement.GraphQL.Queries.Types.ContentItemType.AddField(FieldType fieldType) in /builds/digital-innovation/tooling-and-services/OrchardCore/src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/Types/ContentItemType.cs:line 81
   at OrchardCore.ContentManagement.GraphQL.Queries.Types.DynamicContentTypeBuilder.Build(FieldType contentQuery, ContentTypeDefinition contentTypeDefinition, ContentItemType contentItemType) in /builds/digital-innovation/tooling-and-services/OrchardCore/src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/Types/DynamicContentTypeBuilder.cs:line 47
   at OrchardCore.ContentManagement.GraphQL.Queries.ContentTypeQuery.BuildAsync(ISchema schema) in /builds/digital-innovation/tooling-and-services/OrchardCore/src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/ContentTypeQuery.cs:line 66
   at OrchardCore.Apis.GraphQL.Services.SchemaService.GetSchemaAsync() in /builds/digital-innovation/tooling-and-services/OrchardCore/src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/Services/SchemaService.cs:line 56
   at OrchardCore.Apis.GraphQL.GraphQLMiddleware.ExecuteAsync(HttpContext context, ISchemaFactory schemaService) in /builds/digital-innovation/tooling-and-services/OrchardCore/src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/GraphQLMiddleware.cs:line 80
   at OrchardCore.Apis.GraphQL.GraphQLMiddleware.Invoke(HttpContext context, IAuthorizationService authorizationService, IAuthenticationService authenticationService, ISchemaFactory schemaService) in /builds/digital-innovation/tooling-and-services/OrchardCore/src/OrchardCore.Modules/OrchardCore.Apis.GraphQL/GraphQLMiddleware.cs:line 64
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext() in /builds/digital-innovation/tooling-and-services/OrchardCore/src/OrchardCore.Modules/OrchardCore.Diagnostics/DiagnosticsStartupFilter.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by carlwoodhouse** [comment]
so yes; its due to the fact the name doesnt conform with the graphql spec. Not sure how we want to proceed as this isnt even possibly through the admin, only recipes. Thoughts @sebastienros ?

**Comment by sebastienros** [comment]
I'd suggest to just prevent that, even from recipes. Not sure what other special cases you will hit after that.
