### ISSUE TITLE
Table textfieldindex no exists while enabled Content Fields Indexing (SQL)  module

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/OrchardCore#5443]
Hi, after I enabled `Content Fields Indexing (SQL) ` module, then I create a new content, click post, an exception occurred:

`MySqlException: Table 'lh_op.lh_textfieldindex' doesn't exist`

    MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in MySqlDataReader.cs
    MySql.Data.MySqlClient.MySqlDataReader.CreateAsync
    YesSql.Session.FlushAsync()
    YesSql.Services.DefaultQuery+Query<T>.FirstOrDefaultImpl()
    OrchardCore.ContentManagement.DefaultContentManager.PublishAsync(ContentItem contentItem) in DefaultContentManager.cs
                var previous = await _session
    OrchardCore.Contents.Controllers.AdminController.<EditAndPublishPOST>b__25_0(ContentItem contentItem) in AdminController.cs
                    await _contentManager.PublishAsync(contentItem);
    OrchardCore.Contents.Controllers.AdminController.EditPOST(string contentItemId, string returnUrl, bool stayOnSamePage, Func<ContentItem, Task> conditionallyPublish) in AdminController.cs
                await conditionallyPublish(contentItem);
    OrchardCore.Contents.Controllers.AdminController.EditAndPublishPOST(string contentItemId, string submitPublish, string returnUrl) in AdminController.cs

                return await EditPOST(contentItemId, returnUrl, stayOnSamePage, async contentItem =>

Orchard Core Version: dev branch 2020/01/14

**Comment by Skrypt** [comment]
Never tried with MySql but your migration probably failed.

**Comment by RockNHawk** [comment]
@Skrypt Thank you for your reply, I am familiar with Orchard. Where does Orchard_framework_datamigrationrecord correspond in Orcahrd Core ?

**Comment by Skrypt** [comment]
It's in the Document table of your database and it would be OrchardCore.ContentFields.Indexing.SQL.Migrations I think.

**Comment by RockNHawk** [comment]
Thank you for your detail reply, there are an  `OrchardCore.ContentFields.Migrations` item and no `OrchardCore.ContentFields.Indexing.SQL.Migrations` item, and `Version` is `null`:


        {
            "DataMigrationClass": "OrchardCore.ContentFields.Migrations",
            "Version": null
        },


and I see two error log about this :

this log appears once, it's not new log, the log date is fist day I setup the Orchard Core instance:

    2020-01-15 16:35:17.9908|Default|80000002-0003-fd00-b63f-84710c7967bb||OrchardCore.Data.Migration.DataMigrationManager|ERROR|Error while running migration version 0 for 'OrchardCore.ContentFields'. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
    ---> System.IO.IOException: The process cannot access the file 'C:\Users\x\git\OrchardCore\src\OrchardCore.Cms.Web\App_Data\Sites\Default\ContentDefinition.json' because it is being used by another process.
    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
    at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
    at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
    at System.IO.StreamWriter..ctor(String path, Boolean append)
    at System.IO.File.CreateText(String path)
    at OrchardCore.ContentManagement.FileContentDefinitionStore.SaveContentDefinitionAsync(ContentDefinitionRecord contentDefinitionRecord) in C:\Users\x\git\OrchardCore\src\OrchardCore\OrchardCore.ContentManagement\FileContentDefinitionStore.cs:line 68
    at OrchardCore.ContentManagement.ContentDefinitionManager.UpdateContentDefinitionRecord() in C:\Users\x\git\OrchardCore\src\OrchardCore\OrchardCore.ContentManagement\ContentDefinitionManager.cs:line 348
    at OrchardCore.ContentManagement.ContentDefinitionManager.StorePartDefinition(ContentPartDefinition contentPartDefinition) in C:\Users\x\git\OrchardCore\src\OrchardCore\OrchardCore.ContentManagement\ContentDefinitionManager.cs:line 132
    at OrchardCore.ContentManagement.Metadata.ContentDefinitionManagerExtensions.AlterPartDefinition(IContentDefinitionManager manager, String name, Action`1 alteration) in C:\Users\x\git\OrchardCore\src\OrchardCore\OrchardCore.ContentManagement.Abstractions\IContentDefinitionManager.cs:line 60
    at OrchardCore.ContentManagement.Metadata.ContentDefinitionManagerExtensions.MigrateFieldSettings[TField,TSettings](IContentDefinitionManager manager) in C:\Users\x\git\OrchardCore\src\OrchardCore\OrchardCore.ContentManagement.Abstractions\IContentDefinitionManager.cs:line 114
    at OrchardCore.ContentFields.Migrations.Create() in C:\Users\x\git\OrchardCore\src\OrchardCore.Modules\OrchardCore.ContentFields\Migrations.cs:line 52
    --- End of inner exception stack trace ---
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
    at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in C:\Users\x\git\OrchardCore\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 199    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
    at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in C:\Users\x\git\OrchardCore\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 199

-------

** and this log  appears multiple times **

    2020-01-15 16:42:25.4248|Default|80000056-0005-ff00-b63f-84710c7967bb||OrchardCore.Data.Migration.DataMigrationManager|ERROR|Could not run migrations automatically on 'OrchardCore.ContentFields' System.InvalidOperationException: Nullable object must have a value.
    at System.Nullable`1.get_Value()
    at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in C:\Users\x\git\OrchardCore\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 181
    at OrchardCore.Data.Migration.DataMigrationManager.UpdateAllFeaturesAsync() in C:\Users\x\git\OrchardCore\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 370    at System.Nullable`1.get_Value()
    at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in C:\Users\x\git\OrchardCore\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 181
    at OrchardCore.Data.Migration.DataMigrationManager.UpdateAllFeaturesAsync() in C:\Users\x\git\OrchardCore\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 370


** It seems the initial migration process failed, So how could I rerun a full migration ? **


here the full document JSON:

    {
        "Id": 1,
        "DataMigrations": [
            {
                "DataMigrationClass": "OrchardCore.Users.Migrations",
                "Version": 4
            },
            {
                "DataMigrationClass": "OrchardCore.Liquid.Migrations",
                "Version": 1
            },
            {
                "DataMigrationClass": "OrchardCore.ContentManagement.Records.Migrations",
                "Version": 5
            },
            {
                "DataMigrationClass": "OrchardCore.Contents.Migrations",
                "Version": 1
            },
            {
                "DataMigrationClass": "OrchardCore.Alias.Migrations",
                "Version": 1
            },
            {
                "DataMigrationClass": "OrchardCore.ContentFields.Migrations",
                "Version": null
            },
            {
                "DataMigrationClass": "OrchardCore.Deployment.Migrations",
                "Version": 1
            },
            {
                "DataMigrationClass": "OrchardCore.Widgets.Migrations",
                "Version": 1
            },
            {
                "DataMigrationClass": "OrchardCore.Flows.Migrations",
                "Version": 3
            },
            {
                "DataMigrationClass": "OrchardCore.Html.Migrations",
                "Version": 4
            },
            {
                "DataMigrationClass": "OrchardCore.Indexing.Migrations",
                "Version": 1
            },
            {
                "DataMigrationClass": "OrchardCore.Layers.Migrations",
                "Version": 1
            },
            {
                "DataMigrationClass": "OrchardCore.Lists.Migrations",
                "Version": 2
            },
            {
                "DataMigrationClass": "OrchardCore.Markdown.Migrations",
                "Version": 2
            },
            {
                "DataMigrationClass": "OrchardCore.Media.Migrations",
                "Version": 1
            },
            {
                "DataMigrationClass": "OrchardCore.Title.Migrations",
                "Version": 2
            },
            {
                "DataMigrationClass": "OrchardCore.Menu.Migrations",
                "Version": 1
            },
            {
                "DataMigrationClass": "OrchardCore.OpenId.YesSql.Migrations.OpenIdMigrations",
                "Version": 3
            },
            {
                "DataMigrationClass": "OrchardCore.Taxonomies.Migrations",
                "Version": 2
            },
            {
                "DataMigrationClass": "OrchardCore.ContentPreview.Migrations",
                "Version": 1
            }
        ]
    }

**Comment by RockNHawk** [comment]
@Skrypt

**Comment by RockNHawk** [comment]
OrchardCore.Data.Migration.DataMigrationManager|ERROR|Error while running migration version 0 for 'OrchardCore.ContentFields'. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
    ---> System.IO.IOException: The process cannot access the file 'C:\Users\x\git\OrchardCore\src\OrchardCore.Cms.Web\App_Data\Sites\Default\ContentDefinition.json' because it is being used by another process.

The `ContentDefinition.json` file locked, I also had the Table not exists problem in earlier versions, maybe It's a Orchard Core bug ?

see this issue: https://github.com/OrchardCMS/OrchardCore/issues/4938

**Comment by RockNHawk** [comment]
and in src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs, should make some modidy to avoid `OrchardCore.Data.Migration.DataMigrationManager|ERROR|Could not run migrations automatically on 'OrchardCore.ContentFields' System.InvalidOperationException: Nullable object must have a value.` error:

modify:

    var current = 0;
    if (dataMigrationRecord != null)
    {
        current = dataMigrationRecord.Version.Value;
    }

to:

    var current = 0;
    if (dataMigrationRecord != null)
    {
        current = dataMigrationRecord.Version ?? 0;
    }


and after I do the change, a new error appeared in log:

2020-02-03 14:27:03.9914|Default|80000096-0002-ff00-b63f-84710c7967bb||OrchardCore.Data.Migration.DataMigrationManager|ERROR|Error while running migration version 0 for 'OrchardCore.ContentFields'. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Specified key was too long; max key length is 3072 bytes
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Specified key was too long; max key length is 3072 bytes
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 49
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 126
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 387
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\CommandExecutor.cs:line 62
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 226
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 74
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in C:\projects\dapper\Dapper\SqlMapper.cs:line 2797
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in C:\projects\dapper\Dapper\SqlMapper.cs:line 568
   at YesSql.Sql.SchemaBuilder.Execute(IEnumerable`1 statements)
   at YesSql.Sql.SchemaBuilder.AlterTable(String name, Action`1 table)
   at OrchardCore.ContentFields.Indexing.SQL.Migrations.Create() in C:\Users\x\git\Lin.Hong\lh-backend\OrchardCoreProject\src\OrchardCore.Modules\OrchardCore.ContentFields\Indexing\SQL\Migrations.cs:line 51
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in C:\Users\x\git\Lin.Hong\lh-backend\OrchardCoreProject\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 199    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in C:\Users\x\git\Lin.Hong\lh-backend\OrchardCoreProject\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 199

**Comment by Skrypt** [comment]
Which version of Orchard Core you are on? It looks like an old version of that Migration tried to execute instead of the actual appropriate migration. If you are on latest dev it should not cause any issue. Else upgrade to latest will fix the issue.

Here from reading your comments it looks like the OrchardCore.ContentFields migration file did not execute either.

And your issue is related with an issue reported earlier about Index length which are different from one Database to an other. I believe there is a PR that has been done recently that fixes this issue. Else if you don't want to merge latest dev you can fix this issue by changing to `.WithLength(3072))` and it should work.

**Comment by RockNHawk** [comment]
Yeah, my Orchard Core Version: dev branch 2020/01/14

I have compare the lastet version's code many issue are fixed in code (except ContentDefinition.json file locked issue not sure), I will update to the latest version and make a fresh install.

Thank you very much!

**Comment by RockNHawk** [comment]
@Skrypt 

I have update dev branch to the 20120203 version, and delete the App_Data then restart IISExpress and re-install a new Orchard instance, sitll have `ContentDefinition.json` file locked issue.

The ContentField table are successfully created.

2020-02-04 10:47:56.9608|Default|80000066-0003-fe00-b63f-84710c7967bb||OrchardCore.Data.Migration.DataMigrationManager|ERROR|Error while running migration version 0 for 'OrchardCore.ContentFields'. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: The process cannot access the file 'C:\Users\x\git\Lin.Hong\lh-backend\Lin.Hong.Console.Web\App_Data\Sites\Default\ContentDefinition.json' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.CreateText(String path)
   at OrchardCore.ContentManagement.FileContentDefinitionStore.SaveContentDefinitionAsync(ContentDefinitionRecord contentDefinitionRecord) in C:\Users\x\git\Lin.Hong\lh-backend\OrchardCoreProject\src\OrchardCore\OrchardCore.ContentManagement\FileContentDefinitionStore.cs:line 68
   at OrchardCore.ContentManagement.ContentDefinitionManager.UpdateContentDefinitionRecord() in C:\Users\x\git\Lin.Hong\lh-backend\OrchardCoreProject\src\OrchardCore\OrchardCore.ContentManagement\ContentDefinitionManager.cs:line 348
   at OrchardCore.ContentManagement.ContentDefinitionManager.StorePartDefinition(ContentPartDefinition contentPartDefinition) in C:\Users\x\git\Lin.Hong\lh-backend\OrchardCoreProject\src\OrchardCore\OrchardCore.ContentManagement\ContentDefinitionManager.cs:line 132
   at OrchardCore.ContentManagement.Metadata.ContentDefinitionManagerExtensions.AlterPartDefinition(IContentDefinitionManager manager, String name, Action`1 alteration) in C:\Users\x\git\Lin.Hong\lh-backend\OrchardCoreProject\src\OrchardCore\OrchardCore.ContentManagement.Abstractions\IContentDefinitionManager.cs:line 60
   at OrchardCore.ContentManagement.Metadata.ContentDefinitionManagerExtensions.MigrateFieldSettings[TField,TSettings](IContentDefinitionManager manager) in C:\Users\x\git\Lin.Hong\lh-backend\OrchardCoreProject\src\OrchardCore\OrchardCore.ContentManagement.Abstractions\IContentDefinitionManager.cs:line 114
   at OrchardCore.ContentFields.Migrations.Create() in C:\Users\x\git\Lin.Hong\lh-backend\OrchardCoreProject\src\OrchardCore.Modules\OrchardCore.ContentFields\Migrations.cs:line 22
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in C:\Users\x\git\Lin.Hong\lh-backend\OrchardCoreProject\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 200    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in C:\Users\x\git\Lin.Hong\lh-backend\OrchardCoreProject\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 200
2020-02-04 10:49:22.3949|Default|80000023-0002-fe00-b63f-84710c7967bb||OrchardCore.Data.Migration.DataMigrationManager|ERROR|Error while running migration version 0 for 'OrchardCore.ContentFields'. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: The process cannot access the file 'C:\Users\x\git\Lin.Hong\lh-backend\Lin.Hong.Console.Web\App_Data\Sites\Default\ContentDefinition.json' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.CreateText(String path)
   at OrchardCore.ContentManagement.FileContentDefinitionStore.SaveContentDefinitionAsync(ContentDefinitionRecord contentDefinitionRecord) in C:\Users\x\git\Lin.Hong\lh-backend\OrchardCoreProject\src\OrchardCore\OrchardCore.ContentManagement\FileContentDefinitionStore.cs:line 68
   at OrchardCore.ContentManagement.ContentDefinitionManager.UpdateContentDefinitionRecord() in C:\Users\x\git\Lin.Hong\lh-backend\OrchardCoreProject\src\OrchardCore\OrchardCore.ContentManagement\ContentDefinitionManager.cs:line 348
   at OrchardCore.ContentManagement.ContentDefinitionManager.StorePartDefinition(ContentPartDefinition contentPartDefinition) in C:\Users\x\git\Lin.Hong\lh-backend\OrchardCoreProject\src\OrchardCore\OrchardCore.ContentManagement\ContentDefinitionManager.cs:line 132
   at OrchardCore.ContentManagement.Metadata.ContentDefinitionManagerExtensions.AlterPartDefinition(IContentDefinitionManager manager, String name, Action`1 alteration) in C:\Users\x\git\Lin.Hong\lh-backend\OrchardCoreProject\src\OrchardCore\OrchardCore.ContentManagement.Abstractions\IContentDefinitionManager.cs:line 60
   at OrchardCore.ContentManagement.Metadata.ContentDefinitionManagerExtensions.MigrateFieldSettings[TField,TSettings](IContentDefinitionManager manager) in C:\Users\x\git\Lin.Hong\lh-backend\OrchardCoreProject\src\OrchardCore\OrchardCore.ContentManagement.Abstractions\IContentDefinitionManager.cs:line 114
   at OrchardCore.ContentFields.Migrations.Create() in C:\Users\x\git\Lin.Hong\lh-backend\OrchardCoreProject\src\OrchardCore.Modules\OrchardCore.ContentFields\Migrations.cs:line 41
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in C:\Users\x\git\Lin.Hong\lh-backend\OrchardCoreProject\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 200    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in C:\Users\x\git\Lin.Hong\lh-backend\OrchardCoreProject\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 200

**Comment by RockNHawk** [comment]
Here are the DataMigrationRecord Document:

       {
            "DataMigrationClass": "OrchardCore.ContentFields.Migrations",
            "Version": null
        },
        {
            "DataMigrationClass": "OrchardCore.ContentFields.Indexing.SQL.Migrations",
            "Version": 2
        }
