### ISSUE TITLE
Workflow NullReferenceException in Contact Us form workflow

### ISSUE THREAD

**Issue by OrchardSkills** [OrchardCMS/OrchardCore#5623]
Was working in previous versions of Orchard Core

version 1.0.0-rc1-12064

2020-02-23 14:51:12.1955|Default|0HLTOK9FJTDQK:000000E5||OrchardCore.Workflows.Services.WorkflowManager|ERROR|An unhandled error occurred while executing an activity. Workflow ID: '20'. Activity: '47j30tb53gecc2yqewbx3x8pn4', 'EmailTask'. Putting the workflow in the faulted state. System.NullReferenceException: Object reference not set to an instance of an object.
   at OrchardCore.Email.Workflows.Activities.EmailTask.ExecuteAsync(WorkflowExecutionContext workflowContext, ActivityContext activityContext) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Email\Workflows\Activities\EmailTask.cs:line 83
   at OrchardCore.Workflows.Services.WorkflowManager.ExecuteWorkflowAsync(WorkflowExecutionContext workflowContext, ActivityRecord activity) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Workflows\Services\WorkflowManager.cs:line 312    at OrchardCore.Email.Workflows.Activities.EmailTask.ExecuteAsync(WorkflowExecutionContext workflowContext, ActivityContext activityContext) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Email\Workflows\Activities\EmailTask.cs:line 83
   at OrchardCore.Workflows.Services.WorkflowManager.ExecuteWorkflowAsync(WorkflowExecutionContext workflowContext, ActivityRecord activity) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Workflows\Services\WorkflowManager.cs:line 312

**Comment by Skrypt** [comment]
Line 83 of EmailTask.cs is 

```
            var message = new MailMessage
            {
                From = author.Trim(),
                To = recipients.Trim(),
                Subject = subject.Trim(),
                Body = body?.Trim(),
                IsBodyHtml = IsBodyHtml
            };
```

So your issue is a NRE (System.NullReferenceException: Object reference not set to an instance of an object.) which means one of these values is returning a NULL value from the Workflow. Maybe something has changed.

**Comment by jtkech** [comment]
`From = author.Trim()` has been added recently https://github.com/OrchardCMS/OrchardCore/commit/a06418561ab5a56f62ad983e4da266aeb011d679

There is a new `Author` property

**Comment by Skrypt** [comment]
Isn't that supposed to be the "sender" from the EmailActivity?

**Comment by jtkech** [comment]
I don't know, just saw that there is a new `Author` property that is evaluated

So maybe the `EmailTask` would need to be re-edited to provide a valid expression for the author

**Comment by petedavis** [comment]
Yeah we hit the same issue. A new Author property that allows the From and Sender to be separated. However, the edit view doesnt allow editing the Author field, so is always null and boom.

I'll do a quick PR

**Comment by hishamco** [comment]
> I don't know, just saw that there is a new Author property that is evaluated

I just added this in my latest PR, there's a distinction between the author of the email and the sender of the email, because the email can authored by someone and sent by another one, but usually the author and the sender are same

Thanks @petedavis for the PR, seems I miss something in the Workflow side

**Comment by petedavis** [comment]
No worrries @hishamco 

I have also made it backwards compatible for older instances and will reuse the sender value if the Author expression is not defined.
