### ISSUE TITLE
Better support for transient SQL Exceptions

### ISSUE THREAD

**Issue by jasonchester** [OrchardCMS/OrchardCore#5656]
I am getting the error below when running in a linux container in kubernetes against an MSSQL Azure DB instance.

```json
      "Message": "Server provided routing information, but timeout already expired.",
      "Source": "Core Microsoft SqlClient Data Provider",
 ```

This error is occurring during startup and causes the orchard tenant to become unavailable and require a restart of the orchard application. Multiple restarts are usually required to resolve this issue.

The following SO issue appears relevant: https://stackoverflow.com/questions/54186894/getting-transient-errors-when-making-calls-against-azure-sql-database-from-azure

It suggests the EF context be configured to retry on error.

```csharp
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    optionsBuilder
        .UseSqlServer("<connection string>", options => options.EnableRetryOnFailure());
}
```

Looking at the orchard code base you should be able to add the retry in OrchardCore.Data
https://github.com/OrchardCMS/OrchardCore/blob/77b12d612c5d51173db4bb950aaed2037b5777d4/src/OrchardCore/OrchardCore.Data/OrchardCoreBuilderExtensions.cs#L57-L63

Full Error
```json
{
  "@timestamp": "2020-03-02T14:24:42.1149974+00:00",
  "level": "Error",
  "messageTemplate": "Connection id \"{ConnectionId}\", Request id \"{TraceIdentifier}\": An unhandled exception was thrown by the application.",
  "message": "Connection id \"\"0HLTUMLJU7LLF\"\", Request id \"\"0HLTUMLJU7LLF:00000001\"\": An unhandled exception was thrown by the application.",
  "exceptions": [
    {
      "Depth": 0,
      "ClassName": "Microsoft.Data.SqlClient.SqlException",
      "Message": "Server provided routing information, but timeout already expired.",
      "Source": "Core Microsoft SqlClient Data Provider",
      "StackTraceString": "   at Microsoft.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod(Exception e)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at YesSql.Store.InitializeAsync()
   at YesSql.StoreFactory.CreateAsync(IConfiguration configuration)
   at Microsoft.Extensions.DependencyInjection.OrchardCoreBuilderExtensions.<>c.<AddDataAccess>b__0_1(IServiceProvider sp) in C:\\projects\\orchardcore\\src\\OrchardCore\\OrchardCore.Data\\OrchardCoreBuilderExtensions.cs:line 89
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.OrchardCoreBuilderExtensions.<>c.<AddDataAccess>b__0_2(IServiceProvider sp) in C:\\projects\\orchardcore\\src\\OrchardCore\\OrchardCore.Data\\OrchardCoreBuilderExtensions.cs:line 99
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitNoCache(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at OrchardCore.Environment.Shell.Builders.ShellContextFactory.OrchardCore.Environment.Shell.Builders.IShellContextFactory.CreateShellContextAsync(ShellSettings settings) in C:\\projects\\orchardcore\\src\\OrchardCore\\OrchardCore\\Environment\\Shell\\Builders\\ShellContextFactory.cs:line 41
   at OrchardCore.Environment.Shell.ShellHost.GetOrCreateShellContextAsync(ShellSettings settings) in C:\\projects\\orchardcore\\src\\OrchardCore\\OrchardCore\\Environment\\Shell\\ShellHost.cs:line 87
   at OrchardCore.Environment.Shell.ShellHost.PreCreateAndRegisterShellsAsync() in C:\\projects\\orchardcore\\src\\OrchardCore\\OrchardCore\\Environment\\Shell\\ShellHost.cs:line 179
   at OrchardCore.Environment.Shell.ShellHost.InitializeAsync() in C:\\projects\\orchardcore\\src\\OrchardCore\\OrchardCore\\Environment\\Shell\\ShellHost.cs:line 60
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\\projects\\orchardcore\\src\\OrchardCore\\OrchardCore\\Modules\\ModularTenantContainerMiddleware.cs:line 33
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)",
      "RemoteStackTraceString": null,
      "RemoteStackIndex": 0,
      "HResult": -2146232060,
      "HelpURL": null
    }
  ],
  "fields": {
    "ConnectionId": "0HLTUMLJU7LLF",
    "TraceIdentifier": "0HLTUMLJU7LLF:00000001",
    "EventId": {
      "Id": 13,
      "Name": "ApplicationError"
    },
    "SourceContext": "Microsoft.AspNetCore.Server.Kestrel",
    "RequestId": "0HLTUMLJU7LLF:00000001",
    "RequestPath": "/",
    "SpanId": "|b7588471-4fce4142f91f04f9.",
    "TraceId": "b7588471-4fce4142f91f04f9",
    "ParentId": ""
  }
}
```

**Comment by sebastienros** [comment]
The retry logic should be already baked in the ADO.NET driver I think.

If we need to add some retry logic, at least for the connection, then we should do it in yessql.

EF code for reference: https://github.com/dotnet/efcore/blob/7aa0e2c6552a6c4e38753cf6d7c1f2d91076a650/src/EFCore.SqlServer/SqlServerRetryingExecutionStrategy.cs

**Comment by carlwoodhouse** [comment]
you can just configure transient settings in your db connection string; as said above then ado.net will handle it.

**Comment by sebastienros** [comment]
@jasonchester can you check that the connection string parameters will solve this?
