### ISSUE TITLE
Error using _Layout.cshtml in a custom module

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#5667]
My custom module uses a page and when I try to access, I got

```
InvalidOperationException: The following sections have been defined but have not been rendered by the page at '/Areas/My.Theme.Bootstrap/Pages/Shared/_Layout.cshtml': 'Header'. To ignore an unrendered section call IgnoreSection("sectionName").
```
Although I have this statement already at my theme

![section](https://user-images.githubusercontent.com/1761249/75856457-10e87400-5dfd-11ea-9015-4ea37053f6fa.png)

![theme](https://user-images.githubusercontent.com/1761249/75856557-42f9d600-5dfd-11ea-8dd8-971abc6cc6e9.png)

This is where my view is located within the theme.

**Comment by dodyg** [comment]
My `_ViewImports.cshtml` has

```

@inherits OrchardCore.DisplayManagement.Razor.RazorPage<TModel>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, OrchardCore.DisplayManagement
@addTagHelper *, OrchardCore.ResourceManagement
@addTagHelper *, OrchardCore.Menu


```

**Comment by dodyg** [comment]
Full stack is 

```
System.InvalidOperationException: The following sections have been defined but have not been rendered by the page at '/Pages/Shared/_Layout.cshtml': 'Header'. To ignore an unrendered section call IgnoreSection("sectionName").
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.EnsureRenderedBodyOrSections()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Diagnostics\DiagnosticsStartupFilter.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at OrchardCore.ContentPreview.PreviewStartupFilter.<>c.<<Configure>b__1_1>d.MoveNext() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.ContentPreview\PreviewStartupFilter.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 207
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 59
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by dodyg** [comment]
It's exactly this case I think https://github.com/OrchardCMS/OrchardCore/issues/2673

**Comment by ns8482e** [comment]
It seems improvements made to  [RazorPage.cs](https://github.com/OrchardCMS/OrchardCore/blob/63f466c8814cd74969f41b51960a47594dfa67bf/src/OrchardCore/OrchardCore.DisplayManagement/Razor/RazorPage.cs#L250) also require to apply on Page.cs

**Comment by ns8482e** [comment]
Are using your own _layout not orchard’s precompiled ?

**Comment by sebastienros** [comment]
Could this be fixed by https://github.com/OrchardCMS/OrchardCore/pull/5651 that was merged a day ago ?

**Comment by ns8482e** [comment]
I guess this is same as #5576 ?

**Comment by LRathje** [comment]
If you use MVC views in a module this problem still exist.
You can place a RenderSection in the _Layout.cshtml and a section definition in a cshtml viewpage. The definition is recognized, but the rendersection does not pick it up and you get the exact same error message as @dodyg mentioned above like:
`The following sections have been defined but have not been rendered by the page at '/Areas/...../Views/Shared/_Layout.cshtml': 'Menu'. To ignore an unrendered section call IgnoreSection("sectionName"). `
Please observe this is not for page, but for mvc views..

**Comment by sebastienros** [comment]
@LRathje I would suggest your start a new issue with your own repro steps focusing on views. That will give it more visibility.

**Comment by LRathje** [comment]
Thanks - I will :)
