### ISSUE TITLE
 antiforgery issue

### ISSUE THREAD

**Issue by roballred** [OrchardCMS/OrchardCore#5880]
I downloaded the latest from the dev branch. Setup as SAAS in azure using sql. That worked just fine. Added a tenant but the set up screen never posted. 

Downloaded latest docker, did the same setup (Sql server, SAAS, then added tenant) and it all worked. 
Browsers are the latest from Firefox developer and Chrome
Hope this helps.

 from the logs:
`2020-04-06 16:48:37.9411|ThemeTester|80000765-0000-da00-b63f-84710c7967bb||Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery|ERROR|An exception was thrown while deserializing the token. Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {dd99c97a-563a-4be2-bca8-c69ce495ae36} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)    at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
`

**Comment by roballred** [comment]
works in IE 11

**Comment by sebastienros** [comment]
Can anyone repro with Chrome also? Specific chrome version?

**Comment by roballred** [comment]
Chrome Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by deanmarcussen** [comment]
The error from your logs suggest that it did not find the `DataProtectionKey`.

These are normally stored in `App_Data\Sites\tenant_name\DataProtection-Keys`

Can you check that the `key-dd99c97a-563a-4be2-bca8-c69ce495ae36` exists?

It should probably be in the `Sites\Default` folder.

Also can you confirm if you are using http or https? and if you have any chrome console errors related to SameSite cookie options.

I can't repro. 
Tenant creation works fine for me, standard Windows Azure WebApp

**Comment by roballred** [comment]
the key does exist and is as follows:
key id="392ccb96-1b28-4053-bc87-b1e2e4cc4fcc"

The azure sites default to https, which is what I have been using.

Just did it again, got a 400 error on chrome, logged in and did the same thing in IE and it worked.

weird stuff.

**Comment by sebastienros** [comment]
Nobody has been able to repro so far. Can you share a step by step repro? or some recording. Thanks

**Comment by roballred** [comment]
I did a pull of the latest code today and it works now.
