### ISSUE TITLE
Content Types settings lost

### ISSUE THREAD

**Issue by RajasekarPR** [OrchardCMS/OrchardCore#6030]
Hi @sebastienros , @deanmarcussen 

Migrated my application from .netcore 2.2 to .netcore 3.1 and referenced the below orchard core nuget package.

version : 1.0.0-rc1-12916

Before upgrading, created PromoBanner content type with Securable as true, Versionable as true, Draftable as true and Stereotype as Widget.

Screenshot :

![image](https://user-images.githubusercontent.com/39621436/80178423-cb397200-861b-11ea-842f-fe85135d33cb.png)

After upgrading , those field values missed in orchard core admin end.

Screenshot  

![image](https://user-images.githubusercontent.com/39621436/80177867-895bfc00-861a-11ea-9e50-76f0812c9499.png)

Kindly do the needful.

**Comment by Skrypt** [comment]
//cc @deanmarcussen Could this be because the migration did not trigger?

**Comment by deanmarcussen** [comment]
Yes, this has likely happened because of a migration which should run to convert the settings from the old design, to the new design.

We have seen that sometimes another migration can fail, which then causes this migration to not run.

I would check your logs @RajasekarPR for any failed migrations.
The log error if it exists will occur on startup, so worth restarting your site.

**Comment by RajasekarPR** [comment]
@sebastienros @deanmarcussen 

Just written the migration, that solved the issue. But getting the below while publishing the content item

kindly do the needful.

![image](https://user-images.githubusercontent.com/39621436/80481840-d6b8d000-8970-11ea-8dee-2d2b7029e803.png)

**Comment by deanmarcussen** [comment]
> I would check your logs @RajasekarPR for any failed migrations.

You must have a migration that is failing, because the error above indicates that the most recent `Autoroute` migration failed.

Please can you check your logs as you should have some sql errors indicating why that migration is failing.

Please post logs, and provide information about what sql database you are running.

**Comment by RajasekarPR** [comment]
@deanmarcussen 

Got below log :

2020-04-28 17:56:59.7635|Default|00-2cab48115b5a284db372e5f848d1995a-01253f490fc7a44d-00||OrchardCore.Data.Migration.DataMigrationManager|INFO|Applying migration for 'OrchardCore.Contents' from version 3. 
2020-04-28 17:56:59.9521|Default|00-2cab48115b5a284db372e5f848d1995a-01253f490fc7a44d-00||OrchardCore.Data.Migration.DataMigrationManager|ERROR|Error while running migration version 3 for 'OrchardCore.Contents'. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Content part name contains invalid characters (Parameter 'name')
   at OrchardCore.ContentManagement.Metadata.Builders.ContentTypeDefinitionBuilder.PartConfigurerImpl.Build() in C:\projects\orchardcore\src\OrchardCore\OrchardCore.ContentManagement.Abstractions\Metadata\Builders\ContentTypeDefinitionBuilder.cs:line 180
   at OrchardCore.ContentManagement.Metadata.Builders.ContentTypeDefinitionBuilder.WithPart(String name, ContentPartDefinition partDefinition, Action`1 configuration) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.ContentManagement.Abstractions\Metadata\Builders\ContentTypeDefinitionBuilder.cs:line 154
   at OrchardCore.ContentManagement.Records.Migrations.<>c__DisplayClass5_0.<UpdateFrom3>b__0(ContentTypeDefinitionBuilder builder) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.ContentManagement\Records\Migrations.cs:line 95
   at OrchardCore.ContentManagement.Metadata.ContentDefinitionManagerExtensions.AlterTypeDefinition(IContentDefinitionManager manager, String name, Action`1 alteration) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.ContentManagement.Abstractions\IContentDefinitionManager.cs:line 53
   at OrchardCore.ContentManagement.Records.Migrations.UpdateFrom3() in C:\projects\orchardcore\src\OrchardCore\OrchardCore.ContentManagement\Records\Migrations.cs:line 79
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 228    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 228
2020-04-28 17:56:59.9836|Default|00-2cab48115b5a284db372e5f848d1995a-01253f490fc7a44d-00||OrchardCore.Data.Migration.DataMigrationManager|INFO|Updating feature 'OrchardCore.Autoroute' 
2020-04-28 17:56:59.9836|Default|00-2cab48115b5a284db372e5f848d1995a-01253f490fc7a44d-00||OrchardCore.Data.Migration.DataMigrationManager|INFO|Updating feature 'OrchardCore.ContentTypes' 
2020-04-28 17:56:59.9836|Default|00-2cab48115b5a284db372e5f848d1995a-01253f490fc7a44d-00||OrchardCore.Data.Migration.DataMigrationManager|INFO|Applying migration for 'OrchardCore.Autoroute' from version 1. 
2020-04-28 17:57:00.0074|Default|00-2cab48115b5a284db372e5f848d1995a-01253f490fc7a44d-00||OrchardCore.Data.Migration.DataMigrationManager|ERROR|Error while running migration version 1 for 'OrchardCore.Autoroute'. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Content type name contains invalid characters (Parameter 'name')
   at OrchardCore.ContentManagement.Metadata.Builders.ContentTypeDefinitionBuilder.Build() in C:\projects\orchardcore\src\OrchardCore\OrchardCore.ContentManagement.Abstractions\Metadata\Builders\ContentTypeDefinitionBuilder.cs:line 52
   at OrchardCore.ContentManagement.Metadata.ContentDefinitionManagerExtensions.AlterTypeDefinition(IContentDefinitionManager manager, String name, Action`1 alteration) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.ContentManagement.Abstractions\IContentDefinitionManager.cs:line 53
   at OrchardCore.ContentManagement.Metadata.ContentDefinitionManagerExtensions.MigratePartSettings[TPart,TSettings](IContentDefinitionManager manager) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.ContentManagement.Abstractions\IContentDefinitionManager.cs:line 75
   at OrchardCore.Autoroute.Migrations.UpdateFrom1() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Autoroute\Migrations.cs:line 52
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 228    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 228
2020-04-28 17:57:00.0175|Default|00-2cab48115b5a284db372e5f848d1995a-01253f490fc7a44d-00||OrchardCore.Data.Migration.DataMigrationManager|INFO|Updating feature 'OrchardCore.ContentFields' 
2020-04-28 17:57:00.0794|Default|00-2cab48115b5a284db372e5f848d1995a-01253f490fc7a44d-00||OrchardCore.Data.Migration.DataMigrationManager|ERROR|Error while running migration version 0 for 'OrchardCore.ContentFields'. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Newtonsoft.Json.JsonSerializationException: Error converting value "TextArea" to type 'OrchardCore.ContentFields.Settings.EditorOption'. Path 'Editor'.
 ---> System.ArgumentException: Requested value 'TextArea' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at OrchardCore.ContentManagement.Metadata.ContentDefinitionManagerExtensions.<>c__DisplayClass3_0`2.<MigrateFieldSettings>b__0(ContentPartDefinitionBuilder partBuilder) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.ContentManagement.Abstractions\IContentDefinitionManager.cs:line 116
   at OrchardCore.ContentManagement.Metadata.ContentDefinitionManagerExtensions.AlterPartDefinition(IContentDefinitionManager manager, String name, Action`1 alteration) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.ContentManagement.Abstractions\IContentDefinitionManager.cs:line 60
   at OrchardCore.ContentManagement.Metadata.ContentDefinitionManagerExtensions.MigrateFieldSettings[TField,TSettings](IContentDefinitionManager manager) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.ContentManagement.Abstractions\IContentDefinitionManager.cs:line 112
   at OrchardCore.ContentFields.Migrations.Create() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.ContentFields\Migrations.cs:line 49
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 200    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 200
2020-04-28 17:57:00.0794|Default|00-2cab48115b5a284db372e5f848d1995a-01253f490fc7a44d-00||OrchardCore.Media.Azure.CreateMediaBlobContainerEvent|DEBUG|Testing Azure Media Storage container media existence 
2020-04-28 17:57:00.7959|Default|00-2cab48115b5a284db372e5f848d1995a-01253f490fc7a44d-00||OrchardCore.Media.Azure.CreateMediaBlobContainerEvent|DEBUG|Azure Media Storage container media created. 
2020-04-28 17:57:01.0100|Default|00-2cab48115b5a284db372e5f848d1995a-01253f490fc7a44d-00||OrchardCore.Modules.ModularTenantRouterMiddleware|INFO|Begin Routing Request

**Comment by deanmarcussen** [comment]
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.ArgumentException: Content part name contains invalid characters (Parameter 'name')

Here is why the migration is failing (which causes every subsequent migration to fail)

You have a part with an invalid character in the name, which is now failing the `ToSafeName` test.

You will need to adjust that part name in your `ContentDefinition.json` (and possibly content items that are using it)

**Comment by RajasekarPR** [comment]
@deanmarcussen Previously we have created a part name with spaces like 'Custom Pages', so the migration fails.

Is there any method to Rename the content part name or content type name ?

If not, we have to remove the existing things and have to create from scratch ?

**Comment by deanmarcussen** [comment]
> Is there any method to Rename the content part name or content type name ?

You would have to manually edit your `ContentDefinition.json` file, or the database record for the same.

> If not, we have to remove the existing things and have to create from scratch ?

Once you have the content definition updated, the content items should work, but they will have lost the values for that part. So you would either need to create from scratch, or manually edit these content item records in the `Document` table, adjusting the json key for the part name to the new part name (with no spaces)

**Comment by RajasekarPR** [comment]
@deanmarcussen Done it through database update. Works fine now. Thanks dean.
