### ISSUE TITLE
Using a MenuItem stereotype content type with one or more content parts results in "Shape type 'MenuItem_SummaryAdmin' not found"

### ISSUE THREAD

**Issue by jaketyb** [OrchardCMS/OrchardCore#6173]
## Description

Attaching content parts to MenuItem stereotype content types will cause an exception.
This functionality is desired because it allows us to attach additional functionality/fields to MenuItem content types.

## Steps to reproduce
1. Create a content part with 1 or more fields, e.g. text.
2. Create a content type with the 'MenuItem' stereotype.
3. Add the content part created in step 1 to the content type definition.
4. Create a new content item from the content type.
5. Browsing the content items will result in the following error:

```
System.Exception: Shape type 'MenuItem_SummaryAdmin' not found
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context)
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 173
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at AspNetCore._Areas_OrchardCore_Contents_Views_Admin_List.ExecuteAsync() in /Areas/OrchardCore.Contents/Views/Admin/List.cshtml:line 117
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Epitomy.WebShop.Runtime.WebShopProfileRedirectMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\Users\barronj\Documents\Workspaces\Sodium\src\dev\beta\OrchardCore\Modules\Epitomy.WebShop\Runtime\WebShopProfileRedirectMiddleware.cs:line 24
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Epitomy.WebShop.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext() in C:\Users\barronj\Documents\Workspaces\Sodium\src\dev\beta\OrchardCore\Modules\Epitomy.WebShop\Diagnostics\DiagnosticsStartupFilter.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 82
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 101
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 59
   at Epitomy.WebShop.Runtime.YesSqlTransactionRollbackMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next) in C:\Users\barronj\Documents\Workspaces\Sodium\src\dev\beta\OrchardCore\Modules\Epitomy.WebShop\Runtime\YesSqlTransactionRollbackMiddleware.cs:line 29
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

## Current workaround

We just create a `MenuItem.SummaryAdmin.cshtml` template which makes use of the existing `Content.SummaryAdmin.cshtml` template, e.g.:

```
@{
	var shape = await New.Content_SummaryAdmin();
	shape.ContentItem = Model.ContentItem;
	shape.Actions = Model.Actions;
	shape.Header = Model.Header;
	shape.Meta = Model.Meta;
	shape.Content = Model.Content;
}

@await DisplayAsync(shape)
```

**Comment by sebastienros** [comment]
Can someone repro the issue and explain why it then tries to find this shape?

**Comment by jtkech** [comment]
There is a simple way to repro

- In the already existing `Link Menu Item` type definition, check `Creatable` and `Listable`

- Then create a `Link Menu Item` and go to the Admin Content Items page

- Then it searchs for a `MenuItem_SummaryAdmin` shape because the stereotype is `MenuItem` and the display type `SummaryAdmin`

Unchecking `Creatable` and `Listable` in the custom `MenuItem` type fixes the first issue, but then when editing the main menu it fails after trying to find the `ContentPart_Thumbnail` shape.

    Exception: Shape type 'ContentPart_Thumbnail' not found

**Comment by arkadiuszwojcik** [comment]
Probably same issue as in: #4237
