### ISSUE TITLE
Autoroute UpdateFrom3 migration error

### ISSUE THREAD

**Issue by vesko-k** [OrchardCMS/OrchardCore#6210]
Latest from "dev" branch:
2020-05-18 18:00:44.7041|Default||2030f2fc-419987d8858f32d1.||OrchardCore.Data.Migration.DataMigrationManager|ERROR|Error while running migration version 3 for 'OrchardCore.Autoroute'. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'if'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in C:\projects\dapper\Dapper\SqlMapper.cs:line 2797
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in C:\projects\dapper\Dapper\SqlMapper.cs:line 568
   at YesSql.Sql.SchemaBuilder.Execute(IEnumerable`1 statements)
   at YesSql.Sql.SchemaBuilder.AlterTable(String name, Action`1 table)
   at OrchardCore.Autoroute.Migrations.UpdateFrom3() in D:\Projects\SmartWebCore\OrchardCore\src\OrchardCore.Modules\OrchardCore.Autoroute\Migrations.cs:line 80
ClientConnectionId:e8d181af-65b1-469b-822f-f5c6d7072407
Error Number:156,State:1,Class:15
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in D:\Projects\SmartWebCore\OrchardCore\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 228    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in D:\Projects\SmartWebCore\OrchardCore\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 228

**Comment by jtkech** [comment]
Which database and version?

I can repro with sql server 2014, the offending command being

    "drop index if exists [IDX_AutoroutePartIndex_ContentItemId]"

The DROP IF EXISTS syntax was introduced in SQL Server 2016, see [this related comment](https://github.com/microsoft/sql-server-samples/issues/351#issuecomment-354833638)

**Comment by vesko-k** [comment]
Yes MSSQL Server is 2012. I was wondering if the problem exists in other databases, MySql, SqLite or PostgreSQL.

**Comment by jtkech** [comment]
> Yes MSSQL Server is 2012. I was wondering if the problem exists in other databases

A least it works with sqlite, didn't try it with others

> There is no min requirements page in the docu, i think it should be

I think it is because drop index was never used before, it is now used for autoroute migrations, but you're right should be in the doc

> If the only incompatibility with older versions of SQL server is DROP INDEX IF EXISTS, that should be avoided, i think.

@sebastienros do we have to check that MSSQL Server <= 2014 and then apply e.g. the workaround [described here](https://github.com/microsoft/sql-server-samples/issues/351#issuecomment-354833638), or just say in the doc that MSSQL Server > 2014 is required.

**Comment by vesko-k** [comment]
If the problem is just in DDL, it is ridiculous to be the only reason to use SQL Server > 2014. But if other features that exists in only SQL Server > 2014 and are manadatory, then it is reasonable to be described as minimum requirement. In other case, the DDL must be re-written to be compatible. That's my thoughts.

**Comment by deanmarcussen** [comment]
Are you running SQL Server 2012 in production or for development?

Agree it should be in the docs as well.

It's not just the `DROP INDEX` that we want a higher version of SQL for.

The Index Key Lengths on the older version are also to small for some of the max lengths we use on the `AliasPart` alias lengths, and the Content Fields Indexes.

This results in warnings on earlier versions, and exceptions when you try to go over the key length limits.

I'm not sure if there are other issues we would encounter with other features, these are just the two I'm aware of.

**Comment by vesko-k** [comment]
It's development environment. What about other databases SQ Lite, PostgreSQL, MySQL. If we expect compatibility issues then it's questionable why to add providers for them?

**Comment by PiemP** [comment]
Hi guys, 

I have the same problem. How can I solve it? I have to manually drop the index?
Thank you.

**Comment by vesko-k** [comment]
Even you manually drop the index, the migration will not pass, because the version of the migration record will still show that an update is needed. In theory you may do migrations manually and manually update the migration record for the autoroute, but it's risky and I don't recommend that approach.

**Comment by PiemP** [comment]
I believe (**not sure**) to have solved the issue by manually dropping the index **IDX_AutoroutePartIndex_Published** and **IDX_AutoroutePartIndex_ContentItemId** , editing the source code and comment this lines in the `Migration.cs` file of the `OrchardCore.Autoroute` module:
```
// This code can be removed in a later version.
        public int UpdateFrom3()
        {
            SchemaBuilder.AlterTable(nameof(AutoroutePartIndex), table => table
                .AddColumn<string>("ContainedContentItemId", c => c.WithLength(26))
            );

            SchemaBuilder.AlterTable(nameof(AutoroutePartIndex), table => table
                .AddColumn<string>("JsonPath", c => c.Unlimited())
            );

            SchemaBuilder.AlterTable(nameof(AutoroutePartIndex), table => table
                .AddColumn<bool>("Latest", c => c.WithDefault(false))
            );
           
           //HERE
            /*SchemaBuilder.AlterTable(nameof(AutoroutePartIndex), table => table
                .DropIndex("IDX_AutoroutePartIndex_ContentItemId")
            );*/

            SchemaBuilder.AlterTable(nameof(AutoroutePartIndex), table => table
                .CreateIndex("IDX_AutoroutePartIndex_ContentItemIds", "ContentItemId", "ContainedContentItemId")
            );

           //AND HERE
            /*SchemaBuilder.AlterTable(nameof(AutoroutePartIndex), table => table
                .DropIndex("IDX_AutoroutePartIndex_Published")
            );*/

            SchemaBuilder.AlterTable(nameof(AutoroutePartIndex), table => table
                .CreateIndex("IDX_AutoroutePartIndex_State", "Published", "Latest")
            );

            return 4;
        }
```

**Comment by szilardcsere89** [comment]
That worked for me:
1. Create a new site installation with a new database
2. Enable autoroute (if it weren't)
3. Compare the indexes and columns in the table with the existing one (`AutoroutePartIndex`)
4. Make all the changes that are required
5. Don't forget to update the `version` in the corresponding record of the Document table (not in the column but JSON, see the image below) (usually, the first record where type = `OrchardCore.Data.Migration.Records.DataMigrationRecord, OrchardCore.Data`)
![image](https://user-images.githubusercontent.com/5823033/83874270-8124cf80-a735-11ea-893b-6ae3f54957e0.png)
