### ISSUE TITLE
MapIndex type variable could not be bound in session QueryIndex/Query method

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/OrchardCore#6270]
Below is my MapIndex type
```
public class PddOrderPartIndex:MapIndex
    {
        public string ContentItemId { get; set; }
        public string PddOrderId { get; set; }
        public bool IsSyncToPdd { get; set; }
        //public bool IsDelivery { get; set; }
    }

    public class PddOrderPartIndexProvider : IndexProvider<ContentItem>
    {
        public override void Describe(DescribeContext<ContentItem> context)
        {
            context.For<PddOrderPartIndex>().Map(item => {
                var part = item.As<PddOrderPart>();
                return new PddOrderPartIndex()
                {
                    PddOrderId = part.PinDuoDuoId,
                    IsSyncToPdd = part.IsSyncToPdd,
                    ContentItemId = part.ContentItem.ContentItemId
                };
            });
        }
    }
```
And the index provider is added to IoC in the module startup class
```
public override void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<IIndexProvider, PddOrderPartIndexProvider>();
            services.AddScoped<PddOrderPartIndex>();
        }
```
But when I query the index using Session with QueryIndex method, OrchardCore throw below exception to me:
```
An unhandled exception has occurred while executing the request.
System.InvalidOperationException: variable 'pddOrderIndex' of type 'Kongbao.Pdd.Indexes.PddOrderPartIndex' referenced from scope '', but it is not defined
   at System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(ParameterExpression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.LambdaExpression.Compile()
   at YesSql.Services.DefaultQuery.Evaluate(Expression expression)
   at YesSql.Services.DefaultQuery.Evaluate(Expression expression)
   at YesSql.Services.DefaultQuery.<Evaluate>b__12_1(Expression a)
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
   at YesSql.Services.DefaultQuery.Evaluate(Expression expression)
   at YesSql.Services.DefaultQuery.ConvertFragment(StringBuilder builder, Expression expression)
   at YesSql.Services.DefaultQuery.ConvertPredicate(StringBuilder builder, Expression expression)
   at YesSql.Services.DefaultQuery.Filter[TIndex](Expression`1 predicate)
   at YesSql.Services.DefaultQuery.QueryIndex`1.YesSql.IQueryIndex<T>.Where(Expression`1 predicate)
   at YesSql.QueryExtensions.QueryIndex[TIndex](ISession session, Expression`1 predicate)
   at Kongbao.Pdd.Services.PinDuoDuoService.ImportPddOrder(List`1 orderList, String userId, String pddAccount) in C:\Repos\kongbao\backend\Kongbao.Pdd\Services\PinDuoDuoService.cs:line 173
```

What did I missed?

**Comment by HengzheLi** [comment]
Found the issue. I used List<T>.Contains(XX) in QueryIndex which could not be convert to sql in YesSql. Use IsIn solve the issue.
