### ISSUE TITLE
Upload document in Database using CSV

### ISSUE THREAD

**Issue by MuhammadTalha10** [OrchardCMS/OrchardCore#6343]
Hi, i want to upload data in DocumentTable in Orchard core database by CSV file is there any possibility for this ? (I am using SQL Server DB)

**Comment by deanmarcussen** [comment]
The easiest option is to convert your csv file to a json `recipe` format and upload it via the admin.

See the Import/Export feature

**Comment by MuhammadTalha10** [comment]
System.IO.FileNotFoundException: Could not find file '/tmp/xd45y2ua.2qj/Recipe.json'.
File name: '/tmp/xd45y2ua.2qj/Recipe.json'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFileInfo.CreateReadStream()
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 56
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken)
   at OrchardCore.Recipes.Services.RecipeDeploymentTargetHandler.ImportFromFileAsync(IFileProvider fileProvider) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Recipes\Services\RecipeDeploymentTargetHandler.cs:line 29
   at OrchardCore.Deployment.Core.Services.DeploymentManager.ImportDeploymentPackageAsync(IFileProvider deploymentPackage) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Deployment.Core\Services\DeploymentManager.cs:line 51
   at OrchardCore.Deployment.Controllers.ImportController.Import(IFormFile importedPackage) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Deployment\Controllers\ImportController.cs:line 69
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at OrchardCore.Media.Services.MediaFileStoreResolverMiddleware.Invoke(HttpContext context) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Media\Services\MediaFileStoreResolverMiddleware.cs:line 122
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Diagnostics\DiagnosticsStartupFilter.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 83
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 103
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 61
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by MuhammadTalha10** [comment]
{
  "name": "Product upload",
  "displayName": "Product upload by json file",
  "description": "Product upload by json file to fulfil need of bulk upload",
  "author": "admin",
  "website": "https://magna.azurewebsites.net",
  "version": "2.0",
  "issetuprecipe": false,
  "categories": [ "default" ],
  "tags": [ "tag" ],
  "variables": {
    "variable1": "[js:uuid()]"
  },
  "steps": [
    {
      "name": "content",
      "Data": [
        {
          "ContentType": "Product",
          "DisplayText": "product json import",
          "Owner": null,
          "Author": "admin",
          "Product": {
            "ProductDescription": { "Text": "dcs abc" },
            "ProductCode": { "Text": "product json import" },
            "WeightPackWeight": { "Text": "3wjmk" },
            "PicturePictures": { "Paths": [ "Company/food-retouching-catagory.jpg" ] },
            "NutritionalInfo": { "Text": "ewj3eiwu" },
            "SubCatagory": {
              "TaxonomyContentItemId": "48nen8z6h8n72v5dg6ebp92snd",
              "TermContentItemIds": [ "4e7sd0gpwwmk123rc0g593a5wa" ]
            }
          },
          "TitlePart": { "Title": "product json import" },
          "SearchablePart": { "Keywords": "pro" }

        }
      ]
    }
  ]
}

**Comment by MuhammadTalha10** [comment]
@deanmarcussen  I have share my json file content i am facing this error can you please guide me!

**Comment by MuhammadTalha10** [comment]
i want to add a taxonomy part in content item products

**Comment by hishamco** [comment]
Also I think you could register a custom `ContentSerializer` for YesSQL, then you can use DI to return `IEnumerable<IContentSerializer>` and pickup the right implementation

@sebastienros correct me if this is doable

**Comment by sebastienros** [comment]
Try to look at https://github.com/dalenewman/OrchardCore.Transformalize
