### ISSUE TITLE
Exception on image resize on x64

### ISSUE THREAD

**Issue by ArieGato** [OrchardCMS/OrchardCore#6414]
Hi,

I get an exception when an image from media is resized with querystring parameters. This exception is in the logging.
```
2020-06-13 14:06:17.364 +02:00 [ERR] The image 'https://.../media/digid.png?width=100&height=100' could not be processed
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Runtime.Intrinsics.X86.Ssse3.MultiplyAddAdjacent(Vector128`1 left, Vector128`1 right)
   at SixLabors.ImageSharp.Formats.Png.PngEncoderCore.EncodePixels[TPixel](Image`1 pixels, IndexedImageFrame`1 quantized, ZlibDeflateStream deflateStream)
   at SixLabors.ImageSharp.Formats.Png.PngEncoderCore.WriteDataChunks[TPixel](Image`1 pixels, IndexedImageFrame`1 quantized, Stream stream)
   at SixLabors.ImageSharp.Formats.Png.PngEncoderCore.Encode[TPixel](Image`1 image, Stream stream)
   at SixLabors.ImageSharp.Formats.Png.PngEncoder.Encode[TPixel](Image`1 image, Stream stream)
   at SixLabors.ImageSharp.Image.EncodeVisitor.Visit[TPixel](Image`1 image)
   at SixLabors.ImageSharp.Image`1.Accept(IImageVisitor visitor)
   at SixLabors.ImageSharp.Advanced.AdvancedImageExtensions.AcceptVisitor(Image source, IImageVisitor visitor)
   at SixLabors.ImageSharp.Image.Save(Stream stream, IImageEncoder encoder)
   at SixLabors.ImageSharp.ImageExtensions.Save(Image source, Stream stream, IImageFormat format)
   at SixLabors.ImageSharp.Web.FormattedImage.Save(Stream destination)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.ProcessRequestAsync(HttpContext context, Boolean processRequest, IImageResolver sourceImageResolver, ImageContext imageContext, IDictionary`2 commands)
```
The web site is deployed on a 64 bit windows server in iis, so I guess it is caused by the X86 call. Is there something I need to configure for it to work properly?

Thnx,
Arjan

**Comment by infofromca** [comment]
can we consider other libs ?
for 1--this
2--licence in future
https://devblogs.microsoft.com/dotnet/net-core-image-processing/

**Comment by JimBobSquarePants** [comment]
@infofromca Do your research properly. 

1. License is Apache 2.0
2. System.Drawing is NOT supported by Microsoft on servers.

@hishamco Raise an issue on our repo please looks like we’re just missing a supports check.

**Comment by hishamco** [comment]
Thanks for your respond @JimBobSquarePants, I filed an issue there

**Comment by infofromca** [comment]
@JimBobSquarePants 
as I remember, thereis a plan to change that on License is Apache 2.0

**Comment by JimBobSquarePants** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.drawing?redirectedfrom=MSDN&view=dotnet-plat-ext-3.1#remarks

**Comment by antonfirsov** [comment]
One issue among many others:
On Unixes, System.Drawing is based on mono/libgdiplus, which has reliability flaws, unlikely to be fixed in the near future.

**Comment by JimBobSquarePants** [comment]
I've got a PR ready for a fix. Once merged, referencing our MyGet build will be the quickest way to get the fix.

**Comment by ArieGato** [comment]
That's very quick. I will test it as soon as I can. I also requested details on the cpu of the server where the site is hosted.

**Comment by ArieGato** [comment]
I tested the library and the exception no longer occurs. The image is resized correctly.

@JimBobSquarePants I had some trouble finding the nuget package. I had to check the build to find out that it was 1.0.0-unstable0048. The highest version is 1.0.0-unstable1162 which dates from April the 30th.

**Comment by JimBobSquarePants** [comment]
Yeah the automatic versioning tool we use is having a hiccup. I’m gonna update it today and hopefully that should fix it, otherwise I have to raise an issue upstream

**Comment by ArieGato** [comment]
I got additional information from our hosting party. The CPU is a Xeon E5-2670 V3, but it is configured in compatibility mode. So those instructions are not available.

**Comment by Piedone** [comment]
This fix should've long arrived to OC too. Please reopen if still applicable.
