### ISSUE TITLE
Error while running migration version 1 for 'OrchardCore.Menu'.

### ISSUE THREAD

**Issue by pivielti** [OrchardCMS/OrchardCore#6467]
Hi everyone,

I tried to upgrade my web app running on the version 1.0.0-rc1-10004 to version 1.0.0-rc2-13450. 

At runtime the following error append and it seems that the liquid tag is not working correctly because I can see all the html tags for all the markdown fields rendered with `{{ Model.Html | markdownify | liquid }}`.

__Error call stack :__

`fail: OrchardCore.Data.Migration.DataMigrationManager[0]
      Error while running migration version 1 for 'OrchardCore.Menu'.
System.InvalidOperationException: Unable to resolve service for type 'OrchardCore.Facebook.Login.Services.IFacebookLoginService' while attempting to activate 'OrchardCore.Facebook.Login.Recipes.FacebookLoginSettingsStep'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateEnumerable(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices[T](IServiceProvider provider)
   at OrchardCore.Recipes.Services.RecipeExecutor.<>c__DisplayClass9_0.<<ExecuteStepAsync>b__0>d.MoveNext() in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 156
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 194
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteStepAsync(RecipeExecutionContext recipeStep) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 154
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 100
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 117
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken)
   at OrchardCore.Recipes.Services.RecipeMigrator.ExecuteAsync(String recipeFileName, IDataMigration migration) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeMigrator.cs:line 41
   at OrchardCore.Menu.Migrations.UpdateFrom1Async() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Menu\Migrations.cs:line 30
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Data\Migration\DataMigrationManager.cs:line 224`

**Comment by jtkech** [comment]
@pivielti 

Okay, so there is a migration using the `RecipeMigrator` meaning it uses the `RecipeExecutor` which at one point resolves all `IRecipeStepHandler`. Regading your trace these handlers include the `FacebookLoginSettingsStep`, so you may have the `OC.Facebook` module enabled.

Then `FacebookLoginSettingsStep` failed to resolve `IFacebookLoginService` which is registered if the `OC.Facebook.Login` feature is enabled, so you may not have enabled this feature

So the workaround is to enable `OC.Facebook.Login` but there is still an issue, the `FacebookLoginSettingsStep` should not be registered with the `OC.Facebook` module main feature but only when enabling the `OC.Facebook.Login` feature

I will do a PR

**Comment by pivielti** [comment]
Thank you @jtkech, the migration has run successfully after the fix.
