### ISSUE TITLE
NullReferenceException When Displaying Blank HtmlBodyParts

### ISSUE THREAD

**Issue by thomasebsmith** [OrchardCMS/OrchardCore#6686]
When displaying a blank HtmlBodyPart while sanitizing is off, a NullReferenceException is thrown:
> System.NullReferenceException: Object reference not set to an instance of an object.
   at Shortcodes.ShortcodesProcessor.EvaluateAsync(String input)
   at OrchardCore.Html.Drivers.HtmlBodyPartDisplayDriver.BuildViewModelAsync(HtmlBodyPartViewModel model, HtmlBodyPart htmlBodyPart, HtmlBodyPartSettings settings) in orchardcore\src\OrchardCore.Modules\OrchardCore.Html\Drivers\HtmlBodyPartDisplayDriver.cs:line 91
   at OrchardCore.DisplayManagement.ShapeFactoryExtensions.<CreateAsync>g__Awaited|6_0[TModel](ValueTask task, IShape shape) in orchardcore\src\OrchardCore\OrchardCore.DisplayManagement\IShapeFactory.cs:line 80
   at OrchardCore.DisplayManagement.Implementation.DefaultShapeFactory.CreateAsync(String shapeType, Func\`1 shapeFactory, Action\`1 creating, Action\`1 created) in orchardcore\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultShapeFactory.cs:line 92
   at OrchardCore.DisplayManagement.Views.ShapeResult.ApplyImplementationAsync(BuildShapeContext context, String displayType) in orchardcore\src\OrchardCore\OrchardCore.DisplayManagement\Views\ShapeResult.cs:line 107
   at OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator.BuildDisplayAsync(ContentItem contentItem, BuildDisplayContext context) in orchardcore\src\OrchardCore\OrchardCore.ContentManagement.Display\ContentDisplay\ContentItemDisplayCoordinator.cs:line 106

### Reproducing
1. Create a new Orchard Core CMS project.
2. Start the site, and initialize it with the blog recipe.
3. Turn off HtmlBodyPart sanitizing for the article content type (Content > Content Definition > Content Types > Edit Article > HtmlBody > Sanitize HTML).
4. Edit the "About" page and delete of all its HTML, so that its HtmlBodyPart is completely empty.
5. Visit the "About" page. Notice the NullReferenceException in the debug logs.

### Possible Causes
It looks like the problem occurs because of the use of [`_liquidTemplateManager.RenderAsync`](https://github.com/OrchardCMS/OrchardCore/blob/1362bf3d06ede66a69c981fee5113e9d1433866c/src/OrchardCore.Modules/OrchardCore.Liquid/Services/LiquidTemplateManager.cs#L26) in [`HtmlBodyPartDisplayDriver.BuildViewModelAsync`](https://github.com/OrchardCMS/OrchardCore/blob/1362bf3d06ede66a69c981fee5113e9d1433866c/src/OrchardCore.Modules/OrchardCore.Html/Drivers/HtmlBodyPartDisplayDriver.cs#L79). `_liquidTemplateManager.RenderAsync` will convert an empty or whitespace HTML string into null, and this causes a NullReferenceException when processing shortcodes.

### Possible Fixes
- `_liquidTemplateManager.RenderAsync` could be changed to not return null.
- `HtmlBodyPartDisplayDriver.BuildViewModelAsync` could handle null HTML.
- [`ShortcodeService.ProcessAsync`](https://github.com/OrchardCMS/OrchardCore/blob/1362bf3d06ede66a69c981fee5113e9d1433866c/src/OrchardCore.Modules/OrchardCore.Shortcodes/Services/ShortcodeService.cs#L16) could handle null input.

**Comment by deanmarcussen** [comment]
Which version of OC are you running?

**Comment by thomasebsmith** [comment]
I tested this on rc2-13809 and rc2-13837. It seems to happen on rc2-13852 too.

**Comment by deanmarcussen** [comment]
cool thanks @thomasebsmith I can repro

**Comment by wAsnk** [comment]
As I can see this is fixed in dev.

**Comment by deanmarcussen** [comment]
Fixed by https://github.com/OrchardCMS/OrchardCore/pull/6661
