### ISSUE TITLE
When executing a Set Property Task (Workflows) the Esprima .NET is throwing the exception argument was out of range.

### ISSUE THREAD

**Issue by OrchardSkills** [OrchardCMS/OrchardCore#6787]
Found the issue.

Set Property not needed. Updated Create Content Task and read from the form. Please close the issue.

When executing a Set Property Task (Workflows) in the Esprima .NET assembly an exception argument was out of range occurs.

![image](https://user-images.githubusercontent.com/59172485/88810540-b74d6100-d172-11ea-8849-77f4bb508e94.png)

JavaScript parsing: "JSON.parse(readBody())"

![image](https://user-images.githubusercontent.com/59172485/88811682-195a9600-d174-11ea-9bae-6271cf92b9e7.png)

Edit Set Property Task

![image](https://user-images.githubusercontent.com/59172485/88811932-663e6c80-d174-11ea-9196-d9effa6f8749.png)

Content Type Subscriber

![image](https://user-images.githubusercontent.com/59172485/88812343-d947e300-d174-11ea-8eba-9d95dc909989.png)

JSON of Content Type Subscriber and Workflow Subscribe
{
  "name": "",
  "displayName": "",
  "description": "",
  "author": "",
  "website": "",
  "version": "",
  "issetuprecipe": false,
  "categories": [],
  "tags": [],
  "steps": [
    {
      "name": "ContentDefinition",
      "ContentTypes": [
        {
          "Name": "Subscriber",
          "DisplayName": "Subscriber",
          "Settings": {
            "ContentTypeSettings": {
              "Creatable": true,
              "Listable": true,
              "Draftable": true,
              "Versionable": true,
              "Securable": true
            }
          },
          "ContentTypePartDefinitionRecords": [
            {
              "PartName": "Subscriber",
              "Name": "Subscriber",
              "Settings": {}
            },
            {
              "PartName": "AutoroutePart",
              "Name": "AutoroutePart",
              "Settings": {}
            },
            {
              "PartName": "HtmlBodyPart",
              "Name": "HtmlBodyPart",
              "Settings": {}
            },
            {
              "PartName": "TitlePart",
              "Name": "TitlePart",
              "Settings": {}
            }
          ]
        }
      ],
      "ContentParts": [
        {
          "Name": "Subscriber",
          "Settings": {},
          "ContentPartFieldDefinitionRecords": [
            {
              "FieldName": "TextField",
              "Name": "FirstName",
              "Settings": {
                "ContentPartFieldSettings": {
                  "DisplayName": "FirstName"
                },
                "TextFieldSettings": {
                  "Hint": "First Name",
                  "Required": true
                },
                "ContentIndexSettings": {}
              }
            },
            {
              "FieldName": "TextField",
              "Name": "LastName",
              "Settings": {
                "ContentPartFieldSettings": {
                  "DisplayName": "LastName"
                },
                "TextFieldSettings": {
                  "Hint": "Last Name",
                  "Required": true
                },
                "ContentIndexSettings": {}
              }
            },
            {
              "FieldName": "TextField",
              "Name": "Email",
              "Settings": {
                "ContentPartFieldSettings": {
                  "DisplayName": "Email",
                  "Editor": "Email"
                },
                "TextFieldSettings": {
                  "Hint": "Email Address",
                  "Required": true
                },
                "ContentIndexSettings": {}
              }
            }
          ]
        }
      ]
    },
    {
      "name": "WorkflowType",
      "data": [
        {
          "WorkflowTypeId": "4b7psmtjxkg6y28747227zvpm5",
          "Name": "Subscribe",
          "IsEnabled": true,
          "IsSingleton": false,
          "DeleteFinishedWorkflows": false,
          "Activities": [
            {
              "ActivityId": "490ffr423ce120w4g011dy8xw8",
              "Name": "HttpRequestEvent",
              "X": 10,
              "Y": 0,
              "IsStart": true,
              "Properties": {
                "ActivityMetadata": {
                  "Title": "Subscribe Request Event"
                },
                "HttpMethod": "POST",
                "Url": "/workflows/Invoke?token=CfDJ8Mkgifjf5GZNmC3NSADOrKBj0vVHCpt66JQinMajuyceYlKDzIwX_GGI1BeKr7r2qTfXgE45OsaSjLDzyACdco5nCbBIRjPRVcledqrEayIjSc4XCtFtuB66QFRWYqm1_GJ2NzzamsuDXdVgt1APOSLPjHout-CfNs-e7cC5p1I_7TFwGvC0RW6PhRDXED7WudaMB42pAr0TIhOQzyEVDI9mEeI2-2KjHSMtK1KZPth0",
                "ValidateAntiforgeryToken": true,
                "TokenLifeSpan": 0
              }
            },
            {
              "ActivityId": "4cdnx3e1w1hv9vxwpz5zxs34cv",
              "Name": "SetPropertyTask",
              "X": 450,
              "Y": 10,
              "IsStart": false,
              "Properties": {
                "ActivityMetadata": {
                  "Title": "Subscribe"
                },
                "PropertyName": "Subscriber",
                "Value": {
                  "Expression": "JSON.parse(readBody())"
                }
              }
            },
            {
              "ActivityId": "4b2b2d7tbwsvvzbcfgrhfg76w6",
              "Name": "CreateContentTask",
              "X": 880,
              "Y": 10,
              "IsStart": false,
              "Properties": {
                "ContentType": "Subscriber",
                "Publish": true,
                "ContentProperties": {
                  "Expression": "{\r\n  \"FirstName\": {\r\n    \"Text\": \"{{ Subscriber.FirstName}}\"\r\n  },\r\n  \"LastName\": {\r\n    \"Text\": \"{{ Subscriber.LastName}}\"\r\n  },\r\n  \"Email\": {\r\n    \"Text\": \"{{ Subscriber.EMail}}\"\r\n  }\r\n}\r\n"
                },
                "ActivityMetadata": {
                  "Title": "Create Subscriber Content Task"
                }
              }
            }
          ],
          "Transitions": [
            {
              "Id": 0,
              "SourceActivityId": "490ffr423ce120w4g011dy8xw8",
              "SourceOutcomeName": "Done",
              "DestinationActivityId": "4cdnx3e1w1hv9vxwpz5zxs34cv"
            },
            {
              "Id": 0,
              "SourceActivityId": "4cdnx3e1w1hv9vxwpz5zxs34cv",
              "SourceOutcomeName": "Done",
              "DestinationActivityId": "4b2b2d7tbwsvvzbcfgrhfg76w6"
            },
            {
              "Id": 0,
              "SourceActivityId": "4b2b2d7tbwsvvzbcfgrhfg76w6",
              "SourceOutcomeName": "Failed",
              "DestinationActivityId": "4b2b2d7tbwsvvzbcfgrhfg76w6"
            }
          ]
        }
      ]
    }
  ]
}

Here are the Headers:

General:
Request URL: https://localhost:44300/workflows/Invoke?token=CfDJ8Mkgifjf5GZNmC3NSADOrKBj0vVHCpt66JQinMajuyceYlKDzIwX_GGI1BeKr7r2qTfXgE45OsaSjLDzyACdco5nCbBIRjPRVcledqrEayIjSc4XCtFtuB66QFRWYqm1_GJ2NzzamsuDXdVgt1APOSLPjHout-CfNs-e7cC5p1I_7TFwGvC0RW6PhRDXED7WudaMB42pAr0TIhOQzyEVDI9mEeI2-2KjHSMtK1KZPth0
Request Method: POST
Status Code: 202 
Remote Address: [::1]:44300
Referrer Policy: no-referrer-when-downgrade

Response Headers:
content-length: 0
date: Wed, 29 Jul 2020 15:57:17 GMT
server: Microsoft-IIS/10.0
set-cookie: .AspNetCore.Mvc.CookieTempDataProvider=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=lax; httponly
status: 202
x-powered-by: OrchardCore
x-powered-by: ASP.NET

Request Headers:
:authority: localhost:44300
:method: POST
:path: /workflows/Invoke?token=CfDJ8Mkgifjf5GZNmC3NSADOrKBj0vVHCpt66JQinMajuyceYlKDzIwX_GGI1BeKr7r2qTfXgE45OsaSjLDzyACdco5nCbBIRjPRVcledqrEayIjSc4XCtFtuB66QFRWYqm1_GJ2NzzamsuDXdVgt1APOSLPjHout-CfNs-e7cC5p1I_7TFwGvC0RW6PhRDXED7WudaMB42pAr0TIhOQzyEVDI9mEeI2-2KjHSMtK1KZPth0
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: max-age=0
content-length: 290
content-type: application/x-www-form-urlencoded
cookie: _ga=GA1.1.2006263536.1568727981; __utmz=111872281.1568841202.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utma=111872281.2006263536.1568727981.1593097776.1593101432.22; _gid=GA1.1.795784584.1595860635; orchantiforgery_DefaultC%253a%255cUsers%255cAngul%255cDocuments%255cGitHub%255cOrchardCore%255csrc%255cOrchardCore.Cms.Web=CfDJ8Mkgifjf5GZNmC3NSADOrKAEDDqxbyOO54n01fE4u1k4J1miLoh8HberKeAdbYNG0a7HOefP_ujdpZmYYargUQjgvaJaP1qHTj8MCwfVjjn4HLu0Sh0Pqri0Rg8kqDo0sPLrsesZlTYHqi2kTxTPgA0; orchauth_Default=CfDJ8Mkgifjf5GZNmC3NSADOrKANTOcM4HFhHTQoZxVh4bNMMdVKOqYMcWTRRqLjUwhhoPnr2uPQpXmbe-BWxIfNQB3m2966d_7YTaTRBbBAysRXeOuhiUiSvI_60H1GX7XiKJTFnZhGKfGx0CnzyZWRdP7D5dWUfSs0Xng1YCoPT_DGF-2s_ksOCxM6D4uPcSaPSqUOesivaYiDi_fuFP5H_UX3JDCKhzp11xIwlYT1LtPr_28cMlJynygk8TsZ3Wm-kqCF4TDR-HLVi5VlP94eZcjJnfrNYX2Nf4BUBu3qovJAFx4zQdiCWlSyNNuKEMRBrEi6WQHs4F1VL8BOcPMlh7u-QuKmR8NP9O-JbT8MJFEVWgF5giWOXoZbg1090Jy-zS-m_Y_hvkLMW2CE0ILQZgyv4483w3VjXyCUtewLgiCj5GQswRciFobUrd07T9cFFUV0Lb5VBYlcCbANnn4tRrDMYmolV06wEeKQdhpth-2OyRL2VWUpzQXonjXDmsqeu2WvA4UutKfvICtnVYdmAI4mbaeBulEcvc3oCXuRHgXju2IUdqJRJoaJe27nSZmbBCRwoYNdcvDqCfLAeUI2XGJNRFATkIFOk8EWqBMRL7KTDfP2LLhw1Sjw4bdMisFiiYQvK0lw4STmHEN7uxqfHO6dGAkL18sZI-TaavQDdkELzrXByLFZ60TuXNm5bITOEIuhKaltLX4VcaqnXySNiFY9chghsJmqQMJpTGgJAMGrU7AJdAzx-0uEQbyyUecjytpnLum39flvLL_MMFm3EHtwu_jgmCnI-BcklS02mlVH0IkyXab2696MLd8XQ-BwplsZvxebPlgHiy3ScOoGQaf5O7LkI9U4721CRIJ_ClPx8WjdtQqTwApKrPXI7XNWnm-qAhXk9v30xhhlDppuQnMzH93w_wpKyE4djY1hOhmsMQo4h9u1ZxrveoeafUCZsyJ21FQ_2JgyzjCBTEanjI_rESvPUkVQC4Y_rsWFzzVrgrq6mMXDujLGCvJJX4OGRzu-T1lycd55rt9K0cLcOoqL_lp88R5WtivkuWe5BwKVYz2-NsxvQR8myaAwMregPiRRSNfNoqigY5l2IidDPwmpM85Hlw00zCy_XsXecNvgAV_PbooWNAO_2aeo19FTfVPHhnnyBwqqcp-zFlZT9A7SA6SFZfoTZDYa44dSKXNGLdhHNJisXx1CAmrL6KBX7iFH258SXHNSpcjJ3ponx-G52_bJlxhxbhwFvUI0RVDKSbgI7aUk_NYRGrJzotLRPBi6C4HOTF7p1ERPgtNyreTNEfuHFLbSVhD4xIlPZJLFA3bh1WIexaGVqNsXRAP7nrJcneHSq1slJPFznNggvgO9ditygoXjQuo4UDWwm7kA9dV3K2odjQLOGf8toYElkMxkeQNvRk_-3urUNfwod6-qn3BPw6KGf8CbEPGgVf31CwIfaP0ZqcVGn5GdP3wwJblMjBSon7jfI5k46Hg46pXBwxWZXw2hsvTzvbk0mOnxdnofYtptMOrgRt11G3WxooJW4Q7g1zBdtIY5vJnCQI5Y_l7yCfnnTJxQ683Yv7BKO9T9SIz_05elBadlc7bwN_1n9IK446ErTK1VKbNO9-FeIkJ_F0Rz3c7923Y7-7USPFCTOBX22kOR-AwggknPzuQABNKdSHCOCXZ70UsULKXhan6hGbzIzkmR22jB82VhV_t288z0xREPYrkO8PgcS_DF2dqw-5ygGnE_XF-ghgV_893sF3VQgRORPlb34yZx9Fh-wOdckIQ1RGCa91ieZuarmsviY4_OG2qLqJVSDA0VYTJLfQ3-ZiA2mRfyyVFwbZf7wiidG0uHx5Umls65jxFnz8gRap4Rs7hhomPQ415tfEIX8_RZYOzCZt1rYSuvLRnN2MDz6p3-1gzPfWPUEmC0WkIWdPsYZSOUKaaSXZ4JZpxDxw2y28fb2E3sSPUxF5IuIDJBgUacLp7mHqpGNafayW6BPBIWWAXtk7zfBLU7eqbvb32934bDO8yAHXsVmJJszoD7CxvwQ7TpTkLYDdh2ZqKAwyRKlrXl5JMpDlD_wYiV6G9tSlGKHQHVTUFoBY4PokniBNyQ9Rl0GrRgmO-vKxqayMfWFlSSR7Zv5g-ANN0s0zBhMBIDKm_FUDtoWnQxw0IxGcur7NazrnyooGXD43cj17y7D_JbL67iiB9v6RR4QSlAsgLXDQq6vQ1wIF_PZxf3T5ecQkBNecVI3liUTm39a8ifm_OzVIM-IZQDJSKZaH5oGXQ4I2bCdJrX3UC7HFW_BF2f7_iyN1b-QXblZx5iuuDB2beZ4QE9Dg6lwjaSbTJ728lNEcrixYYm; admin_Default=-1434965894
dnt: 1
origin: https://localhost:44300
referer: https://localhost:44300/subscribe
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: same-origin
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Mobile Safari/537.36

Query String Parameters:
token: CfDJ8Mkgifjf5GZNmC3NSADOrKBj0vVHCpt66JQinMajuyceYlKDzIwX_GGI1BeKr7r2qTfXgE45OsaSjLDzyACdco5nCbBIRjPRVcledqrEayIjSc4XCtFtuB66QFRWYqm1_GJ2NzzamsuDXdVgt1APOSLPjHout-CfNs-e7cC5p1I_7TFwGvC0RW6PhRDXED7WudaMB42pAr0TIhOQzyEVDI9mEeI2-2KjHSMtK1KZPth0

Form Data:
__RequestVerificationToken: CfDJ8Mkgifjf5GZNmC3NSADOrKALhVPjE2kTGwyAcEBBJvMyMrfgXVqwsRSszER_X_4MYafksZ-7wD7Js0rSm6vNFHPbyw4R9OwFpBorj-YYLgUq7apNhVDApBFnayfysunAlRMofzlGttRtsQk75eAdWGd1Twepmfl5KdYp4cS4ITuk9lAk_nRV0iRcDUlLBcaEDg
FirstName: William
LastName: Best
Email: wpbest@gmail.com

System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Specified argument was out of the range of valid values.

2020-07-28 15:16:13.5841|Default||73ecfb9c-4c34123acffc64c9.||OrchardCore.Workflows.Services.WorkflowManager|ERROR|An unhandled error occurred while executing an activity. Workflow ID: '21'. Activity: '4cdnx3e1w1hv9vxwpz5zxs34cv', 'SetPropertyTask'. Putting the workflow in the faulted state. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'column')
Actual value was 1.
   at Esprima.Position.ThrowArgumentOutOfRangeException(String name, Int32 column)
   at Esprima.Position..ctor(Int32 line, Int32 column)
   at Jint.Native.Json.JsonParser.ThrowError(Token token, String messageFormat, Object[] arguments)
   at Jint.Native.Json.JsonParser.ThrowUnexpected(Token token)
   at Jint.Native.Json.JsonParser.ParseJsonValue()
   at Jint.Native.Json.JsonParser.Parse(String code, ParserOptions options)
   at Jint.Native.Json.JsonParser.Parse(String code)
   at Jint.Native.Json.JsonInstance.Parse(JsValue thisObject, JsValue[] arguments)
   at Jint.Runtime.Interop.ClrFunctionInstance.Call(JsValue thisObject, JsValue[] arguments)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.EvaluateInternal()
   at Jint.Runtime.Interpreter.Expressions.JintExpression.GetValue()
   at Jint.Runtime.Interpreter.Statements.JintExpressionStatement.ExecuteInternal()
   at Jint.Runtime.Interpreter.JintStatementList.Execute()
   at Jint.Engine.Execute(Program program)
   at OrchardCore.Scripting.JavaScript.JavaScriptEngine.Evaluate(IScriptingScope scope, String script) in C:\Users\Angul\Documents\GitHub\OrchardCore\src\OrchardCore\OrchardCore.Scripting.JavaScript\JavaScriptEngine.cs:line 53
   at OrchardCore.Scripting.DefaultScriptingManager.Evaluate(String directive, IFileProvider fileProvider, String basePath, IEnumerable`1 scopedMethodProviders) in C:\Users\Angul\Documents\GitHub\OrchardCore\src\OrchardCore\OrchardCore.Infrastructure\Scripting\DefaultScriptingManager.cs:line 45
   at OrchardCore.Workflows.Evaluators.JavaScriptWorkflowScriptEvaluator.EvaluateAsync[T](WorkflowExpression`1 expression, WorkflowExecutionContext workflowContext, IGlobalMethodProvider[] scopedMethodProviders) in C:\Users\Angul\Documents\GitHub\OrchardCore\src\OrchardCore.Modules\OrchardCore.Workflows\Scripting\JavaScriptWorkflowScriptEvaluator.cs:line 44
   at OrchardCore.Workflows.Activities.SetPropertyTask.ExecuteAsync(WorkflowExecutionContext workflowContext, ActivityContext activityContext) in C:\Users\Angul\Documents\GitHub\OrchardCore\src\OrchardCore.Modules\OrchardCore.Workflows\Activities\SetPropertyTask.cs:line 46
   at OrchardCore.Workflows.Services.WorkflowManager.ExecuteWorkflowAsync(WorkflowExecutionContext workflowContext, ActivityRecord activity) in C:\Users\Angul\Documents\GitHub\OrchardCore\src\OrchardCore.Modules\OrchardCore.Workflows\Services\WorkflowManager.cs:line 312    at Esprima.Position.ThrowArgumentOutOfRangeException(String name, Int32 column)
   at Esprima.Position..ctor(Int32 line, Int32 column)
   at Jint.Native.Json.JsonParser.ThrowError(Token token, String messageFormat, Object[] arguments)
   at Jint.Native.Json.JsonParser.ThrowUnexpected(Token token)
   at Jint.Native.Json.JsonParser.ParseJsonValue()
   at Jint.Native.Json.JsonParser.Parse(String code, ParserOptions options)
   at Jint.Native.Json.JsonParser.Parse(String code)
   at Jint.Native.Json.JsonInstance.Parse(JsValue thisObject, JsValue[] arguments)
   at Jint.Runtime.Interop.ClrFunctionInstance.Call(JsValue thisObject, JsValue[] arguments)
   at Jint.Runtime.Interpreter.Expressions.JintCallExpression.EvaluateInternal()
   at Jint.Runtime.Interpreter.Expressions.JintExpression.GetValue()
   at Jint.Runtime.Interpreter.Statements.JintExpressionStatement.ExecuteInternal()
   at Jint.Runtime.Interpreter.JintStatementList.Execute()
   at Jint.Engine.Execute(Program program)
   at OrchardCore.Scripting.JavaScript.JavaScriptEngine.Evaluate(IScriptingScope scope, String script) in C:\Users\Angul\Documents\GitHub\OrchardCore\src\OrchardCore\OrchardCore.Scripting.JavaScript\JavaScriptEngine.cs:line 53
   at OrchardCore.Scripting.DefaultScriptingManager.Evaluate(String directive, IFileProvider fileProvider, String basePath, IEnumerable`1 scopedMethodProviders) in C:\Users\Angul\Documents\GitHub\OrchardCore\src\OrchardCore\OrchardCore.Infrastructure\Scripting\DefaultScriptingManager.cs:line 45
   at OrchardCore.Workflows.Evaluators.JavaScriptWorkflowScriptEvaluator.EvaluateAsync[T](WorkflowExpression`1 expression, WorkflowExecutionContext workflowContext, IGlobalMethodProvider[] scopedMethodProviders) in C:\Users\Angul\Documents\GitHub\OrchardCore\src\OrchardCore.Modules\OrchardCore.Workflows\Scripting\JavaScriptWorkflowScriptEvaluator.cs:line 44
   at OrchardCore.Workflows.Activities.SetPropertyTask.ExecuteAsync(WorkflowExecutionContext workflowContext, ActivityContext activityContext) in C:\Users\Angul\Documents\GitHub\OrchardCore\src\OrchardCore.Modules\OrchardCore.Workflows\Activities\SetPropertyTask.cs:line 46
   at OrchardCore.Workflows.Services.WorkflowManager.ExecuteWorkflowAsync(WorkflowExecutionContext workflowContext, ActivityRecord activity) in C:\Users\Angul\Documents\GitHub\OrchardCore\src\OrchardCore.Modules\OrchardCore.Workflows\Services\WorkflowManager.cs:line 312

**Comment by OrchardSkills** [comment]
Found the issue.

Set Property not needed. Updated Create Content Task and read from the form.
