### ISSUE TITLE
Using the ExportModelStateAttribute with a view model containing a bool: The parameter conversion from type 'Newtonsoft.Json.Linq.JArray' to type 'System.Boolean' failed...

### ISSUE THREAD

**Issue by rjpowers10** [OrchardCMS/OrchardCore#7174]
I have a form within a content item, although I'm not using the actual "forms" feature to build the form. This is just a custom form that I designed and it so happens to be rendered within a content item.

The tricky thing is handling ModelState errors. I can't simply return a ViewResult when ModelState.IsValid is false, since I don't know how to build the view model for my content item. If I redirect I lose my ModelState. To fix the problem of losing the ModelState on redirect, I found the ExportModelStateAttribute attribute in the Forms module. This does what I want, except that it doesn't seem to work when my form contains a bool.

I have a simplified example to reproduce it

- Create a new site (I used the blog theme)
- Enable the Forms feature (To gain access to ExportModelStateAttribute)
- I added the following code to the forms module:

My controller
```
using Microsoft.AspNetCore.Mvc;
using OrchardCore.Forms.Filters;
using OrchardCore.Forms.ViewModels;

namespace OrchardCore.Forms.Controllers
{
    public class MyTestController : Controller
    {
        public IActionResult Get()
        {
            var vm = new MyViewModel();
            return View(vm);
        }

        [ExportModelState]
        public IActionResult Post(MyViewModel vm)
        {
            ModelState.AddModelError("", "This is a test");
            return RedirectToAction(nameof(Get));
        }
    }
}
```

My view model
```
namespace OrchardCore.Forms.ViewModels
{
    public class MyViewModel
    {
        public bool TestBool { get; set; }
    }
}
```

My template
```
@model OrchardCore.Forms.ViewModels.MyViewModel

<form asp-action="Post" asp-controller="MyTest" asp-area="OrchardCore.Forms" method="post">
    <input asp-for="TestBool" />
    <button type="submit">Submit</button>
</form>
```

I think I know what the problem is.

In OrchardCore.Forms.Helpers.ModelStateHelpers.cs, I can see that the RawValue of my bool is a string[].
![image](https://user-images.githubusercontent.com/68876423/94700540-9687c000-0309-11eb-82f4-50eac040945f.png)

But when it gets deserialized, it becomes a JArray
![image](https://user-images.githubusercontent.com/68876423/94700583-a6070900-0309-11eb-92c2-04178c20d27b.png)

Over in [ASP.NET's ModelBindingHelper.cs](https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Core/src/ModelBinding/ModelBindingHelper.cs), this causes a problem in model binding.

![image](https://user-images.githubusercontent.com/68876423/94701162-5117c280-030a-11eb-8368-c77332afc6b5.png)

```
System.InvalidOperationException: The parameter conversion from type 'Newtonsoft.Json.Linq.JArray' to type 'System.Boolean' failed because no type converter can convert between these types.
   at Microsoft.AspNetCore.Mvc.ModelBinding.ModelBindingHelper.ConvertSimpleType(Object value, Type destinationType, CultureInfo culture)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ModelBindingHelper.UnwrapPossibleArrayType(Object value, Type destinationType, CultureInfo culture)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ModelBindingHelper.ConvertTo(Object value, Type type, CultureInfo culture)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GetModelStateValue(ViewContext viewContext, String key, Type destinationType)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateInput(ViewContext viewContext, InputType inputType, ModelExplorer modelExplorer, String expression, Object value, Boolean useViewData, Boolean isChecked, Boolean setId, Boolean isExplicitValue, String format, IDictionary`2 htmlAttributes)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateCheckBox(ViewContext viewContext, ModelExplorer modelExplorer, String expression, Nullable`1 isChecked, Object htmlAttributes)
   at Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper.GenerateCheckBox(ModelExplorer modelExplorer, TagHelperOutput output, IDictionary`2 htmlAttributes)
   at Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper.Process(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.TagHelpers.TagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)
   at AspNetCore._Areas_OrchardCore_Forms_Views_MyTest_Get.<ExecuteAsync>b__14_0() in C:\Users\Ryan.Powers\source\repos\OrchardCore-dev\src\OrchardCore.Modules\OrchardCore.Forms\Views\MyTest\Get.cshtml:line 5
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.GetChildContentAsync(Boolean useCachedResult, HtmlEncoder encoder)
   at Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCore._Areas_OrchardCore_Forms_Views_MyTest_Get.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext() in C:\Users\Ryan.Powers\source\repos\OrchardCore-dev\src\OrchardCore.Modules\OrchardCore.Diagnostics\DiagnosticsStartupFilter.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at OrchardCore.ContentPreview.PreviewStartupFilter.<>c.<<Configure>b__1_1>d.MoveNext() in C:\Users\Ryan.Powers\source\repos\OrchardCore-dev\src\OrchardCore.Modules\OrchardCore.ContentPreview\PreviewStartupFilter.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\Users\Ryan.Powers\source\repos\OrchardCore-dev\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 63
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\Users\Ryan.Powers\source\repos\OrchardCore-dev\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 233
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\Users\Ryan.Powers\source\repos\OrchardCore-dev\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 59
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I don't have any great ideas on how to fix this, unfortunately.

**Comment by rjpowers10** [comment]
These look relevant but I haven't quite found a satisfying answer. I'm afraid there could be more cases I'm not thinking of.

[https://stackoverflow.com/questions/38594282/json-net-serializes-a-json-array-into-a-jarray-when-the-destination-is-an-object](https://stackoverflow.com/questions/38594282/json-net-serializes-a-json-array-into-a-jarray-when-the-destination-is-an-object)

[https://stackoverflow.com/questions/5546142/how-do-i-use-json-net-to-deserialize-into-nested-recursive-dictionary-and-list](https://stackoverflow.com/questions/5546142/how-do-i-use-json-net-to-deserialize-into-nested-recursive-dictionary-and-list)

**Comment by ns8482e** [comment]
@rjpowers10  good finding and It seems correct fix. Can you provide the pull request for fix you provided?

`JsonConvert.DeserializeObject`  gives `JArray` because `RawValue` is boxed to `object` and original type is not preserved in serialized string.

However in above fix I would suggest, instead of two `foreach` you could use ternary operator within the single `foreach` as below.
```cs
object rawValue = (item.RawValue is JArray jArray)
                ? jArray.ToObject<object[]>()
                : item.RawValue;
                modelState.SetModelValue(item.Key, rawValue, item.AttemptedValue);
```
