### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#7206]
### Prepare the project
Do some housekeeping on GitHub in the [main repo](https://github.com/OrchardCMS/OrchardCore).

- [ ] Close remaining issues for the version (including merging corresponding pull requests if suitable) or assign then to the next one.
- [ ] Assign all issues that were closed for an upcoming version (including a wildcard version like "1.0.x") to this version (milestone).

### Prepare the code
Update the source so everything looks like on the new version.

- [ ] Update code generation templates in `OrchardCore.ProjectTemplates`.
- [ ] Make sure that [OrchardCore.Samples works](https://github.com/OrchardCMS/OrchardCore.Samples).
- [ ] Create a `release/<version name>` branch out of `dev`.
- [ ] Update the `OrchardCore.Commons.props` file: Update `VersionPrefix` for release versions (like "1.0.0") and `VersionSuffix` for pre-release versions (like "rc2", for the full version to be e.g. "1.0.0-rc2").
- [ ] Update module versions in `ManifestConstants`.
- [ ] Change docker version in _.travis.yml_ and _appveyor.yml_.

### Test the release
Make sure everything works all right.

- [ ] Test the [guides](https://docs.orchardcore.net/en/dev/docs/guides/) with the NuGet packages from the Cloudsmith feed (branches under `release/` are automatically published too). Test at least the following guides:
    - [Creating a modular ASP.NET Core application](https://docs.orchardcore.net/en/dev/docs/guides/create-modular-application-mvc/)
    - [Creating an Orchard Core CMS website](https://docs.orchardcore.net/en/dev/docs/guides/create-cms-application/)
    - [Creating a new decoupled CMS Website](https://docs.orchardcore.net/en/dev/docs/guides/decoupled-cms/)
### Prepare and publish Orchard Core Translations

Update everything in the [Translations project](https://github.com/OrchardCMS/OrchardCore.Translations). Only do this once all the code changes are done since localized strings can change until then.

- [ ] Update `packageVersion` and/or `versionPrefix` in _appveyor.yml_.
- [ ] Update .po files with [PoExtractor](https://github.com/lukaskabrt/PoExtractor). This will also update [Crowdin](https://crowdin.com/project/orchard-core).
- [ ] Publish the new version on NuGet.
- [ ] Update the `OrchardCore.Translations.All` package reference in the main repo's _src/OrchardCore.Build/Dependencies.props_ file to refer to the new NuGet package.

### Prepare the documentation
Update the docs so they contain information about the new release so once the release is out you'll just need to point to new information.

- [ ] Create release notes in a specific documentation section. You can take the previous release notes as a template.
    - Overview of the release's highlights and goals. What do you want people to remember this release for?
    - Prerequisites. What framework version do you need, anything else to work with Orchard?
    - Upgrade steps, any migration necessary from previous versions, breaking changes.
    - Full changelog. You can generate this with [github-changelog](https://github.com/cfpb/github-changelog) with the `changelog OrchardCMS OrchardCore <previous version> <current version>` command, e.g. `changelog OrchardCMS OrchardCore 1.0.0-rc1 1.0.0-rc2`. Alternatively, you can use [Antoine's app](https://github.com/agriffard/Changelog.OrchardCore) too.

### Publish the release
Do the harder parts of making the release public. This should come after everything above is done.

- [ ] Merge `release/<version name>` to `master`.
    - Merges to `master` need two approvals so you'll need to create a pull request.
    - Merge it as a merge commit, not squash merge.
- [ ] Tag `master` with the full version name, including the prefix and suffix (e.g. "1.0.0-rc2").
- [ ] Test the [guides](https://docs.orchardcore.net/en/dev/docs/guides/) with the packages now automatically published to NuGet. Test at least the following guides:
    - [Creating a modular ASP.NET Core application](https://docs.orchardcore.net/en/dev/docs/guides/create-modular-application-mvc/)
    - [Creating an Orchard Core CMS website](https://docs.orchardcore.net/en/dev/docs/guides/create-cms-application/)
    - [Creating a new decoupled CMS Website](https://docs.orchardcore.net/en/dev/docs/guides/decoupled-cms/)
- [ ] Update [Try Orchard Core](https://github.com/OrchardCMS/TryOrchardCore).

### Publicize the release
Let the whole world know about our shiny new release. Savor this part! These steps will make the release public so only do them once everything else is ready.

- [ ] Update the documentation to mention the version in all places where the latest version is referenced, for example, but not limited to (do a search for the package version string): [Status in the root README](https://docs.orchardcore.net/en/dev/#status), CLI templates, commands, the [Creating a new decoupled CMS Website](https://docs.orchardcore.net/en/dev/docs/guides/decoupled-cms/) guide.
- [ ] Update the tagged [release](https://github.com/OrchardCMS/OrchardCore/releases) on GitHub: Change its title to something more descriptive (e.g. "Orchard Core 1.0.0 RC 2"), add a link in its description to the release notes in the documentation (something like `For details on this version see the [release notes in the documentation](link here).`). Add a link to this release under [Status in the root README](https://docs.orchardcore.net/en/dev/#status).
- [ ] Publish a blog post on the website.
- [ ] Ask to publish a blog post on [DevBlogs](https://devblogs.microsoft.com/).
- [ ] Ask to publish a blog post on [.NET Foundation News](https://dotnetfoundation.org/news).
- [ ] Tweet

**Comment by agriffard** [comment]
We all know it always takes a long time between the moment we decide a Release and the actual Release itself.
RC 2 was a good rehearsal to define the Release steps so lets make this 1.0 a great milestone.

Preliminary steps:
- Please comment about the current pull requests that should be included according to you.
- Check the issues assigned to milestone 1.0 and tell us if you can contribute: https://github.com/OrchardCMS/OrchardCore/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0

It is yet the best time to make changes that bring breaking changes.
After the Release of 1.0, it will be a bit more difficult.

At some point, I think we will then have to "stop" merging new PRs (that are not necessary or fixing issues) until the release is done.

**Comment by agriffard** [comment]
I know that we ask a lot from the core contributors and that reviewing others's PRs is a tough work and responsability.
If your are not comfortable with the process, please ask for help on specific issues.

People are not always aware of all the time it requires to do all this tasks but you can be sure that is really appreciated and that is one of the most valuable contributions to the project.

Thank you everyone for your work.

**Comment by hishamco** [comment]
Thanks @agriffard for starting this, regarding to me I can assist in the translations part, just few notes:

- We can focus on the `1.0.0` issues

- Avoid working on new features, because this happen always of course this will defer the release coz every new features needs a design, review ... etc, so let us focus on `1.0.0` issues

- Could we assign the remaining issues for the core members - without pressure - and it is free for the community to pick one of those, I know most of us are busy, but we can do balancing here and let the dev picks the one who interested in, instead of wasting the time for other things, unless it's urgent

- Try to look for the old PRs, there are 99 PRs at the time of writing this

Hope to hear the feedback from others, thanks

**Comment by ns8482e** [comment]
Is OC 1.0.0 targeting .NET 5?

**Comment by deanmarcussen** [comment]
> Is OC 1.0.0 targeting .NET 5?

I think that makes sense.

**Comment by sebastienros** [comment]
I think we should ship a version on 3.1 because it's LTS (@Skrypt reminded us) and later another one with 5.0. Some users might care about relying on a dotnet version that will be supported for a long time.

**Comment by DrewBrasher** [comment]
I'm still learning Orchard Core but I would like to help with the development.  Are there any issues for release 1 that would be good for someone new to start with?  I saw 1 labeled "good first issue" but it looked like it was already being worked on.

**Comment by jptissot** [comment]
> 
> 
> I'm still learning Orchard Core but I would like to help with the development. Are there any issues for release 1 that would be good for someone new to start with? I saw 1 labeled "good first issue" but it looked like it was already being worked on.

Check the issues assigned to the 1.0 milestone: https://github.com/OrchardCMS/OrchardCore/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0

**Comment by Piedone** [comment]
I'd like to see Audit Trail (https://github.com/OrchardCMS/OrchardCore/pull/6679) included, but that's on us :|.

**Comment by sheryever** [comment]
I think version 1 should target netcore 3.1 because it has the LTS, .NET5 is not LTS.

It is mid December and we are waiting for release 1.0 to use in production, Is there any clue when will we receive or we can use the current master repo for production?

**Comment by Piedone** [comment]
The current master branch is the latest released version, i.e. RC2, and it's suitable for production use. You can use the current dev branch in production as well, which is the most up to date, and this is what a lot of people are doing too.

**Comment by LMSSonos** [comment]
@sheryever we are using orchard betas since multiple months in production and work stable. Upgrades have never been an issue

**Comment by Tokyo1985** [comment]
When will Release 1.0 be released?

**Comment by deanmarcussen** [comment]
Migration release notes (to be included in any final document)

When migrating from RC2 to xxx please follow this procedure

- Logout from the site before upgrading.
  - If you have not logged out and receive an ASP.NET Claims related exception, please clear your cookies before restarting the migration.
- Start the site, and request the home page. All migrations should complete successfully. Please check the log files in `App_Data/Logs` after resuming usage of the site, to ensure the success of these migrations.

For more information here are the details of the migrations involved
- Migrating the `User` to use a `UserId` property.
  - This migration will reset all the `Users` in the database. On existing `Users` the `UserName` will be used as the `UserId` property. When new `Users` are created, they will be assigned a generated `UserId` property. The `ContentItem.Owner` value will match either the existing `UserName` or the generated `UserId` value. The `ContentItem.Author` property will update as content items are edited to the most recent `UserName` of the editor that published the `ContentItem`.
- Migrating the `Layers` feature to use the `OrchardCore.Rules` feature.
- Migrating `Menus` to use the `ContentItem.DisplayText` property.
- Many improvements to database indexes 

@agriffard I think that covers it for the most part.

**Comment by sebastienros** [comment]
Before merging release/1.0, we'll rename the master branch to main.

**Comment by thedrycake** [comment]
When do you plan to release the version 1.0.0 (a non-prerelease) of OrchardCore.Localization.Core?

**Comment by sebastienros** [comment]
@thedrycake  https://github.com/OrchardCMS/OrchardCore/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0

**Comment by hung-doan** [comment]
thanks you @sebastienros for the release. 
There are breaking changes
- Obsolete methods
- OpenIddict 3.0

Also a few more features. 

I wonder if we need any migration step for the upgrading from the RC2 to v1.0.0. 
Currently, I'm using the RC2 for the production page, so I'm considering if there is any risk after the upgrading.

**Comment by hung-doan** [comment]
Doing the upgrading from RC2 to v1.0.0. 
Here are a few breaking change that would impact to the migrations. 

**1/ OrchardCore.OpenId.Core: Migration issue in UpdateFrom7Async when using Microsoft SQL Server (not sure with others)**
- Error message: 
```
 Error: Invalid column name 'IsLockoutEnabled'.
```
- Discussion thread: https://github.com/OrchardCMS/OrchardCore/issues/9658
- Root cause: UpdateFrom7Async delete some records which are referenced by some indexes (these indexes will be then removed also)
- Solution: firstly remove the indexes, then run the migration. 
Execute this script to invalidate the indexes via a dummy constrains
```sql
/**
* OpenIdApplicationIndex
*/

-- DROP THE EXISTING FOREIGN KEY
ALTER TABLE [dbo].[OC_OpenIdApplicationIndex] DROP CONSTRAINT 
	[OC_FK_OpenIdApplicationIndex]
GO

-- ADD THE SAME 'KEY' NAME BACK IN AS A DUMMY CONSTRAINT
ALTER TABLE [dbo].[OC_OpenIdApplicationIndex] ADD CONSTRAINT
	[OC_FK_OpenIdApplicationIndex] CHECK (DocumentId > 0)
GO

/**
* OpenIdAppByRoleNameIndex
*/
-- 
ALTER TABLE [dbo].[OC_OpenIdAppByRoleNameIndex_Document] DROP CONSTRAINT 
	[OC_FK_OpenIdAppByRoleNameIndex_Document_DocumentId]
GO

-- ADD THE SAME 'KEY' NAME BACK IN AS A DUMMY CONSTRAINT
ALTER TABLE [dbo].[OC_OpenIdAppByRoleNameIndex_Document] ADD CONSTRAINT
	[OC_FK_OpenIdAppByRoleNameIndex_Document_DocumentId] CHECK (DocumentId > 0)
GO


-- DROP THE EXISTING FOREIGN KEY
ALTER TABLE [dbo].[OC_OpenIdAppByRoleNameIndex_Document] DROP CONSTRAINT 
	[OC_FK_OpenIdAppByRoleNameIndex_Document_Id]
GO

-- ADD THE SAME 'KEY' NAME BACK IN AS A DUMMY CONSTRAINT
ALTER TABLE [dbo].[OC_OpenIdAppByRoleNameIndex_Document] ADD CONSTRAINT
	[OC_FK_OpenIdAppByRoleNameIndex_Document_Id] CHECK (DocumentId > 0)
GO

```

**2. There are breaking changes in the sharp name, so that It would impact to the UI overriding.** 
In my case: 
- Contents_Button_Edit_SummaryAdmin.cshtml --(changed to)--> ContentsButtonEdit_SummaryAdmin.cshtml
- Contents_Button_Actions_SummaryAdmin.cshtml --(changed to)--> ContentsButtonActions_SummaryAdmin.cshtml

**3. Do not display Setup recipes in admin** 
- RC: Display Setup recipes in admin
- v1.0.0: Do not Display Setup recipes in admin
- Ref: Setup recipes in admin:  https://github.com/OrchardCMS/OrchardCore/pull/8417

**4. Base Admin theme: CSS identifiers are changed might impact to the CSS selector/overriding priorities**
- In v1.0.0 It introduce the dark theme. Which wrap the CSS selectors under `:root[data-theme='darkmode']` or `:root[data-theme='default']`

In my case, this more specific CSS selector cause some change in the CSS Specificity and impact to my CSS overriding rules . 
So that I have to review all my custom CSS to override the theme again.

**Comment by hungdoan-groove** [comment]
5. Value of  ClaimTypes.NameIdentifier has been changed from User.Id to User.UserId
Where: 
- User.Id: 
    - Number
    - Is DocumentId
- User.UserId
    - String
    - Autogenerated

**Comment by hung-doan** [comment]
5. Value of  ClaimTypes.NameIdentifier has been changed from User.Id to User.UserId
Where: 
- User.Id: 
    - Number
    - Is DocumentId
- User.UserId
    - String
    - Autogenerated

**Comment by hung-doan** [comment]
6/ User name is now only accept contain letters or digits.
In RC
- Username can be an email or else

In v1.0
- Username can only contain letters or digits
- Migrate any user names replacing '@' with '+' as user names can no longer be an email address. 

https://github.com/OrchardCMS/OrchardCore/blob/545b647a9b9e7af53eb67e3598647e14eedb3241/src/OrchardCore.Modules/OrchardCore.Users/Migrations.cs#L152-L170

See:
- https://github.com/OrchardCMS/OrchardCore/pull/7645
- https://gitter.im/OrchardCMS/OrchardCore?at=6000c2bbe578cf1e95eb196d

**Comment by Skrypt** [comment]
@hung-doan Can I ask you which version of SQL Server you are using? If it's under SQL Server 2016 these issues might happen because it doesn't support the syntax of the SQL queries we did.

**Comment by hung-doan** [comment]
@Skrypt I'm using : Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19043: ) 

Database is imported from Azure SQL Database with Combability level "130 -  in SQL Server 2016"
I changed the  Combability level to  SQL Server 2019. 
I still get the same error. 
![image](https://user-images.githubusercontent.com/11371581/131464688-db326231-be55-412f-9ac8-6cdf60bf1d82.png)

**Comment by Skrypt** [comment]
One migration failed to execute and it seems to be one from the OrchardCore.Users module where it adds a UserId.

https://github.com/OrchardCMS/OrchardCore/blob/ce53b9a90e2ba329e9b0a039a298d489302edefe/src/OrchardCore.Modules/OrchardCore.Users/Migrations.cs#L154

Basically you need to execute everything starting from this migration. To do so you can set the migration value in the database to "6" so that it re-execute them. Look at your logs afterward to see if any error happened and report it here.

**Comment by hung-doan** [comment]
@Skrypt not sure it's the cause as my current migration version is just around 4
```
{"DataMigrationClass":"OrchardCore.Users.Migrations","Version":4}
```

All modules
```
{
    "Id": 1,
    "DataMigrations": [{
            "DataMigrationClass": "OrchardCore.Deployment.Migrations",
            "Version": 1
        }, {
            "DataMigrationClass": "OrchardCore.Liquid.Migrations",
            "Version": 1
        }, {
            "DataMigrationClass": "OrchardCore.ContentManagement.Records.Migrations",
            "Version": 5
        }, {
            "DataMigrationClass": "OrchardCore.Contents.Migrations",
            "Version": 1
        }, {
            "DataMigrationClass": "OrchardCore.ContentFields.Migrations",
            "Version": 2
        }, {
            "DataMigrationClass": "OrchardCore.Html.Migrations",
            "Version": 5
        }, {
            "DataMigrationClass": "OrchardCore.Indexing.Migrations",
            "Version": 1
        }, {
            "DataMigrationClass": "OrchardCore.Lists.Migrations",
            "Version": 2
        }, {
            "DataMigrationClass": "OrchardCore.Markdown.Migrations",
            "Version": 4
        }, {
            "DataMigrationClass": "OrchardCore.Media.Migrations",
            "Version": 1
        }, {
            "DataMigrationClass": "OrchardCore.Title.Migrations",
            "Version": 2
        }, {
            "DataMigrationClass": "OrchardCore.OpenId.YesSql.Migrations.OpenIdMigrations",
            "Version": 3
        }, {
            "DataMigrationClass": "OrchardCore.Users.Migrations",
            "Version": 4
        }
    ]
}
```

In my app the exception came from `OrchardCore.OpenId`. 
```
2021-08-31 14:47:23.352 +07:00 [INF] Updating feature 'OrchardCore.Users'
2021-08-31 14:47:23.352 +07:00 [INF] Applying migration for 'OrchardCore.Users' from version 4.
2021-08-31 14:47:23.354 +07:00 [INF] Applying migration for 'OrchardCore.Users' from version 5.
2021-08-31 14:47:23.354 +07:00 [INF] Applying migration for 'OrchardCore.Users' from version 6.
2021-08-31 14:47:23.354 +07:00 [INF] Applying migration for 'OrchardCore.Users' from version 7.
2021-08-31 14:47:23.354 +07:00 [INF] Applying migration for 'OrchardCore.Users' from version 8.
2021-08-31 14:47:23.357 +07:00 [INF] Applying migration for 'OrchardCore.Users' from version 9.
2021-08-31 14:47:23.359 +07:00 [INF] Applying migration for 'OrchardCore.Users' from version 10.
2021-08-31 14:47:23.361 +07:00 [INF] Applying migration for 'OrchardCore.Users' from version 11.
2021-08-31 14:47:23.365 +07:00 [INF] Updating feature 'OrchardCore.Lists'
2021-08-31 14:47:23.365 +07:00 [INF] Updating feature 'OrchardCore.ContentTypes'
2021-08-31 14:47:23.365 +07:00 [INF] Applying migration for 'OrchardCore.Lists' from version 2.
2021-08-31 14:47:23.366 +07:00 [INF] Updating feature 'OrchardCore.OpenId'
2021-08-31 14:47:23.366 +07:00 [INF] Applying migration for 'OrchardCore.OpenId' from version 3.
2021-08-31 14:47:23.367 +07:00 [INF] Applying migration for 'OrchardCore.OpenId' from version 4.
2021-08-31 14:47:23.391 +07:00 [INF] Applying migration for 'OrchardCore.OpenId' from version 5.
2021-08-31 14:47:23.401 +07:00 [INF] Applying migration for 'OrchardCore.OpenId' from version 6.
2021-08-31 14:47:23.405 +07:00 [DBG] Creating described context for tenant 'Default'
2021-08-31 14:47:23.405 +07:00 [DBG] Composing blueprint
2021-08-31 14:47:23.468 +07:00 [DBG] Done composing blueprint
2021-08-31 14:47:23.600 +07:00 [INF] Applying migration for 'OrchardCore.OpenId' from version 7.
2021-08-31 14:47:52.150 +07:00 [ERR] Error while running migration version 7 for 'OrchardCore.OpenId'.
Microsoft.Data.SqlClient.SqlException (0x80131904): The DELETE statement conflicted with the REFERENCE constraint "OC_FK_OpenIdApplicationIndex". The conflict occurred in database "MyDb", table "dbo.OC_OpenIdApplicationIndex", column 'DocumentId'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreResults(Boolean& moreResults)
   at Microsoft.Data.SqlClient.SqlDataReader.TryNextResult(Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.NextResult()
   at YesSql.Commands.CreateIndexCommand.<AddToBatch>b__6_0(DbDataReader dr)
   at YesSql.Commands.BatchCommand.ExecuteAsync(DbConnection connection, DbTransaction transaction, ISqlDialect dialect, ILogger logger)
   at YesSql.Session.FlushAsync()
   at YesSql.Session.FlushAsync()
   at OrchardCore.OpenId.YesSql.Migrations.OpenIdMigrations.UpdateFrom7Async()
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId)
ClientConnectionId:0de48100-af6a-41e0-a158-a1bcd331655a
Error Number:547,State:0,Class:16
2021-08-31 14:47:52.164 +07:00 [DBG] Testing Azure Media Storage container cms existence
2021-08-31 14:47:52.390 +07:00 [DBG] Azure Media Storage container cms created.
2021-08-31 14:47:54.523 +07:00 [ERR] An unhandled exception has occurred while executing the request.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'UserId'.
Invalid column name 'IsLockoutEnabled'.
Invalid column name 'LockoutEndUtc'.
Invalid column name 'AccessFailedCount'.
Invalid column name 'UserId'.
Invalid column name 'IsLockoutEnabled'.
Invalid column name 'LockoutEndUtc'.
....
```
**In my view, the errors are causes by this deletion** 
https://github.com/OrchardCMS/OrchardCore/blob/e13cda97e036205ddb7c2fa1c655cc07385bbc2d/src/OrchardCore/OrchardCore.OpenId.Core/YesSql/Migrations/OpenIdMigrations.cs#L488-L496


The failure of this migration will prevents other migration to be executed and cause the error `Invalid column name '****'`
