### ISSUE TITLE
Method 'get_Version' in type 'OrchardCore.Environment.Extensions.Manifests.ManifestInfo' from assembly 'OrchardCore, Version=1.0.0.0

### ISSUE THREAD

**Issue by takaz-ams** [OrchardCMS/OrchardCore#7216]
System.TypeLoadException: Method 'get_Version' in type 'OrchardCore.Environment.Extensions.Manifests.ManifestInfo' from assembly 'OrchardCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at OrchardCore.Environment.Extensions.ExtensionManager.<>c__DisplayClass33_0.<EnsureInitializedAsync>b__0(Module module)
   at OrchardCore.Modules.EnumerableExtensions.<>c__DisplayClass0_1`1.<<ForEachAsync>b__1>d.MoveNext() in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\EnumerableExtensions.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Environment.Extensions.ExtensionManager.EnsureInitializedAsync() in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Extensions\ExtensionManager.cs:line 282
   at OrchardCore.Environment.Extensions.ExtensionManager.LoadFeaturesAsync() in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Extensions\ExtensionManager.cs:line 118
   at OrchardCore.Environment.Shell.ShellHost.PreCreateAndRegisterShellsAsync() in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Shell\ShellHost.cs:line 274
   at OrchardCore.Environment.Shell.ShellHost.InitializeAsync() in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Shell\ShellHost.cs:line 60
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 33
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by hishamco** [comment]
Steps to reproduce?

**Comment by Skrypt** [comment]
You need to have a Manifest.cs file in your modules for them to compile correctly I believe. I'm guessing that this is the issue here.

**Comment by jtkech** [comment]
Quite recently in `ManifestInfo` the version accessor has been replaced by a regular property getter.

So, maybe a module / theme needs to be rebuild, or there is a missmatch version on a referenced module / theme package

**Comment by sebastienros** [comment]
I think this will be solve by cleaning the project and rebuilding everything,
