### ISSUE TITLE
Shell error when creating site

### ISSUE THREAD

**Issue by dallasbeek** [OrchardCMS/OrchardCore#7275]
First time setup crashes if App_Data/Sites/Default directory doesn't exist and using SQL Server.

In my scenario I was using docker-compose to mount directory and overriding default App_Data path

**Comment by deanmarcussen** [comment]
This would suggest a permissions issue on the mounted directory.

Can you provide the exception from the logs.

**Comment by dallasbeek** [comment]
Again I'm building and running this on docker

Here is the log from my container

`
      Connection id "0HM3H7DU5F5CO", Request id "0HM3H7DU5F5CO:00000001": An unhandled exception was thrown by the application.
System.IO.DirectoryNotFoundException: Could not find a part of the path '/app/Data/Sites/Default/ContentDefinition.json'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.CreateText(String path)
   at OrchardCore.ContentManagement.FileContentDefinitionStore.SaveContentDefinitionAsync(ContentDefinitionRecord contentDefinitionRecord) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.ContentManagement\FileContentDefinitionStore.cs:line 68
   at OrchardCore.ContentManagement.ContentDefinitionManager.UpdateContentDefinitionRecord() in C:\projects\orchardcore\src\OrchardCore\OrchardCore.ContentManagement\ContentDefinitionManager.cs:line 348
   at OrchardCore.ContentManagement.ContentDefinitionManager.StoreTypeDefinition(ContentTypeDefinition contentTypeDefinition) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.ContentManagement\ContentDefinitionManager.cs:line 127
   at OrchardCore.ContentManagement.Metadata.ContentDefinitionManagerExtensions.AlterTypeDefinition(IContentDefinitionManager manager, String name, Action`1 alteration) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.ContentManagement.Abstractions\IContentDefinitionManager.cs:line 54
   at OrchardCore.ContentTypes.RecipeSteps.ContentDefinitionStep.UpdateContentType(ContentTypeDefinition type, ContentTypeDefinitionRecord record) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.ContentTypes\RecipeSteps\ContentDefinitionStep.cs:line 66
   at OrchardCore.ContentTypes.RecipeSteps.ContentDefinitionStep.ExecuteAsync(RecipeExecutionContext context) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.ContentTypes\RecipeSteps\ContentDefinitionStep.cs:line 37
   at OrchardCore.Recipes.Services.RecipeExecutor.<>c__DisplayClass9_0.<<ExecuteStepAsync>b__0>d.MoveNext() in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 173
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 206
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteStepAsync(RecipeExecutionContext recipeStep) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 154
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 100
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeExecutor.cs:line 117
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken)
   at OrchardCore.Setup.Services.SetupService.SetupInternalAsync(SetupContext context) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Setup.Core\SetupService.cs:line 190
   at OrchardCore.Setup.Services.SetupService.SetupAsync(SetupContext context) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Setup.Core\SetupService.cs:line 85
   at OrchardCore.Setup.Controllers.SetupController.IndexPOST(SetupViewModel model) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Setup\Controllers\SetupController.cs:line 170
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 63
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 206
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 59
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
`

docker-compose calls my Dockerfile to build and publish. ( Create Volume Manually docker volume create --name=muslweb-data


`
version: "3.7"

services:

    muslweb:
        image: muslhq:muslweb
        build:
          context: .
          dockerfile: src/Musl.Cms.Web/Dockerfile
        ports:
          - "8020:80"
          - "8021:443"
        volumes: 
          - muslweb-data:/app/Data
        environment: 
          VIRTUAL_HOST: musllocal.musl.com
          SSL_POLICY: Mozilla-Modern
          WEBSITES_ENABLE_APP_SERVICE_STORAGE: "false"
          ORCHARD_APP_DATA: "/app/Data"

volumes:
  muslweb-data:
    external: true
          
networks:
  default:
    external:
      name: nginx-proxy
`

The following check in my startup seems to fix the error.

`
        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void CheckAppDirectory(IApplicationBuilder app, IWebHostEnvironment env)
        {
            var envData = Environment.GetEnvironmentVariable(OrchardAppData);

            var appDataPath =
                !string.IsNullOrEmpty(envData)
                    ? Path.Combine(env.ContentRootPath, envData, DefaultSitesPath, "Default")
                    : Path.Combine(env.ContentRootPath, DefaultAppDataPath, DefaultSitesPath, "Default");

            if (!Directory.Exists(appDataPath))
            {
                Directory.CreateDirectory(appDataPath);
            }
        }

        private const string OrchardAppData = "ORCHARD_APP_DATA";
        private const string DefaultAppDataPath = "App_Data";
        private const string DefaultSitesPath = "Sites";

`

**Comment by deanmarcussen** [comment]
I think this error was fixed here https://github.com/OrchardCMS/OrchardCore/issues/6585

Which is on the dev branch nightly builds / docker/latest feed.

Which version are you running on @dallasbeek ?
