### ISSUE TITLE
Exception with latest JInt

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#7452]
I am getting this exception with the latest dev branch. 
```
An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.
   at Jint.Runtime.Descriptors.Specialized.IndexDescriptor.get_CustomValue()
   at Jint.Native.Object.ObjectInstance.UnwrapJsValue(PropertyDescriptor desc, JsValue thisObject)
   at Jint.Native.Object.ObjectInstance.Get(JsValue property, JsValue receiver)
   at Jint.Runtime.TypeConverter.OrdinaryToPrimitive(ObjectInstance input, Types hint)
   at Jint.Runtime.TypeConverter.ToPrimitive(JsValue input, Types preferredType)
   at Jint.Runtime.Interpreter.Expressions.JintExpression.EqualUnlikely(JsValue x, JsValue y)
   at Jint.Runtime.Interpreter.Expressions.JintExpression.Equal(JsValue x, JsValue y)
   at Jint.Runtime.Interpreter.Expressions.JintBinaryExpression.EqualBinaryExpression.EvaluateInternal()
   at Jint.Runtime.Interpreter.Expressions.JintBinaryExpression.GetValue()
   at Jint.Runtime.Interpreter.Statements.JintIfStatement.ExecuteInternal()
   at Jint.Runtime.Interpreter.JintStatementList.Execute()
   at Jint.Engine.Execute(Script program)
   at OrchardCore.Scripting.JavaScript.JavaScriptEngine.Evaluate(IScriptingScope scope, String script) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Scripting.JavaScript\JavaScriptEngine.cs:line 47
   at OrchardCore.Scripting.DefaultScriptingManager.Evaluate(String directive, IFileProvider fileProvider, String basePath, IEnumerable`1 scopedMethodProviders) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Infrastructure\Scripting\DefaultScriptingManager.cs:line 45
```

This is the GlobalMethod I wrote that returns the JObject

``` 
            _formAsJsonObject = new GlobalMethod
            {
                Name = "requestFormAsJsonObject",
                Method = serviceProvider => (Func<JObject>)(() =>
                {
                    var httpContextAccessor = serviceProvider.GetRequiredService<IHttpContextAccessor>();
                    var sanitizer = serviceProvider.GetRequiredService<IHtmlSanitizerService>();

                    return new JObject(httpContextAccessor.HttpContext.Request.Form.Select(
                      field =>
                      {
                          var arr = field.Value.ToArray();
                          if (arr.Length == 1)
                          {
                              return new JProperty(field.Key, sanitizer.Sanitize(field.Value[0]));
                          }
                          return new JProperty(field.Key, JArray.FromObject(arr.Select(o => sanitizer.Sanitize(o))));
                      }
                    ).ToArray());
                }
                )
            };
        }
```

And the script that causes the exception: 

```
var data = requestFormAsJsonObject();

if(data.name == "") {
 addError('name', 'test'); 
}
```

**Comment by sebastienros** [comment]
Is that a `JObject` object that is returned from `requestFormAsJsonObject()` and you are trying to access the property `name` ?

**Comment by jptissot** [comment]
Yes, this worked with the dev version from a week ago. I assume the jint update commit broke this code.

**Comment by jptissot** [comment]
You can see my failing tests here: 

https://github.com/StatCan/StatCan.OrchardCore/runs/1333658270#step:6:491

**Comment by sebastienros** [comment]
Try `data["name"]`

**Comment by jptissot** [comment]
Same error.

**Comment by jptissot** [comment]
@sebastienros you can see a failing test here: https://github.com/OrchardCMS/OrchardCore/commit/4d1a223fdf675e3efe99da8014c419ffbcf5de15

**Comment by sebastienros** [comment]
Please update with https://www.nuget.org/packages/Jint/3.0.0-beta-1914
