### ISSUE TITLE
Unable to log into backend after deployment with specified username and password

### ISSUE THREAD

**Issue by InfDev** [OrchardCMS/OrchardCore#7566]
Unable to log into backend after deployment with specified username and password: recipe "Blog", Sqlite. Source: dev branch on 8:30 AM Tuesday, November 10, 2020 (GMT)

**Comment by Skrypt** [comment]
What have you deployed exactly? Can you check if you have a UserId in your UserIndex table in your database?

**Comment by InfDev** [comment]
Id	DocumentId	NormalizedUserName	NormalizedEmail	IsEnabled	UserId
1	18	INFDEV	ALEX.SHLYAKHTO@GMAIL.COM	1	4760y8arzsm2m3c9v2j8xz1jnm

**Comment by InfDev** [comment]
Source includes latest commit # 7565. Recompiled and reinstalled 3 times

**Comment by deanmarcussen** [comment]
We're going to need a bit more information here to help you.

- What did you deploy and were did it get deployed?
- Did it work locally?
- What did your logs report?
- What error do you recieve when trying to login?

**Comment by InfDev** [comment]
1. I cloned the repo today (dev branch).
2. Compiled in Release config and published to directory.
3. Copied it to another directory on the same computer and connected it to IIS.

LOG:
``` text
2020-11-10 10:39:54.1994||||Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository|WARN|Using an in-memory repository. Keys will not be persisted to storage. 
2020-11-10 10:39:54.2445||||Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager|WARN|Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits. 
2020-11-10 10:39:54.2778||||Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager|WARN|No XML encryptor configured. Key {438f0d49-958f-469a-9896-7dfaa1e994c7} may be persisted to storage in unencrypted form. 
2020-11-10 10:39:56.1143|Default||ff96e1aa-46af83a695b92415.||Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery|ERROR|An exception was thrown while deserializing the token. Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {d2372acc-8bad-4fc7-8ab8-a4171b68e6cf} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)    at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
2020-11-10 13:35:58.4576||||Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository|WARN|Using an in-memory repository. Keys will not be persisted to storage. 
2020-11-10 13:35:58.4926||||Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager|WARN|Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits. 
2020-11-10 13:35:58.5191||||Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager|WARN|No XML encryptor configured. Key {7c10cc1f-a328-46f5-a1f6-9a6278789dde} may be persisted to storage in unencrypted form.
```

**Comment by deanmarcussen** [comment]
`The key {d2372acc-8bad-4fc7-8ab8-a4171b68e6cf} was not found in the key ring`

This suggests that your cookies are not working properly.

I assume it worked correctly when you ran it in debug before publishing?

Have you checked you have given the correct permissions for IIS to the directory you copied it to?

**Comment by sebastienros** [comment]
I posted a link to a SO answer in gitter yesterday, same issue with ios. Can someone find it and paste it here?

**Comment by sebastienros** [comment]
https://stackoverflow.com/questions/40783170/neither-user-profile-nor-hklm-registry-available-using-an-ephemeral-key-reposit

**Comment by InfDev** [comment]
I solved the problem.
 
**The thing is that for the backend, login is possible only via the https protocol.
In IIS on my local machine, I used IIS Express Development Certificate.**

Thanks you.
