### ISSUE TITLE
Recipe error

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#7611]
Seeing this in the logs ona. blank site... need to investigate:

```
2020-11-13 17:55:48.4385|Default|00-46cf52f8ec78b94aa8eccc66373687ae-e1f0eef0eef84641-00||OrchardCore.Recipes.Services.RecipeHarvester|ERROR|IExtensionInfo thrown from 
OrchardCore.Environment.Extensions.ExtensionInfo by AggregateException Newtonsoft.Json.JsonReaderException: Invalid property identifier character: ,. Path 'steps[0].data[0].TaxonomyPart.Terms[1].TitlePart', line 164, position 16.
   at Newtonsoft.Json.JsonTextReader.ParsePropertyAsync(CancellationToken cancellationToken)
   at Newtonsoft.Json.JsonTextReader.ParseObjectAsync(CancellationToken cancellationToken)
   at Newtonsoft.Json.Linq.JContainer.ReadContentFromAsync(JsonReader reader, JsonLoadSettings settings, CancellationToken cancellationToken)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFromAsync(JsonReader reader, JsonLoadSettings options, CancellationToken cancellationToken)
   at Newtonsoft.Json.Linq.JObject.LoadAsync(JsonReader reader, JsonLoadSettings settings, CancellationToken cancellationToken)
   at OrchardCore.Recipes.Services.RecipeReader.GetRecipeDescriptor(String recipeBasePath, IFileInfo recipeFileInfo, IFileProvider recipeFileProvider) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeReader.cs:line 22    at Newtonsoft.Json.JsonTextReader.ParsePropertyAsync(CancellationToken cancellationToken)
   at Newtonsoft.Json.JsonTextReader.ParseObjectAsync(CancellationToken cancellationToken)
   at Newtonsoft.Json.Linq.JContainer.ReadContentFromAsync(JsonReader reader, JsonLoadSettings settings, CancellationToken cancellationToken)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFromAsync(JsonReader reader, JsonLoadSettings options, CancellationToken cancellationToken)
   at Newtonsoft.Json.Linq.JObject.LoadAsync(JsonReader reader, JsonLoadSettings settings, CancellationToken cancellationToken)
   at OrchardCore.Recipes.Services.RecipeReader.GetRecipeDescriptor(String recipeBasePath, IFileInfo recipeFileInfo, IFileProvider recipeFileProvider) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Recipes.Core\Services\RecipeReader.cs:line 22
```

**Comment by sebastienros** [comment]
I believe that your json is wrong on line 164, position 16 ;)

Check for a property name with a "," in it
