### ISSUE TITLE
PagerShapes KeyNotFoundException

### ISSUE THREAD

**Issue by PiemP** [OrchardCMS/OrchardCore#7681]
Hello guys, 

Today, when I try to understand why a button is not translated, I have found this on my log file:
```
OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay|ERROR|Func`2 thrown from System.Func`2[[OrchardCore.DisplayManagement.Implementation.ShapeDisplayContext, OrchardCore.DisplayManagement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Threading.Tasks.Task, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] by KeyNotFoundException System.Collections.Generic.KeyNotFoundException: The given key 'Pager' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OrchardCore.Navigation.PagerShapesTableProvider.<Discover>b__0_10(ShapeDisplayContext displaying) in D:\lavoro\.net_core\OrchardCore-Fork-OrchardCorePA\OrchardCore\src\OrchardCore.Modules\OrchardCore.Navigation\PagerShapes.cs:line 125
   at OrchardCore.DisplayManagement.Descriptors.ShapeAlterationBuilder.<>c__DisplayClass12_0.<OnDisplaying>b__0(ShapeDisplayContext ctx) in D:\lavoro\.net_core\OrchardCore-Fork-OrchardCorePA\OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement\Descriptors\ShapeAlterationBuilder.cs:line 120
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.<>c.<ExecuteAsync>b__7_2(Func`2 action, ShapeDisplayContext displayContext) in D:\lavoro\.net_core\OrchardCore-Fork-OrchardCorePA\OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 83
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger) in D:\lavoro\.net_core\OrchardCore-Fork-OrchardCorePA\OrchardCore\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 133    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OrchardCore.Navigation.PagerShapesTableProvider.<Discover>b__0_10(ShapeDisplayContext displaying) in D:\lavoro\.net_core\OrchardCore-Fork-OrchardCorePA\OrchardCore\src\OrchardCore.Modules\OrchardCore.Navigation\PagerShapes.cs:line 125
   at OrchardCore.DisplayManagement.Descriptors.ShapeAlterationBuilder.<>c__DisplayClass12_0.<OnDisplaying>b__0(ShapeDisplayContext ctx) in D:\lavoro\.net_core\OrchardCore-Fork-OrchardCorePA\OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement\Descriptors\ShapeAlterationBuilder.cs:line 120
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.<>c.<ExecuteAsync>b__7_2(Func`2 action, ShapeDisplayContext displayContext) in D:\lavoro\.net_core\OrchardCore-Fork-OrchardCorePA\OrchardCore\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 83
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger) in D:\lavoro\.net_core\OrchardCore-Fork-OrchardCorePA\OrchardCore\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 133
```
The problem coming from thi line of code: 
```
dynamic pager = displaying.Shape.Properties["Pager"];
```

I could make a PR about it and replace `Properties` with `TryGetValue` on the `PagerShapes.cs` file.
Thank you.

**Comment by Skrypt** [comment]
Ok we face some NRE's here when we want to make alternates working back. I did change that code last night and it should be working because I reverted it to what it was before. The TryGetValue here will fail because on line 125 we get the entire Shape and not just Shape.Pager. I will try to fix this today again.

**Comment by Skrypt** [comment]
Ok I just tried and everything works fine with Pager and PagerSlim. Though, did you create a Pager-CurrentPage.liquid file in a theme or somewhere?

**Comment by PiemP** [comment]
> Ok I just tried and everything works fine with Pager and PagerSlim in the Admin. Though, did you create a Pager-CurrentPage.liquid file in a theme or somewhere?

No, I'm only list some content items in the backend

**Comment by Skrypt** [comment]
Clean your logs and try to go to the Blog page and Content Item page in the admin. Blog will use PagerSlim and Content Item will use full Pager. If you still get the log entry let me know. But first merge latest dev.

**Comment by PiemP** [comment]
Seems all ok!
Thank you @Skrypt
