### ISSUE TITLE
Setup recipe error with feature "OrchardCore.Contents.Deployment.ExportContentToDeploymentTarget"

### ISSUE THREAD

**Issue by NogginBox** [OrchardCMS/OrchardCore#7853]
I created a recipe using export. While trying to setup a new site using this there was an error and the setup did not finish.

With some investigation and slowing retying with less and less of the recipe I narrowed it down to the features step and enabling "OrchardCore.Contents.Deployment.ExportContentToDeploymentTarget".

This is the error:
```
2020-12-04 16:01:29.7385|Default||f7db1253-41ee635ee5d2c7c6.||OrchardCore.Data.Migration.DataMigrationManager|ERROR|Error while running migration version 0 for 'OrchardCore.Contents'. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: DeploymentPlanIndex'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 418
   at YesSql.Store.ProduceAsync[T](WorkerQueryKey key, Func`2 work, Object[] args)
   at YesSql.Services.DefaultQuery.Query`1.ListImpl()
   at OrchardCore.Deployment.DeploymentPlanService.CreateOrUpdateDeploymentPlansAsync(IEnumerable`1 deploymentPlans) in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore.Modules/OrchardCore.Deployment/DeploymentPlanService.cs:line 97
   at OrchardCore.Recipes.Services.RecipeExecutor.<>c__DisplayClass7_0.<<ExecuteStepAsync>b__0>d.MoveNext() in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore/OrchardCore.Recipes.Core/Services/RecipeExecutor.cs:line 174
```

This is the offending features step recipe:
```
{
      "name": "Feature",
      "enable": [
        "Application.Default",
        "OrchardCore.Settings",
        "OrchardCore.Admin",
        "OrchardCore.AdminMenu",
        "OrchardCore.Liquid",
        "OrchardCore.Contents",
        "OrchardCore.ContentTypes",
        "OrchardCore.Alias",
        "OrchardCore.Autoroute",
        "OrchardCore.Shortcodes",
        "OrchardCore.ContentFields",
        "OrchardCore.ContentPreview",
        "OrchardCore.Deployment",
        "OrchardCore.Contents.Deployment.AddToDeploymentPlan",
        "OrchardCore.Contents.Deployment.ExportContentToDeploymentTarget",
        "OrchardCore.Contents.FileContentDefinition",
        "OrchardCore.CustomSettings",
        "OrchardCore.Deployment.Remote",
        "OrchardCore.Diagnostics",
        "OrchardCore.DynamicCache",
        "OrchardCore.Resources",
        "OrchardCore.Email",
        "OrchardCore.Widgets",
        "OrchardCore.Features",
        "OrchardCore.Flows",
        "OrchardCore.HomeRoute",
        "OrchardCore.Html",
        "OrchardCore.Scripting",
        "OrchardCore.Layers",
        "OrchardCore.Lists",
        "OrchardCore.Media",
        "OrchardCore.Title",
        "OrchardCore.Menu",
        "OrchardCore.Microsoft.Authentication.AzureAD",
        "OrchardCore.Navigation",
        "OrchardCore.PublishLater",
        "OrchardCore.Queries",
        "OrchardCore.Queries.Sql",
        "OrchardCore.Users",
        "OrchardCore.Recipes",
        "OrchardCore.Roles",
        "OrchardCore.Shortcodes.Templates",
        "OrchardCore.Themes",
        "OrchardCore.Users.Registration",
        "OrchardCore.Workflows",
        "TheAdmin",
        "My.CustomTheme"
      ]
    }
```

Commenting out the one line enabling ```ExportContentToDeploymentTarget``` fixes the issue.

**Comment by jtkech** [comment]
Maybe a missing dependency

In the `OC.Contents` manifest file, i think that the `ExportContentToDeploymentTarget` feature needs to depend on `OC.ContentTypes` in place of `OC.Contents`. Note: `OC.ContentTypes` depends on `OC.Contents`

**Comment by NogginBox** [comment]
@jtkech I switched the dependency as suggested, but it does not fix the error. The error says ```Error while running migration version 0 for 'OrchardCore.Contents'.```, but I can't figure out why that is affected by having the ```ExportContentToDeploymentTarget ``` feature enabled.

**Comment by jtkech** [comment]
@NogginBox 

Okay i could repro by adding these features to the blog recipe

So, here the problem is that when the `ExportContentToDeploymentTarget` migration recipe is executed, the `OC.Deployment` migration was not executed yet and then the `DeploymentPlanIndex` table was not created.

Feature dependencies are important e.g. for the order services are registered, also for the order of migrations types that are enlisted through `ITypeFeatureProvider`. Yes, migrations are not resolved through the DI but by type, the order is still preserved for any migrations defined by the main feature of any module, but not for another "sub" feature of this module if its specific migrations class is not decorated by the `[Feature("TheFeatureId")]` attribute. Most of the time this is not a problem, but here the migration recipe does a query using the `DeploymentPlanIndex` table through the `DeploymentPlanService` => `_session.Query<DeploymentPlan, DeploymentPlanIndex>( ...`

Here, there are many workarounds to get the `OC.Deployment` migrations executed before, we can add to `O.Contents` a dependency on `OC.Deployment`, it works but that's a bad dependency, as a last resort, in the `OC.Deployment` manifest we can also define a negative priority (priority also acts on features ordering). But here, as said above, the right fix is to decorate `ExportContentToDeploymentTargetMigrations` with the feature attribute

    [Feature("OrchardCore.Contents.Deployment.ExportContentToDeploymentTarget")]
    public class ExportContentToDeploymentTargetMigrations : DataMigration

I think that there are other migrations classes (specific to a "sub" feature) that would also need to be decorated, I will do a PR soon to fix at least this issue.
