### ISSUE TITLE
Adding Azure AAD authentication results in Value cannot be null or empty. (Parameter 'areaName')

### ISSUE THREAD

**Issue by januszj** [OrchardCMS/OrchardCore#8343]
After adding Azure AAD authentication with Microsoft.AspNetCore.Authentication.AzureAD.UI (3.1.11) I got following exception:
```
System.ArgumentException: Value cannot be null or empty. (Parameter 'areaName')
   at Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.MapAreaControllerRoute(IEndpointRouteBuilder endpoints, String name, String areaName, String pattern, Object defaults, Object constraints, Object dataTokens)
   at OrchardCore.Mvc.Routing.DefaultAreaControllerRouteMapper.TryMapAreaControllerRoute(IEndpointRouteBuilder routes, ControllerActionDescriptor descriptor) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Mvc.Core\Routing\DefaultAreaControllerRouteMapper.cs:line 22
   at OrchardCore.Mvc.Startup.Configure(IApplicationBuilder app, IEndpointRouteBuilder routes, IServiceProvider serviceProvider) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Mvc.Core\Startup.cs:line 56
   at OrchardCore.Modules.ModularTenantRouterMiddleware.<>c__DisplayClass7_0.<ConfigureTenantPipeline>b__1(IEndpointRouteBuilder routes) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 123
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.ConfigureTenantPipeline(IApplicationBuilder appBuilder) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 128
   at OrchardCore.Modules.ModularTenantRouterMiddleware.<BuildTenantPipeline>b__6_0(IApplicationBuilder builder) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 99
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.BuildTenantPipeline() in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 108
   at OrchardCore.Modules.ModularTenantRouterMiddleware.InitializePipelineAsync(ShellContext shellContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 77
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 63
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 206
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 59
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### To Reproduce
1. Use OrchardCore.Samples - https://github.com/OrchardCMS/OrchardCore.Samples
2. In MultiTenantApplication add this to project file:
<PackageReference Include="Microsoft.AspNetCore.Authentication.AzureAD.UI" Version="3.1.11" />
3. Replace ConfigureServices with this code in Startup.cs:

```
// This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
                .AddAzureAD(options => Configuration.Bind("AzureAd", options));

            services.AddOrchardCore().AddMvc().WithTenants();
        }
```
4. In appsettings.json add this section, please use your Azure AAD details:
```
"AzureAd": {
    "Instance": "https://login.microsoftonline.com/",
    "Domain": "<yourdomain>.onmicrosoft.com",
    "TenantId": "<yourTenantId>",
    "ClientId": "<yourClientId>",
    "CallbackPath": "/signin-oidc"
  },
```
5. You should see Exception from above

### Expected behavior
It should still work

**Comment by jtkech** [comment]
Try to use one of our OrchardCoreBuilder helper, so that it is registered in a tenant container

    services.AddOrchardCore()
        .AddMvc()
        .WithTenants()
        .ConfigureServices(tenantServices =>
        {
            tenantServices.AddAuthentication(AzureADDefaults.AuthenticationScheme)
                .AddAzureAD(options => Configuration.Bind("AzureAd", options));
        });

**Comment by januszj** [comment]
Thanks, this resoved initial error, but I got this now:
```
InvalidOperationException: Could not resolve feature for type AccountController
OrchardCore.Environment.Extensions.TypeFeatureProvider.GetFeatureForDependency(Type dependency) in TypeFeatureProvider.cs
OrchardCore.Mvc.ModularApplicationModelProvider.OnProvidersExecuted(ApplicationModelProviderContext context) in ModularApplicationModelProvider.cs
Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelFactory.CreateApplicationModel(IEnumerable<TypeInfo> controllerTypes)
Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetDescriptors()
Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.get_ActionDescriptors()
OrchardCore.Mvc.Startup.Configure(IApplicationBuilder app, IEndpointRouteBuilder routes, IServiceProvider serviceProvider) in Startup.cs
OrchardCore.Modules.ModularTenantRouterMiddleware+<>c__DisplayClass7_0.<ConfigureTenantPipeline>b__1(IEndpointRouteBuilder routes) in ModularTenantRouterMiddleware.cs
Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action<IEndpointRouteBuilder> configure)
OrchardCore.Modules.ModularTenantRouterMiddleware.ConfigureTenantPipeline(IApplicationBuilder appBuilder) in ModularTenantRouterMiddleware.cs
OrchardCore.Modules.ModularTenantRouterMiddleware.<BuildTenantPipeline>b__6_0(IApplicationBuilder builder) in ModularTenantRouterMiddleware.cs
Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter+<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
OrchardCore.Modules.ModularTenantRouterMiddleware.BuildTenantPipeline() in ModularTenantRouterMiddleware.cs
OrchardCore.Modules.ModularTenantRouterMiddleware.InitializePipelineAsync(ShellContext shellContext) in ModularTenantRouterMiddleware.cs
OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in ModularTenantRouterMiddleware.cs
OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute) in ShellScope.cs
OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in ModularTenantContainerMiddleware.cs
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
