### ISSUE TITLE
TaxonomyIndex deadlock

### ISSUE THREAD

**Issue by tropcicstefan** [OrchardCMS/OrchardCore#8518]
### Describe the bug
Getting errors on TaxonomyFieldDisplayDriver when multiple users edit content type with taxonomy.

### To Reproduce
Wasn't able to reproduce it locally. 

### Expected behavior
No deadlocks, notifying users that something went wrong

UPDATE
After profiling this is my conclusion. Two users try to alter different content items with different taxonomy field, in this specific case even different content types(not that it matters). And when one of the transactions tries to delete from taxonomy index table(because new documents are in process of saving), those two transactions simply lock each other. 
Deleting from index table 4 times per saving doesn't help this situation either.

Profiler file:
[TI case.zip](https://github.com/OrchardCMS/OrchardCore/files/5944991/TI.case.zip)

### Screenshots
```
2021-02-08 14:34:26.1832|Default||28e297b0-4b1796cf8144f63d.||OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator|ERROR|IContentFieldDisplayDriver thrown from OrchardCore.Taxonomies.Drivers.TaxonomyFieldDisplayDriver by SqlException Microsoft.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 66) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Dapper.SqlMapper.ExecuteMultiImplAsync(IDbConnection cnn, CommandDefinition command, IEnumerable multiExec) in /_/Dapper/SqlMapper.Async.cs:line 624
   at YesSql.Session.FlushAsync()
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at OrchardCore.ContentManagement.DefaultContentManager.GetAsync(String contentItemId, VersionOptions options) in /builds/orchard-backend/src/OrchardCore/OrchardCore.ContentManagement/DefaultContentManager.cs:line 209
   at OrchardCore.Taxonomies.Drivers.TaxonomyFieldDisplayDriver.<>c__DisplayClass4_0.<<Edit>b__0>d.MoveNext() in /builds/orchard-backend/src/OrchardCore.Modules/OrchardCore.Taxonomies/Drivers/TaxonomyFieldDriver.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.DisplayManagement.ShapeFactoryExtensions.<CreateAsync>g__Awaited|6_0[TModel](ValueTask task, IShape shape) in /builds/orchard-backend/src/OrchardCore/OrchardCore.DisplayManagement/IShapeFactory.cs:line 83
   at OrchardCore.DisplayManagement.Implementation.DefaultShapeFactory.CreateAsync(String shapeType, Func`1 shapeFactory, Action`1 creating, Action`1 created) in /builds/orchard-backend/src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultShapeFactory.cs:line 92
   at OrchardCore.DisplayManagement.Views.ShapeResult.ApplyImplementationAsync(BuildShapeContext context, String displayType) in /builds/orchard-backend/src/OrchardCore/OrchardCore.DisplayManagement/Views/ShapeResult.cs:line 114
   at OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator.<>c.<<UpdateEditorAsync>b__11_2>d.MoveNext() in /builds/orchard-backend/src/OrchardCore/OrchardCore.ContentManagement.Display/ContentDisplay/ContentItemDisplayCoordinator.cs:line 401
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1,T2,T3,T4](IEnumerable`1 events, Func`6 dispatch, T1 arg1, T2 arg2, T3 arg3, T4 arg4, ILogger logger) in /builds/orchard-backend/src/OrchardCore/OrchardCore.Abstractions/Modules/Extensions/InvokeExtensions.cs:line 187
ClientConnectionId:b59c5a75-eb44-4dd6-8b98-c77414b0b3ab
Error Number:1205,State:51,Class:13    at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Dapper.SqlMapper.ExecuteMultiImplAsync(IDbConnection cnn, CommandDefinition command, IEnumerable multiExec) in /_/Dapper/SqlMapper.Async.cs:line 624
   at YesSql.Session.FlushAsync()
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at OrchardCore.ContentManagement.DefaultContentManager.GetAsync(String contentItemId, VersionOptions options) in /builds/orchard-backend/src/OrchardCore/OrchardCore.ContentManagement/DefaultContentManager.cs:line 209
   at OrchardCore.Taxonomies.Drivers.TaxonomyFieldDisplayDriver.<>c__DisplayClass4_0.<<Edit>b__0>d.MoveNext() in /builds/orchard-backend/src/OrchardCore.Modules/OrchardCore.Taxonomies/Drivers/TaxonomyFieldDriver.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.DisplayManagement.ShapeFactoryExtensions.<CreateAsync>g__Awaited|6_0[TModel](ValueTask task, IShape shape) in /builds/orchard-backend/src/OrchardCore/OrchardCore.DisplayManagement/IShapeFactory.cs:line 83
   at OrchardCore.DisplayManagement.Implementation.DefaultShapeFactory.CreateAsync(String shapeType, Func`1 shapeFactory, Action`1 creating, Action`1 created) in /builds/orchard-backend/src/OrchardCore/OrchardCore.DisplayManagement/Implementation/DefaultShapeFactory.cs:line 92
   at OrchardCore.DisplayManagement.Views.ShapeResult.ApplyImplementationAsync(BuildShapeContext context, String displayType) in /builds/orchard-backend/src/OrchardCore/OrchardCore.DisplayManagement/Views/ShapeResult.cs:line 114
   at OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator.<>c.<<UpdateEditorAsync>b__11_2>d.MoveNext() in /builds/orchard-backend/src/OrchardCore/OrchardCore.ContentManagement.Display/ContentDisplay/ContentItemDisplayCoordinator.cs:line 401
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1,T2,T3,T4](IEnumerable`1 events, Func`6 dispatch, T1 arg1, T2 arg2, T3 arg3, T4 arg4, ILogger logger) in /builds/orchard-backend/src/OrchardCore/OrchardCore.Abstractions/Modules/Extensions/InvokeExtensions.cs:line 187


Deadlock graph
<deadlock-list>
	<deadlock victim="process1829a89468">
		<process-list>
			<process id="process1829a89468" taskpriority="0" logused="6868" waitresource="KEY: 6:72057594045857792 (90cdc7da9a54)" waittime="1383" ownerId="963097435" transactionname="user_transaction" lasttranstarted="2021-02-08T14:34:24.763" XDES="0x188af38428" lockMode="U" schedulerid="8" kpid="221128" status="suspended" spid="66" sbid="0" ecid="0" priority="0" trancount="2" lastbatchstarted="2021-02-08T14:34:24.780" lastbatchcompleted="2021-02-08T14:34:24.780" lastattention="1900-01-01T00:00:00.780" clientapp="Core Microsoft SqlClient Data Provider" hostname="web-backend" hostpid="111762" loginname="Orchard" isolationlevel="read uncommitted (1)" xactid="963097435" currentdb="6" currentdbname="Orchard" lockTimeout="4294967295" clientoption1="671088672" clientoption2="128056">
				<executionStack>
					<frame procname="adhoc" line="1" stmtstart="18" stmtend="120" sqlhandle="0x020000008b54bb03da2f9d30bc23f1f0a22cca70b667413a0000000000000000000000000000000000000000">unknown</frame>
					<frame procname="unknown" line="1" sqlhandle="0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000">unknown</frame>
				</executionStack>
				<inputbuf>(@Id int)delete from [TaxonomyIndex] where [DocumentId] = @Id</inputbuf>
			</process>
			<process id="process187c501468" taskpriority="0" logused="95968" waitresource="KEY: 6:72057594045857792 (7555b024caab)" waittime="1380" ownerId="963097296" transactionname="user_transaction" lasttranstarted="2021-02-08T14:34:24.150" XDES="0x1898858428" lockMode="U" schedulerid="10" kpid="224372" status="suspended" spid="61" sbid="0" ecid="0" priority="0" trancount="2" lastbatchstarted="2021-02-08T14:34:24.790" lastbatchcompleted="2021-02-08T14:34:24.787" lastattention="1900-01-01T00:00:00.787" clientapp="Core Microsoft SqlClient Data Provider" hostname="web-backend" hostpid="111762" loginname="Orchard" isolationlevel="read uncommitted (1)" xactid="963097296" currentdb="6" currentdbname="Orchard" lockTimeout="4294967295" clientoption1="671088672" clientoption2="128056">
				<executionStack>
					<frame procname="adhoc" line="1" stmtstart="18" stmtend="120" sqlhandle="0x020000008b54bb03da2f9d30bc23f1f0a22cca70b667413a0000000000000000000000000000000000000000">unknown</frame>
					<frame procname="unknown" line="1" sqlhandle="0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000">unknown</frame>
				</executionStack>
				<inputbuf>(@Id int)delete from [TaxonomyIndex] where [DocumentId] = @Id</inputbuf>
			</process>
		</process-list>
		<resource-list>
			<keylock hobtid="72057594045857792" dbid="6" objectname="Orchard.dbo.TaxonomyIndex" indexname="PK__Taxonomy__3214EC071ED57953" id="lock17ff49c280" mode="X" associatedObjectId="72057594045857792">
				<owner-list>
					<owner id="process187c501468" mode="X"/>
				</owner-list>
				<waiter-list>
					<waiter id="process1829a89468" mode="U" requestType="wait"/>
				</waiter-list>
			</keylock>
			<keylock hobtid="72057594045857792" dbid="6" objectname="Orchard.dbo.TaxonomyIndex" indexname="PK__Taxonomy__3214EC071ED57953" id="lock18a66f9f00" mode="X" associatedObjectId="72057594045857792">
				<owner-list>
					<owner id="process1829a89468" mode="X"/>
				</owner-list>
				<waiter-list>
					<waiter id="process187c501468" mode="U" requestType="wait"/>
				</waiter-list>
			</keylock>
		</resource-list>
	</deadlock>
</deadlock-list>
sa 24 2021-02-08 14:34:26.177
```

**Comment by tropcicstefan** [comment]
Generating nonclustered index on DocumentId in TaxonomyIndex and AliasPartIndex table fixed the issue for now, maybe add those indices to fast growing, big tables like Taxonomy and Alias by default?

**Comment by jtkech** [comment]
@tropcicstefan 

For info we already added many indexes including the `DocumentId` recently, on the dev branch (cloudsmith feed)
