### ISSUE TITLE
**InvalidCastException** when using inheritance in my models within IndexProvider

### ISSUE THREAD

**Issue by lampersky** [OrchardCMS/OrchardCore#8802]
I'm getting **InvalidCastException** when using inheritance in my models within IndexProvider.

```
InvalidCastException: Unable to cast object of type 
'YesSql.Indexes.DescribeContext`1[TestModule.Models.AnotherPerson]' to type 
'YesSql.Indexes.DescribeContext`1[TestModule.Models.Person]'.
```

I have two models, **Person** and **AnotherPerson** which inherit from **Person**.
I've created two Indexes and two IndexProviders.

I've tried exactly the same without OC, just yessql and there everything is working fine, as expected.
So, it looks to me like problem with **registering indexes**. I'm not sure it is a bug, maybe I'm doing something wrong.

Here is a [repro repo](https://github.com/lampersky/OrchardCore/commit/1f0bf7dbac405f0bf699da49fa82df41c5d92f2c)

I've extended my local yessql version by additional test case and here is a screen from working example (pure yessql):
![image](https://user-images.githubusercontent.com/6403130/110527138-e1a6ca00-8116-11eb-9509-8b52026a0839.png)

My models:
```
namespace TestModule.Models
{
    public class Person
    {
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public int Age { get; set; }
        public bool Anonymous { get; set; }
        public int Version { get; set; }
    }
}
```

```
namespace TestModule.Models
{
    //this throws exception
    public class AnotherPerson : Person
    {
        public AnotherPerson() : base() { }
        public string AdditionalField1 { get; set; }
        public string AdditionalField2 { get; set; }
        public string AdditionalField3 { get; set; }
    }
}
```
Indices and IndexProviders:
```
namespace TestModule.Indexes
{
    public class PersonByAge : MapIndex
    {
        public string Name { get; set; }
        public int Age { get; set; }
        public bool Adult { get; set; }
    }

    public class PersonAgeIndexProvider : IndexProvider<Person>
    {
        public override void Describe(DescribeContext<Person> context)
        {
            context
                .For<PersonByAge>()
                .Map(person => new PersonByAge
                {
                    Age = person.Age,
                    Adult = person.Age >= 18,
                    Name = person.Firstname
                });
        }
    }
}
```

```
namespace TestModule.Indexes
{
    public class AnotherPersonByAge : PersonByAge
    {
        public string AdditionalField1 { get; set; }
        public string AdditionalField2 { get; set; }
        public string AdditionalField3 { get; set; }
    }

    public class AnotherPersonAgeIndexProvider : IndexProvider<AnotherPerson>
    {
        public override void Describe(DescribeContext<AnotherPerson> context)
        {
            context
                .For<AnotherPersonByAge>()
                .Map(person => new AnotherPersonByAge
                {
                    Age = person.Age,
                    Adult = person.Age >= 18,
                    Name = person.Firstname,
                    AdditionalField1 = person.AdditionalField1,
                    AdditionalField2 = person.AdditionalField2,
                    AdditionalField3 = person.AdditionalField3
                });
        }
    }
}
```

Migrations:
```
namespace TestModule
{
    public class Migrations : DataMigration
    {
        public int Create()
        {
            SchemaBuilder.CreateMapIndexTable<PersonByAge>(_ => _
                .Column<int>(nameof(PersonByAge.Age))
                .Column<bool>(nameof(PersonByAge.Adult))
                .Column<string>(nameof(PersonByAge.Name))
            );

            SchemaBuilder.CreateMapIndexTable<AnotherPersonByAge>(_ => _
                .Column<int>(nameof(AnotherPersonByAge.Age))
                .Column<bool>(nameof(AnotherPersonByAge.Adult))
                .Column<string>(nameof(AnotherPersonByAge.Name))
                .Column<string>(nameof(AnotherPersonByAge.AdditionalField1))
                .Column<string>(nameof(AnotherPersonByAge.AdditionalField2))
                .Column<string>(nameof(AnotherPersonByAge.AdditionalField3))
            );

            return 1;
        }
    }
}
```
Startup:
```
namespace TestModule
{
    public class Startup : StartupBase
    {
        public override void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<IIndexProvider, AnotherPersonAgeIndexProvider>();
            services.AddSingleton<IIndexProvider, PersonAgeIndexProvider>();

            services.AddTransient<IDataMigration, Migrations>();
        }
    }
}
```
example Controller:
```
namespace TestModule.Controllers
{
    public class TestController : Controller
    {
        private readonly ISession _session;

        public TestController(ISession session)
        {
            _session = session;
        }

        [HttpGet]
        public async Task<IActionResult> AddTestData()
        {
            _session.Save(new Person
            {
                Firstname = "Dawid",
                Age = 99
            });
            _session.Save(new AnotherPerson
            {
                Firstname = "Dawid",
                Age = 99,
                AdditionalField1 = "test"
            });
            await _session.CommitAsync();
            return Ok();
        }

        [HttpGet]
        public async Task<IActionResult> GetTestData()
        {
            var query1 = _session.Query<AnotherPerson, AnotherPersonByAge>();
            var items1 = await query1.ListAsync();
            var query2 = _session.Query<Person, PersonByAge>();
            var items2 = await query2.ListAsync();
            return Ok(new { items1, items2 });
        }
    }
}
```

exception is thrown at `await _session.CommitAsync();` inside my controller:
```
public async Task<IActionResult> AddTestData()
        {
            _session.Save(new Person
            {
                Firstname = "Dawid",
                Age = 99
            });
            _session.Save(new AnotherPerson
            {
                Firstname = "Dawid",
                Age = 99,
                AdditionalField1 = "test"
            });
            await _session.CommitAsync();
            return Ok();
        }
```

and here is stack trace:

```
System.InvalidCastException: Unable to cast object of type 'YesSql.Indexes.DescribeContext`1[TestModule.Models.AnotherPerson]' to type 'YesSql.Indexes.DescribeContext`1[TestModule.Models.Person]'.
   at YesSql.Indexes.IndexProvider`1.YesSql.Indexes.IIndexProvider.Describe(IDescriptor context)
   at YesSql.Store.CreateDescriptors(Type target, String collection, IEnumerable`1 indexProviders)
   at YesSql.Store.Describe(Type target, String collection)
   at YesSql.Session.GetDescriptors(Type t, String collection)
   at YesSql.Session.MapNew(Document document, Object obj, String collection)
   at YesSql.Session.SaveEntityAsync(Object entity, String collection)
   at YesSql.Session.FlushAsync()
   at YesSql.Session.CommitAsync()
   at YesSql.Session.CommitAsync()
   at TestModule.Controllers.TestController.AddTestData() in C:\repo\OrchardCore\src\OrchardCore.Modules\OrchardCore.Mvc.TestModule\Controllers\TestController.cs:line 32
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext() in C:\repo\OrchardCore\src\OrchardCore.Modules\OrchardCore.Diagnostics\DiagnosticsStartupFilter.cs:line 34
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at OrchardCore.ContentPreview.PreviewStartupFilter.<>c.<<Configure>b__1_1>d.MoveNext() in C:\repo\OrchardCore\src\OrchardCore.Modules\OrchardCore.ContentPreview\PreviewStartupFilter.cs:line 21
--- End of stack trace from previous location ---
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\repo\OrchardCore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 63
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell) in C:\repo\OrchardCore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 238
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\repo\OrchardCore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 59
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

_Originally posted by @lampersky in https://github.com/OrchardCMS/OrchardCore/discussions/8801_

**Comment by deanmarcussen** [comment]
That's an interesting one, especially with the YesSql test passing.

The difference (possibly) is that in OC we register them, and therefore pass them as `IIndexProvider` rather than in your test where they are passed as `AnotherPersonAgeIndexProvider` and `PersonAgeIndexProvider`

Since you have the yessql test, perhaps try registering them as an array of `IIndexProvider` and see if you can repro?

```
store.RegisterIndexes(
  new IIndexProvider [] 
  {
     new AnotherPersonAgeIndexProvider(),
     new PersonAgeIndexProvider()
  }
);
```

I'm assuming there is some type inference in YesSql that is causing the issue.

**Comment by lampersky** [comment]
I will try and will get back to you. Thanks @deanmarcussen

**Comment by lampersky** [comment]
I rechecked, and it looks like yesterday I forgot to register both indexes, that's why I was thinking it is working in pure yessql.

Now, I can confirm, the problem can be repro in yessql.
Thanks again @deanmarcussen, I will create issue in yessql repo.

As shown below, no matter how you register indexes, test case fails:

![image](https://user-images.githubusercontent.com/6403130/110607789-df328780-818b-11eb-84da-ee77a48e4653.png)

![image](https://user-images.githubusercontent.com/6403130/110607970-130dad00-818c-11eb-9445-a52adbcfdc49.png)

**Comment by lampersky** [comment]
https://github.com/sebastienros/yessql/issues/354

**Comment by lampersky** [comment]
I was able to fix this issue, but it would be good if someone could check [this](https://github.com/sebastienros/yessql/issues/354#issuecomment-795227106) solution.
If it's ok, then I can prepare PR for yessql.
