### ISSUE TITLE
Lucene Queries Fluid 2.0 issue

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#8832]
### Describe the bug

{{ from }} and {{ size }} is not working anymore.

### Screenshots

![image](https://user-images.githubusercontent.com/3228637/110851742-6f052e00-827f-11eb-99a6-b2a97a0f2db6.png)

![image](https://user-images.githubusercontent.com/3228637/110852334-3a45a680-8280-11eb-9908-522385b607c7.png)

### Stack trace

```
2021-03-11 15:31:44.5466|Default|00-6d2d367aeab59f46958cb4abacf4865d-fc9c7034eba45246-00||OrchardCore.Lucene.Controllers.AdminController|ERROR|Error while executing query System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at OrchardCore.Lucene.LuceneQueryService.SearchAsync(LuceneQueryContext context, JObject queryObj) in E:\Repositories\affaires-extra-sc\src\OrchardCore\OrchardCore.Lucene.Core\LuceneQueryService.cs:line 36
   at OrchardCore.Lucene.Controllers.AdminController.<>c__DisplayClass26_0.<<Query>b__0>d.MoveNext() in E:\Repositories\affaires-extra-sc\src\OrchardCore.Modules\OrchardCore.Lucene\Controllers\AdminController.cs:line 391    at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at OrchardCore.Lucene.LuceneQueryService.SearchAsync(LuceneQueryContext context, JObject queryObj) in E:\Repositories\affaires-extra-sc\src\OrchardCore\OrchardCore.Lucene.Core\LuceneQueryService.cs:line 36
   at OrchardCore.Lucene.Controllers.AdminController.<>c__DisplayClass26_0.<<Query>b__0>d.MoveNext() in E:\Repositories\affaires-extra-sc\src\OrchardCore.Modules\OrchardCore.Lucene\Controllers\AdminController.cs:line 391
```

/cc @sebastienros

**Comment by Skrypt** [comment]
See

https://github.com/OrchardCMS/OrchardCore/blob/29d1bd62996cabc775d52be0e9f8d4a35f04aa4f/src/OrchardCore.Modules/OrchardCore.Lucene/Services/LuceneQuerySource.cs#L65
