### ISSUE TITLE
Recipe enabling a module throws `SqliteException: SQLite Error 1: 'no such table: WorkflowTypeIndex'.`

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#8967]
### Describe the bug

Getting this exception when executing a recipe that enables the `OrchardCore.Workflows.Http` module.
Orchard version `1.0.0-rc2-15907`

### To Reproduce
1. Run our codebase: https://github.com/StatCan/StatCan.OrchardCore
2. Setup the site with the `HackathonTheme` setup recipe using SQLite
3. Go to the admin site and execute the `Contact form example` recipe from the Recipes admin page
4. Exception occurs. All requests fail.
5. Restart the site
6. Exception is gone but recipe did not fully complete
7. Run the `Contact form example` recipe a second time
8. Executes properly

### Expected behavior
No exception is thrown when the recipe enables the `OrchardCore.Workflows.Http` module.

Here is the recipe: https://github.com/StatCan/StatCan.OrchardCore/blob/056ccbf797d5e9ab79883e602e9bac149dfb4e99/src/Modules/StatCan.OrchardCore.VueForms/Recipes/ContactForm.recipe.json#L17

Setup recipe: https://github.com/StatCan/StatCan.OrchardCore/blob/5249e65dd61eeb1406b8db356773827d6a7071ef/src/Themes/HackathonTheme/Recipes/hackathon.setup.recipe.json#L11

/cc @jtkech

**Comment by jptissot** [comment]
Stack trace: 

```bash
fail: OrchardCore.Data.Migration.DataMigrationManager[0]
      => SpanId:0400faa130e32343, TraceId:94b608cf0079404196686602bfb8fc29, ParentId:0000000000000000 => ConnectionId:0HM7ETR0DSNQQ => RequestPath:/Admin/Recipes/Execute RequestId:0HM7ETR0DSNQQ:0000001B => OrchardCore.Recipes.Controllers.AdminController.Execute (OrchardCore.Recipes)
      Error while running migration version 0 for 'OrchardCore.Workflows'.
      System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
       ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 6: 'database table is locked: sqlite_master'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
         at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2813
         at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 572
         at YesSql.Sql.SchemaBuilder.Execute(IEnumerable`1 statements)
         at YesSql.Sql.SchemaBuilder.CreateMapIndexTable(Type indexType, Action`1 table, String collection)
         at YesSql.Sql.SchemaBuilderExtensions.CreateMapIndexTable[T](ISchemaBuilder builder, Action`1 table, String collection)
         at OrchardCore.Workflows.Migrations.Create()
         --- End of inner exception stack trace ---
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
         at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId)
fail: OrchardCore.ContentManagement.DefaultContentManager[0]
      => SpanId:0400faa130e32343, TraceId:94b608cf0079404196686602bfb8fc29, ParentId:0000000000000000 => ConnectionId:0HM7ETR0DSNQQ => RequestPath:/Admin/Recipes/Execute RequestId:0HM7ETR0DSNQQ:0000001B => OrchardCore.Recipes.Controllers.AdminController.Execute (OrchardCore.Recipes)
      IContentHandler thrown from OrchardCore.Contents.Workflows.Handlers.ContentsHandler by SqliteException
      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: WorkflowTypeStartActivitiesIndex'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 418
         at YesSql.Store.ProduceAsync[T](WorkerQueryKey key, Func`2 work, Object[] args)
         at YesSql.Services.DefaultQuery.Query`1.ListImpl()
         at OrchardCore.Workflows.Services.WorkflowManager.TriggerEventAsync(String name, IDictionary`2 input, String correlationId, Boolean isExclusive, Boolean isAlwaysCorrelated)
         at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger)
fail: OrchardCore.ContentManagement.DefaultContentManager[0]
      => SpanId:0400faa130e32343, TraceId:94b608cf0079404196686602bfb8fc29, ParentId:0000000000000000 => ConnectionId:0HM7ETR0DSNQQ => RequestPath:/Admin/Recipes/Execute RequestId:0HM7ETR0DSNQQ:0000001B => OrchardCore.Recipes.Controllers.AdminController.Execute (OrchardCore.Recipes)
      IContentHandler thrown from OrchardCore.Contents.Workflows.Handlers.ContentsHandler by SqliteException
      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: WorkflowTypeStartActivitiesIndex'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 418
         at YesSql.Store.ProduceAsync[T](WorkerQueryKey key, Func`2 work, Object[] args)
         at YesSql.Services.DefaultQuery.Query`1.ListImpl()
         at OrchardCore.Workflows.Services.WorkflowManager.TriggerEventAsync(String name, IDictionary`2 input, String correlationId, Boolean isExclusive, Boolean isAlwaysCorrelated)
         at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger)
fail: OrchardCore.ContentManagement.DefaultContentManager[0]
      => SpanId:0400faa130e32343, TraceId:94b608cf0079404196686602bfb8fc29, ParentId:0000000000000000 => ConnectionId:0HM7ETR0DSNQQ => RequestPath:/Admin/Recipes/Execute RequestId:0HM7ETR0DSNQQ:0000001B => OrchardCore.Recipes.Controllers.AdminController.Execute (OrchardCore.Recipes)
      IContentHandler thrown from OrchardCore.Contents.Workflows.Handlers.ContentsHandler by SqliteException
      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: WorkflowTypeStartActivitiesIndex'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 418
         at YesSql.Store.ProduceAsync[T](WorkerQueryKey key, Func`2 work, Object[] args)
         at YesSql.Services.DefaultQuery.Query`1.ListImpl()
         at OrchardCore.Workflows.Services.WorkflowManager.TriggerEventAsync(String name, IDictionary`2 input, String correlationId, Boolean isExclusive, Boolean isAlwaysCorrelated)
         at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger)
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      => SpanId:0400faa130e32343, TraceId:94b608cf0079404196686602bfb8fc29, ParentId:0000000000000000 => ConnectionId:0HM7ETR0DSNQQ => RequestPath:/Admin/Recipes/Execute RequestId:0HM7ETR0DSNQQ:0000001B
      An unhandled exception has occurred while executing the request.
      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: WorkflowTypeIndex'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 418
         at YesSql.Store.ProduceAsync[T](WorkerQueryKey key, Func`2 work, Object[] args)
         at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
         at OrchardCore.Workflows.Recipes.WorkflowTypeStep.ExecuteAsync(RecipeExecutionContext context)
         at OrchardCore.Recipes.Services.RecipeExecutor.<>c__DisplayClass7_0.<<ExecuteStepAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
         at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteStepAsync(RecipeExecutionContext recipeStep)
         at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, IDictionary`2 environment, CancellationToken cancellationToken)
         at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, IDictionary`2 environment, CancellationToken cancellationToken)
         at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, IDictionary`2 environment, CancellationToken cancellationToken)
         at OrchardCore.Recipes.Controllers.AdminController.Execute(String basePath, String fileName)
         at lambda_method931(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
         at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
         at OrchardCore.ContentPreview.PreviewStartupFilter.<>c.<<Configure>b__1_1>d.MoveNext()
      --- End of stack trace from previous location ---
         at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext)
         at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
         at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
         at NetEscapades.AspNetCore.SecurityHeaders.SecurityHeadersMiddleware.Invoke(HttpContext context) in C:\projects\netescapades-aspnetcore-securityheaders\src\NetEscapades.AspNetCore.SecurityHeaders\SecurityHeadersMiddleware.cs:line 68
         at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      => SpanId:2216da5b8f098443, TraceId:c86007bab67b49419becdd40f2f57a79, ParentId:0000000000000000 => ConnectionId:0HM7ETR0DSNQR => RequestPath:/Admin/Recipes RequestId:0HM7ETR0DSNQR:00000001
      An unhandled exception has occurred while executing the request.
      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: WorkflowTypeIndex'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 418
         at YesSql.Store.ProduceAsync[T](WorkerQueryKey key, Func`2 work, Object[] args)
         at YesSql.Services.DefaultQuery.Query`1.ListImpl()
         at OrchardCore.Workflows.Http.Services.WorkflowTypeRouteEntries.CreateDocumentAsync()
         at OrchardCore.Documents.DocumentManager`1.GetOrCreateImmutableAsync(Func`1 factoryAsync)
         at OrchardCore.Workflows.Http.Services.WorkflowRouteEntries`1.GetWorkflowRouteEntriesAsync(String httpMethod, RouteValueDictionary routeValues)
         at OrchardCore.Workflows.Http.Filters.WorkflowActionFilter.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
         at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
         at OrchardCore.ContentPreview.PreviewStartupFilter.<>c.<<Configure>b__1_1>d.MoveNext()
      --- End of stack trace from previous location ---
         at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext)
         at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell)
         at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
         at NetEscapades.AspNetCore.SecurityHeaders.SecurityHeadersMiddleware.Invoke(HttpContext context) in C:\projects\netescapades-aspnetcore-securityheaders\src\NetEscapades.AspNetCore.SecurityHeaders\SecurityHeadersMiddleware.cs:line 68
         at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by jtkech** [comment]
@jptissot 

Maybe related to the execution order issue in #8785, this when a module / feature, adds some functionalities with the `RequireFeatures` attribute, but doesn't depend on the required feature (in the manifest) because the set of these functionalities is not an real feature.

E.g. if in a migration you create contents that trigger WFs through a content handler in the `OC.Contents` module, but to register this handler `OC.Contents` only requires `OC.Workflows` but doesn't depend on it (in the manifest), so it is executed before the WF index table was created. Note: We could also prevent a WF execution during a migration.

I'm thinking about it since the last days, aybe time to work on it ;)

Then check if it fixes your issue by trying your repo directly

**Comment by jtkech** [comment]
Okay, i will take a look this night, thanks

**Comment by jtkech** [comment]
@jptissot 

Did not have enough time to try it directly but here what i saw

So before we were using

                await _recipeExecutor.ExecuteAsync(executionId, recipe, new Dictionary<string, object>
                {
                    { "SiteName", site.SiteName },
                    { "AdminUsername", User.Identity.Name },
                    { "AdminUserId", User.FindFirstValue(ClaimTypes.NameIdentifier) }
                },

Now we use `IRecipeEnvironmentProvider`, the `RecipeEnvironmentSiteNameProvider` provides the `SiteName`, the `RecipeEnvironmentSuperUserProvider` provides the `AdminUserId`

                var superUser = await _userService.GetUserByUniqueIdAsync(siteSettings.SuperUser);
                if (superUser != null)
                {
                    environment["AdminUserId"] = siteSettings.SuperUser;
                }

But there is no provider for the `AdminUsername`. There is the `RecipeEnvironmentFeatureProvider` that provides it through an http feature but only for a setup.

So maybe we would just need to do in the super user provider

                    var superUser = await _userService.GetUserByUniqueIdAsync(siteSettings.SuperUser);
                    if (superUser != null)
                    {
                        environment["AdminUserId"] = siteSettings.SuperUser;
                        environment["AdminUsername"] = superUser.UserName;
                    }

So maybe it just fails because of this missing property, resulting in a bad migration.

I saw that you use in your recipe

    "Author": "[js: parameters('AdminUsername')]"

Can you re-try it but by just using an hard coded value e.g. "admin"?

**Comment by jtkech** [comment]
Hi @jptissot,

I think i found a fix for this kind of issue, see my last comment in #9046

**Comment by jptissot** [comment]
Thank you @jtkech I will try it and report back :)

**Comment by jptissot** [comment]
I think it fixed the issue :)

**Comment by jtkech** [comment]
@jptissot Cool, good to know, thanks
