### ISSUE TITLE
Image src doubles and blog breaks completely in Azure

### ISSUE THREAD

**Issue by abazanov** [OrchardCMS/OrchardCore#8989]
### To Reproduce
1. Go to 'heartsunited.org.uk' and also 'heartsunited.org.uk/blog'
3. Scroll down to 'Team'

It is working fine on my local machine. I am uploading the databases as well for both instances. As soon as it is in Azure, it does not work. But it used to work. I don't know what happened. I published a second page that was using a similar Content Type. But with the blog, I really don't know what is going on. I attach error logs.

[orchard-blog-log-2021-03-26.log](https://github.com/OrchardCMS/OrchardCore/files/6211973/orchard-log-2021-03-26.2.log)
[orchard-homepage-log-2021-03-26.log](https://github.com/OrchardCMS/OrchardCore/files/6211983/orchard-log-2021-03-26.3.log)

Again, works fine on my local laptop, in Azure, blows up.

**Comment by deanmarcussen** [comment]
The dns is not resolving for your url, so couldn't actually visit the site.

From the logs i see two issue.

this one https://github.com/OrchardCMS/OrchardCore/issues/8887

which looks like it may have been resolved in later releases. 

What version of OC are you running?

There is some suggestion it maybe due to some .net upgrades.

The second one, i.e. the image src, I can see the error in the logs, but would need to know what the generated url was that is causing it?

Possibly the two are connected.

**Comment by abazanov** [comment]
Hi @deanmarcussen Thank you for replying.

That is strange. Are you unable to visit https://www.heartsunited.org.uk/ then?

I am able to see it OK. How do I check the version of OC?

Here are some screenshots.

![image](https://user-images.githubusercontent.com/5940942/112655873-be835680-8e48-11eb-977b-b4a4a9dbe4e1.png)

![image](https://user-images.githubusercontent.com/5940942/112655970-d6f37100-8e48-11eb-918c-751902c2d0dd.png)

Can you see how the src is concatenated twice?

The blog, is just a fail and nothing really. You can't see the list.

![image](https://user-images.githubusercontent.com/5940942/112656229-191cb280-8e49-11eb-91c3-b2fdb1f0e21c.png)

![image](https://user-images.githubusercontent.com/5940942/112656275-25087480-8e49-11eb-8ddf-247e210a419a.png)

But it is workign just fine on my local PC. Really strange.

**Comment by deanmarcussen** [comment]
I'm going to take a stab in the dark and suggest you're on RC2.

Here's how to upgrade to the preview feed https://docs.orchardcore.net/en/dev/docs/getting-started/preview-package-source/

@jtkech might confirm but it looks like some encoding changes in the latest dotnet security fixes may be causing the problem on earlier RC2 sites.

**Comment by abazanov** [comment]
Thanks @deanmarcussen I will give it a try and let you know.

Can I ask, once I add the preview feed, which exact packages do I need to update, and in what project? Sorry, I am not that knowledgeable about OC.

Thank you for your help.

**Comment by jtkech** [comment]
@deanmarcussen @abazanov 

I already had the `System.FormatException` (and also the concatened url issue) but in `MediaImageSharpConfiguration`, not in `MediaResizingFileProvider`, so not the same version i assume, it was trying to parse a `width` that was equals to `2048ab`, so it was failing

This when i tried (for some tests) an older OrchardCore version (from memory before Fluid 2), but because it is working now, in fact the part of code that was throwing was no more executed ;), i suspected an ISharp issue (e.g. its width command processor) that has been fixed in the meantime.

Then about the encoding issue throwing an `Index ArgumentOutOfRangeException` related to the aspnetcore `ViewBufferTextWriter`, there are others related issues, we already fixed some, yesterday i found some others workarounds that fix more or less globally other use cases, see #8984.

Note: I suspect that the weird behavior of the concatened url is somewhere related to the encoding issue

We will work on it this night ;)

**Comment by abazanov** [comment]
Thanks @jtkech for looking at it so urgently.

I downloaded the latest version of .NET SDK (dotnet-sdk-5.0.201-win-x64.exe and installed it. I also updated my Visual Studio 2019 to the very latest version as well, and now, I can reproduce the error on my workstation as well. So it is definitely tied to the latest version of .NET, because the Azure Hosting Plan would probably have the latest installed. That is what was confusing me. 

So now, I get the same error on my blog instance as some other people have...


System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Buffers.ViewBufferTextWriter.Write(Char[] buffer, Int32 index, Int32 count)
   at OrchardCore.DisplayManagement.Liquid.ViewBufferTextWriterContent.CharrArrayHtmlContent.WriteTo(TextWriter writer, HtmlEncoder encoder) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement.Liquid\ViewBufferTextWriterContent.cs:line 102
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Buffers.ViewBuffer.WriteTo(TextWriter writer, HtmlEncoder encoder)
   at OrchardCore.DisplayManagement.Liquid.HtmlContentValue.WriteTo(TextWriter writer, TextEncoder encoder, CultureInfo cultureInfo) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement.Liquid\HtmlContentValue.cs:line 61
   at Fluid.Ast.OutputStatement.WriteToAsync(TextWriter writer, TextEncoder encoder, TemplateContext context)
   at Fluid.Ast.ForStatement.WriteToAsync(TextWriter writer, TextEncoder encoder, TemplateContext context)
   at Fluid.BaseFluidTemplate`1.Awaited(ValueTask`1 task, TextWriter writer, TextEncoder encoder, TemplateContext context, List`1 statements, Int32 startIndex)
   at OrchardCore.DisplayManagement.Liquid.LiquidViewTemplate.RenderAsync(RazorPage`1 page) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement.Liquid\LiquidViewTemplate.cs:line 128
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(String partialViewName, Object model, ViewDataDictionary viewData, TextWriter writer)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.PartialAsync(String partialViewName, Object model, ViewDataDictionary viewData)
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.<ProcessAsync>g__Awaited|12_0(Task`1 task) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 296
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 116
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 174
   at CallSite.Target(Closure , CallSite , Object )
   at OrchardCore.DisplayManagement.Zones.ZoneShapes.ColumnGrouping(Object DisplayAsync, Object Shape, IShapeFactory ShapeFactory) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement\Zones\ZoneShapes.cs:line 305
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.<ProcessAsync>g__Awaited|12_0(Task`1 task) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 296
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 116
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 174
   at CallSite.Target(Closure , CallSite , Object )
   at OrchardCore.DisplayManagement.Zones.ZoneShapes.CardGrouping(Object DisplayAsync, Object Shape, IShapeFactory ShapeFactory) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement\Zones\ZoneShapes.cs:line 204
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.<ProcessAsync>g__Awaited|12_0(Task`1 task) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 296
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 116
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 174
   at CallSite.Target(Closure , CallSite , Object )
   at OrchardCore.DisplayManagement.Zones.ZoneShapes.ContentZone(Object DisplayAsync, Object Shape, IShapeFactory ShapeFactory) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement\Zones\ZoneShapes.cs:line 116
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.<ProcessAsync>g__Awaited|12_0(Task`1 task) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 296
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 116
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 174
   at OrchardCore.DisplayManagement.Liquid.Filters.LiquidViewFilters.<ShapeRender>g__Awaited|11_0(Task`1 task) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement.Liquid\Filters\LiquidViewFilters.cs:line 114
   at Fluid.Ast.FilterExpression.EvaluateAsync(TemplateContext context)
   at Fluid.Ast.OutputStatement.<WriteToAsync>g__Awaited|7_0(ValueTask`1 t, TextWriter w, TextEncoder enc, TemplateContext ctx)
   at Fluid.BaseFluidTemplate`1.Awaited(ValueTask`1 task, TextWriter writer, TextEncoder encoder, TemplateContext context, List`1 statements, Int32 startIndex)
   at OrchardCore.DisplayManagement.Liquid.LiquidViewTemplate.RenderAsync(RazorPage`1 page) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement.Liquid\LiquidViewTemplate.cs:line 128
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(String partialViewName, Object model, ViewDataDictionary viewData, TextWriter writer)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.PartialAsync(String partialViewName, Object model, ViewDataDictionary viewData)
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.<ProcessAsync>g__Awaited|12_0(Task`1 task) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 296
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 116
   at OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay.ExecuteAsync(DisplayContext context) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.DisplayManagement\Implementation\DefaultHtmlDisplay.cs:line 174
   at CallSite.Target(Closure , CallSite , Object )
   at AspNetCore._Areas_OrchardCore_Contents_Views_Item_Display.ExecuteAsync() in C:\Workspace\HUM\HUM.Web\src\OrchardCore.Modules\OrchardCore.Contents\Views\Item\Display.cshtml:line 7
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext() in C:\Workspace\HUM\HUM.Web\src\OrchardCore.Modules\OrchardCore.Diagnostics\DiagnosticsStartupFilter.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at OrchardCore.ContentPreview.PreviewStartupFilter.<>c.<<Configure>b__1_1>d.MoveNext() in C:\Workspace\HUM\HUM.Web\src\OrchardCore.Modules\OrchardCore.ContentPreview\PreviewStartupFilter.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 64
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 239
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\Workspace\HUM\HUM.Web\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 61
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

--------------------------------

The Home Page image urls are broken as per the earlier screenshots I posted above. 

I hope you guys will come up with a fix soon, because my site is not looking pretty at the moment. I am greatful for all yrou good work.

Thanks!

**Comment by jtkech** [comment]
@abazanov 

We are working on it, a workaround is coming soon, hoping it will fix your use case

**Comment by jtkech** [comment]
All, a possible workaround is coming, see #8984

**Comment by sebastienros** [comment]
I have identified the issue, and it's triggered by the newly release dotnet runtime, but the bug is in our code. I believe you are using a version of OC more recent than the nuget version since this component was added more recently. The component should be remove in the same PR JT is already working on and mentioned.

**Comment by abazanov** [comment]
To: @jtkech @sebastienros 
 
Guys, you are superstars! We are back online now. Many thanks for your super effort. And so quick as well. 

Gob bless!

**Comment by jtkech** [comment]
@abazanov no problem, thanks
