### ISSUE TITLE
Violation of PRIMARY KEY constraint 'PK__t4h_Docu__3214EC07B34ED974'. Cannot insert duplicate key in object 'dbo.t4h_Document'. The duplicate key value is (81).

### ISSUE THREAD

**Issue by bashuss** [OrchardCMS/OrchardCore#9088]
### Describe the bug
Any Admin Interface action that would create a new entry in document table states that it was successful, but actually fails. The system stays unchanged.

This is a multi tenant setup with two mandants. Development in VS2019 and a live-preview run on the same sql server data bases. Strange enough, in both databases the document table id (primary key) is not set to auto increment. Is that a yesql thing or an error that somehow manifested during a migration or a recipe (some failed during execution)?

The current max. document id was 184, so 81 is out of sync with that.

### To Reproduce in my system (always)
1. Create new user (no matter what settings)
2. Click on Save
3. The screen states that the user was successfully created
4. The user list shown stays unchanged to before step 1 even after reopening. Database is unchanged

### Stacktrace
```
2021-04-07 13:35:58.4306|Default||84cac8ee-4fdd80b5c8b67272.||OrchardCore.DisplayManagement.DisplayManager|ERROR|IDisplayDriver`1 thrown from OrchardCore.Users.Drivers.UserDisplayDriver by SqlException Microsoft.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK__t4h_Docu__3214EC07B34ED974'. Cannot insert duplicate key in object 'dbo.t4h_Document'. The duplicate key value is (81).
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 325
   at Dapper.SqlMapper.ExecuteMultiImplAsync(IDbConnection cnn, CommandDefinition command, IEnumerable multiExec) in /_/Dapper/SqlMapper.Async.cs:line 654
   at YesSql.Session.FlushAsync()
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at OrchardCore.Users.Services.UserStore.FindByNameAsync(String normalizedUserName, CancellationToken cancellationToken) in C:\Users\bernd\Desktop\tatsch-vor-helf\OrchardCore-1.0.0-rc2\src\OrchardCore\OrchardCore.Users.Core\Services\UserStore.cs:line 121
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByNameAsync(String userName)
   at Microsoft.AspNetCore.Identity.UserValidator`1.ValidateUserName(UserManager`1 manager, TUser user, ICollection`1 errors)
   at Microsoft.AspNetCore.Identity.UserValidator`1.ValidateAsync(UserManager`1 manager, TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.ValidateUserAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.UpdateUserAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.SetEmailAsync(TUser user, String email)
   at OrchardCore.Users.Drivers.UserDisplayDriver.UpdateAsync(User user, UpdateEditorContext context) in C:\Users\bernd\Desktop\tatsch-vor-helf\OrchardCore-1.0.0-rc2\src\OrchardCore.Modules\OrchardCore.Users\Drivers\UserDisplayDriver.cs:line 128
   at OrchardCore.DisplayManagement.DisplayManager`1.<>c.<<UpdateEditorAsync>b__7_0>d.MoveNext() in C:\Users\bernd\Desktop\tatsch-vor-helf\OrchardCore-1.0.0-rc2\src\OrchardCore\OrchardCore.DisplayManagement\DisplayManager.cs:line 133
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1,T2](IEnumerable`1 events, Func`4 dispatch, T1 arg1, T2 arg2, ILogger logger) in C:\Users\bernd\Desktop\tatsch-vor-helf\OrchardCore-1.0.0-rc2\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 151
ClientConnectionId:8489809b-081d-41f8-90aa-414363a2b5e2
Error Number:2627,State:1,Class:14    at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 325
   at Dapper.SqlMapper.ExecuteMultiImplAsync(IDbConnection cnn, CommandDefinition command, IEnumerable multiExec) in /_/Dapper/SqlMapper.Async.cs:line 654
   at YesSql.Session.FlushAsync()
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at OrchardCore.Users.Services.UserStore.FindByNameAsync(String normalizedUserName, CancellationToken cancellationToken) in C:\Users\bernd\Desktop\tatsch-vor-helf\OrchardCore-1.0.0-rc2\src\OrchardCore\OrchardCore.Users.Core\Services\UserStore.cs:line 121
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByNameAsync(String userName)
   at Microsoft.AspNetCore.Identity.UserValidator`1.ValidateUserName(UserManager`1 manager, TUser user, ICollection`1 errors)
   at Microsoft.AspNetCore.Identity.UserValidator`1.ValidateAsync(UserManager`1 manager, TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.ValidateUserAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.UpdateUserAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.SetEmailAsync(TUser user, String email)
   at OrchardCore.Users.Drivers.UserDisplayDriver.UpdateAsync(User user, UpdateEditorContext context) in C:\Users\bernd\Desktop\tatsch-vor-helf\OrchardCore-1.0.0-rc2\src\OrchardCore.Modules\OrchardCore.Users\Drivers\UserDisplayDriver.cs:line 128
   at OrchardCore.DisplayManagement.DisplayManager`1.<>c.<<UpdateEditorAsync>b__7_0>d.MoveNext() in C:\Users\bernd\Desktop\tatsch-vor-helf\OrchardCore-1.0.0-rc2\src\OrchardCore\OrchardCore.DisplayManagement\DisplayManager.cs:line 133
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1,T2](IEnumerable`1 events, Func`4 dispatch, T1 arg1, T2 arg2, ILogger logger) in C:\Users\bernd\Desktop\tatsch-vor-helf\OrchardCore-1.0.0-rc2\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\InvokeExtensions.cs:line 151
```

**Comment by jtkech** [comment]
Which version?

Just tried it works on my side but with the last dev branch

**Comment by bashuss** [comment]
I am quite sure that it will work in your version. It seems very much like the real trouble is that something damaged the database or keeps it out of sync somehow.
So I guess this is just a symptom of a problem that happend before.

I was the official stable RC2 version. Main Project shows 1.0.0.0

Can you check for me, if the primary key of the documents table is supposed to have auto increment turned on or off? It is off in both of my databases. But as there is a unique constraint on the key, something has to take care, that it gets a unique value on insert commands ... so either this is orchard, yesql or the db-server itself.

I need to identify, where it happens, so I can get my project to work again.
================

My guess is that having two instances of orchard run on the same database may cause this. (development and live preview).

**Comment by deanmarcussen** [comment]
The primary key should be auto increment off.

YesSql uses the Identifiers table to generate id blocks. You may want to see if something has going missing with that table.

**Comment by bashuss** [comment]
So I shut down both instances of orchard core and only restarted one of them from VisualStudio.
Before the Identifiers table with the same prefixes as the documents table showed just one entry with two columns:
dimension: <null>
nextval: 201
The 201 was a few ids above the last used id in document table.

I tried inserting users as shown above. The first time it failed with the same error, the second time it succeeded. Also another User could be inserted without a problem. The ids of the inserted users were 142 and 143 though.
The entry in the Identifiers table did not change.

So I guess the next id is either queried on demand or there is an in memory pointer to the next id, which would make it likely to fail, if two instances run at the same time and both insert documents.

**Comment by jtkech** [comment]
@bashuss 

Normally each instance try to lease its own range of numbers ( a block of 20 values)
https://github.com/sebastienros/yessql/blob/1d04a007d893f0287ecc721f087d4f9764f9c90f/src/YesSql.Core/Services/DbBlockIdGenerator.cs#L121

                // Ensure we overwrite the value that has been read by this
                // instance in case another client is trying to lease a range
                // at the same time

When a given instance reaches the end of its block it tries to lease a new block

Yes, i could repro the exact same issue if i update manually the `nextval` to a value < max id - 20 and restart the app

Then, if i update again the `nextval` to a value > max id and **restart the app**, it works again

So, maybe the `Identifiers` table was not updated correctly at some point, not necessarily because of concurrent updates (there are 20 retries), maybe more because of a network issue, which would explain that at some point another instance leases the same block of ids or an overlapped one.

At least, i think that when restarting the app we would need to check that the `nextval` is not lower than the max id of the related document table, and if so maybe restart the internal cursor to the max id + 1 block size, and update the nextval to the max id + 2 block size, need more thinkings.

Can you open an issue on the YesSql repo?

**Comment by bashuss** [comment]
Yes, I will open a new issue there.

It is great, that you found a way to reproduce the symptom. In my opinion, it would also be necessary to have this kind of error notified to the (admin-) user. It is very frustrating, if orchard appears frozen to changes, but tells you that all is fine.

One thing still seems a bit strange to me. The way I understand your explanation, the 20 id leases is a block that is upended after the nextval value the instance finds when it needs a new block. This would not explain, why the newly generated ids were below maxid. 
Is there a recovering mechanism of unused Ids?
If so, this is not reflected in the database and therefore prone to create this type of error.

I'll switch to YesSql now.

**Comment by jtkech** [comment]
> This would not explain, why the newly generated ids were below maxid.

Because it is not aware of this maxid, after restarting on the 1rst update it only reads the current nextval and leases a new block from it, what we could do at least before leasing a new block is to check if the current maxid >= nextval.

**Comment by Piedone** [comment]
There seems to be nothing else to do here.
