### ISSUE TITLE
ConcurrencyException thrown by OrchardCore.Contents.Workflows.Handlers.ContentsHandler

### ISSUE THREAD

**Issue by scleaver** [OrchardCMS/OrchardCore#9093]
I am pretty sure this is my issues in particular but just in case!

I am seeing some ConcurrencyException in production similar to https://github.com/OrchardCMS/OrchardCore/issues/7449 it is coming from a section of code that creates content via the API. This works perfectly fine using SQL Server locally but as soon as it is up in PRD - BOOM!

```
OrchardCore.ContentManagement.DefaultContentManager|ERROR|IContentHandler thrown from OrchardCore.Contents.Workflows.Handlers.ContentsHandler by ConcurrencyException YesSql.ConcurrencyException: The document could not be updated as it has been changed by another process.
   at YesSql.Commands.UpdateDocumentCommand.ExecuteAsync(DbConnection connection, DbTransaction transaction, ISqlDialect dialect, ILogger logger)
   at YesSql.Session.FlushAsync()
   at YesSql.Services.DefaultQuery.Query`1.ListImpl()
   at OrchardCore.Workflows.Services.WorkflowManager.TriggerEventAsync(String name, IDictionary`2 input, String correlationId, Boolean isExclusive, Boolean isAlwaysCorrelated)
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger)    at YesSql.Commands.UpdateDocumentCommand.ExecuteAsync(DbConnection connection, DbTransaction transaction, ISqlDialect dialect, ILogger logger)
   at YesSql.Session.FlushAsync()
   at YesSql.Services.DefaultQuery.Query`1.ListImpl()
   at OrchardCore.Workflows.Services.WorkflowManager.TriggerEventAsync(String name, IDictionary`2 input, String correlationId, Boolean isExclusive, Boolean isAlwaysCorrelated)
   at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger)
```
then occassionally

```
OrchardCore.Modules.ModularBackgroundService|ERROR|Error while processing background task 'Kast.Connectivity.Services.DataSyncExecutorBackgroundTask' on tenant 'XXX'. YesSql.ConcurrencyException: The document could not be updated as it has been changed by another process.
   at YesSql.Commands.UpdateDocumentCommand.ExecuteAsync(DbConnection connection, DbTransaction transaction, ISqlDialect dialect, ILogger logger)
   at YesSql.Session.FlushAsync()
   at YesSql.Services.DefaultQuery.Query`1.ListImpl()
   at Kast.Connectivity.Elvanto.Providers.PullGroupsDataSyncProvider.RunAsync() ....
```

I did recently deploy some enhancements to this section code but rolling back to an earlier code base does not fix the issue.

The bizarrest thing occurred though... I saw one of the content items being created via the API created then disappear in the admin UI on next refresh.

Build is 1.0.0-rc2-15886

**Comment by scleaver** [comment]
This is the code base I am on at present https://github.com/OrchardCMS/OrchardCore/tree/eda07c1a7ad92e97fcadf3aa0a823b4464142012

Looks like there has been a lot of commits since then.

**Comment by scleaver** [comment]
This is my code issue - closing.
