### ISSUE TITLE
Exception thrown with the latest version.

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#9222]
Creating the ticket to not forget about this issue: 
See https://github.com/StatCan/StatCan.OrchardCore/runs/2375122578?check_suite_focus=true#step:7:217

```
fail: OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay[0]
      => SpanId:43d89afb404f324b, TraceId:609990e5e9197e449cd123aad201de22, ParentId:0000000000000000 => ConnectionId:0HM82HFJLO2PM => RequestPath:/t1fomn8s/ RequestId:0HM82HFJLO2PM:00000009 => OrchardCore.Diagnostics.Controllers.DiagnosticsController.Error (OrchardCore.Diagnostics)
      Func`2 thrown from System.Func`2[[OrchardCore.DisplayManagement.Implementation.ShapeDisplayContext, OrchardCore.DisplayManagement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Threading.Tasks.Task, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] by NpgsqlOperationInProgressException
      Npgsql.NpgsqlOperationInProgressException (0x80004005): A command is already in progress: SELECT "t1fomn8s_Document".* FROM "t1fomn8s_Document" INNER JOIN "t1fomn8s_ContentItemIndex" AS "ContentItemIndex_a1" ON "ContentItemIndex_a1"."DocumentId" = "t1fomn8s_Document"."Id" WHERE (("ContentItemIndex_a1"."ContentItemId" = @p0) and ("ContentItemIndex_a1"."Published" = @p1)) limit 1
         at Npgsql.NpgsqlConnector.<StartUserAction>g__DoStartUserAction|233_0(<>c__DisplayClass233_0& )
         at Npgsql.NpgsqlConnector.StartUserAction(ConnectorState newState, NpgsqlCommand command, CancellationToken cancellationToken, Boolean attemptPgCancellation)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 418
         at YesSql.Store.ProduceAsync[T,TState](WorkerQueryKey key, Func`2 work, TState state)
         at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
         at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
         at OrchardCore.Alias.Services.AliasPartContentHandleHelper.QueryAliasIndex(ISession session, String alias)
         at OrchardCore.Alias.Services.AliasPartContentHandleProvider.GetContentItemIdAsync(String handle)
         at OrchardCore.ContentManagement.ContentHandleManager.GetContentItemIdAsync(String handle)
         at OrchardCore.Menu.MenuShapes.<>c.<<Discover>b__0_0>d.MoveNext()
      --- End of stack trace from previous location ---
         at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger)
fail: OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay[0]
      => SpanId:9a5b9d8b359e224b, TraceId:edaf1c5f625273489569407ab5a90275, ParentId:0000000000000000 => ConnectionId:0HM82HFJLO2PK => RequestPath:/t1fomn8s/login RequestId:0HM82HFJLO2PK:0000000E => OrchardCore.Users.Controllers.AccountController.Login (OrchardCore.Users)
      Func`2 thrown from System.Func`2[[OrchardCore.DisplayManagement.Implementation.ShapeDisplayContext, OrchardCore.DisplayManagement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Threading.Tasks.Task, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] by NpgsqlOperationInProgressException
      Npgsql.NpgsqlOperationInProgressException (0x80004005): A command is already in progress: SELECT "t1fomn8s_Document".* FROM "t1fomn8s_Document" INNER JOIN "t1fomn8s_AliasPartIndex" AS "AliasPartIndex_a1" ON "AliasPartIndex_a1"."DocumentId" = "t1fomn8s_Document"."Id" WHERE ("AliasPartIndex_a1"."Alias" = @p0) limit 1
         at Npgsql.NpgsqlConnector.<StartUserAction>g__DoStartUserAction|233_0(<>c__DisplayClass233_0& )
         at Npgsql.NpgsqlConnector.StartUserAction(ConnectorState newState, NpgsqlCommand command, CancellationToken cancellationToken, Boolean attemptPgCancellation)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 418
         at YesSql.Store.ProduceAsync[T,TState](WorkerQueryKey key, Func`2 work, TState state)
         at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
         at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
         at OrchardCore.Alias.Services.AliasPartContentHandleHelper.QueryAliasIndex(ISession session, String alias)
         at OrchardCore.Alias.Services.AliasPartContentHandleProvider.GetContentItemIdAsync(String handle)
         at OrchardCore.ContentManagement.ContentHandleManager.GetContentItemIdAsync(String handle)
         at OrchardCore.Menu.MenuShapes.<>c.<<Discover>b__0_0>d.MoveNext()
      --- End of stack trace from previous location ---
         at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger)
fail: OrchardCore.DisplayManagement.Implementation.DefaultHtmlDisplay[0]
      => SpanId:712c5b057d6b5446, TraceId:3ff5333287261344a6832021bb9eabe7, ParentId:0000000000000000 => ConnectionId:0HM82HFJLO2PN => RequestPath:/t1fomn8s/ RequestId:0HM82HFJLO2PN:00000009 => OrchardCore.Diagnostics.Controllers.DiagnosticsController.Error (OrchardCore.Diagnostics)
      Func`2 thrown from System.Func`2[[OrchardCore.DisplayManagement.Implementation.ShapeDisplayContext, OrchardCore.DisplayManagement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Threading.Tasks.Task, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] by NpgsqlOperationInProgressException
      Npgsql.NpgsqlOperationInProgressException (0x80004005): A command is already in progress: SELECT "t1fomn8s_Document".* FROM "t1fomn8s_Document" INNER JOIN "t1fomn8s_AliasPartIndex" AS "AliasPartIndex_a1" ON "AliasPartIndex_a1"."DocumentId" = "t1fomn8s_Document"."Id" WHERE ("AliasPartIndex_a1"."Alias" = @p0) limit 1
         at Npgsql.NpgsqlConnector.<StartUserAction>g__DoStartUserAction|233_0(<>c__DisplayClass233_0& )
         at Npgsql.NpgsqlConnector.StartUserAction(ConnectorState newState, NpgsqlCommand command, CancellationToken cancellationToken, Boolean attemptPgCancellation)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 418
         at YesSql.Store.ProduceAsync[T,TState](WorkerQueryKey key, Func`2 work, TState state)
         at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
         at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
         at OrchardCore.Alias.Services.AliasPartContentHandleHelper.QueryAliasIndex(ISession session, String alias)
         at OrchardCore.Alias.Services.AliasPartContentHandleProvider.GetContentItemIdAsync(String handle)
         at OrchardCore.ContentManagement.ContentHandleManager.GetContentItemIdAsync(String handle)
         at OrchardCore.Menu.MenuShapes.<>c.<<Discover>b__0_0>d.MoveNext()
      --- End of stack trace from previous location ---
         at OrchardCore.Modules.InvokeExtensions.InvokeAsync[TEvents,T1](IEnumerable`1 events, Func`3 dispatch, T1 arg1, ILogger logger)
```

**Comment by jtkech** [comment]
@jptissot 

Just noticed that you also have a non awaited migration here https://github.com/StatCan/StatCan.OrchardCore/blob/64f6cb0e05e5aa4ed2dc718cdb82bca3c145257d/src/Themes/HackathonTheme/Migrations.cs#L25

and an async void here https://github.com/StatCan/StatCan.OrchardCore/blob/64f6cb0e05e5aa4ed2dc718cdb82bca3c145257d/src/Themes/HackathonTheme/Migrations.cs#L64

**Comment by jptissot** [comment]
Thank you, fixed :)

**Comment by jptissot** [comment]
I made a new PR to track this issue.

https://github.com/StatCan/StatCan.OrchardCore/pull/230

**Comment by jptissot** [comment]
@jtkech I am pretty sure the bug was introduced in this pr: https://github.com/OrchardCMS/OrchardCore/pull/9005

**Comment by jtkech** [comment]
Yes but normally it has been fixed in the meantime but you need a version higher than rc2-16116

Just installed postgreSQL and fetched your `update_oc` branch and tried the `vuetify-saas-setup` recipe

The setup was not completing at all without any logs, as we saw for our headless recipe before the fix

Then i tried it with the last rc2-16126, and all seems to work

**Comment by jtkech** [comment]
I'm doing manually step by step what is done in the `hackathon.js` func test ;)

**Comment by jtkech** [comment]
But too complex to follow ;)

So i did a new setup with the `digital-theme-setup` recipe

And i could repro your above postgreSQL issue => `A command is already in progress`

So, i now have something to work on ;)

**Comment by jptissot** [comment]
I am pretty sure this issue stems from this fluid pr: https://github.com/sebastienros/fluid/pull/303

**Comment by jptissot** [comment]
We did some test with @jtkech and cloned the fluid repository reverted the changes https://github.com/sebastienros/fluid/pull/303 and all my tests now pass.

**Comment by jptissot** [comment]
This commit fixes the issue: https://github.com/sebastienros/fluid/commit/9066957e5117447bed4084b7d1100527058cfbdb
