### ISSUE TITLE
Deploying Ochard Core as a headless CMS with Docker

### ISSUE THREAD

**Issue by sddev-dotnet** [OrchardCMS/OrchardCore#9225]
### Describe the bug
I am deploying a preinstalled website into a docker image for deployment to Azure Kubernetes Service. The site was previously hosted using Azure App Services, so there is a database present already. I can build and run the docker image locally (using Windows Subsystem for Linux with Ubuntu) and I have no problems, but when the container tries to run in my AKS cluster, I get the following error: 

```
Connection id "0HM821IJI0AU5", Request id "0HM821IJI0AU5:00000001": An unhandled exception was thrown by the application.
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at OrchardCore.Environment.Shell.Builders.ServiceProviderExtensions.CreateChildContainer(IServiceProvider serviceProvider, IServiceCollection serviceCollection)
   at OrchardCore.Environment.Shell.Builders.ShellContainerFactory.CreateContainer(ShellSettings settings, ShellBlueprint blueprint)
   at OrchardCore.Environment.Shell.Builders.ShellContextFactory.CreateDescribedContextAsync(ShellSettings settings, ShellDescriptor shellDescriptor)
   at OrchardCore.Shells.Database.Configuration.DatabaseShellsSettingsSources.AddSourcesAsync(IConfigurationBuilder builder)
   at OrchardCore.Environment.Shell.Configuration.ShellsSettingsSourcesExtensions.AddSourcesAsync(IConfigurationBuilder builder, IShellsSettingsSources sources)
   at OrchardCore.Environment.Shell.ShellSettingsManager.LoadSettingsAsync(String tenant)
   at OrchardCore.Environment.Shell.Distributed.DistributedShellHostedService.LoadingAsync()
   at OrchardCore.Environment.Shell.ShellHost.PreCreateAndRegisterShellsAsync()
   at OrchardCore.Environment.Shell.ShellHost.InitializeAsync()
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

I have tried using the following Options:
- OrchardCore.Autosetup - This successfully creates a new instance, but doesn't work if the database exists already
- Azure Shells Configuration Provider - I can see my App_Data content in the blob container, but it doesn't seem to handle ContentDefinitions.json properly. I get a null reference exception related to content types
- Database Shells Configuration Provider - sames as the Azure Shells one

Here is my startup file: 
```
public class Startup
    {
        private IConfiguration _config;
        public Startup(IConfiguration configuration)
        {
            _config = configuration;
        }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddLogging(x => x.AddConsole());
            services.AddOrchardCms()
                //.AddSetupFeatures("OrchardCore.AutoSetup")
                .AddAzureShellsConfiguration();
            services.AddCors();
            services.AddApplicationInsightsTelemetry(_config.GetValue<string>("ApplicationInsights:TelemetryKey"));
            services.AddApplicationInsightsKubernetesEnricher();
        }
        
        public void Configure(IApplicationBuilder app, IHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseCors(x => x.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader());
            app.UseStaticFiles();
            app.UseOrchardCore();
        }
    }
```

and the settings in appsettings.json (inside the OrchardCore object)
```
 "OrchardCore_Shells_Azure": {
      "ConnectionString": "DefaultEndpointsProtocol=https;AccountName....", // Set to your Azure Storage account connection string.
      "ContainerName": "privateweb", // Set to the Azure Blob container name.
      "BasePath": "app_data", // Optionally, set to a subdirectory inside your container.
      "MigrateFromFiles": false // Optionally, enable to migrate existing App_Data files to Blob automatically.
    }
```
and here is my Dockerfile
```
FROM mcr.microsoft.com/dotnet/sdk:3.1 as build


WORKDIR /src
COPY ./ ./

# Restore Nuget packages
RUN dotnet restore --configfile ./Nuget.config ./SDDev.Net.Admin.sln 


RUN dotnet publish -c Release -o /publish



#Publish stage
# To enable ssh & remote debugging on app service change the base image to the one below
# FROM mcr.microsoft.com/azure-functions/dotnet:2.0-appservice 
FROM mcr.microsoft.com/dotnet/aspnet:3.1

RUN apt-get update \
    && apt-get install -y --allow-unauthenticated \
        libc6-dev \
        libgdiplus \
        libx11-dev \
     && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=build /publish  ./
COPY --from=build /src/devops/App_Data  /App_Data

ENV ORCHARD_APP_DATA=/App_Data
RUN chmod 644 /App_Data


ENTRYPOINT ["dotnet", "SDDev.Net.Admin.dll"]
```

### Expected behavior
Expected the container to startup and run properly in Azure AKS.

**Comment by jtkech** [comment]
> but it doesn't seem to handle ContentDefinitions.json properly

For info it is in a file by defaut because we enable the related feature `OrchardCore.Contents.FileContentDefinition` in our recipes, if this feature is not enabled the definitions are in the database.

For an existing database, you need to export the definitions while the above feature is still enabled, and then import them while the above feature is not enable.

**Comment by Piedone** [comment]
What JT recommends is now also documented: https://docs.orchardcore.net/en/latest/guides/content-definitions/
