### ISSUE TITLE
Interlock problem between access token request and and update user request

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/OrchardCore#9698]
### Describe the bug
I've been able to get log related to another scenario where interlocks happen.

When an opein id access token requests an access token using password flow and a concurrent  request is updating an user happens this interlock. The scenario is not very relevant I think, the important part of this is I can show you the sqls of a concurrent scenario where two concurrent requests accessing different records cause an interlock. The log contains the value of the params so you can check interlocked queries are not related to same records, however problem is they compete for owning same indexes. 

In the log I attach you can see changes on table UserByRoleNameIndex. Take into account that it is not a reduce index, I transformed it to map index, in order to avoid another interlock problem caused by reduce indexes, which I reported on another issue https://github.com/OrchardCMS/OrchardCore/issues/9639

### Screenshots
I show you here mixed info from sql profiler and from logs. It shows relevant info related to two concurrent procceses interlocked, you can see together with the log of each request also the resource which owns each one and the resource each one requires to continue. Causing the interlock.

```
REQUEST 1
OWNS 
	Object: UserIndex 
	Index: IDX_UserIndex_DocumentId
REQUESTS 
	Object: Document
	Index: PK
	
2021-06-15 23:32:10.1660|[26]|Default|00-beb502a3b76c374eb465233910b6f712-4d7be08f8ceac040-00||Server.Extensions.DbAccess.DapperConnectionWithSQLLoggerFactory|INFO|Dapper query:
"delete from [UserIndex] where [DocumentId] = @Id_1;
delete from [UserByRoleNameIndex] where [DocumentId] = @Id_2;
delete from [UserByLoginInfoIndex] where [DocumentId] = @Id_3;
delete from [UserByClaimIndex] where [DocumentId] = @Id_4;
insert into [UserIndex] ([UserId], [NormalizedUserName], [NormalizedEmail], [IsEnabled], [IsLockoutEnabled], [LockoutEndUtc], [AccessFailedCount], [DocumentId]) 
values (@UserId7, @NormalizedUserName7, @NormalizedEmail7, @IsEnabled7, @IsLockoutEnabled7, @LockoutEndUtc7, @AccessFailedCount7, @DocumentId7) ; 
select SCOPE_IDENTITY() [Id];
insert into [UserByRoleNameIndex] ([RoleName], [DocumentId]) values (@RoleName8, @DocumentId8) ; 
select SCOPE_IDENTITY() [Id];
insert into [UserByRoleNameIndex] ([RoleName], [DocumentId]) values (@RoleName9, @DocumentId9) ; 
select SCOPE_IDENTITY() [Id];
values (@ConsumerOID10, @PhoneNumber10, @ProviderOID10, @DocumentId10) ; 
select SCOPE_IDENTITY() [Id];update [Document] set [Content] = @Content_11, [Version] = @Version_11 where [Id] = @Id_11;"
Parameters: "[Id_1, 101], [Id_2, 101], [Id_3, 101], [Id_4, 101], [Id_5, 101], [Id_6, 101], [DocumentId7, 101], [AccessFailedCount7, 0], 
[LockoutEndUtc7, <null>], [IsLockoutEnabled7, True], [IsEnabled7, True], 
[NormalizedEmail7, PROVIDER.CONSUMERREQUESTPROVIDERINFOBYEMAILANDNORESULTSWEREFOUND@PCCOM.ES], 
[NormalizedUserName7, PROVIDER.CONSUMERREQUESTPROVIDERINFOBYEMAILANDNORESULTSWEREFOUND], [UserId7, 4vrjh3nm8gbzntnkm18hfmezxy], 
[DocumentId8, 101], [RoleName8, PENDING PROVIDER USER], [DocumentId9, 101], [RoleName9, NO PROVIDER USER], [DocumentId10, 101], 
[ProviderOID10, 0], [PhoneNumber10, <null>], [ConsumerOID10, 0], [Version_11, 1], 
[Content_11, {"Id":101,"UserId":"4vrjh3nm8gbzntnkm18hfmezxy","UserName":"provider.consumerRequestProviderInfoByEmailAndNoResultsWereFound","NormalizedUserName":"PROVIDER.CONSUMERREQUESTPROVIDERINFOBYEMAILANDNORESULTSWEREFOUND","Email":"provider.consumerRequestProviderInfoByEmailAndNoResultsWereFound@pccom.es","NormalizedEmail":"PROVIDER.CONSUMERREQUESTPROVIDERINFOBYEMAILANDNORESULTSWEREFOUND@PCCOM.ES","PasswordHash":"AQAAAAEAACcQAAAAELEe2rc9//UOM3BAIO6yYJQMpH3lcObkPkeAjqmr/tJdBZb5G3x/boV5o+jXxjh8EQ==","SecurityStamp":"XDE7VWTGFWUDU3FMPOIVXUVNOSKQRBPK","EmailConfirmed":true,"IsEnabled":true,"IsLockoutEnabled":true,"AccessFailedCount":0,"RoleNames":["PENDING PROVIDER USER","NO PROVIDER USER"],"UserClaims":[],"LoginInfos":[],"UserTokens":[],"Properties":{"UserProfile":{"UserTypes":[1],"Name":"provider.consumerRequestProviderInfoByEmailAndNoResultsWereFound","NewEmailRequested":null,"IsPhoneConfirmed":false,"PhoneNumber":null,"NewPhoneNumberRequested":null,"ConsumerOID":0,"ProviderOID":0}}}], 
[Id_11, 101]", elapsed: 0 ms, context: "Empty", connection: "Empty" 
```
```
REQUEST 2
OWNS 
	Object: Document
	Index: PK
REQUESTS 
	Object: UserIndex 
	Index: IDX_UserIndex_DocumentId
	
2021-06-15 23:32:10.1660|[21]|Default|00-a5e91186c5946041900adbbf30bf07d5-9a0622edc659d148-00||Server.Extensions.DbAccess.DapperConnectionWithSQLLoggerFactory|INFO|Dapper query:
"SELECT TOP (1) [Document].* FROM [Document] INNER JOIN [UserIndex] AS [UserIndex_a1] ON [UserIndex_a1].[DocumentId] = [Document].[Id] WHERE ([UserIndex_a1].[NormalizedUserName] = @p0)"
Parameters: "[p0, CONSUMER.CONSUMERREQUESTPROVIDERINFOBYPHONEANDNORESULTSWEREFOUND]", elapsed: 0 ms, context: "Empty", connection: "Empty" 
2021-06-15 23:32:10.1865|[9]|Default|00-b523360830fde64684e36ad84181fd0b-9db04f99195c0048-00||Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|ERROR|An unhandled exception has occurred while executing the request. Microsoft.Data.SqlClient.SqlException (0x80131904): La transacción (id. de proceso 55) quedó en interbloqueo en bloqueo recursos con otro proceso y fue elegida como sujeto del interbloqueo. Ejecute de nuevo la transacción.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.ReadAsyncExecute(Task task, Object state)
   at Microsoft.Data.SqlClient.SqlDataReader.InvokeAsyncCall[T](AAsyncCallContext`1 context)
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 436
   at YesSql.Store.ProduceAsync[T,TState](WorkerQueryKey key, Func`2 work, TState state)
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at OrchardCore.Users.Services.UserStore.FindByNameAsync(String normalizedUserName, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByNameAsync(String userName)
   at OrchardCore.Users.Services.UserService.AuthenticateAsync(String userName, String password, Action`2 reportError)
   at OrchardCore.OpenId.Controllers.AccessController.ExchangePasswordGrantType(OpenIddictRequest request)
   at Server.UsersWebAPI.Authentication_Controllers.OverrideAccesController.Token() in D:\PROYECTOS\Server\Server.Modules\Server.UsersWebAPI\0 Authentication Controllers\OverrideAccesController.cs:line 114
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
ClientConnectionId:4076a1ca-abd8-4b91-87d3-38ab8d386cd1
Error Number:1205,State:51,Class:13    at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.ReadAsyncExecute(Task task, Object state)
   at Microsoft.Data.SqlClient.SqlDataReader.InvokeAsyncCall[T](AAsyncCallContext`1 context)
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 436
   at YesSql.Store.ProduceAsync[T,TState](WorkerQueryKey key, Func`2 work, TState state)
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at YesSql.Services.DefaultQuery.Query`1.FirstOrDefaultImpl()
   at OrchardCore.Users.Services.UserStore.FindByNameAsync(String normalizedUserName, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByNameAsync(String userName)
   at OrchardCore.Users.Services.UserService.AuthenticateAsync(String userName, String password, Action`2 reportError)
   at OrchardCore.OpenId.Controllers.AccessController.ExchangePasswordGrantType(OpenIddictRequest request)
   at Server.UsersWebAPI.Authentication_Controllers.OverrideAccesController.Token() in D:\PROYECTOS\Server\Server.Modules\Server.UsersWebAPI\0 Authentication Controllers\OverrideAccesController.cs:line 114
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

Could be this caused by inserting and reading at the same time same table from two concurrent requests despite we use read uncommited isolation level?

**Comment by jersiovic** [comment]
Taking a look to execution plans of the queries, it seems clear following queries are those which cause the interlock:

This  insert makes the transaction needs to own all indexes defined for UserIndex table for updating them. 
`insert into [UserIndex] ([UserId], [NormalizedUserName], [NormalizedEmail], [IsEnabled], [IsLockoutEnabled], [LockoutEndUtc], [AccessFailedCount], [DocumentId]) 
values (@UserId7, @NormalizedUserName7, @NormalizedEmail7, @IsEnabled7, @IsLockoutEnabled7, @LockoutEndUtc7, @AccessFailedCount7, @DocumentId7) ;`
This should not be a problem. Problem is in the same transaction this update also needs to own  Index PK at Document 	table
`update [Document] set [Content] = @Content_11, [Version] = @Version_11 where [Id] = @Id_11;"`

That interlocks the other concurrent request because it executes following query which requests IDX_UserIndex_DocumentId at UserIndex table and Index PK at Document table: 
`
SELECT TOP (1) [Document].* 
FROM [Document] 
INNER JOIN UserIndex] AS [UserIndex_a1] 
WITH (INDEX(IDX_FK_UserIndex))
ON [UserIndex_a1].[DocumentId] = [Document].[Id] 
WHERE ([UserIndex_a1].[NormalizedUserName] = 'CONSUMER.CONSUMERREQUESTPROVIDERINFOBYPHONEANDNORESULTSWEREFOUND')
`

**Comment by jersiovic** [comment]
With that in mind the only solution I'm able to think is to split innto two the transaction for flushing changes.
One for updating indexes and the other for updating documents.
If sth fail updating documents we can take actions to restore previous state cause in document tables we still will have original data and with it we can restore original values for indexes.

Do you have a better solution than this?

**Comment by sebastienros** [comment]
I am not sure it's a good solution
- What do you do if it fails to restore the original data?
- What if another query happens between the two transactions?

**Comment by jersiovic** [comment]
To avoid that problem only think I can think is to have version number on index tables and at document table keep as many versions of a document as savechanges operations are in course. 
The foreign key at index table will be composed of the document id and the document version.
For new document operations we will use 2 commits. First commit first the insert at document table. Next the insert at indexes tables.
For  update document operatios we will use 3 commits. First commit add a new document with changes for next document version. Next we will commit changes on index tables , after this commit no index pointing to old version document. Next a commit for removing old version document.
For delete document operations we will use 2 commits. First we will commit the operation for removing indexes pointing to that version of the document. Next a commit for removing the docume t with that version.

For queries to db not based on indexes we will return only last version of a document.
For queries based on indexes internally we wil do a left join between index table and document table, returning only las version of each document with more than one version. (With a group by.. having query)

With this strategy if second commit or third commit fails, no big problem to left db consistent, cause we can remove all record added on previous commits and throw an exception.

**Comment by jersiovic** [comment]
@sebastienros what do you think of my last proposal? I could  try to work on it for a PR but it is useless if you don't agree on the solution
