### ISSUE TITLE
ResourceManager, randomly NullReferenceException when load stylesheet

### ISSUE THREAD

**Issue by PiemP** [OrchardCMS/OrchardCore#9842]
### Describe the bug

I don't know if this issue can be reproduced in the dev code because I don't update my OrchardCore code from December 2020 and I see some changes in the `ResourceManager` class.

Randomly the site loose all the CSS reference and it's rendered without style. Need to restart IIS to solve the problem. 
```
2021-07-02 11:59:50.8935-ERROR||5db74bac-4f62171e1c10217d.||OrchardCore.ResourceManagement.TagHelpers.ResourcesTagHelper|An error occurred while rendering Stylesheet resource. System.NullReferenceException: Object reference not set to an instance of an object.
   at OrchardCore.ResourceManagement.ResourceManager.ExpandDependencies(ResourceDefinition resource, RequireSettings settings, OrderedDictionary allResources) in \OrchardCore\OrchardCore.ResourceManagement\ResourceManager.cs:line 419
   at OrchardCore.ResourceManagement.ResourceManager.DoGetRequiredResources(String resourceType) in \OrchardCore\OrchardCore.ResourceManagement\ResourceManager.cs:line 395
   at OrchardCore.ResourceManagement.ResourceManager.RenderStylesheet(IHtmlContentBuilder builder) in \OrchardCore\OrchardCore.ResourceManagement\ResourceManager.cs:line 572
   at OrchardCore.ResourceManagement.TagHelpers.ResourcesTagHelper.Process(TagHelperContext tagHelperContext, TagHelperOutput output) in \OrchardCore\OrchardCore.ResourceManagement\TagHelpers\ResourcesTagHelper.cs:line 83    at OrchardCore.ResourceManagement.ResourceManager.ExpandDependencies(ResourceDefinition resource, RequireSettings settings, OrderedDictionary allResources) in \OrchardCore\OrchardCore.ResourceManagement\ResourceManager.cs:line 419
   at OrchardCore.ResourceManagement.ResourceManager.DoGetRequiredResources(String resourceType) in \OrchardCore\OrchardCore.ResourceManagement\ResourceManager.cs:line 395
   at OrchardCore.ResourceManagement.ResourceManager.RenderStylesheet(IHtmlContentBuilder builder) in \OrchardCore\OrchardCore.ResourceManagement\ResourceManager.cs:line 572
   at OrchardCore.ResourceManagement.TagHelpers.ResourcesTagHelper.Process(TagHelperContext tagHelperContext, TagHelperOutput output) in \OrchardCore\OrchardCore.ResourceManagement\TagHelpers\ResourcesTagHelper.cs:line 83
```

### To Reproduce

Windows Server 2019
IIS 10.0.17763.1
OrchardCore SaaS  - execution InProcess

### Expected behavior

See the site always with all CSS like happen often.

Sorry for the less details. I have found the exception this morning but I can't understand where it come out.

**Comment by PiemP** [comment]
I try to merge #7951 to my code

**Comment by Piedone** [comment]
I assume after https://github.com/OrchardCMS/OrchardCore/pull/7951 this if fixed. If not, please reopen.
