### ISSUE TITLE
GraphQL TypeLoadException

### ISSUE THREAD

**Issue by avestura** [OrchardCMS/OrchardCore#9968]
### Describe the bug

Following [Getting Started](https://docs.orchardcore.net/en/latest/docs/getting-started/) documentation gives ` System.TypeLoadException: Could not load type 'GraphQL.Conversion.IFieldNameConverter' from assembly 'GraphQL, Version=4.5.0.0, Culture=neutral, PublicKeyToken=null'.` error.

### To Reproduce
1. Follow [Getting Started](https://docs.orchardcore.net/en/latest/docs/getting-started/) documentation.
2. Launch your application

### Expected behavior
The site should be up and asking for initial input like the title of the site.

### Error
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.TypeLoadException: Could not load type 'GraphQL.Conversion.IFieldNameConverter' from assembly 'GraphQL, Version=4.5.0.0, Culture=neutral, PublicKeyToken=null'.
         at System.Reflection.RuntimeAssembly.GetExportedTypes()
         at System.Reflection.Assembly.get_ExportedTypes()
         at OrchardCore.Environment.Extensions.ExtensionManager.<>c__DisplayClass33_0.<EnsureInitializedAsync>b__0(Module module)
         at OrchardCore.Modules.EnumerableExtensions.<>c__DisplayClass0_1`1.<<ForEachAsync>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at OrchardCore.Environment.Extensions.ExtensionManager.EnsureInitializedAsync()
         at OrchardCore.Environment.Extensions.ExtensionManager.LoadFeaturesAsync()
         at OrchardCore.Environment.Shell.ShellHost.PreCreateAndRegisterShellsAsync()
         at OrchardCore.Environment.Shell.ShellHost.InitializeAsync()
         at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by agriffard** [comment]
I tested following the documentation and I don't have the behaviour you are describing.

Are you using OrchardCore.Application.Cms.Targets Version="1.0.0" ?

GraphQL Version is 2.4

**Comment by avestura** [comment]
@agriffard 

> Are you using OrchardCore.Application.Cms.Targets Version="1.0.0" ?

Yes. And this is my `paket.lock` file including versions:

`paket.lock` > _OrchardCore.Application.Cms.Targets_
```
OrchardCore.Application.Cms.Targets (1.0)
  OrchardCore.Application.Cms.Core.Targets (>= 1.0) - restriction: >= netcoreapp3.1
  OrchardCore.Translations.All (>= 1.0) - restriction: >= netcoreapp3.1
  SafeMode (>= 1.0) - restriction: >= netcoreapp3.1
  TheAgencyTheme (>= 1.0) - restriction: >= netcoreapp3.1
  TheBlogTheme (>= 1.0) - restriction: >= netcoreapp3.1
  TheComingSoonTheme (>= 1.0) - restriction: >= netcoreapp3.1
  TheTheme (>= 1.0) - restriction: >= netcoreapp3.1
```

`paket.lock` > _GraphQL_
```
GraphQL (4.5) - restriction: >= netcoreapp3.1
  GraphQL-Parser (>= 7.1) - restriction: >= netstandard2.0
  Microsoft.CSharp (>= 4.7) - restriction: >= netstandard2.0
  System.ComponentModel.Annotations (>= 4.7) - restriction: >= netstandard2.0
  System.Runtime.CompilerServices.Unsafe (>= 4.7.1) - restriction: >= netstandard2.0
```

`paket.lock` > _OrchardCore.Apis.GraphQL.Abstractions_
```
OrchardCore.Apis.GraphQL.Abstractions (1.0) - restriction: >= netcoreapp3.1
  GraphQL (>= 2.4) - restriction: >= netcoreapp3.1
  OrchardCore.DisplayManagement.Abstractions (>= 1.0) - restriction: >= netcoreapp3.1
  OrchardCore.Infrastructure.Abstractions (>= 1.0) - restriction: >= netcoreapp3.
```

**Comment by deanmarcussen** [comment]
Your issue is because somwhere you have installed GraphQL version 4.5

Orchard's on GraphQL v2.4 and trying to use 4.5 will cause this conflict
